### ISSUE TITLE
deleteFromAllBoxes() 

### ISSUE THREAD

**Issue by peekpt** [hivedb/hive#101]
**Problem**
Having the same object referenced across multiple boxes it's possible to save() It will update the object in all the boxes the object it's referenced to. But if you delete() the object it only deletes from the box you are referencing. 

If you have something like

```
Fruit (box)
-String name

Basket (box)
-List<Fruit> items
```
If you add the object to both Box, you can have edit the fruit name from any box, but if you can't delete the object from all boxes.

In database this can be expected behavior or not.

**Feature Request**
 Have a alternative deleteFromAllBoxes()

**Comment by leisim** [comment]
You can only save or delete objects which are stored directly in a box and not within another object.

You cannot add the same object to multiple boxes (there will be an exception).

Hive does not support "backlinks" and will likely not support it in the futue.

**Comment by peekpt** [comment]
Are you saying that if you need to have some relationship we need to use
IDs?

A sábado, 19/10/2019, 12:40, Simon Leier <notifications@github.com>
escreveu:

**Comment by leisim** [comment]
Unfortunately yes. Currently I have no idea how we could improve this. Do you have something in mind?

**Comment by peekpt** [comment]
Maybe instead of List <Fruit> having BoxValues<Fruit> which is just a
shortcut to Fruit.values

A sábado, 19/10/2019, 14:16, Simon Leier <notifications@github.com>
escreveu:

**Comment by leisim** [comment]
I like the idea and I'll try to implement this without breaking the binary format. Also I'll have to test performance. If everything works, this should be in the next version.

**Comment by peekpt** [comment]
Cool! That boxvalues internally should be just a list of shortcuts to items
on the other box ( not all the items of course) but when you add items to
that pseudo list you should be pretending you are adding the object itself.
Internally it just holds the shortcuts.
When you are exposing the list, it should detect if one item was deleted
and remove the item from the list. Well it maybe be a list of keys
internally but externally it's a list of objects. Maybe call it
ValueCollection.

But FYI currently is working with adding an object to a box and then add to
a List of other box, you update save() the object and it updates in all the
boxes, ( in the list you save() the list of course) which it comes handy if
you want to hold the Object on the list.



A domingo, 20/10/2019, 00:59, Simon Leier <notifications@github.com>
escreveu:

**Comment by leisim** [comment]
But FYI currently is working with adding an object to a box and then add to a List of other box, you update save() the object and it updates in all the boxes


The cached object is updated since there only exists one instance of that object. When you restart the app, the changes of the object in the list should be gone

**Comment by peekpt** [comment]
Oh! I see... So you must copy the object! 
One way you could do about deleting and do that linking collection and because sometimes we don't want the object deleted from other boxes: instead of delete() from the current box just disable() it. You can't see from the owner box, but you can see from other boxes and be able to enable() again.

**Comment by leisim** [comment]
I don't think it is possible to clone objects in Dart. We would need to use mirrors for that :/

One problem I haven't solved yet: Say we have a `Fruit` object in the fruits box and a `BoxValues<Fruit>` list in another box which contains that fruit.

If we delete the fruit from the fruits box, the list somehow needs to be notified that the fruit no longer exists. This is already not easy but maybe the box with the list is not even open currently.

**Comment by peekpt** [comment]
And you have to delete from all lists, because the object can exists in many lists.

**Comment by leisim** [comment]
Exactly :/

**Comment by peekpt** [comment]
The Fruit object should have a hidden list of "shortcuts" to each box> list it is referenced then delete item from the list.
Each time a list is modified it should add or delete from the objects hidden list

**Comment by leisim** [comment]
But it will be quite expensive to create this list of shortcuts. I'm not sure it is worth the trouble.

If the box with the `BoxValues` is opened before the box with fruits, each object needs to be checked.

**Comment by peekpt** [comment]
Testing on the fly maybe the option to go. About the key, when working with objects aren't we getting a incremental key, or not writing in the deleted ones?

**Comment by leisim** [comment]
> when working with objects aren't we getting a incremental key, or not writing in the deleted ones?

Yes if you use `box.add()` but not for `box.put()`

**Comment by peekpt** [comment]
Many to many usually uses a separated table with the IDs linking the tables. If it was possible to create a box let say "relationships" where we could add some object that has two IDs from different boxes, and in the code we could filter like:
Relationships.values.where((value)=> value.A is Fruit || value.B is Basket).where ...

**Comment by leisim** [comment]
What do you think about this [`HiveList`](https://github.com/hivedb/hive/blob/dev/hive/lib/src/hive_list.dart) class I implemented? It works without using an additional box or breaking any API or binary format. 
The only downside is that it is lazy and will fast enough for almost anything, I wouldn't use it for queries.

**Comment by peekpt** [comment]
Awesome work!  But I need some pratical to understand it better. Another thing to implement is cascading deleting , example if you remove a fruit it removes all basket that has the object. Cool great work

**Comment by leisim** [comment]
You would just use the `HiveList` instead of a regular list in your object. It has one parameter in the constructor which is the "other" box (for example "Fruits").

Now you can add, remove or change the order of the objects in the `HiveList`. Internally it just keeps the name of the remote box and the keys (ordered) of the objects from the remote box.

Each time you access an object from the `HiveList` it will get the object from the remote box with matching key.

If the object doesn't exist anymore (because it has been removed from the remote box in the meantime) it just returns `null`.

**Comment by leisim** [comment]
> Another thing to implement is cascading deleting , example if you remove a fruit it removes all basket that has the object.

I'm not sure I understand what you mean exactly...

**Comment by peekpt** [comment]
If basket has a hivelist and if I want to delete one fruit and all the basket values that has that fruit referenced on the hivelist

**Comment by leisim** [comment]
You mean the same object is stored in multiple `HiveList`s and if you remove it from one, it will be removed everywhere?

**Comment by peekpt** [comment]
No like this:

Fruits box:
Fruit A
Fruit B
Fruit C

Basket box
Hivelist A - Fruit A, Fruit B
Hivelist B - Fruit B, Fruit C

When deleting Fruit A from fruits box:

Fruits box:
Fruit B
Fruit C

Basket box
Hivelist B - Fruit B, Fruit C

**Comment by leisim** [comment]
What is the use case for this?

**Comment by peekpt** [comment]
Hmm,
Let's say you have a CD store and have a promo pack which has an hivelist of CD . If a CD sold out it no longer make sense to have promo packs with that CD

**Comment by leisim** [comment]
I see... I think this is something for step two. I'd say we test the `HiveList` (especially it's performance) and see if it is the right way to go.

What do you think.

(Btw, thanks for your great input and ideas)

**Comment by peekpt** [comment]
My pleasure to help. If I can remeber this feature is present on iOS when building coredata relationships . Yes it's better to test it first

**Comment by leisim** [comment]
I've never worked with coredata and I'll take a look how it works in detail.

**Comment by peekpt** [comment]
https://cocoacasts.com/core-data-relationships-and-delete-rules check de delete rules

**Comment by peekpt** [comment]
What about having  global method  which connects to an hidden box called relationships that will store all boxes relationships, like HiveLink(Box a, Box b) that will perform like Hivelist.
then the user could call it with Hive.linkValues(box A, box B) and get a and b values.

**Comment by peekpt** [comment]
![hive many to many](https://user-images.githubusercontent.com/222385/67230301-f9ec4b00-f434-11e9-98a3-29f49a94e96a.png)


Hive.linkValues(box, box) :  Iterable<LinkValue>

LinkValue.firstBox: FirstBoxValue
LinkValue.secondBox: SecondBoxValue

**Comment by peekpt** [comment]
another feature would be: equality with comparison of Objects by key. So we could do

 HiveObjectA == HiveObjectB

**Comment by leisim** [comment]
> `var allPostsWithCoolTag = Hive.linkValues(posts, tags).where((link)=>link.secondBox.name == 'cooltag' ).map((link)=>link.firstBox).toList(); `

Thanks for the detailed explanation. I'm still a bit worried about performance. This needs some testing.

> another feature would be: equality with comparison of Objects by key. So we could do `HiveObjectA == HiveObjectB`

Great idea and very easiy to implement. This will be part of the next update 👍

**Comment by peekpt** [comment]
One great feature is to let user decide about object deletion. One approach I will probably use is to add a boolean parameter to the object called 'disabled', to maintain the object accessible from other boxes via HiveList.

**Comment by leisim** [comment]
> One great feature is to let user decide about object deletion. One approach I will probably use is to add a boolean parameter to the object called 'disabled', to maintain the object accessible from other boxes via HiveList.

I agree, this is a cool feature. I didn't even think about this before you showed me the core data docs. But is it flexible enough to work for all situations? Also I don't want to introduce complicated features which can be easily implemented by the user.
Users today already struggle with some of the details in using Hive. My number one goals for Hive are great performance and ease of use...

**Comment by peekpt** [comment]
I completely understand but they are just ideas, of course some are redundant , but at least the most frequently used IMO should be implemented.  I design this graph to show what's my idea, it misses implementations for delete but you get the general idea. 
![hive-many-to-many-rel](https://user-images.githubusercontent.com/222385/67289012-cf060380-f4d5-11e9-9060-daf7cb581c02.png)

**Comment by leisim** [comment]
What is the advantage over the following:

```dart
class Post extends HiveObject {
  @HiveField(0)
  String content;

  @HiveField(1)
  String userKey;

  User get user => Hive.box<User>('users').get(userKey);

  @HiveField(2)
  String tagKey;

  Tag get tag => Hive.box<Tag>('tags').get(tagKey);
}
```

You can still do filtering like:
```dart
var postsWithTag = Hive.box<Post>('posts').values.where((p) => p.tag.name == 'tag1');
```

Maybe we could even create a `HiveLink` object or annotation which contains the logic with the keys.

**Comment by peekpt** [comment]
Yes an hivelink would be the best option and the user could store List<Hivelink> wherever he wants. The advantage is many to many relationship, posts could have many tags and tags could have many posts. Users can have many posts but a post can only have one User.

**Comment by peekpt** [comment]
This method of linking will cover all relationships
One-to-on, one-to-many and many-to-many and avoids of using hiveobject as an hivefield each object only resides in it's box

**Comment by leisim** [comment]
But how would you for example implement a person object which has friends and enemies?

**Comment by peekpt** [comment]
Oh... Good question... . I never thought in having person inside person.
But you can have a enimies box and a friends box and put hivelinks inside
then you can easily list anything

A quarta, 23/10/2019, 01:07, Simon Leier <notifications@github.com>
escreveu:

**Comment by peekpt** [comment]
Imagine the options. You have Hivelink with two values , let's say primary and secondary. You now have total control on deletion:
Hivelink.delete() deletes the link and keep values
Hivelink.delete(primary:true) deletes the Hivelink and primary
Same for secondary

**Comment by peekpt** [comment]
out off main topic, discussion proceeds on #102
