### ISSUE TITLE
What is the recommended way to integration test an app that registers type adapters?

### ISSUE THREAD

**Issue by danallen88** [hivedb/hive#1013]
**Question**
In the `main()` function of our app we run the following code:

```dart
WidgetsFlutterBinding.ensureInitialized();
await Hive.initFlutter();
Hive.registerAdapter(MobileSettingsAdapter());
```

and for each integration test we must run this `main()` method to start the app up.  However for Flutter integration tests it seems that there is no tear down, so we get the following error for all tests after the first test successfully runs:

> HiveError: There is already a TypeAdapter for typeId 0.

This may not be a Hive issue, but the `resetAdapters` method is not part of the public API so I'm wondering how others are getting around this?

**Version**
```sh
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.0, on macOS 11.5.2 20G95 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.1)
[✓] Connected device (4 available)
[✓] HTTP Host Availability
```
hive_flutter: ^1.1.0
hive: ^2.2.2

**Comment by alestiago** [comment]
#1014 does solve?

**Comment by danallen88** [comment]
It would, thanks @alestiago!
