### ISSUE TITLE
Updates or Deletions to entries that have been added to a box don't persist

### ISSUE THREAD

**Issue by clicksrv** [hivedb/hive#103]
**Steps to Reproduce**
In my project, I add items initially, and after that, I fetch updates for these items. I can also delete these items from my lists. I find that adding data to the box persists (I use 'put' for adding). However, after fetching updates for these items, I put the refreshed items over the existing one. Using a WatchBoxBuilder, all the values get updated as expected on the screen, but none of the updates persist if I close the app and open again. The same happens with deletion, where I remove an item, it happens on my current session, but as soon as I close and re-open, the product is back.

To help understand the structure used in my project:
_Box **'watchlists' :** String name -> List<int> productHashes
Box **'products' :** int productHash -> Product product_

productHash is product.hashCode, where Product extends Equatable, with properties selected to make it unique (hashCode doesn't change on refresh, products stay unique).

**Code sample**
_product_manager.dart_
```
import 'dart:async';

import 'package:hive/hive.dart';
import 'package:../models/product_model.dart';
import 'package:../services/product_provider.dart';
import 'package:../services/watchlist_manager.dart';

class ProductManager {
  static final String boxName = 'products';
  static Box _productList;

  static Future init() async {
    Completer c = Completer();
    Hive.registerAdapter(ProductAdapter(), 0);
    _productList = await Hive.openBox(boxName);
    c.complete(_productList);
    return c.future;
  }

  static Future close() async {
    await _productList.compact();
    return _productList.close();
  }

  static Future<bool> addProduct(String watchList, Product product) async {
    if (WatchListManager.containsProduct(watchList, product.hashCode)) {
      return false;
    } else if (_productList.containsKey(product.hashCode)) {
      return WatchListManager.addProduct(watchList, product.hashCode);
    } else {
      await _productList.put(product.hashCode, product);
      return WatchListManager.addProduct(watchList, product.hashCode);
    }
  }

  static Future<bool> removeProduct(String watchList, Product product) async {
    if (_productList.containsKey(product.hashCode)) {
      bool productRemoved = await WatchListManager.removeProduct(watchList, product.hashCode);

      if (!WatchListManager.productExistsInAnyWatchList(product.hashCode)) {
        await ProductManager.removeProductHash(product.hashCode);
      }

      return productRemoved;
    } else {
      return false;
    }
  }

  static Future<void> removeProductHash(int productHash) async {
    return _productList.delete(productHash);
  }

  static Future<void> refreshProducts() async {
    List<Future<Product>> futures = List<Future<Product>>();

    for (var product in _productList.values) {
      Future<Product> productFuture = ProductProvider().refreshProduct(product);
      futures.add(productFuture);
      productFuture.then((result) async => await _productList.put(result.hashCode, result));
    }

    return Future.wait(futures);
  }

  static Future<Product> refreshProduct(Product product) async {
    Future<Product> future = ProductProvider().refreshProduct(product);
    future.then((result) async => await _productList.put(result.hashCode, result));
    return future;
  }
}
```

**Version**
 - Platform: Android
 - Flutter version: 1.10.7
 - Hive version: 1.1.1

**Comment by leisim** [comment]
This sounds more like a problem on your side tbh. Unfortunately I can't read much out of your code because the context is missing. Maybe you can create a smaller sample or demo app which shows the problem.

**Comment by leisim** [comment]
Maybe take a look at the [todo sample app](https://github.com/hivedb/samples/tree/master/todo)...

**Comment by clicksrv** [comment]
I did have a look at the Sample app before starting. I am going to go through it again to see any issues that might be there with my approach.

Regarding the code provided, this is the part specific to the hive box which is being called from the UI interactions in the app. WatchList manager is another box, but is supposedly not an issue because it contains a very basic map to keep track of which watchlist holds which products from the product list.

Let me review my code along with the ToDo app and I'll see if I can resolve the issue.

**Comment by clicksrv** [comment]
Okay, so I have a question.
Documentation at https://docs.hivedb.dev/boxes/read specifies:

> In the sample above, only the cached object has been changed and not the underlying data. To persist the change, box.put('myList', myList) would need to be called.

And the way I am calling the same in my code is:
```
static Future<Product> refreshProduct(Product product) async {
    Future<Product> future = ProductProvider().refreshProduct(product);
    future.then((result) async =>
    await _productList.put(result.hashCode, result));
    return future;
  }
```

The parameter product is being passed to this method from a WatchBox builder. Each product's hashcode is unique and specific to it, and hence I am using the same as a key in the box.

So I am getting the refreshed product, and over-writing the current instance in the box with my new refreshed product with `_productList.put(result.hashCode, result)`. According to the documentation, this should persist the data, but it is not. If I reload the app, I find the product in the original state, and not the refreshed state.

The difference I noted is that for my Product Model class, I have not extended HiveObject, but Equatable.

**Comment by leisim** [comment]
Without seeing you code it is really hard to diagnose the problem. Do you use a generated `TypeAdapter`?

**Comment by clicksrv** [comment]
Yes, I use a generated TypeAdapter.

Here's the model:
```
import 'package:equatable/equatable.dart';
import 'package:hive/hive.dart';
import 'package:price_tracker/services/product_helper.dart';

part 'product_model.g.dart';

@HiveType()
// ignore: must_be_immutable
class Product extends Equatable {
  @HiveField(0)
  String url;

  @HiveField(1)
  String marketplace;

  String invalidReason;

  @HiveField(3)
  String id;
  @HiveField(4)
  String name;

  @HiveField(5)
  DateTime dateAdded;
  @HiveField(6)
  DateTime dateLastRefreshed;

  @HiveField(7)
  String currency;

  @HiveField(8)
  Map<DateTime, double> priceHistory;

  @HiveField(9)
  String displayImageUrl;

  Product(this.url);

  @override
  List<Object> get props => [id, marketplace];

  @override
  String toString() {
    return invalidReason == null
        ? "Product {ID: $id, Name: $name, Last Price: ${ProductHelper
        .getFormattedLastKnownPrice(this)}, URL: $url}"
        : "Product {InvalidReason: $invalidReason, ID: $id, Name: $name, URL: $url}";
  }
}
```

And here's the generated TypeAdapter:
```
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'product_model.dart';

// **************************************************************************
// TypeAdapterGenerator
// **************************************************************************

class ProductAdapter extends TypeAdapter<Product> {
  @override
  Product read(BinaryReader reader) {
    var numOfFields = reader.readByte();
    var fields = <int, dynamic>{
      for (var i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return Product(
      fields[0] as String,
    )
      ..marketplace = fields[1] as String
      ..id = fields[3] as String
      ..name = fields[4] as String
      ..dateAdded = fields[5] as DateTime
      ..dateLastRefreshed = fields[6] as DateTime
      ..currency = fields[7] as String
      ..priceHistory = (fields[8] as Map)?.cast<DateTime, double>()
      ..displayImageUrl = fields[9] as String;
  }

  @override
  void write(BinaryWriter writer, Product obj) {
    writer
      ..writeByte(9)
      ..writeByte(0)
      ..write(obj.url)
      ..writeByte(1)
      ..write(obj.marketplace)
      ..writeByte(3)
      ..write(obj.id)
      ..writeByte(4)
      ..write(obj.name)
      ..writeByte(5)
      ..write(obj.dateAdded)
      ..writeByte(6)
      ..write(obj.dateLastRefreshed)
      ..writeByte(7)
      ..write(obj.currency)
      ..writeByte(8)
      ..write(obj.priceHistory)
      ..writeByte(9)
      ..write(obj.displayImageUrl);
  }
}

```

**Comment by leisim** [comment]
Looks alright. Unfortunately I cannot reproduce this issue. Either you are doing something wrong or there is a big in Hive which only happens very rarely.

Maybe you could share a small project which shows the problem.

Did you try to run the sample?

**Comment by clicksrv** [comment]
I did, actually. And the sample ran fine. Tested persistence as well.

I'll create a small sample project to try and share if I can replicate the same issue.

**Comment by clicksrv** [comment]
Hey @leisim, I tried to make a small project. What I did was re-use the todo app to test with my model and service classes. To my surprise, everything worked fine there. After a few busy days, came around to my app to see what changes I need to make.

I was anyways planning to use the FutureBuilder for initializing the app with a loading screen, so I made that change, where I moved the initialization method from the main() method to the FutureBuilder. To my surprise, now the data is persisting without any other changes made!

Thanks a lot for your help and your awesome contribution with this library!

**Comment by leisim** [comment]
> I moved the initialization method from the main() method to the FutureBuilder. To my surprise, now the data is persisting without any other changes made!

I'm also surprised that it makes a difference. I'll keep an eye on this issue and I'm happy that it works now for you :+1:
