### ISSUE TITLE
Error saving locally Bad state: Cannot add new events after calling close

### ISSUE THREAD

**Issue by ash-hashtag** [hivedb/hive#1034]
![image](https://user-images.githubusercontent.com/94179580/179211806-45769f3b-b9a7-4e6f-85f9-525ed7cfddad.png)

`
try {
      final box = await Hive.openLazyBox('local');
      await box.clear();
      await box.put('data', data);
      await box.close();
      print("saved data");
      return true;
    } catch (err) {
      print('Error saving locally $err');
      return false;
    }
`

data is just List<Map>

**Version**
 - Platform: Android,
 - Flutter version: 3.0.4
 - Hive version: ^1.1.0

**Comment by Macacoazul01** [comment]
@ash-hashtag when the error happens?
On the first or the second time you executes this code?

**Comment by ash-hashtag** [comment]
Second I think, I mean I open box before when opening the app and gets all the data and closes, and this is before I close the app, to store back all the data.

**Comment by Macacoazul01** [comment]
But why are you closing the box?

**Comment by ash-hashtag** [comment]
I don't have to? Oops, I thought it should be closed after using it. But can't I open it again after closing it before?
