### ISSUE TITLE
Separate paths per box

### ISSUE THREAD

**Issue by passsy** [hivedb/hive#104]
## Problem
Hive uses the path of `Hive.init(path)` globally. This makes it difficult for SDKs to use hive because it doesn't allow to write in a special "sdk" folder when the implementer also uses hive.

On Android exists a special `cache` folder. I'd like to write some boxes there, and other in a different folder. This isn't possible right now.

## Solution

Allow opening boxes with a path.
`Hive.openBox(path: absolutePath);`

**Comment by leisim** [comment]
Thanks for this idea. I completely agree and will implement this with the next version.

**Comment by leisim** [comment]
This is now possible with v1.2.0 using `Hive.openBox(path: "some/path")`.
