### ISSUE TITLE
 Equatable

### ISSUE THREAD

**Issue by peekpt** [hivedb/hive#105]
What about adding Equatable to HiveObject lib generated by the builder, instead of adding key comparison, we can have parameters comparison.

https://pub.dev/packages/equatable

we could turn on and of by using meta @Equatable() before the class

**Comment by leisim** [comment]
I'm not using equatable myself but I heard from others that Hive doesn't work with equatable.

**Comment by peekpt** [comment]
Ok, thank you! I've never tried my self also.
