### ISSUE TITLE
Snippets for VSCode 

### ISSUE THREAD

**Issue by peekpt** [hivedb/hive#106]
**Snippets**
Creates HiveTypes structure

how to install:
- Call your commands prompt Cmd+Shift+P and type "user snipp"
- Select Configure User Snippets and choose dart.json
- Paste the code above and save it.

usage:
- create a file example.dart 
- enter in the file you created _hive_ or _hivc_  to recall the snippet
  - _hive_: extends HiveObject
  - _hivc_: simple HiveType class

```dart
{
"HiveType class extends HiveObject": {
		"prefix": "hive",
		"body": [
			"import 'package:hive/hive.dart';",
			"",
			"part '${TM_FILENAME_BASE}.g.part';",
			"",
			"@HiveType()",
			"class ${TM_FILENAME_BASE/(.*)/${1:/pascalcase}/} extends HiveObject {",
			"\t@HiveField(0)",
			"\tString id;",
			"\t${0:// Hive fields go here}",
			"}",
		],
		"description": "Creates an HiveType class extending HiveObject structure based on the filename."
	},
	"HiveType class": {
		"prefix": "hivc",
		"body": [
			"import 'package:hive/hive.dart';",
			"",
			"part '${TM_FILENAME_BASE}.g.part';",
			"",
			"@HiveType()",
			"class ${TM_FILENAME_BASE/(.*)/${1:/pascalcase}/} {",
			"\t@HiveField(0)",
			"\tString id;",
			"\t${0:// Hive fields go here}",
			"}",
		],
		"description": "Creates an HiveType class structure based on the filename."
	}
}
```

**Comment by leisim** [comment]
Wooow this is so cool. I didn't even know you could create snippets yourself 😍

I'm not able to test them currently but if it works and I get your permission, I'd love to create a documentation page for this snippet...

**Comment by peekpt** [comment]
Yes of course you can 😄

**Comment by leisim** [comment]
I'd love to take this a step further with code actions and maybe checks for Hive using the [analyzer plugin SDK](https://github.com/dart-lang/sdk/tree/master/pkg/analyzer_plugin/doc/tutorial). I think it would be cool if you could, for example, add all annotations to an existing class.

I have never used the analyzer so I don't know what is possible but I think it is very powerful...

We can use this issue to discuss the possibilities.

**Comment by peekpt** [comment]
Well snippets are a VSCode  thing, there's also a documentation for it.

But changing code with the analyzer seems to be a laborious job to do.
I've never seen that kind of behaviour before.

**Comment by leisim** [comment]
> But changing code with the analyzer seems to be a laborious job to do.
I've never seen that kind of behaviour before.

I don't think it is too hard. I know that `moor` uses the analyzer to check SQL statements. And I believe Flutter uses it for code actions like `center widget` etc.
The advantage of the analyzer is that it also works on Android Studio without changes.

But the snippets are enough for now. There are more important tasks than code actions currently.

**Comment by peekpt** [comment]
Maybe it's possible to use some kind of regex, detecting the symbols like class, String, Int,List and add the annotations the line before.🤔

**Comment by leisim** [comment]
Yes exactly. We can also check whether the `fieldId`s are unique.

**Comment by peekpt** [comment]
![hivesnippetsGIF](https://user-images.githubusercontent.com/222385/67619688-43061b80-f7f6-11e9-9efc-29231e89b387.gif)


```dart
{
      "HiveType class extends HiveObject": {
		"prefix": "hive",
		"body": [
			"import 'package:hive/hive.dart';",
			"",
			"part '${TM_FILENAME_BASE}.g.part';",
			"",
			"@HiveType()",
			"class ${TM_FILENAME_BASE/(.*)/${1:/pascalcase}/} extends HiveObject {",
			"\t@HiveField(0)",
			"\tString id;",
			"\t${0:// Hive fields go here}",
			"}",
		],
		"description": "Creates an HiveType class extending HiveObject structure based on the filename."
	},
	"HiveType class": {
		"prefix": "hivc",
		"body": [
			"import 'package:hive/hive.dart';",
			"",
			"part '${TM_FILENAME_BASE}.g.part';",
			"",
			"@HiveType()",
			"class ${TM_FILENAME_BASE/(.*)/${1:/pascalcase}/} {",
			"\t@HiveField(0)",
			"\tString id;",
			"\t${0:// Hive fields go here}",
			"}",
		],
		"description": "Creates an HiveType class structure based on the filename."
	},
	"@HiveField(#)": {
		"prefix": "hf",
		"body": [
			"@HiveField(${1})",
			"${2};",
			"${0}"
		],
		"description": "Creates @HiveField({number})"
	},
	"@HiveType()": {
		"prefix": "ht",
		"body": [
			"@HiveType()",
			"${0}"
		],
		"description": "Creates @HiveType()"
	},
	"@HiveField(#) String": {
		"prefix": "hfs",
		"body": [
			"@HiveField(${1})",
			"String ${2};",
			"${0}"
		],
		"description": "Creates @HiveField({number}) String"
	},
	"@HiveField(#) int": {
		"prefix": "hfi",
		"body": [
			"@HiveField(${1})",
			"int ${2};",
			"${0}"
		],
		"description": "Creates @HiveField({number}) int"
	},
	"@HiveField(#) bool": {
		"prefix": "hfb",
		"body": [
			"@HiveField(${1})",
			"bool ${2};",
			"${0}"
		],
		"description": "Creates @HiveField({number}) bool"
	},
	"@HiveField(#) List": {
		"prefix": "hfl",
		"body": [
			"@HiveField(${1})",
			"List<${2}> ${3};",
			"${0}"
		],
		"description": "Creates @HiveField({number}) List<>"
	}
}
```

**Comment by leisim** [comment]
Thanks again! The snippets work great and I created a [documentation page](https://docs.hivedb.dev/more/vscode-snippets) for them.

**Comment by leisim** [comment]
I changed the docs...
