### ISSUE TITLE
Hive not working when trying to fetch data from work manager or foreground app

### ISSUE THREAD

**Issue by neelayak** [hivedb/hive#1060]
So I tried to get the saved data from hive but i am getting error 
this happens when trying to use Hive.openbox 
`Unhandled Exception: HiveError: You need to initialize Hive or provide a path to store the box.
#0      BackendManager.open
package:hive/…/vm/backend_manager.dart:21
#1      HiveImpl._openBox
package:hive/src/hive_impl.dart:101
#2      HiveImpl.openBox
package:hive/src/hive_impl.dart:142
#3      MyTaskHandler.onEvent
package:motivationapp/main.dart:286
#4      FlutterForegroundTask.setTaskHandler.<anonymous closure>
package:flutter_foreground_task/flutter_foreground_task.dart:355
#5      FlutterForegroundTask.setTaskHandler.<anonymous closure>
package:flutter_foreground_task/flutter_foreground_task.dart:346
#6      MethodChannel._handleAsMethodCall
package:flutter/…/services/platform_channel.dart:404
#7      MethodChannel.setMethodCallHandler.<anonymous closure>
package:flutter/…/services/platform_channel.dart:397
#8      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/bi<…>
`

**Comment by ksh-b** [comment]
how did you solve this
