### ISSUE TITLE
expect List but got a CastList<int, dynamic> 

### ISSUE THREAD

**Issue by visionawe** [hivedb/hive#1067]
In the first run, the data is correct, but after refreshing the page, you get castlist<int, dynamic> instead of List.
This problem did not exist and it happened without changing the codes!

```
@HiveType(typeId: 5)
class FileSchema {
  @HiveField(0)
  String file;

  @HiveField(1)
  List bytes;

  @HiveField(2)
  int v;
```
```
var _files  = await Hive.openBox<FileSchema>('filesBox');
FileSchema _file = await  B.boxFiles.get(id);
```

**Version**
 - Platform: Android, Windows, Web
 - Flutter version: 3.3.0
 - hive: ^2.2.3
 - hive_flutter: ^1.1.0

**Comment by AliHoseinpoor** [comment]
same problem

**Comment by yaragroup** [comment]
@AliHoseinpoor 
سلام علی جان
فیلد "Hive"ی که میخوای آرایه توش ذخیره بشه رو به این شکل تعریف کن
```
  @HiveField(1)
  Uint8List? bytes;
```
من String64 رو که از سرور گرفتم به bytes تبدیل میکنم و توی فیلد ذخیره می‌کنم
`Uint8List decodeImage = const Base64Codec().decode(res.body);
`
شما هم حتما به Uint8List  تبدیل کن و بعد put کن
`boxFiles.put(key, myFile(name: ... , bytes:decodeImage));
`
برای فراخوانیش
`Uint8List? bytes = boxFiles.get(key);
`
اگه میخوای مطمئن بشی که در صورتی <castlist<int, dynamic برگردوند تصویر نمایش داده بشه اول میتونی چک کنی
`if (bytes .runtimeType.toString().contains('CastList')) return Image.memory(Uint8List.fromList(bytes));
`
و در حالت عادی
`Image.memory(bytes);
`
با این روند من دیگه به اون مشکل برنخوردم، ان‌شاالله شما هم مشکلت حل بشه.
