### ISSUE TITLE
Consider providing full OSS license

### ISSUE THREAD

**Issue by filiph** [hivedb/hive#107]
I am not a lawyer, so take everything here with a grain of salt.

I was a bit worried when I saw that GitHub doesn't autodetect the OSS license of this project. It does link to the LICENSE file, but only says "see license".

<img width="265" alt="Screen Shot 2019-10-25 at 7 27 12 PM" src="https://user-images.githubusercontent.com/919717/67613033-852f4e80-f75d-11e9-9952-c327a45342f9.png">

I'd rather like to see:

<img width="242" alt="Screen Shot 2019-10-25 at 7 27 28 PM" src="https://user-images.githubusercontent.com/919717/67613037-8bbdc600-f75d-11e9-9178-1ff5c87a2ec7.png">

From what I understand from the legalese at https://www.apache.org/licenses/LICENSE-2.0, I think you're not doing anything wrong, technically, by showing only the short text. But I, for one, would feel better if GitHub just automatically said the project is Apache 2.0, like it does for many other OSS projects.

See https://github.com/moby/moby/blob/master/LICENSE for an example how to include the full license.

<img width="1134" alt="Screen Shot 2019-10-25 at 7 27 01 PM" src="https://user-images.githubusercontent.com/919717/67613040-96785b00-f75d-11e9-99a4-1f863190d0d0.png">

**Comment by leisim** [comment]
Initially I used the long version but the Flutter `showLicensePage()` method did not like it #34.

I'm sure it makes not difference whether the full license is included but I'll change that.

**Comment by leisim** [comment]
Done.
