### ISSUE TITLE
Analyzer 5 support

### ISSUE THREAD

**Issue by megamaddu** [hivedb/hive#1084]
**Is your feature request related to a problem? Please describe.**

Other dependencies are beginning to to require `analyzer: ^5.0.0`, such as `freezed: 2.1.1`. I'm not sure if this is a hard requirement, I'm not aware of what's changing in analyzer 5. But I didn't see another issue tracking this so here it is!

**Version**
 - Platform: -
 - Flutter version: 3
 - Hive version: 1.1.3

**Comment by Constans** [comment]
`auto_route_generator: ^5.0.3` requires `analyzer: ^6.0.0` already. 
So it might be a good idea to request 6?

**Comment by Constans** [comment]
This seems resolved in the [2.0.0 version](https://pub.dev/packages/hive_generator/changelog#200).
