### ISSUE TITLE
Exporting/Importing the database

### ISSUE THREAD

**Issue by NourEldinShobier** [hivedb/hive#111]
**Question**
Is it possible to export the database from one device to another?

**Comment by leisim** [comment]
You can just copy the box file to the other device.

**Comment by DevonTomatoSandwich** [comment]
How exactly do you do that? 

ps. I'm new to hive and have been playing with it for the last two days so i might have missed this in the docs or maybe there is a tutorial? Thanks for making a great noSQL db :)

**Comment by leisim** [comment]
Hive stores it's data in normal files. You can get the path with `yourbox.path`.
For example, you could do the following:
```dart
var file = File(yourBox.path);
var bytes = await file.readAsBytes();
```
