### ISSUE TITLE
Is there an option not to encrypt the database?

### ISSUE THREAD

**Issue by allomy** [hivedb/hive#1120]
**Question**
Hi, is there an option not to encrypt the database? Like the below code, is the above **_box_** encrypted or unencrypted?

**Code sample**
```dart
var box = Hive.box('myBox')
```

**Comment by Wizzel1** [comment]
@allomy  In your example, the box is unencrypted. Check out this section in the documentation to encrypt your box: 
https://docs.hivedb.dev/#/advanced/encrypted_box

**Comment by allomy** [comment]
Thank you for you reply! @Wizzel1
