### ISSUE TITLE
Error: Expected a value of type 'FutureOr<type>', but got one of type 'type'

### ISSUE THREAD

**Issue by abikko** [hivedb/hive#1126]
Call await function after hot reload/hot restart and after refreshing the page.

**Code sample**
```
@override
  Future<T?> load<T>({required String table, required String key, T? defaultValue}) async {
    return await Hive.box(table).get(key, defaultValue: defaultValue);
  }
```

**Error log:**
```
Error: Expected a value of type 'FutureOr<List<String>?>', but got one of type 'List<dynamic>'
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 99:3        castError
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 452:10  cast
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/classes.dart 193:14     as_FutureOr
packages/discounts_mobile/data/client/local/hive_local_client.dart 16:5           load
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50                <fn>
dart-sdk/lib/async/zone.dart 1653:54                                              runUnary
dart-sdk/lib/async/future_impl.dart 147:18                                        handleValue
dart-sdk/lib/async/future_impl.dart 766:44                                        handleValueCallback
dart-sdk/lib/async/future_impl.dart 795:13                                        _propagateToListeners
dart-sdk/lib/async/future_impl.dart 430:9                                         callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                                  _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                                   _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15               <fn>

```

**Version**
 - Platform: Bug on Web, but also works properly on iOS, Android
 - Flutter version: [3.3.10]
 - Hive version: [^2.2.3]
 - Hive Flutter version: [^1.1.0]

**Comment by aytunch** [comment]
Hi @abikko and @simc 
I am having the exact same problem on Chrome. App works fine in iOS&Android but I get this exception on web.
Code does not print line 102. I guess there is an internal exception thrown.
`[log] [ERROR] 20:37:59 <fn>: Expected a value of type 'List<String>', but got one of type 'List<dynamic>'`
Do you have any suggestions?

<img width="880" alt="Screenshot 2023-02-27 at 20 34 18" src="https://user-images.githubusercontent.com/6442915/221640873-12c70a40-b33f-4ee6-81d4-5e35749728d6.png">
<img width="961" alt="Screenshot 2023-02-27 at 20 35 14" src="https://user-images.githubusercontent.com/6442915/221640930-6964a0d5-73ed-4e42-b3b0-404f40da152b.png">
<img width="938" alt="Screenshot 2023-02-27 at 20 35 51" src="https://user-images.githubusercontent.com/6442915/221641092-ea9d3738-6cc8-42df-9af8-95aaa63b350c.png">
<img width="1035" alt="Screenshot 2023-02-27 at 20 37 02" src="https://user-images.githubusercontent.com/6442915/221641273-3d9a5e0e-389d-422e-8a97-59a18289e529.png">
<img width="882" alt="Screenshot 2023-02-27 at 20 37 53" src="https://user-images.githubusercontent.com/6442915/221641303-92a0cad8-2041-4c9d-8160-5b23d5fef686.png">

**Comment by aytunch** [comment]
@themisir do you have any pointers for this? would upgrading hive to 2.0.0-dev solve this? thanks

**Comment by themisir** [comment]
Hey @abikko ,

I believe this is one of the known limitation. I don't really remember the exact reason, but I know how to "fix" it.

The problem is type argument info of the generic types get lost and instead of `List<String>` for example hive returns `List<dynamic>` which you need to explicitly cast to String list using `List.cast<String>()` method or consume as is.

**Comment by aytunch** [comment]
Hi @themisir thanks for the quick reply.
I can't find anywhere to use `List.cast<String>()` since the exception is thrown inside of the plugin call.
This is what I use;
```
Box<List<String>> get _blockedContacts {
    final box = Hive.box<List<String>>('blocks');
    return box;
  }

final result = _blockedContacts.get(0);    //This is where we get the cast exception.
```

And I debugged the plugin code up until here. Maybe this will give you a hint:
<img width="657" alt="Screenshot 2023-02-28 at 01 58 49" src="https://user-images.githubusercontent.com/6442915/221709064-2d210957-480d-4605-a8ee-f1f31817616e.png">

I have no idea how `E`'s type changed from `List<String>` to <List<dynamic>`

**Comment by themisir** [comment]
@aytunch this is what i meant:

```dart
final box = Hive.box<List>();
final values = box.get(0).cast<String>();
```

**Comment by aytunch** [comment]
@themisir Thanks for this solution. It saved me from the exception but it also caused losing the type safety. Now my box is `Box<List<dynamic>>` instead of `Box<List<String>>`

Do you think this is a bug in the repo? Like an edge case? If that's your intuition, I would like to create a new issue.
