### ISSUE TITLE
Make Hive to work in a test environment

### ISSUE THREAD

**Issue by jacobaraujo7** [hivedb/hive#113]
It would be great if Hive could boot a memory db to run unit tests.

**Comment by leisim** [comment]
Hi, Hive already works for unit tests and you can use `Hive.openBoxFromBytes()` to open a memory db.

**Comment by jacobaraujo7** [comment]
Thanks!

**Comment by jacobaraujo7** [comment]
```
Hive.openBoxFromBytes("testBox", Uint8List(12000))
```
Not work for me :(

Error: 
```
package:hive/src/binary/frame.dart 48:7                                 Frame.fromBytes
package:hive/src/binary/frame_helper.dart 17:25                         FrameHelper.framesFromBytes
package:hive/src/backend/storage_backend_memory.dart 28:21              StorageBackendMemory.initialize
===== asynchronous gap ===========================
dart:async                                                              _asyncErrorWrapperHelper
package:teddy_todo/app/shared/services/local_storage_service.dart       LocalStorageService._initLocalStorage
package:teddy_todo/app/shared/services/local_storage_service.dart 10:5  new LocalStorageService
test/app/shared/services/local_storage_service_test.dart 12:15          main.<fn>
```

**Comment by leisim** [comment]
You cannot provide a bytelist with non zero size but no content. Try to use
```dart
Hive.openBoxFromBytes("testBox", Uint8List(0))
```

**Comment by jacobaraujo7** [comment]
thanks!!

**Comment by jacobaraujo7** [comment]
When I try to add data to the box in test, give problem
```
NoSuchMethodError: The method 'call' was called on null.
Receiver: null
Tried calling: call(1, 0)
dart:core                                 Object.noSuchMethod
package:hive/src/box/box_base.dart 145:9  BoxBase.performCompactionIfNeeded
package:hive/src/box/box_impl.dart 82:11  BoxImpl._writeFrames
```

**Comment by jacobaraujo7** [comment]
Anybody help me?

**Comment by leisim** [comment]
Could you share a small sample that shows the error?

**Comment by jacobaraujo7** [comment]
Hello!!
```
Hive.openBoxFromBytes("testBox", Uint8List(0));
...
box.put("anything");
```

This error happened when use put method.

**Comment by JanRegent** [comment]
Hi
I got problems too in widget tests when Hive.openBox was used in Widget
I am using listeners until Hive will work in tests
> ` 
hiveSaveControler.addListener(() async{ db.hiveSave(hiveSaveControler.text); });
  hiveLoadControler.addListener((){       db.hiveLoad(hiveLoadControler.text); });
  `

Hive is amazing, Thanks a lot :-)

**Comment by jacobaraujo7** [comment]
Any ideas on this issue?

**Comment by leisim** [comment]
Does it still happen with the new version (`v1.2.0-dev3`)?

**Comment by leisim** [comment]
Please reopen if you still experience this issue.

**Comment by gmukul01** [comment]
@leisim openBoxFromBytes is not exported in the below version:

hive: ^1.4.0+1
hive_flutter: ^0.3.0+1

**Comment by awaik** [comment]
```- Removed `Hive.openBoxFromBytes()` (use the `bytes` parameter of `Hive.openBox()` instead)```
hive-1.4.1+1/CHANGELOG.md
