### ISSUE TITLE
Hive 3.0 Beta vs Isar

### ISSUE THREAD

**Issue by mikhael28** [hivedb/hive#1148]
**Question**
I was wondering, what exactly is new in Hive 3.0? You mention a 'in-memory storage backend' - would someone explain what implications this has? I'm not seeing any documentation in particular, I apologize if I'm missing something. A link would be more than fine. 

I am also wondering, is Hive going to be supported in the future? I was under the impression that Isar was going to be the database of the future, and that Hive is essentially going to be unsupported moving forward outside of API changes to adapt to new Dart/Flutter SDK requirements. 

I would be interested to know whether, from the maintainers/communities perspective, whether it makes sense to upgrade completely to Isar from Hive (at the very least, for new projects), or stick with Hive?

**Comment by mikhael28** [comment]
Release notes I mentioned: https://pub.dev/packages/hive/versions/3.0.0-dev/changelog

**Comment by xpwmaosldk** [comment]
I'm curious too. It just says to use Isar, and why it should be used and why 3.0 persists is not explained.

**Comment by mikhael28** [comment]
I think, from my perspective, Hive is a perfect little kv store - I don't see myself needing to migrate to Isar, as the functionality that Hive has for my use case (non-encrypted data store) is perfect.
