### ISSUE TITLE
Hive & BLoC

### ISSUE THREAD

**Issue by peekpt** [hivedb/hive#116]
**Questions**
1. What is the best approach to use Hive With Bloc?
2. Should it be initialized in main(), or could it be initialized in the BLoC?
3. Should be used WatchBoxBuilder or should  be used a BLoC exporting state to BlocBuilder?
4. What's the best way to watch a box inside the BLoC and yield a State?

**Comment by leisim** [comment]
Unfortunately I have never really used BLoC (it has too much overhead imo). So I don't know best practices or how to use Hive with BloC optimally.

If someone is experienced with BloC and has some ideas for improvements, I'll help implementing :+1:

**Comment by jonataslaw** [comment]
I use BLoC with Slidy CLI and bloc_pattern (you should probably use flutter_bloc, but the foundation is the same) and I have 2 approaches to using Hive in my projects.
The safest:
I create a database_service.dart
inside it I create the init () method;
And I initialize all my boxes in it.

I also create in this class the insert, delete, and any other method you need.

I create a SplashScreen, and in it I call service init.

////////////////////////////////
You can also use FutureBuilder in the first widget below your materialApp and use service_database init as the future to ensure all your boxes are open. So you can use them without await anywhere in the code.

Use WatchBoxBuilder, object and variable access is not business logic.

**Comment by peekpt** [comment]
Thank you for your reply. Well I may agree with you on the Business part but Hive already has CRUD  integrated and I think it's over coding encapsulating it with bloc. Also Hive uses models as HiveObject to read write from database. Boxes are also synced once you open them.

**Comment by wisecoders** [comment]
I am initializing it with Main. 

in my repository, I am just checking if the data exists in Hive Box, I am reading it from there and sending the list back to my Bloc else getting it from API and storing it in Hive and send the list to my Bloc.  

using Watchbox build to my shoppingCart like the one attached.

![Screenshot_20191115-090555](https://user-images.githubusercontent.com/6834902/68949114-5a964b80-0787-11ea-83a5-15ab82ac374e.png)

**Comment by peekpt** [comment]
What I'm trying to say is that using BLoc  is a bit redundant and adding extra code to the equation. let's see a pratical example:

a Bloc which outputs a list state.
The events are AddItem, UpdateItem and RemoveItem.
you have to do ifs inside the BLoC and yield the state.
In the Bloc Builder you have to do ifs again to find the event you want. 
Another extra work if you want the Blocbuilder to listen only to one key.
Besides that you need to work with key for hiveObject ex: RemoveItem(key).

Add List Animations to the equation and you are in trouble
