### ISSUE TITLE
Allow deletion of encrypted box on error.

### ISSUE THREAD

**Issue by JonnyBorges** [hivedb/hive#117]
**Steps to Reproduce**
I have a production application that I use hive to store user tokens. I use it in conjunction with Flutter_secure_storage to ensure token storage security.
However, if the user exits the application at login (where an encrypted box has already been opened), they will no longer be able to write their token as a new hash will be generated, Flutter_secure_storage will deliver a different hash than the one it was created in. , and you just can't delete the box, because you can't open it.
In this case of "lost secure-key" the only way to log in is to uninstall and reinstall the application, and I would like to have some way to delete the box if something goes wrong, as often the generated key may not be written to secure_storage (imagine that the app suddenly closes, or the battery runs out, or something), in which case there is no way to override secure_key.

**Code sample**
```dart

var boxsecure = await Hive.openBox(
      'secure',
      encryptionKey: "lost_key",
    ); // works, but... imagine that the moment I was writing the key in SecureStorage, 
       // the smarthphone has shut down or the app is unexpectedly closed.

 var boxsecure = await Hive.openBox(
      'secure',
      encryptionKey: "wrong_key",
    );

//Now, imagine that you will generate new key:
var new_key = Hive.generateSecureKey();

var boxsecure = await Hive.openBox(
      'secure',
      encryptionKey: "new_key",
    ); // don't work :( box corrupted

//Now, delete key on error:

 boxsecure.delete("Token"); // don't work because the box isn't opened :(


```
I suppose this behavior is intentional, however, I suggest there is a way to force the deletion of an encrypted box, or even better, to destroy all its contents in case of loggout.
example:
```dart
boxsecure.delete("Token").forced();
```
or 

```dart
boxsecure.deleteAll().forced;
```

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: all
 - Hive version: all

**Comment by leisim** [comment]
I'll implement a way to delete a box which has not been opened in the next version.

Unfortunately Hive has no way of knowing if your encryption key is correct. While opening a box with an incorrect key *might* fail, it may also succeed (it will always succeed with a lazy box).

You should implement a check yourself. I recommend storing the hash of your key in a seperate box (please use a cryptographic hashing algorithm like SHA256) and compare it before opening the encrypted box.

**Comment by leisim** [comment]
This is now possible in v1.2.0 using `Hive.deleteBoxFromDisk()`.
