### ISSUE TITLE
Using Hive DB in a Background Process

### ISSUE THREAD

**Issue by clicksrv** [hivedb/hive#122]
**Question**
I am trying to run a background process in Flutter where the contents of my Hive box are updated periodically. I understand that I've to most probably use an Isolate to achieve background dart execution, but I'm unsure how to go about it.

Can anybody help me out here, probably with a small sample? I am new to Isolates, and quite confused as to how to approach this.

**Version**
 - Platform: iOS, Android
 - Flutter version: 1.10.15
 - Hive version: 1.1.1

**Comment by leisim** [comment]
Unfortunately, Hive does not support opening boxes in multiple isolates. That means you can either close the box in the main isolate, update it in your background isolate and reopen it in the main isolate or you pass the data from the background to the main isolate and perform the update there...

**Comment by clicksrv** [comment]
So yes, I will only be executing from this isolate when the app is closed, from the background service. I hope that will resolve the concurrency issue.

**Comment by leisim** [comment]
Then it is no problem. You cannot do anything wrong. Hive checks if a box is opened in another isolate and throws an exception which tells you what is going on...

**Comment by clicksrv** [comment]
Could you please help me with a small sample of how I can do this on an Isolate? How I would write and execute such an isolate in the first place?

**Comment by marcelgarus** [comment]
Creating an Isolate is simple in Flutter, there's a `compute` function that automatically creates one. Otherwise, you'd need to manually spawn an Isolate via `Isolate.spawn`. It's possible to have Dart code execute in the background while the app isn't running, but it's not very well documented yet. Here's the [only piece about background execution on the Flutter website](https://flutter.dev/docs/development/packages-and-plugins/background-processes), which just points to a Medium article with sample code.

**Comment by clicksrv** [comment]
Thanks @marcelgarus, I've already had a look at these resources. Still having a bit of a tough time figuring out how to get it to work. The medium article is not beginner friendly. What I understand is that the background processes need to be set up using native code which will be called from flutter. Now, from that native code that gets executed, I need to call flutter/dart code (which will be in an isolate).

**Comment by clicksrv** [comment]
I tried implementing this with compute(), and here is the code that i've written:

```
Future<void> executeBgUpdate() async {
  return compute(_performUpdate, null);
}

Future<void> _performUpdate(_) async {

  WidgetsFlutterBinding.ensureInitialized();
  final appDocumentDir =
  await path_provider.getApplicationDocumentsDirectory();
  Hive.init(appDocumentDir.path);

  final _productList = await Hive.openBox(ProductManager.boxName);

  List<Future<Product>> futures = List<Future<Product>>();

  for (var product in _productList.values) {
    Future<Product> productFuture = ProductProvider().refreshProduct(product);
    futures.add(productFuture);
    productFuture.then((result) async =>
    await _productList.put(result.hashCode, result));
  }

  return Future.wait(futures);
}
```

I started without the `WidgetsFlutterBinding.ensureInitialized();`, but I caught an exception asking me to add this, and I added this, but now I am getting an error on this:

```
E/flutter (14862): [ERROR:flutter/lib/ui/ui_dart_state.cc(144)] Unhandled Exception: Exception: error: native function 'Window_setNeedsReportTimings' (2 arguments) cannot be found
E/flutter (14862): #0      Window.onReportTimings= (dart:ui/window.dart:955:7)
E/flutter (14862): #1      SchedulerBinding.addTimingsCallback (package:flutter/src/scheduler/binding.dart:233:14)
E/flutter (14862): #2      SchedulerBinding.initInstances (package:flutter/src/scheduler/binding.dart:206:7)
E/flutter (14862): #3      PaintingBinding.initInstances (package:flutter/src/painting/binding.dart:21:11)
E/flutter (14862): #4      SemanticsBinding.initInstances (package:flutter/src/semantics/binding.dart:22:11)
E/flutter (14862): #5      RendererBinding.initInstances (package:flutter/src/rendering/binding.dart:29:11)
E/flutter (14862): #6      WidgetsBinding.initInstances (package:flutter/src/widgets/binding.dart:253:11)
E/flutter (14862): #7      new BindingBase (package:flutter/src/foundation/binding.dart:56:5)
E/flutter (14862): #8      new _WidgetsFlutterBinding&BindingBase&GestureBinding (package:flutter/src/widgets/binding.dart)
E/flutter (14862): #9      new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding (package:flutter/src/widgets/binding.dart)
E/flutter (14862): #10     new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding (package:flutter/src/widgets/binding.dart)
E/flutter (14862): #11     new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding (package:flutter/src/widgets/binding.dart)
E/flutter (14862): #12     new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding (package:flutter/src/widgets/binding.dart)
E/flutter (14862): #13     new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding (package:flutter/src/widgets/binding.dart)
E/flutter (14862): #14     new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding (package:flutter/src/widgets/binding.dart)
E/flutter (14862): #15     new WidgetsFlutterBinding (package:flutter/src/widgets/binding.dart)
E/flutter (14862): #16     WidgetsFlutterBinding.ensureInitialized (package:flutter/src/widgets/binding.dart:1083:7)
E/flutter (14862): #17     _performUpdate (package:price_tracker/services/background_update_service.dart:17:25)
E/flutter (14862): #18     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
E/flutter (14862): #19     _performUpdate (package:price_tracker/services/background_update_service.dart:15:28)
E/flutter (14862): #20     _IsolateConfiguration.apply (package:flutter/src/foundation/_isolates_io.dart:77:16)
E/flutter (14862): #21     _spawn.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:84:45)
E/flutter (14862): #22     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
E/flutter (14862): #23     _spawn.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:84:5)
E/flutter (14862): #24     Timeline.timeSync (dart:developer/timeline.dart:161:22)
E/flutter (14862): #25     _spawn (package:flutter/src/foundation/_isolates_io.dart:82:18)
E/flutter (14862): #26     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
E/flutter (14862): #27     _spawn (package:flutter/src/foundation/_isolates_io.dart:80:26)
E/flutter (14862): #28     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:308:17)
E/flutter (14862): #29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by leisim** [comment]
I have no idea why this error happens but it has probably nothing to do with Hive.

I would try to remove code until it works to see what causes this error...

**Comment by clicksrv** [comment]
Yes @leisim, the code hasn't reached the Hive part. So, in order to initialize Hive, I'm using path_provider, which in turn requires the app to be running (and hence we're using WidgetsFlutterBinding.ensureInitialized if we execute Hive.init() before our app starts.

But the isolate is a thread with completely independent memory, so we have to initialize a session in the isolate for Hive. But we don't have the Flutter session running for the isolate, and running `await path_provider.getApplicationDocumentsDirectory();` isn't working, even with WidgetsFlutterBinding.ensureInitialized. How do I solve this issue, considering I don't want the box placed anywhere outside of the app's respective document directory?

**Comment by leisim** [comment]
Maybe you could call `getApplicationDocumentsDirectory()` in you main isolate and pass it to the `performUpdate()` isolate.

**Comment by clicksrv** [comment]
Yes, I did that and it is working now!

**Comment by stilyng94** [comment]
Sorry for bringing the issue up again. Firebase Messaging onBackground handler executes code in a background isolate [link](https://firebase.flutter.dev/docs/messaging/usage#background-messages). I called `Hive.close()` to close to Hive when app enters in the background mode so that i can call it from the onBackground Isolate. I can receive a notification and store but on app resume when i read from hive i still get my old stale data until i restart the application. Please help me.

**Comment by TheMisir** [comment]
> Sorry for bringing the issue up again. Firebase Messaging onBackground handler executes code in a background isolate [link](https://firebase.flutter.dev/docs/messaging/usage#background-messages). I called `Hive.close()` to close to Hive when app enters in the background mode so that i can call it from the onBackground Isolate. I can receive a notification and store but on app resume when i read from hive i still get my old stale data until i restart the application. Please help me.

Because dart isolates doesn't shares memory, hive instance on UI isolate doesn't notice the change when you do something on background isolate. So you might have to somehow notify your UI isolate to reload data (by closing / reopening boxes).

**Comment by stilyng94** [comment]
> Because dart isolates doesn't shares memory, hive instance on UI isolate doesn't notice the change when you do something on background isolate. So you might have to somehow notify your UI isolate to reload data (by closing / reopening boxes).

I have a code implemented a code that closes all the boxes upon app going to Background mode and Reopen them when app is in Foreground. Yet still the data can't sync. Can you please help me with a code solving it or direct me to an article.

**Comment by madd-project** [comment]
You did a Great work @clicksrv 
Everyone said, you can't able to do this Task with the Hive..

But irrespective of the what world says, you stayed in yourself.

You are Really an inspiring @clicksrv .

I was trying to Make use of Hive and also Background Services, but I am not able to do it.

Can you Write down Code (just minimal), that was working fine (before closing the issue), 
So to help others that are facing it including me..

Love you
Thanks...

**Comment by anilthapa1939** [comment]
> > Because dart isolates doesn't shares memory, hive instance on UI isolate doesn't notice the change when you do something on background isolate. So you might have to somehow notify your UI isolate to reload data (by closing / reopening boxes).
> 
> I have a code implemented a code that closes all the boxes upon app going to Background mode and Reopen them when app is in Foreground. Yet still the data can't sync. Can you please help me with a code solving it or direct me to an article.

Hey when you go to background and again come to foreground  how you open the boxes ?
I am getting error 'box has been alreay closed' while opening boxes

**Comment by nimisane** [comment]
I am facing the same issue did anyone find any solutions?

**Comment by kishan-dhankecha** [comment]
Hi @madd-project, Did you get around this problem?

**Comment by jefrrey017** [comment]
If anyone is trying to update your Hive DB from a background process (in my case onBackgroundMessage handler of firebase_messaging), follow this [stackoverflow answer](https://stackoverflow.com/a/70787554/13554826).

It worked like a charm for me

**Comment by kishan-dhankecha** [comment]
@jefrrey017 Yes, that I already tried.

Issue with [this solution](https://stackoverflow.com/questions/70730631/how-can-i-update-the-ui-widget-when-hive-data-get-update-inside-onbackgroundmess/70787554#70787554) is that, as the isolate (created by firebase background handler) can not use `Hive.initFlutter();` we need to use the `Hive.init();`. So that isolate can perform [hive operations in pure dart environment](https://docs.hivedb.dev/#/?id=initialize). But in `Hive.init();` it is necessary to pass path of the directory where we want to store our DB. So I tried calling `getApplicationDocumentsDirectory();` from `path_provider` which will not work in that pure dart isolate because there is no relation with flutter.

As result, While app is in background (not terminated), [this solution](https://stackoverflow.com/questions/70730631/how-can-i-update-the-ui-widget-when-hive-data-get-update-inside-onbackgroundmess/70787554#70787554) works fine but as app is terminated this solution will not work.

**Comment by jefrrey017** [comment]
@kishan-dhankecha I forgot to mention this. In your background message handler, place this line at the first,
`
DartPluginRegistrant.ensureInitialized();
`
This will register all your plugins so that you can use any of your plugins without ending up in an exception.

A complete example,

```

Future<void> backgroundNotificationHandler(RemoteMessage message) async {
 DartPluginRegistrant.ensureInitialized();
//// REST OF THE CODE
}
```
