### ISSUE TITLE
Generated TypeAdapter should use final for local variable declarations

### ISSUE THREAD

**Issue by marcelgarus** [hivedb/hive#130]
**Steps to Reproduce**
Enable `prefer_final_locals` in the `analysis_options.yaml` file of a project that also generates hive type adapters.
The linter will show errors for the generated code. Currently, there's [no way to opt-out of linting in generated files](https://github.com/dart-lang/linter/issues/320).

**Code sample**
Here's the code being generated:
```dart
@override
User read(BinaryReader reader) {
  var numOfFields = reader.readByte();
  var fields = <int, dynamic>{
    for (var i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
  };
  return User(...);
}
```
It would be nice if we used `final` instead of `var`:
```dart
@override
User read(BinaryReader reader) {
  final numOfFields = reader.readByte();
  final fields = <int, dynamic>{
    for (var i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
  };
  return User(...);
}
```

**Comment by leisim** [comment]
The reason why the entire project does not use final locals is that it is [not recommended](https://github.com/dart-lang/pedantic#unused-lints) by the pendatic project.

> `prefer_final_locals` does not reflect common usage.

**Comment by marcelgarus** [comment]
Oh, I see. That's fine then

**Comment by sgehrman** [comment]
Same issue.  I'm using analysis_options which does require prefer_final_locals and it would be great if you could fix it as I have to fix them by hand to get rid of the warnings.

**Comment by sgehrman** [comment]
I'm also seeing

"Type annotate public APIs"

  @override
  final typeId = 0;
