### ISSUE TITLE
Opening another box cancels existing objects id

### ISSUE THREAD

**Issue by Skyost** [hivedb/hive#131]
**Steps to Reproduce**
Open a first box and get an object from it. Open another box and then try to get `object.key` : it returns `null`.

**Code sample**
```
// A, B extends HiveObject
Box<A> testBox = Hive.openBox<A>('a');
A object = testBox.getAt(0);
print(object.key); // Prints a number.
Hive.openBox<B>('b');
print(object.key); // Prints null.
```

**Version**
 - Platform: iOS?, Android, Mac?, Windows?, Linux?, Web?
 - Flutter version: 1.9.1
 - Hive version: 1.1.1

**Comment by leisim** [comment]
Your code does not work for me. `A` seems to be a type so you cannot call `A.key`.

**Comment by Skyost** [comment]
Oops, yes you're right. It was `object` instead of `A`.

**Comment by leisim** [comment]
Could you please test again with v1.2.0?

**Comment by Skyost** [comment]
I'm gonna test it in a few days :wink:

**Comment by leisim** [comment]
Please reopen if you still have this problem with v1.2.0
