### ISSUE TITLE
Data saved to the wrong box, if boxNames are similar.

### ISSUE THREAD

**Issue by pro100svitlo** [hivedb/hive#133]
I have two boxes with similar names. 
First - Box(`name`), - second Box(`other_name`).
As first step, I add list of objects\<A\> to the first box. Then add list of objects\<B\> to the second box. Until I close first box, everything is ok: `Box(name).values` returns me `Itterable<A>`, which I can convert to list.
But as soon as I close first box (or restart app), `Box(name).values` returns me `MappedItterable`, which for some reasons contains objects\<B\>.

In case names are different - everything works fine.

**Comment by nnior** [comment]
I have the same problem.
At first it works perfect, but when I restart the application I get the following error:

`type 'GlobalProduct' is not subtype of type 'Product' in type cast`

In my case, I have these two boxes

```dart
Hive.openBox<Product>('product_box'),
Hive.openBox<GlobalProduct>('global_product_box'),
```


I am using this version:
Channel beta, v1.10.7

**Comment by leisim** [comment]
I cannot reproduce this issue. I tried the following code and it works fine:
```dart
import 'dart:io';

import 'package:hive/hive.dart';

class A {
  String name;

  A(this.name);

  @override
  String toString() {
    return name;
  }
}

class AAdapter extends TypeAdapter<A> {
  @override
  A read(BinaryReader reader) {
    return A(reader.readString());
  }

  @override
  void write(BinaryWriter writer, A obj) {
    writer.writeString(obj.name);
  }
}

class B {
  String name;

  B(this.name);

  @override
  String toString() {
    return name;
  }
}

class BAdapter extends TypeAdapter<B> {
  @override
  B read(BinaryReader reader) {
    return B(reader.readString());
  }

  @override
  void write(BinaryWriter writer, B obj) {
    writer.writeString(obj.name);
  }
}

void main() async {
  Hive.init(Directory.current.path);
  Hive.registerAdapter(AAdapter(), 0);
  Hive.registerAdapter(BAdapter(), 1);

  var boxA = await Hive.openBox('name');
  await boxA.addAll([A('A1'), A('A2'), A('A3')]);

  var boxB = await Hive.openBox('other_name');
  await boxB.addAll([B('B1'), B('B2'), B('B3')]);

  await boxA.close();
  await boxB.close();

  boxA = await Hive.openBox('name');
  print(boxA.values.toList());

  boxB = await Hive.openBox('other_name');
  print(boxB.values.toList());
}
```

**Comment by leisim** [comment]
Please try the new version and reopen the issue if you still have this problem.
