### ISSUE TITLE
Downsides of using Hive as persistent statemanagement

### ISSUE THREAD

**Issue by muellercornelius** [hivedb/hive#134]
I just red the documentation of your library and I like the intuitive way of using it. 

This brought one question to me. Whats the downside of using Hive instead of Bloc?
Yes I know Bloc is a pattern and not a db.... But most of the time the goal of Bloc is to access and modify data from every widget in your app. But the same thing works with Hive as well.

Yes of course you can modify the data from different places and it is not that easy to keep track but the data is everywhere accesible....

Am I missing something important why I shouldnt do that?

**Comment by leisim** [comment]
Be careful. Hive is not a state management solution and should not be used like one.

State can change **very** offen (for example when you create a download bar) Hive would persist each state change which would be unnecessary and expensive.

If you want to **persist** state like the text entered into a form, Hive is a great solution.

**Comment by muellercornelius** [comment]
Yes ok thats true.... I thought about using it to remember if the menu is open and how a list is filtered...

**Comment by leisim** [comment]
> I thought about using it to remember if the menu is open and how a list is filtered...

Hive is perfect for this.

**Comment by peekpt** [comment]
Hive is to be used reflecting user actions like add, delete, modify. Not to be used with widget to widget actions, like progress bar, animations.

**Comment by leisim** [comment]
Please reopen if it is still unclear...
