### ISSUE TITLE
WatchBoxListener

### ISSUE THREAD

**Issue by peekpt** [hivedb/hive#136]
Like BlocListener.

It doesn't rebuild widgets , just a widget that injects functionality in the tree
The builder doesn't return a widget instead you have a child:

WatchBoxListener (
 builder:(context, box) {
    // the code

  },
  child: ...
)

**Comment by leisim** [comment]
What does the code in the `builder()` do?

**Comment by peekpt** [comment]
Ex: fire a snackbar

**Comment by luizjunior05** [comment]
Similar error here.

> hive: ^1.2.0-dev2
> hive_flutter: ^0.2.1

```
return MaterialApp(
        home: BlocBuilder<AuthenticationBloc, AuthenticationState>(
          builder: (context, state) {
            if (state is Uninitialized || (state is Loading)) {
              return SplashScreen();
            }
            if (state is Unauthenticated) {
              return LoginScreen(firebaseService: _firebaseService);
            }
            if (state is Authenticated) {
              return WatchBoxBuilder(
                  box: Hive.box('settings'),
                  builder: (context, box) {
                    if (box.isEmpty || box.get('intro_init')) {
                      return IntroScreen(user: state.user);
                    } else {
                      return HomeScreen();
                    }
                  });
            }
            return Container();
          },
        ),
        theme: ThemeData(primaryColor: Colors.blue),
        debugShowCheckedModeBanner: false,
        routes: Routes.routes);
```

**Comment by luizjunior05** [comment]
> Similar error here.
> 
> > hive: ^1.2.0-dev2
> > hive_flutter: ^0.2.1
> 
> ```
> return MaterialApp(
>         home: BlocBuilder<AuthenticationBloc, AuthenticationState>(
>           builder: (context, state) {
>             if (state is Uninitialized || (state is Loading)) {
>               return SplashScreen();
>             }
>             if (state is Unauthenticated) {
>               return LoginScreen(firebaseService: _firebaseService);
>             }
>             if (state is Authenticated) {
>               return WatchBoxBuilder(
>                   box: Hive.box('settings'),
>                   builder: (context, box) {
>                     if (box.isEmpty || box.get('intro_init')) {
>                       return IntroScreen(user: state.user);
>                     } else {
>                       return HomeScreen();
>                     }
>                   });
>             }
>             return Container();
>           },
>         ),
>         theme: ThemeData(primaryColor: Colors.blue),
>         debugShowCheckedModeBanner: false,
>         routes: Routes.routes);
> ```

I made several package updates and it is now running as expected.

**Comment by leisim** [comment]
@luizjunior05 this is issue is a feature request. You should open your own issue and explain the problem you are experiencing.

**Comment by leisim** [comment]
@peekpt `WatchBoxBuilder` has been deprecated with `hive_flutter` v0.3.0-dev. You can achieve the desired behavior with `ValueListenableBuilder`:

```dart
ValueListenableBuilder(
  valueListenable: yourBox.listenable(),
  child: Text('Some Widget'),
)
```
