### ISSUE TITLE
BoxImpl.get type cast error

### ISSUE THREAD

**Issue by AlexVincent525** [hivedb/hive#144]
**Error Log**
```
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<int, List<AppMessage>>' in type cast
#0      BoxImpl.get (package:hive/src/box/box_impl.dart:34:26)
#1      MessagesProvider.initMessages (package:app/providers/MessagesProvider.dart:29:28)
```

**Steps to Reproduce**
1. Create a box with `Map<int, List<AppMessage>>`.
2. Open the box and wrote some value to box. Such as `appMessagesBox.put(userId, Map<int, List<AppMessage>>())`
3. Hot restart app, the error occurs.

**Code sample**
```
class HiveBoxes {
  static int adapterIndex = 0;
  static Box<Map<int, List<AppMessage>>> appMessagesBox;
  static Future openBoxes() async {
    Hive.registerAdapter(AppMessageAdapter(), adapterIndex++);
    appMessagesBox = await Hive.openBox<Map<int, List<AppMessage>>>('app_messages');
  }
}
```
```
void initMessages() {
  final appBox = HiveBoxes.appMessagesBox;
  if (!appBox.containsKey(currentUser.uid)) {
    appBox.put(currentUser.uid, Map<int, List<AppMessage>>());
  }
  _appsMessages = appBox.get(currentUser.uid).cast<int, List<AppMessage>>();
}
```

**Version**
 - Platform: NOT FULLY TESTED
 - Flutter version: 1.9.1+hotfix.6
 - Hive version: `hive: 1.1.1` `hive_flutter: ^0.2.1`

Cast does't take any effect, is there anything I have missed?

**Comment by AlexVincent525** [comment]
Error log:
```
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<int, List<AppMessage>>' in type cast
#0      BoxImpl.get (package:hive/src/box/box_impl.dart:34:26)
#1      MessagesProvider.initMessages (package:app/providers/MessagesProvider.dart:29:28)
```

**Comment by leisim** [comment]
This is the problem: `Hive.openBox<Map<int, List<AppMessage>>>` due to Dart limitations you can only do the following: `Hive.openBox<Map>`.

You can still put objects of type `Map<int, List<AppMessage>>` in that box but you have to cast them manually.

**Comment by AlexVincent525** [comment]
@leisim Thx and I have figured it out hours ago!
And now the method to handle this is:
```
class HiveBoxes {
  static int adapterIndex = 0;
  static Box<Map> appMessagesBox;

  static Future openBoxes() async {
    Hive.registerAdapter(AppMessageAdapter(), adapterIndex++);
    appMessagesBox = await Hive.openBox<Map>('app_messages');
  }
}
```
```
Map<int, List> _appsMessages;
final appBox = HiveBoxes.appMessagesBox;
var _tempAppsMessages = appBox.get(currentUser.uid);
_appsMessages = _tempAppsMessages.cast<int, List>();
```

**Comment by leisim** [comment]
Perfect :+1:

**Comment by AlexVincent525** [comment]
But I still have some other question, I just write it here without a new issue.

Though data was stored in memory and the values like maps or list was passed by object, can a custom class's properties update be saved in the data?

For now try something like:
```
void _incomingAppsMessage(MessageReceivedEvent event) {
  final message = AppMessage.fromEvent(event);
  if (!_appsMessages.containsKey(message.appId)) {
    _appsMessages[message.appId] = <AppMessage>[];  // [_appMessages] was a map using `get` from the box.
  }
  _appsMessages[message.appId].insert(0, message);
  final tempMessages = List.from(_appsMessages[message.appId]);
  _appsMessages.remove(message.appId);
  _appsMessages[message.appId] = List.from(tempMessages);

  saveAppsMessages();  // Save data manually.
  notifyListeners();
}
```
```
void saveAppsMessages() {
  HiveBoxes.appMessagesBox.put(currentUser.uid, Map.from(_appsMessages));
}
```
Is there a proper way?

**Comment by AlexVincent525** [comment]
And the custom class's properties modify:
```
message.read = true;  // [message] is from the list in [_appsMessages].
saveAppsMessages();
```

**Comment by leisim** [comment]
Sorry I don't quite understand your question.

**Comment by AlexVincent525** [comment]
As you can see, my data type is `Map<int, List<AppMessage>>`. When I `get` a `List<AppMessage>` from the box and changed one of them, such as it's `read` properties, I found out that the changes didn't saved in the box.

**Comment by leisim** [comment]
No it isn't. Hive has no way of knowing when your data changes.

You can either wrap your object with `HiveObject` and use the `save()` method or you just override your previous value.

**Comment by AlexVincent525** [comment]
I already done with `HiveObject`, maybe my data structure was too complicate.
Anyway huge thanks for helping me! ❤️

**Comment by Mayb3Nots** [comment]
Thank you your post helped me a lot. I wasted hours on finding out why my map won't work. I feel like this should be documented better in the docs. I can help to write if you need someone to. Thanks again
