### ISSUE TITLE
Hi Hive guys

### ISSUE THREAD

**Issue by erkhprojects** [hivedb/hive#147]
**Question**
Please explain the problem you are running into.

**Code sample**
```dart
Provide a few simple lines of code to show your problem.
```

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: [e.g. 1.5.4]
 - Hive version: [e.g. 0.5.0]

**Comment by leisim** [comment]
I think you opened this issue by mistake...
