### ISSUE TITLE
Lost score on pub.dev

### ISSUE THREAD

**Issue by erkhprojects** [hivedb/hive#148]
Hi Hive guys I recently checkout your pub.dev page and it seems like you have been lost a great amount of your stability score. 
I recently used your library in my app and the app is online and I woundring about changing my local db to sth else . would you please give us some more info about this?
thank you

**Comment by leisim** [comment]
Hi, I understand your concern. The reason for the lost score is a fixed bug in the Dart analyzer (dart-lang/sdk#39752). When they release a new analyzer, the score will be fixed.

**Comment by leisim** [comment]
I found a workaround to the analyzer bug. `v1.2.0` has a score of 98.
