### ISSUE TITLE
Save non-ASCII characters

### ISSUE THREAD

**Issue by lurcas** [hivedb/hive#149]
How to save non-ASCII characters? I need to save german and french letters like ö,ü or é.

When I try to save strings with these chars I get error:

Unhandled Exception: HiveError: String contains non-ASCII characters.

**Comment by leisim** [comment]
You can save non-ASCII characters as value. Keys need to be ASCII.

**Comment by leisim** [comment]
@lurcas did it work?

**Comment by lurcas** [comment]
Yes it was just the keys. Maybe you should mention that in the docs.

Thanks for the quick help :)

**Comment by leisim** [comment]
https://docs.hivedb.dev/more/limitations

**Comment by lurcas** [comment]
ahh sorry, my fault
