### ISSUE TITLE
hive_generator v0.6.0 does not support final fields

### ISSUE THREAD

**Issue by leisim** [hivedb/hive#154]

**Comment by lesnitsky** [comment]
wasted almost an hour figuring out why objects are empty... :(

**Comment by leisim** [comment]
> wasted almost an hour figuring out why objects are empty... :(

Sorry :/

**Comment by leisim** [comment]
Fixed with latest version of `hive_generator`.

**Comment by lesnitsky** [comment]
Thanks!
