### ISSUE TITLE
Why is it necessary for HiveList members to extend HiveObject?

### ISSUE THREAD

**Issue by SepRST** [hivedb/hive#155]
I need to use HiveList with an immutable object, but HiveObject is not immutable. as mentioned in the docs, extending HiveObject is supposed to be optional. are there any technical reasons for ```HiveList<T extends Hiveobject>```?

```dart
// this gives the following warning:
// This class (or a class which this class inherits from) is marked as '@immutable', 
// but one or more of its instance fields are not final: HiveObject._box, HiveObject._keydart(must_be_immutable)
@immutable
class Person extends HiveObject {
  final String name;
  final HiveList<Person> friends;
  Person({@required this.name, @required this.friends});
}
```

 - Hive version: 1.2.0

**Comment by leisim** [comment]
Yes, unfortunately, `HiveList` depends on its elements being `HiveObjects`. The reason is that the `HiveList` needs to know the key under which the object is stored. And `HiveObject` provides exactly that.

**Comment by leisim** [comment]
I'm going to close this issue because currently there is nothing I can do. While extending `HiveObject` is still optional, they add a lot of convenience and I strongly suggest to extend it.

Queries will also rely heavily on `HiveObject`.

**Comment by gruvw** [comment]
Can't we just use ` with HiveObjectMixin` instead ?
Wouldn't that let the object stay immutable ?
