### ISSUE TITLE
Adding Hive.openAndCloseBox

### ISSUE THREAD

**Issue by azilvl** [hivedb/hive#156]
Sometimes I only need to open a box to do something with it and then close it immediately. but one might forget to close the box and since dart doesn't have `using blocks` and `disposables` a function that automatically does it for you might be useful. what do you think?

currently, I use this extension method to do it. I'm not good at naming things though.
```dart
typedef BoxFunction<E, TResult> = TResult Function(Box<E> box);

extension HiveExtentions on HiveInterface {
  Future<TResult> openAndCloseBox<E, TResult>(
    String name,
    BoxFunction<E, FutureOr<TResult>> function, {
    List<int> encryptionKey,
    KeyComparator keyComparator,
    CompactionStrategy compactionStrategy,
    bool crashRecovery = true,
    bool lazy = false,
  }) async {
    var box = await this.openBox<E>(name,
        compactionStrategy: compactionStrategy,
        crashRecovery: crashRecovery,
        encryptionKey: encryptionKey,
        keyComparator: keyComparator,
        lazy: lazy);
    var result = await function(box);
    await box.close();
    return result;
  }
}
```
usage:
```dart
int key = await Hive.openAndCloseBox('persons', (box) async {
    return await box.add(person);
  });
```
or:
```dart
Person person = await Hive.openAndCloseBox('persons', (box) async {
    return await box.getAt(0);
  });
```

**Comment by azilvl** [comment]
maybe Hive.usingBox() is a better name?

**Comment by leisim** [comment]
Could you give me an example where you need this method? Generally I recommend not to close boxes just to open them again later.
Opening a box is the most expensive operation you can do with Hive. All the data is loaded and stored in RAM.

**Comment by azilvl** [comment]
hmm.well I wanted each one of my use-cases to be independent and unaware of the state of boxes, but I guess I can open them in a lazy singleton class since I don't think my boxes take that much of ram. 
if you don't recommend it then it makes sense to not include it in the API.
