### ISSUE TITLE
unnecessary exception 'HiveObjects needs to be in the box "$boxName".'

### ISSUE THREAD

**Issue by azilvl** [hivedb/hive#157]
so I was trying `HiveList`s and realized if I try to add an object from another box it gives me an exception. 
trying to understand why that's not doable I commented out the check in the `_checkElementIsValid` function located in `hive_list_impl.dart`. and to my surprise, everything seems to be working.
```dart
  void _checkElementIsValid(E obj) {
    if (obj == null) {
      throw HiveError('HiveLists must not contain null elements.');
    // } else if (obj.box != box) {
    //   throw HiveError('HiveObjects needs to be in the box "$boxName".');
    }
  }
```
I tested adding, updating and deleting objects from a `HiveList` with members located in another box and found no issues.

**Version**
 - Platform: Windows
 - Hive version: 1.2.0

**Comment by leisim** [comment]
It works as long as you don't close and reopen the box containing the `HiveList`.

**Comment by azilvl** [comment]
How do you read the HiveList after opening it anyway?
when I reopen the box the HiveList becomes null. even if everything is in the same box and the same type.
```dart
void main(List<String> args) async {
  Hive.init(Directory.current.path);
  Hive.registerAdapter(PersonModelAdapter(), 33);
  var deleteBox = await Hive.openBox<PersonModel>('persons');
  await deleteBox.deleteFromDisk();
  var persons = await Hive.openBox<PersonModel>('persons');

  var mario = PersonModel('Mario');
  var luna = PersonModel('Luna');
  var alex = PersonModel('Alex');
  await persons.addAll([mario, luna, alex]);

  mario.friends = HiveList(persons); 
  mario.friends.addAll([luna, alex]); 
  await persons.close();

  var personsReopened = await Hive.openBox<PersonModel>('persons');
  var marioReopened = personsReopened.getAt(0);
  print(marioReopened.friends); // prints null.
}
```
what am I missing?

**Comment by azilvl** [comment]
this was a misunderstanding, my error was that I put the wrong box in the `HiveList(box)` constructor and when I saw that error I thought HiveLists can't have members outside of the parent box.
