### ISSUE TITLE
hive_generator: not generate file .g.dart

### ISSUE THREAD

**Issue by vandong9** [hivedb/hive#158]
**Steps to Reproduce**
Follow todo example.
1. Create file doto.dart and add the class todo as example
 todo.dart:
import 'package:hive/hive.dart';

@HiveType()
class Todo extends HiveObject {
  @HiveField(0)
  String name;

  @HiveField(1)
  DateTime createDate;

  @HiveField(2)
  bool done = false;
}

2. run command: flutter packages pub run build_runner build --delete-conflicting-outputs

**Result:**
I got message and there is no file todo.g.dart
(base)iMac:location user$ flutter packages pub run build_runner build --delete-conflicting-outputs
[INFO] Generating build script...
[INFO] Generating build script completed, took 561ms

[WARNING] Deleted previous snapshot due to missing asset graph.
[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 15.4s

[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 969ms

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Deleting 1 declared outputs which already existed on disk.
[INFO] Checking for unexpected pre-existing outputs. completed, took 6ms

[INFO] Running build...
[INFO] Generating SDK summary...
[INFO] 4.4s elapsed, 0/16 actions completed.
[INFO] Generating SDK summary completed, took 4.4s

[INFO] 5.5s elapsed, 1/17 actions completed.
[INFO] 6.5s elapsed, 3/19 actions completed.
[INFO] 7.7s elapsed, 3/19 actions completed.
[INFO] 8.9s elapsed, 3/19 actions completed.
[INFO] 9.9s elapsed, 3/19 actions completed.
[INFO] 11.0s elapsed, 3/19 actions completed.
[INFO] 12.1s elapsed, 3/19 actions completed.
[INFO] 13.2s elapsed, 3/19 actions completed.
[INFO] 19.9s elapsed, 4/19 actions completed.
[INFO] 21.0s elapsed, 4/20 actions completed.
[WARNING] hive_generator:hive_generator on lib/features/storage/Hive/todo.dart:
Missing "part 'todo.g.dart';".
[INFO] 22.8s elapsed, 19/21 actions completed.
[INFO] Running build completed, took 22.9s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 64ms

[INFO] Succeeded after 23.0s with 0 outputs (42 actions)

**Code sample**
```
Provide a few simple lines of code to show your problem.
```

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: [1.12.13]
 - Hive version: [1.1.1]

**Comment by leisim** [comment]
You need to add `part 'todo.g.dart'` at the beginning of your `todo.dart` file.

**Comment by vandong9** [comment]
Thanks a lot, it my fail  not follow carefully guide.

**Comment by HaitianZhuu** [comment]
> Thanks a lot, it my fail not follow carefully guide.

Hi, what's the issue you have? I have same issue but I dont know what Im missing.

**Comment by TheMisir** [comment]
> > Thanks a lot, it my fail not follow carefully guide.
> 
> Hi, what's the issue you have? I have same issue but I dont know what Im missing.

Could you share your code?

**Comment by Zchandev** [comment]
Add this to pubspec.yml:

```
dev_dependencies:
  hive_generator: ^0.8.0
```

**Comment by RanylFoumbi** [comment]
> You need to add `part 'todo.g.dart'` at the beginning of your `todo.dart` file.

Then run the follow command    flutter packages pub run build_runner build

**Comment by sauravgpt** [comment]
```
import 'package:flutter/foundation.dart';
import 'package:hive/hive.dart';

part 'vehicle.g.dart';

@HiveType(typeId: 1)
class Vehicle extends HiveObject {
  @HiveField(0)
  final String make;
  @HiveField(1)
  final String model;
  @HiveField(2)
  final String engineSize;
  @HiveField(3)
  final String vehicleIdentificationNumber;
  @HiveField(4)
  final String engineNumber;
  @HiveField(5)
  final String numberOfSeats;
  @HiveField(6)
  final String fuelType;
  @HiveField(7)
  final String registrationDate;
  @HiveField(8)
  final String location;
  @HiveField(9)
  String registrationNumber;

  Vehicle({
    @required this.make,
    @required this.model,
    @required this.engineSize,
    @required this.engineNumber,
    @required this.vehicleIdentificationNumber,
    @required this.fuelType,
    @required this.location,
    @required this.numberOfSeats,
    @required this.registrationDate,
    @required this.registrationNumber,
  });
}
```

Its not working, 
[INFO] Running build...
[INFO] 1.2s elapsed, 0/1 actions completed.
[INFO] 2.3s elapsed, 0/1 actions completed.
[INFO] 8.2s elapsed, 0/1 actions completed.
[WARNING] hive_generator:hive_generator on lib/data/models/vehicleModel.dart:
Missing "part 'vehicleModel.g.dart';".
[INFO] Running build completed, took 8.7s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 167ms

[INFO] Succeeded after 8.9s with 0 outputs (1 actions)

Got these errors

PS: I've tried putting `part 'vehicle.g.dart';` at top but still doesn't work

**Comment by AjanthaB** [comment]
Same issue here

flutter packages pub run build_runner build command does not help

Target of URI hasn't been generated: 'User.g.dart'.
Try running the generator that will generate the file referenced by the URI

**Comment by mbaumgartenbr** [comment]
> ```
> import 'package:flutter/foundation.dart';
> import 'package:hive/hive.dart';
> 
> part 'vehicle.g.dart';
> 
> @HiveType(typeId: 1)
> class Vehicle extends HiveObject {
>   @HiveField(0)
>   final String make;
>   @HiveField(1)
>   final String model;
>   @HiveField(2)
>   final String engineSize;
>   @HiveField(3)
>   final String vehicleIdentificationNumber;
>   @HiveField(4)
>   final String engineNumber;
>   @HiveField(5)
>   final String numberOfSeats;
>   @HiveField(6)
>   final String fuelType;
>   @HiveField(7)
>   final String registrationDate;
>   @HiveField(8)
>   final String location;
>   @HiveField(9)
>   String registrationNumber;
> 
>   Vehicle({
>     @required this.make,
>     @required this.model,
>     @required this.engineSize,
>     @required this.engineNumber,
>     @required this.vehicleIdentificationNumber,
>     @required this.fuelType,
>     @required this.location,
>     @required this.numberOfSeats,
>     @required this.registrationDate,
>     @required this.registrationNumber,
>   });
> }
> ```
> 
> Its not working, 
> [INFO] Running build...
> [INFO] 1.2s elapsed, 0/1 actions completed.
> [INFO] 2.3s elapsed, 0/1 actions completed.
> [INFO] 8.2s elapsed, 0/1 actions completed.
> [WARNING] hive_generator:hive_generator on lib/data/models/vehicleModel.dart:
> Missing "part 'vehicleModel.g.dart';".
> [INFO] Running build completed, took 8.7s
> 
> [INFO] Caching finalized dependency graph...
> [INFO] Caching finalized dependency graph completed, took 167ms
> 
> [INFO] Succeeded after 8.9s with 0 outputs (1 actions)
> 
> Got these errors
> 
> PS: I've tried putting `part 'vehicle.g.dart';` at top but still doesn't work

Make sure the name of both files match.

From logs: (Missing "part 'vehicleModel.g.dart';".)

**Comment by mbaumgartenbr** [comment]
> Same issue here
> 
> flutter packages pub run build_runner build command does not help
> 
> Target of URI hasn't been generated: 'User.g.dart'.
> Try running the generator that will generate the file referenced by the URI

Could you provide a simplified example of what your code looks like and the logs?

**Comment by TheMisir** [comment]
**1. Add `hive_generator` dependency**

Edit your `pubspec.yaml` to include those lines

```yaml
dev_dependencies:
  hive_generator: ^1.1.0 # <-- this line
  build_runner: ^2.0.3.  # <-- and that as well
``` 

**2. Make sure model files does contains part keyword with correct file name**

If the file that contains hive model is named `user.dart`, it should contain this line:

```dart
part 'user.g.dart';
```

**3. Run build_runner to re-generate files**

```shell
flutter pub run build_runner build --delete-conflicting-outputs
```

> If it fails, please add comment with build output logs (what's returned from build_runner build command) otherwise we can't help you. Also most of the times, build output already contains required details to fix the issue, so please check your logs before posting there.

**Comment by m-h-mridul** [comment]
my problem is :: [WARNING] hive_generator:hive_generator on lib/DataModel/AlbumModel.dart:
                          AlbumModel.g.dart must be included as a part directive in the input library with:
                           part 'AlbumModel.g.dart';
 pub.ymal
          dev_dependencies:
            build_runner: ^2.0.5
            hive_generator: ^1.1.0
command run :: flutter packages pub run build_runner build --delete-conflicting-outputs

import 'package:hive/hive.dart';
part 'AlbumModel.g.dart';

@HiveType(typeId: 1)
class AlbumModel {
  @HiveField(0)
  int? userId;
  @HiveField(1)
  int? id;
  @HiveField(2)
  String? title;

   AlbumModel({required this.userId, required this.id, required this.title});

  factory AlbumModel.fromJson(Map<String, dynamic> jsonMake) => AlbumModel(
        id: jsonMake[AlbumModelData.id],
        userId: jsonMake[AlbumModelData.userId],
        title: jsonMake[AlbumModelData.title],
      );

  Map<String, dynamic> toJson() {
    return {'userId': this.userId, 'id': this.id, 'title': this.title};
  }
}

class AlbumModelData {
  static final String tableName = 'listdata';
  static final String userId = 'userId';
  static final String id = 'id';
  static final String title = 'title';
}

**Comment by TheMisir** [comment]
@m-h-mridul the warning message already tells the issue and how to solve it:

```
[WARNING] hive_generator:hive_generator on lib/DataModel/AlbumModel.dart:
AlbumModel.g.dart must be included as a part directive in the input library with:
part 'AlbumModel.g.dart';
```

Just add `part 'AlbumModel.g.dart';` to *lib/DataModel/AlbumModel.dart*.

**Comment by m-h-mridul** [comment]
But i add this at top of the class name plz cheak

**Comment by ARDeveloper75** [comment]
![Screenshot (17)](https://user-images.githubusercontent.com/83186779/126960181-5aa961e1-6ff1-42dc-91bf-05a9442f358b.png)
 I'm following all the topic command but did not solve...

$ flutter pub run build_runner build
[INFO] Generating build script...
[INFO] Generating build script completed, took 881ms

[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 127ms

[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 1.1s

[INFO] Running build...
[INFO] 1.2s elapsed, 0/1 actions completed.

**Comment by mbaumgartenbr** [comment]
Hey @ARDeveloper75 !

Your `part` is spelled with an "s" and the main file doesn't have an "s" in favoriteProduct"s".g.dart.

Either add the "s" to the main file or remove it from the `part` declaration.

I'm pretty sure that is your issue, if not, let me know!

**Comment by ayushi-das** [comment]
![Screenshot (90)](https://user-images.githubusercontent.com/64302051/129715817-241debb3-0bfb-472c-83e4-3a661ac25c29.png)
plz help!

**Comment by themisir** [comment]
> ![Screenshot (90)](https://user-images.githubusercontent.com/64302051/129715817-241debb3-0bfb-472c-83e4-3a661ac25c29.png)
> plz help!

hive_generator uses build_runner for generating files so I don't think this issue is up to hive_generator rather build_runner.

If you've annotated your model with `@HiveType` and added `part '<filename>.g.dart';` it usually works without any issue. You might try renaming file to 'data_model.dart' and part statement to 'data_model.g.dart', I'm not sure if it'll help but might worth trying out.

**Comment by dannndi** [comment]
> ![Screenshot (90)](https://user-images.githubusercontent.com/64302051/129715817-241debb3-0bfb-472c-83e4-3a661ac25c29.png)
> plz help!

try to save the file first, it work in my case

**Comment by oyen-bright** [comment]
the part has to be the name of the file not the name of the class

**Comment by Harshhverma** [comment]
> > ![Screenshot (90)](https://user-images.githubusercontent.com/64302051/129715817-241debb3-0bfb-472c-83e4-3a661ac25c29.png)
> > plz help!
> 
> try to save the file first, it work in my case

Thanks man it's workkk+

**Comment by BarrySong97** [comment]
> > > ![Screenshot (90)](https://user-images.githubusercontent.com/64302051/129715817-241debb3-0bfb-472c-83e4-3a661ac25c29.png)
> > > plz help!
> > 
> > 
> > try to save the file first, it work in my case
> 
> Thanks man it's workkk+

hhh same for me

**Comment by tanojsaipraveen** [comment]
part name should be same as file name CASE SENSITIVE. It works for me

**Comment by Rafik-Bendjema** [comment]
> AlbumModel

that worked thanks , didn't knew it need to have the same name

**Comment by ahmedfawzy35** [comment]
Write the file name in part"filename.g.dart" not class name

**Comment by gopikarp** [comment]
![image](https://github.com/isar/hive/assets/100861026/4d0e762b-1cf9-408b-8073-df38dd6d6ab4)
is there is any solution

**Comment by mohamedkhaled239** [comment]
> flutter pub run build_runner build

add I have same problem

**Comment by zyllus17** [comment]
For those facing the issue make sure to check 5 things first.

1. Save the file before running the command
2. You must have part at the top after your imports. For eg if your file name is `db.dart` then your part will be 
```dart
part 'db.g.dart';
```
3. In your pubspec.yaml you must have these 4 packages in the correct section that is `dependencies` & `dev_dependencies`-
```yaml
dependencies:
  hive: ^2.2.3
  hive_flutter: ^1.1.0
dev_dependencies:
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

```
4. Your file must have `@HiveType(typeId: 1)` otherwise your build will run successfully without generating the build file. For my app I missed it and it was neither throwing any error to add `@HiveType` nor generating the `.g.dart file`. Just add it after the end of your class.

```dart
@HiveType(typeId: 1)
enum ThemeModes {
  @HiveField(0)
  system,
  @HiveField(1)
  light,
  @HiveField(2)
  dark,
}
```
5. Run the command to generate the build
```terminal
flutter pub run build_runner build --delete-conflicting-outputs
```

My complete code -
```dart
import 'package:flutter/material.dart';
import 'package:hive/hive.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';

part 'db.g.dart';

final dbProvider = Provider((ref) => DB());

class DB {
  static const boxName = 'skeleton';
  static const languageSelected = 'languageSelected';
  static const theme = 'theme';

  bool getLanguageSelected() {
    final bool getLanguageSelected =
        (Hive.box(DB.boxName).get(DB.languageSelected) ?? false) as bool;
    return getLanguageSelected;
  }

  ThemeModes? getThemeMode() {
    return Hive.box(DB.boxName).get(
      DB.theme,
      defaultValue: ThemeMode.light,
    ) as ThemeModes?;
  }

  void saveLanguageSelected({required bool languageSelected}) {
    final box = Hive.box(DB.boxName);
    box.put(DB.languageSelected, languageSelected);
  }

  void saveThemeMode(ThemeModes mode) {
    final box = Hive.box(DB.boxName);
    box.put(DB.theme, mode);
  }

  Future<void> removeAllData() async {
    final box = Hive.box(DB.boxName);
    final _ = await box.clear();
  }
}

  Future<void> openHiveBox() async {
    await Hive.openBox(DB.boxName);
    await Hive.openBox<ThemeModes>(DB.boxName);
  }

@HiveType(typeId: 1)
enum ThemeModes {
  @HiveField(0)
  system,
  @HiveField(1)
  light,
  @HiveField(2)
  dark,
}
```

**Comment by abdurrohmandavron** [comment]
> Write the file name in part"filename.g.dart" not class name

Thanks
