### ISSUE TITLE
Keys... Unicode some time soon ?

### ISSUE THREAD

**Issue by cconstab** [hivedb/hive#159]
**Question**
Migrating from Redis to Dart/Hive for a project and hit some Unicode Keys... I read the limitations so know what the problem is.. But would like to know if Unicode keys is on the radar for you ?

I would also love to know why the constraint? 

Thanks so much for an amazing piece of work..

Colin

**Comment by leisim** [comment]
I purposely did not support Unicode keys.

The most important thing for good performance in Hive is to read keys super fast. Decoding ASCII is much faster in Dart than Unicode.

**Comment by cconstab** [comment]
Thanks for the rapid response on Xmas eve/day.. So my best bad option then is to convert keys to ASCII and then again on the way back somehow. Suggestions welcome on the best way/place to do that, or remove the constraint understanding the hit in performance. 

 Some more background for you is my keys are in multiple languages/alphabets and unfortunately I cannot read them all.  In my case a small hit on speed would be well worth the multinational support.

The data in each box is small less than a 1k keys and I have many distributed boxes.. Plus moving away from redis would be awesome..

**Comment by cconstab** [comment]
So been thinking about this and will encode my keys to utf-7 before sending them to HiveDB and will have to decode them on the way back.. I think that will allow me to have UTF8 keys and yet still use HiveDB at full speed..
Might be something to think about to do within Hive itself?
Thanks
Colin

**Comment by leisim** [comment]
> Suggestions welcome on the best way/place to do that, or remove the constraint understanding the hit in performance.

I can create a fork which supports UTF8 it should be very little changes.

The performance hit of using UTF8 will be small but I thought the vast majority of keys will be ASCII so I decided to go with it.

> So been thinking about this and will encode my keys to utf-7 before sending them to HiveDB and will have to decode them on the way back.

I would guess that decoding to UTF-7 might be slower than using UTF-8 in the first place.

**Comment by cconstab** [comment]
A UTF8 fork would be outstanding ! Would love to have that and run it through our set of keys!

The UTF8 - 7 - 8 process is not that bad but a bit cumbersome

https://github.com/michaelspiss/dart-utf7

There is a small bug which I raised with the dev... 

But agree with you UTF8 direct would be great for me and probably others across the globe!

**Comment by cconstab** [comment]
Happy New Year! @leisim do you have an ETA on the Unicode Keys fork ? 

You must have a long backlog so an ETA would be useful for us to know.. 

Thanks!

**Comment by leisim** [comment]
Happy new year! I created a [unicode branch](https://github.com/hivedb/hive/tree/unicode-keys) but I'm not sure if I can maintain it in the long run...
Please let me know if this works for you...

**Comment by cconstab** [comment]
@leisim 
Wow that was quick and as you said only a small number of changes from the main branch..
We will test this week and let you know !

Thanks!

**Comment by cconstab** [comment]
@leisim so Unicode keys work 👍 ..... But only once.. Once the box is closed and then I try to re open it 

I get the following errors..
FormatException: Unfinished UTF-8 octet sequence (at offset 52)
or 
Invalid argument(s): Input data length must be a multiple of cipher's block size

Not sure if this is a result of compaction on exit of something else..

Thanks

Colin

**Comment by leisim** [comment]
Oh that sounds like some decoding part still expects an ASCII string... I'll take a look when I have time.

**Comment by kinex** [comment]
This sounds like an unnecessary optimization to me, I doubt if most apps really need those microseconds this is saving. Now we have to implement some workarounds like md5 hashing keys, so THAT will be SLOW. My suggestion is to add this configurable via `Hive.openBox` parameters, something like `enum KeyType {ascii, unicode}`.

**Comment by 0htls** [comment]
@TheMisir Can Hive have Unicode key?

**Comment by TheMisir** [comment]
> @TheMisir Can Hive have Unicode key?

No

**Comment by SimpleTracker** [comment]
Would love to have Unicode Keys, please

**Comment by themisir** [comment]
> Would love to have Unicode Keys, please

Unfortunately it's not easy as implementing a new feature because having backwards compatibility is one of our main goals right now. To support unicode keys we have to modify hor hive serializes databases and this means it will not work well with previous versions and believe me nobody likes to deal with it when databases suddenly change how they work internally.

**Comment by SimpleTracker** [comment]
> > Would love to have Unicode Keys, please
> 
> Unfortunately it's not easy as implementing a new feature because having backwards compatibility is one of our main goals right now. To support unicode keys we have to modify hor hive serializes databases and this means it will not work well with previous versions and believe me nobody likes to deal with it when databases suddenly change how they work internally.

Thank you for replying @themisir and thank you for creating the awesome Hive!!! 
Got it! I used md5 to create keys for non-Ascii values and all good now!
Thank you again!

**Comment by themisir** [comment]
Actually just realized that in theory we could implement backwards compatible support for unicode using UTF-8.

But I wonder if there's any other reasons behind using ASCII subset only in hive, maybe @leisim have any thoughts on this. If it doesn't have any specific reason I can work on implementing Unicode keys using UTF-8 encoding.

More on that: https://stackoverflow.com/questions/15965811/why-utf8-is-compatible-with-ascii

**Comment by leisim** [comment]
The reason at the time was that decoding utf8 is much slower than ascii and I decided that the performance gain was worth the limitation. I didn't benchmark utf8 decoding in some time so I don't know if it is still much slower 🤷🏼‍♂️

**Comment by themisir** [comment]
Did a quick test for benchmarking encoding & decoding ASCII character only keys (to compare impact of moving to UTF-8 codec on existing data). And got some interesting results.

While UTF8 encoder is 2x slower than ASCII encoder on encoding strings, when decoding UTF8 decoder performed 3x faster than ASCII decoder.

```
Test 1: 100 strings
encoding using ascii encoder took 0:00:00.000387.
encoding using utf8 encoder took 0:00:00.000763.
decoding using ascii decoder took 0:00:00.000457.
decoding using utf8 decoder took 0:00:00.000144.
----------------------------------
Test 2: 10000 strings
encoding using ascii encoder took 0:00:00.031718.
encoding using utf8 encoder took 0:00:00.068544.
decoding using ascii decoder took 0:00:00.037023.
decoding using utf8 decoder took 0:00:00.013334.
----------------------------------
Test 3: 1000000 strings
encoding using ascii encoder took 0:00:03.698673.
encoding using utf8 encoder took 0:00:07.064271.
decoding using ascii decoder took 0:00:03.915486.
decoding using utf8 decoder took 0:00:01.140646.
----------------------------------
```

**Comment by leisim** [comment]
Wow that's the worst result you could hope for haha

**Comment by SimpleTracker** [comment]
> Did a quick test for benchmarking encoding & decoding ASCII character only keys (to compare impact of moving to UTF-8 codec on existing data). And got some interesting results.
> 
> While UTF8 encoder is 2x slower than ASCII encoder on encoding strings, when decoding UTF8 decoder performed 3x faster than ASCII decoder.
> 
> ```
> Test 1: 100 strings
> encoding using ascii encoder took 0:00:00.000387.
> encoding using utf8 encoder took 0:00:00.000763.
> decoding using ascii decoder took 0:00:00.000457.
> decoding using utf8 decoder took 0:00:00.000144.
> ----------------------------------
> Test 2: 10000 strings
> encoding using ascii encoder took 0:00:00.031718.
> encoding using utf8 encoder took 0:00:00.068544.
> decoding using ascii decoder took 0:00:00.037023.
> decoding using utf8 decoder took 0:00:00.013334.
> ----------------------------------
> Test 3: 1000000 strings
> encoding using ascii encoder took 0:00:03.698673.
> encoding using utf8 encoder took 0:00:07.064271.
> decoding using ascii decoder took 0:00:03.915486.
> decoding using utf8 decoder took 0:00:01.140646.
> ----------------------------------
> ```
> 
> Benchmark source code: [codec_benchmark.dart](https://gist.github.com/themisir/2d7ad6d346f8bec49621ae27088b00a2)

Thank you for taking all the effort to dig into this @themisir  & @leisim!

I am not very sure but does this mean the UTF-8 keys are faster when reading from the database but slower when writing to the database?
If that's the case, as the reads are far more often than writes for most scenarios, the utf-8 keys may actually improve the overall speed/experience if the utf8 encoder and decoder are used. 

Thank you!
