### ISSUE TITLE
First time to open a box will block the UI

### ISSUE THREAD

**Issue by ryanhoo** [hivedb/hive#160]
I am working on a project which needs to save lots of data locally(basically key-values).
I use two boxes:
- **local** to hold the data downloaded to user's device
- **remote** to cache the remote server response 

both local & remote hold the same type of data structure which is `key(String) -> value(List<Recording>)`, and the Recording only contains a few String fields with a nested Sono field which also contains a few String fields.

I filled in some data in the beginning, which makes **local box** has 1297 keys and each key associates with a list of Recording object, meanwhile **remote box** has 1329 keys and each key also associates with a list of Recording object. The **remote box**'s value, which is a list, might have a size from 0 to 200.

The thing is, next time I re-launch the app, which means I will have to re-initialize the boxes before I can get data from Hive. But when I open this page, the CircularProgressIndicator will freeze for 4 or 5 seconds before it can spin as expected. I leave this page then open this page again, it works fine because the box has already opened last time. It will only block the UI first time to open the box.

Help pls. ;-(

**Code**
```
@override
Widget build(BuildContext context) {
  return Scaffold(
    appBar: AppBar(title: Text('Block UI')),
    body: FutureBuilder(
      future: Future.wait([
        Hive.openBox(box_of_local),
        Hive.openBox(box_of_remote),
      ]),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.done) {
          return Container(
            child: Text('Loaded'),
          );
        }
        return CircularProgressIndicator();
      },
    ),
  );
}
```

**flutter doctor -v**

```
[✓] Flutter (Channel unknown, v1.13.0, on Mac OS X 10.15.2 19C57, locale en-CN)
    • Flutter version 1.13.0 at /Users/ryan/Develop/flutter
    • Framework revision 09126abb22 (3 weeks ago), 2019-12-03 17:43:00 -0800
    • Engine revision 6179380243
    • Dart version 2.7.0 (build 2.7.0-dev.2.1 a4d799c402)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/ryan/Develop/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/ryan/Develop/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • Pixel 2 • FA79F1A01330 • android-arm64 • Android 10 (API 29)

• No issues found!
```

**Comment by leisim** [comment]
Please try to use `openLazyBox()` it should be much faster.

**Comment by ryanhoo** [comment]
@leisim I tried and it works, thanks a lot.

But why `Hive.openBox()` blocks the UI even if it's in a Future call? I am a little bit confused.

**Comment by leisim** [comment]
> But why `Hive.openBox()` blocks the UI even if it's in a Future call? I am a little bit confused.

Because it loads all your data into the memory. Disk io is async but decoding the data is done synchronously (Dart doesn't support multithreading). If you have many entries, it can block your UI.

**Comment by ryanhoo** [comment]
I see, thanks again. @leisim
