### ISSUE TITLE
deleteBoxFromDisk does not work

### ISSUE THREAD

**Issue by siqwin** [hivedb/hive#161]
Trying to open the box like this:

```
Future<Box<T>> openBox<T>(String name) async {
    final result = await Hive.openBox<T>(name).catchError((error) {
      print("Something goes wrong");
      return null;
    });
    if (result == null) {
      await Hive.deleteBoxFromDisk(name);
      return Hive.openBox<T>(name);
    } else {
      return result;
    }
  }
```
I get an error: `HiveError: Cannot read, unknown typeId ...`, so `result` is null, then I try to delete the box from the disk and recreate it, but I get the same error on the second `openBox` call. I'm doing something wrong or `deleteBoxFromDisk` is not working?

**Version**
 - Flutter version: v1.12.13+hotfix.6
 - Hive version: 1.2.0

**Comment by Reprevise** [comment]
You only open a box once using `Hive.openBox()`. After that, you cannot re-open the box unless you close (`Box.close()`) it. To get an instance of a box if it's already open, use `Hive.box()`.

**Comment by oysterpack** [comment]
I ran into the same issue. I debugged it into `BackendManager`

```dart
@override
  Future<void> deleteBox(String name, String path) async {
    await _deleteFileIfExists(File(path_helper.join(path, '$name.hive')));
    await _deleteFileIfExists(File(path_helper.join(path, '$name.hivec')));
    await _deleteFileIfExists(File(path_helper.join(path, '$name.lock')));
  }

  Future<void> _deleteFileIfExists(File file) async {
    if (await file.exists()) { // always returns false
      await file.delete();
    }
  }
```
The deletes never happen because the file path that it is checking for does not exist. While debugging it, I verified that the path looks good - it matches the path that is used to open the box.
In theory, it should work and delete the box files ... but sadly doesn't.

`Hive.deleteBoxFromDisk()` works just fine outside of Flutter, i.e. as a unit test. 
The issue happens when running within Flutter.

### Version:
- Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_US.UTF-8)
- Hive 1.3.0

**Comment by leisim** [comment]
Oh, I think I just found the reason: Hive stores boxes with lowercase names. Could you please try deleting your box with its lowercase name (`yourBox` -> `Hive.deleteBox('yourbox')`);

**Comment by oysterpack** [comment]
I found the reason and can reproduce the issue with a simple unit test:

```
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:hive/hive.dart';

void main() {
  test('delete box', () async {
    // arrange
    final dir = Directory('temp/delete-hive-box');
    Hive.init(dir.path);

    // act
    await Hive.openBox('FOO');
    await Hive.close();
    await Hive.deleteBoxFromDisk('FOO');

    // assert
    expect(dir.listSync().isEmpty, isTrue);
  });
}
```
The issue is that when the box is opened, the box name is lowercased. My box name contained uppercase letters. which explains why the file could not be found.

**Comment by leisim** [comment]
Yeah, you are right! I found the line... Thanks!
