### ISSUE TITLE
Export Database to .db / .hive /another file (csv etc)

### ISSUE THREAD

**Issue by zgramming** [hivedb/hive#162]
Hi, it's possible to export database into **CSV** or file something .db/.hive and otherwise   ? 
It will be good if we have feature like this.  Because it more towards security, user can backup database and if the user uninstall app , user can import old database into app.

**Comment by leisim** [comment]
Just use `yourBox.toMap()` and you basically have JSON.

**Comment by zgramming** [comment]
Sorry,can you explain more detail? It not what i'm think.
 I'm think something like export database in mySQLn, it Will give you file .db , then you can import this file again to app.

**Comment by marcelgarus** [comment]
SQL and CSV are relational databases/tables, while Hive is a document-based NoSQL database.
So, I don't think this is possible. You could probably somehow convert it to other NoSQL databases though, like CouchDB or MongoDB - as far as I'm concerned they allow you to import pure JSON.

**Comment by zgramming** [comment]
Oke i get it.
Thanks for your advice
