### ISSUE TITLE
Only allows one key to watch in hive_flutter dev

### ISSUE THREAD

**Issue by Reprevise** [hivedb/hive#166]
**Steps to Reproduce**
It seems in the hive_flutter dev version we only can listen to one key whereas before we could listen to multiple keys. I'm not sure if this is intended or not but it's a bummer anyhow.

**Code sample**
```
// hive_flutter (not dev)
return WatchBoxBuilder(
  box: Hive.box('myBox'),
  watchKeys: ['firstName', 'lastName'],
  builder: (context, box) {
    return Text(box.get('firstName') + ' ' + box.get('lastName'));
  }
)

// hive_flutter (dev)
return ValueListenableBuilder(
  valueListenable: box.listenable(key: ""),
  builder: (context, Box<Assignment> box, child) {
    ...
  }
);
```

**Version**
 - Platform: Android, iOS
 - Flutter version: 1.12.3
 - Hive version: 1.2.0
 - Hive Flutter version: 0.3.0-dev

**Comment by leisim** [comment]
I published a new version and there is now an additional `keys` parameter.

```dart
return ValueListenableBuilder(
  valueListenable: box.listenable(keys: ['firstName', 'lastName']),
  builder: (context, Box<Assignment> box, child) {
    ...
  }
)
```

**Comment by Reprevise** [comment]
Why is there both a `key` and a `keys` parameter? Won't that cause issues if a user were to fill both out or put the same key in both? Wouldn't it be simpler to just have just the `keys` parameter?

**Comment by leisim** [comment]
I thought it would be nice to have an option to only listen to a single key. Maybe you are right...

**Comment by Reprevise** [comment]
If you want that option, at least make an `assert` that only one of the parameters can have value.

**Comment by leisim** [comment]
> If you want that option, at least make an assert that only one of the parameters can have a value.

I already have one but I think you are right, it is confusing.

**Comment by leisim** [comment]
I removed the `key` parameter.
