### ISSUE TITLE
Documentation Demo Links Broken

### ISSUE THREAD

**Issue by SupposedlySam** [hivedb/hive#168]
**Steps to Reproduce**
Navigate to:
https://docs.hivedb.dev/hive/demos/counter/
https://docs.hivedb.dev/hive/demos/todo/
https://docs.hivedb.dev/hive/demos/sketchpad/

Using latest version of Chrome on MacOS

**Version**
 - Platform: Web

**Comment by leisim** [comment]
Yes, I wanted to remove them but forgot to do so. They will be replaced with tutorials in the tutorial section.

**Comment by leisim** [comment]
Fixed.
