### ISSUE TITLE
paging and remove object from memory only

### ISSUE THREAD

**Issue by vandong9** [hivedb/hive#172]
**Question**
How can i load paging  ?
How can i remove all or specify object which loaded from memory only ?
Thanks.

**Comment by leisim** [comment]
> How can i load paging ?
There is no special paging feature currently. Since you can access entries by index (`box.getAt()`) it should be not very hard to implement it yourself.

> How can i remove all or specify object which loaded from memory only ? 

You cannot remove specific objects from memory. If you close a box, all its entries will be dropped from memory.

**Comment by leisim** [comment]
Please reopen if you have further questions...
