### ISSUE TITLE
Backup & Restore

### ISSUE THREAD

**Issue by Reprevise** [hivedb/hive#173]
I've seen this issue #162 as and I'm wondering on how to import that map (`box.toMap()`) into Hive so I can backup and restore files.

Would the best option be to use `box.putAll()` after opening the box on startup?

**Version**
 - Platform: iOS, Android

**Comment by leisim** [comment]
> Would the best option be to use box.putAll() after opening the box on startup?

Yes exactly. You can also back up the `.hive` file which contains your box.

**Comment by Reprevise** [comment]
How would I do that?

**Comment by leisim** [comment]
You could, for example, back up the file to iCloud or Google Drive.

You can get the content of the box using:
```dart
var boxBytes = await File(yourBox.path).readAsBytes();
```

**Comment by Reprevise** [comment]
Alright, so I assume that partners nicely with `writeAsBytes` for storing the file so when I retrieve the file, how would I decode it into a string and then into a map? Would `String.fromCharCodes()` be viable or something else? I can't figure out a way and `utf8.decode()` gave me an error.

**Comment by leisim** [comment]
I can think of two options:

1. Get a map using `box.toMap()`, convert it to JSON or something similar and back it up. Later you can use `box.putAll()` to put the data back into Hive.

2. Back up the file in which Hive stores the box (`"yourBoxName.hive"`).

You can use for example `File().readAsBytes()` and later `File.writeAsBytes()` but you can also copy the file somewhere etc.

**Comment by Reprevise** [comment]
I get the map and stuff but how would you decode from `Uint8List` (`File.readAsBytes()`) to a map? I've tried using `String.fromCharCodes()` and `utf8.decode()` but the first one gives me an un-usable string and the other one gives me an error.

**Comment by leisim** [comment]
> but how would you decode from `Uint8List` ( `File.readAsBytes()` ) to a map

You don't. These are two separate approaches and it makes no sense (or is impossible?) to mix them. If you need to save a string you should stick to 1. or you convert the binary file to a string using base64.

**Comment by Reprevise** [comment]
Wouldn't just converting the box to a map, then a string and using `writeAsString()` and then later using `readAsString` and converting that to a map with `jsonDecode()`?

**Comment by Reprevise** [comment]
I figured it out by using the method I described above.

**Comment by re-bola** [comment]
@Reprevise 
Can you share a code snippet of the method you used?

**Comment by reesz** [comment]
@bola-malek just in case & for everybody else finding this thread. This is how I'm doing it atm:

```dart
Directory dir = await getApplicationDocumentsDirectory();
Uint8List boxBytes = await File(dir.path + '/hiveBoxName.hive').readAsBytes();
String boxBase64 = base64Encode(boxBytes);
```

and to restore it, just the other way round:

```dart
 String boxBase64 = 'base64_encoded_bytes_from_external_storage';
Uint8List boxBytes = base64Decode(boxBase64);
Directory dir = await getApplicationDocumentsDirectory();
await File(dir.path + '/hiveBoxName.hive').writeAsBytes(boxBytes);
```

The only thing I could imagine is, depending on the box-size, base64 could get quite large I assume? 
The `.toMap()` & JSON-variant probably is a little more efficient, but requires custom parsers for converting custom data structures to/from JSON.
