### ISSUE TITLE
Documentation broken?

### ISSUE THREAD

**Issue by yannickvg** [hivedb/hive#176]
**Steps to Reproduce**
If you go https://docs.hivedb.dev no documentation is visible.

**Version**
 - Platform: Web
 - Flutter version: NA
 - Hive version: NA

**Comment by leisim** [comment]
It works fine on my devices :/
What browser are you using?

**Comment by yannickvg** [comment]
Firefox is not working, I tried with Chrome and that is working fine
<img width="1674" alt="Screenshot 2020-01-10 at 14 38 37" src="https://user-images.githubusercontent.com/3224170/72159699-363ca100-33bd-11ea-9a50-0d2bd4b26fd3.png">

**Comment by leisim** [comment]
Thanks for the info, I'm only using Chrome so I didn't notice.

I'll fix it as soon as I can...

**Comment by leisim** [comment]
It should be fixed now. The reason for the problem was a [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1579867).
