### ISSUE TITLE
Lazy HiveList behavior clarification

### ISSUE THREAD

**Issue by re-bola** [hivedb/hive#178]
Supposed I have the following:

```
@HiveType()
class Person extends HiveObject {
  @HiveField(0)
  String name;

  @HiveField(1)
  HiveList<Person> friends;

  Person(this.name);
}
```

Supposed I'm opening a Lazy box (which I understand only loads key to memory, not values until they are queried), that has 4 persons stored. person1 is friends with person2 and person3. 

When I call `val person1 = await lazyBox.get('person1Key');` are the values/HiveObjects of person2 and person3 also loaded to memory? Or just the keys?

I'm hoping that the answer is just the keys....

**Comment by leisim** [comment]
`HiveLists` currently don't support lazy boxes.
Here is how they work in normal boxes:
The `HiveList` stores the name of the "remote box" (the box which contains its elements) and the key of each element. When you open a box which contains a `LazyBox`, it only loads the keys of its elements. The first time you access one of its elements, they are all loaded from the remote box.

To replicate this behavior for a lazy box, the `HiveList` would need a async access method which is not supported by the Dart list interface and also isn't very useful in my opinion.

For lazy boxes I recommend to just use a `List<String>` and store the keys of the elements.

What is your opinion?

**Comment by re-bola** [comment]
Yeah. I agree. It would be nice if storing the `List<String> keys` is done insider the HiveList implementation for LazyBox. Would that be possible? I could do it externally for my personal project, but I feel like it's actually quite a useful case  (that is, lazy loading of relational data)

**Comment by leisim** [comment]
I think it would be more straightforward to use `List<String>` directly.
