### ISSUE TITLE
Allow hive_generator to use .g.dart from other directories.

### ISSUE THREAD

**Issue by re-bola** [hivedb/hive#184]
I want to be able to put all my .g.part files in a different directory while generating because they clutter my current directory. Happy to implement it with some guidance.

**Comment by leisim** [comment]
I don't think the `build_runner` supports custom directories but I think it is possible to store the generated files in the `.dart_tool` folder. I need to check that.

**Comment by re-bola** [comment]
Okay. build_runner official sucks for not allowing output directories that make sense (you can only specific the output directly for the whole package after the run, which is too much to keep copies of and I don't want to a duplicate structure).
