### ISSUE TITLE
Value Compression

### ISSUE THREAD

**Issue by re-bola** [hivedb/hive#187]
**Is your feature request related to a problem? Please describe.**
For those of us developing apps with preloaded content that needs to be in a database, it's helpful to have compression so that your asset sizes can be smaller and you take overall less space on the user's machine.

**Describe the solution you'd like**
Similar to how encryptedBox works now, you can pass a CompressionStrategy (to be defined) with your openBox call, then it can handle the compression and decompression and reads and writes. 
We could use [Brotli ](https://github.com/google/brotli)and its [dart implementation](https://github.com/tiagohm/brotli) for handling the compression so we don't need to write it ourselves.

I need to do something pretty similar for my app so feel free to assign this to me and I could put up a PR in about 2-3 weeks for this and we can discuss it from there.

**Comment by leisim** [comment]
I don't think compression should be part of Hive.

You would want to compress the entire database and not only a few entries so there is no benefit in supporting it directly.

Maybe you want to create a package with an extension method like `Hive.openCompressedBox()`.

**Comment by re-bola** [comment]
Sure I can do that. Will close for now and share an implementation later when I get around to it.
