### ISSUE TITLE
New putAll method

### ISSUE THREAD

**Issue by carmas123** [hivedb/hive#190]
Hi please can you think to add a custom method like: "putAll"
The idea is to have a putAll(Iterable items, callbackKey) that have a callback function that return the key for each putted element. This can be useful to handle a batch put of objects with a custom key.

The callback can be like this:

`typedef PutAllCallback<T> = String Function(T value, int index);`
or
`typedef PutAllCallback<T,K> = K Function(T value, int index);`

**Comment by leisim** [comment]
I don't think I understand what you are asking... There is already a `box.putAll()` method.

```dart
yourBox.putAll({'key1': 'value1', 'key2': 'value2'});
```

**Comment by carmas123** [comment]
Sorry man I'm new with this lib :)
I solved with your suggestion:

```
final m = Map<dynamic, B>.fromIterable(newList, key: (x) => x.keyField);
myBox.putAll(m);
```

Thank you
