### ISSUE TITLE
Question about inheritance

### ISSUE THREAD

**Issue by carmas123** [hivedb/hive#193]
Hi, I've a base HiveObject that have some hive fields with index 0, 1, 2.
Now I need to extend this class with other fields. Now if the last field index of base class have index 3 in the child class I need to start from 4 or I need to register new type adapter?

**Comment by leisim** [comment]
> Now if the last field index of base class have index 3 in the child class I need to start from 4 or I need to register new type adapter?

You need to start from 4. Generally speaking, just make sure your child classes don't have `fieldIds` that are already used by a parent class.
