### ISSUE TITLE
Have an something that extends ValueNotifier or ValueListenable for a ValueListenableBuilder

### ISSUE THREAD

**Issue by MichaelPriebe** [hivedb/hive#20]
This way you can have a widget update when the value of a certain key updates!

**Comment by leisim** [comment]
You can just use something like this:
```
var box = Hive.box('yourBox');
box.watch('yourKey').listen((e) {
  setState(() {});
});
```

This will update your widget when `yourKey` changes.

**Comment by MichaelPriebe** [comment]
setState is not the best practice though, often rebuilds more than what you need.

**Comment by leisim** [comment]
Could you provide a sample of what you have in mind?

**Comment by MichaelPriebe** [comment]
Maybe like
```dart
HiveListenable darkMode = HiveListenable(myBox, 'darkMode');
```
and
```dart
ValueListenableBuilder(
  valueListenable: darkMode,
  builder: (BuildContext context, bool darkMode, Widget child) {
    return ListTile(
      title: child,
      trailing: Switch(
        value: darkMode,
        onChanged: (bool changed) {
          myBox.put('darkMode', changed);
          // Or maybe darkMode.set(changed);
        },
      ),
    );
  },
  /*
    For this example, Text isnt that expensive,
    but you can put more expensive widgets here
    and they wont constantly rebuild when you want to
    change JUST the switch.
  */
  child: Text('Dark Mode'),
),
```

**Comment by leisim** [comment]
I understand, thanks...

**Comment by leisim** [comment]
I created the [`HiveBuilder`](https://github.com/leisim/hive/blob/master/hive_flutter/lib/src/hive_builder.dart) how do you like it?

[Here](https://github.com/leisim/hive/blob/master/examples/basic_flutter/lib/main.dart) is a simple example how it works.

**Comment by MichaelPriebe** [comment]
I was thinking like this:

```dart
class HiveNotifier extends ValueNotifier {

  final Box box;
  final String key;
  
  HiveNotifier(this.box, this.key) : super(box.get(key)) {
    box.watch(key: key).listen((BoxEvent event) {
      if (event.value == value) return;
      value = event.value;
    });
  }

  @override
  get value => box.get(key);

  @override
  set value(newValue) {
    box.put(key, value);
    notifyListeners();
  }

}
```

Didn't try to see if it works though.

**Comment by haroldolivieri** [comment]
IMHO, I don’t think you need more than `Hive.watch`. You can extend its usage for your own specific implementation (Provider, ScopeModel, InheritedWidget, StreamBuilder).

In my case, I am creating a stream from `Hive.watch` so I can use a StreamBuilder to observe state changes.

You can create your own `ChangeNotifier` and observe changes win watch to notifyListeners() and observe changes either.

But I think this watch should return the initial value when we listen to a specific key. Currently I have to watch and map to receive all values since the very beginning.

```dart
  Stream<List<String>> watchChanges() {
    return Hive.box(boxNameKey)
        .watch(key: recentQueriesKey)
        .map((event) => fetchQueries());
  }
```

**Comment by leisim** [comment]
>IMHO, I don’t think you need more than Hive.watch. You can extend its usage for your own specific implementation (Provider, ScopeModel, InheritedWidget, StreamBuilder).

I agree.

>But what I really think is this watch should return the initial value when we listen to a specific key. Currently I have to watch and map to receive all values since the very beginning.

I don't quite undestand what you mean. Do you want to receive all events for a key since the box has been opened? Hive would need to keep them for any key in case you watch that key anytime later.

**Comment by haroldolivieri** [comment]
Sorry, I’ve updated my comment. 

I would like that `watch` had a seedValue for the time I subscribe to it, but only when I am listening a specific key, like a snapshot.

Otherwise I have to do listen and fetch for the first content not be null, as you do on `WatchBoxWidget`, this shouldn’t be necessary.

**Comment by haroldolivieri** [comment]
You can achieve this seedValue using a BehaviorSubject under the hood, not sure what you’re using.

**Comment by leisim** [comment]
You are right, the reason why I didn't implement that are lazy boxes.

Since lazy boxes don't keep the values in memory, they would need to be fetched for each subscribe call.

I'm not sure how to solve this.

**Comment by haroldolivieri** [comment]
What about a optional param where we can ask for this initialValue? So it would not be a problem to fetch it again for lazyBox under the hood as in cases like mine we will have to fetch it anyway.

**Comment by haroldolivieri** [comment]
Hahah exactly

**Comment by leisim** [comment]
Okay let's do that 👍

**Comment by leisim** [comment]
This has finally been implemented:

```dart
ValueListenableBuilder(
  valueListenable: Hive.box('settings').listenable(),
  builder: (context, box, widget) {
    return Center(
      child: Switch(
        value: box.get('darkMode', defaultValue: false),
        onChanged: (val) => box.put('darkMode', val),
      ),
    );
  },
)
```

**Comment by MichaelPriebe** [comment]
Thanks @leisim! Hopefully we can get key listeners too because I would rather widgets not rebuild when an irrelevant setting changes.

**Comment by leisim** [comment]
@MichaelPriebe You can do `yourBox.listenable(key: 'someKey')`

**Comment by MichaelPriebe** [comment]
Amazing!
