### ISSUE TITLE
hive 1.4 dependency on crypto ^2.1.4 is incompatible with flutter_test

### ISSUE THREAD

**Issue by oysterpack** [hivedb/hive#202]
When I tried to upgrade my Flutter app to `hive: ^1.4.0-dev3`, it failed with the following error:

> Because every version of flutter_test from sdk depends on crypto 2.1.3 and hive >=1.4.0-dev depends on crypto ^2.1.4, flutter_test from sdk is incompatible with hive >=1.4.0-dev.

**Version**
 - Platform: Linux
 - Flutter version: Channel stable, v1.12.13+hotfix.5
 - Hive version: 1.4.0-dev3

**Comment by leisim** [comment]
Thanks for letting me know. I'm planning to remove the crypto dependency for the stable release. Until then, you can use
```yaml
dependency_overrides:
  crypto: 2.1.3
```

**Comment by incker** [comment]
Looks like `hive: ^1.4.0` is not dev - version already, but still have this problem
Tip with `dependency_overrides` helps

**Comment by leisim** [comment]
Thanks for reminding me, I completely forgot about this issue. I'll push a fix later ;)

**Comment by leisim** [comment]
This issue is fixed with the newest version.

**Comment by marcschw** [comment]
Similar new issue with flutter_driver:

Because every version of flutter_driver from sdk depends on crypto 2.1.5 and hive >=2.0.0 depends on crypto ^3.0.0, flutter_driver from sdk is incompatible with hive >=2.0.0.
