### ISSUE TITLE
Cannot write, unknown type: MaterialAccentColor. Did you forget to register an adapter?

### ISSUE THREAD

**Issue by Mravuri96** [hivedb/hive#206]
**Error**
Getting ```Error: HiveError:  Cannot write, unknown type: MaterialAccentColor. Did you forget to register an adapter? ``` , even though i've registered it :(

**Steps to Reproduce**
Trying to store a material accent 
```dart 
Colors.lightBlueAccent
 ```
 color into a box. 

**Possible Solution**
There is currently a PR in the [hive_flutter Repo](https://github.com/hivedb/hive_flutter/pull/2/files), that might fix this issue

**Code sample**
UserData.dart
```dart
import 'package:flutter/material.dart';
import 'package:hive/hive.dart';

part 'UserData.g.dart';

@HiveType(typeId: 0)
class UserData {
  @HiveField(0)
  double bmi;

  @HiveField(1)
  MaterialAccentColor colorValue;

  @HiveField(2)
  String height;

  @HiveField(3)
  String weight;

  @HiveField(4)
  DateTime dateRecorded;

  UserData(
      this.bmi, this.colorValue, this.height, this.weight, this.dateRecorded);
}

```
UserData.g.dart
```dart
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'UserData.dart';

// **************************************************************************
// TypeAdapterGenerator
// **************************************************************************

class UserDataAdapter extends TypeAdapter<UserData> {
  @override
  final typeId = 0;

  @override
  UserData read(BinaryReader reader) {
    var numOfFields = reader.readByte();
    var fields = <int, dynamic>{
      for (var i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return UserData(
      fields[0] as double,
      fields[1] as MaterialAccentColor,
      fields[2] as String,
      fields[3] as String,
      fields[4] as DateTime,
    );
  }

  @override
  void write(BinaryWriter writer, UserData obj) {
    writer
      ..writeByte(5)
      ..writeByte(0)
      ..write(obj.bmi)
      ..writeByte(1)
      ..write(obj.colorValue)
      ..writeByte(2)
      ..write(obj.height)
      ..writeByte(3)
      ..write(obj.weight)
      ..writeByte(4)
      ..write(obj.dateRecorded);
  }
}
``` 
main.dart
```dart
void main() async {
  await Hive.initFlutter();
  Hive.registerAdapter(UserDataAdapter());
  await Hive.openLazyBox<UserData>(
    'UserData',
    encryptionKey: Hive.generateSecureKey(),
    crashRecovery: true,
  )
      .whenComplete(
        () => Hive.openBox(
          'settings',
          crashRecovery: true,
        ),
      )
      .whenComplete(
        () => runApp(
          ChangeNotifierProvider(
            create: (_) => Calculator(),
            child: HomePage(),
            lazy: true,
          ),
        ),
      );
}
```

**Version**
 - Platform: Mac
 - Flutter version: 1.14.7-pre.40
 - Hive version: 1.3.0
 - Hive_flutter version: 0.3.0+1
 - Hive_generator version: 0.7.0

**Comment by leisim** [comment]
Like the error says, you did not register an adapter for `MaterialAccentColor`.

**Comment by Mravuri96** [comment]
> Like the error says, you did not register an adapter for `MaterialAccentColor`.

MaterialAccentColor is a built in type in the material library, should'nt the hive_generator automatically detect it when i run the build runner?

**Comment by leisim** [comment]
Unfortunately Hive does not know how to store a type apart from primitives, lists and maps...

**Comment by Dinver** [comment]
Hi! Sorry, question similar:
> Exception has occurred.
> HiveError (HiveError: Cannot write, unknown type: TimeOfDay. Did you forget to register an adapter?)
How to declare In my custom class, i understand. TimeOfDay class flutter how to generate for it adapter?

**Comment by BoHellgren** [comment]
I solved the Color problem by changing the generated file, like this:
```
 ..write(obj.backgroundColor) _changed to_
 ..write(obj.backgroundColor.toString())

backgroundColor: fields[12] as Color _changed to_
backGroundColor: Color(int.parse(fields[12].split('(0x')[1].split(')')[0], radix: 16)),

**Comment by TheMisir** [comment]
The solution for "Unknown type: ...." errors is to creating and registering an adapter. It doesn't have to be auto generated. I usually write adapters myself for complex types.
