### ISSUE TITLE
A way to update multiple values at once

### ISSUE THREAD

**Issue by nicolasvahidzein** [hivedb/hive#211]
Hello,

i have a listener on a box but i want to trigger the save in one go because they need to be in sync. How can i do that?

**Comment by leisim** [comment]
You can update multiple values using `box.putAll({'key1': 'newVal1', 'key2': 'newVal2'})`. Does that answer your question?

**Comment by nicolasvahidzein** [comment]
Yes sir it does, thank you very much. Closing this ticket.
