### ISSUE TITLE
Associate and compare objects

### ISSUE THREAD

**Issue by mit-73** [hivedb/hive#218]
**Question**
Does HiveDB have the ability to associate and compare objects?

I have two lists, in one data is obtained from API. The second is retrieved from the HiveDB, by adding from the first list. But the problem is that it is a chance to add the same data in the second list.

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: 1.12.13
 - Hive version: 1.3.0

**Comment by leisim** [comment]
Comparing objects is not something Hive supports. You can however generate the key based on the state of the object (like a hashcode). This would prevent having duplicate objects.

**Comment by mit-73** [comment]
> You can however generate the key based on the state of the object (like a hashcode).
How can you do it?

**Comment by frank06** [comment]
Maybe related: Why is `HiveList` a `List` and not a `Set`?  Is allowing duplicate elements a feature?

**Comment by leisim** [comment]
> Is allowing duplicate elements a feature?

Yes, it allows adding duplicate elements. Maybe there should also be a `HiveSet`.

**Comment by frank06** [comment]
As far as I understand, "one-to-many" type relationships won't return duplicates and `HiveList`'s main use-case seems to be a "one-to-many" relationship, correct?  Or what would be a good counter example?

**Comment by leisim** [comment]
Since Hive is not a relational database it does not need to follow the same rules. I'm sure there are use cases for duplicate entries. The main reason for using lists is that the `List` interface is much nicer than `Set`. Lists are ordered (not all sets are) and allow to access an element by index. I don't see a disadvantage in using lists.
