### ISSUE TITLE
How to remove all data from the box?

### ISSUE THREAD

**Issue by Hopheylalal** [hivedb/hive#219]
How to remove all data from the box?

**Comment by leisim** [comment]
Either using `box.clear()` to clear the box or `box.deleteFromDisk()` to also delete the file containing the box.

**Comment by jimmy-robert** [comment]
It looks like `box.clear` operation is not immediately applied:

```dart
box.add(0);
print(box.length); // 1
box.clear();
print(box.length); // 1
```

But `box.deleteAll` works as expected:

```dart
box.add(0);
print(box.length); // 1
box.deleteAll(box.keys);
print(box.length); // 0
```

@leisim: Is that the correct behavior? It doesn't seem right...

**Comment by erabti** [comment]
@jimmy-robert the clear method is async, you have to await for it:
```
await box.clear();
```

**Comment by smkhalsa** [comment]
@erabti @leisim I really think clear should clear the in-memory data immediately, then resolve the Future once the data has been removed from disk (similar to how put works).

**Comment by ag-0214** [comment]
HiveError: The box "box1" is already open and of type Box<BoxOne>. I am trying to use clearAll and I am getting this error message. How can I solve it?

**Comment by EliasDalvite** [comment]
box.clear() didn't solve my problem... Started using box.removeAll() and it does work very well, if anyone still needs help with this.

**Comment by balawantkumar** [comment]
In Flutter, when using the `GetStorage` package, if you're encountering a situation where all data from the storage box is being removed, it's important to investigate the issue thoroughly.

box.erase();

**Comment by hpelitebook745G2** [comment]
@EliasDalvite what version are using? i don't see a `removeAll()` method
