### ISSUE TITLE
Error: You have to provide a non-null typeId

### ISSUE THREAD

**Issue by sgehrman** [hivedb/hive#231]
[SEVERE] hive_generator:hive_generator on lib/hive_db/scan_data.dart:
Error running TypeAdapterGenerator
You have to provide a non-null typeId.

I'm trying to follow the reso coder video.  He had the same issue, but didn't explain the work around.

**Comment by sgehrman** [comment]
Figured it out:  

@HiveType(typeId: 0)

**Comment by frank06** [comment]
@sgehrman Yes, and you need to manually assign different type id's (integers) to your each one of your models

**Comment by leisim** [comment]
Please close this issue if it works now :+1:

**Comment by MikeRee** [comment]
I'm new to hive so this may be a user issue, but I'm running into the same issue.

Versions:
dependencies:
  flutter:
    sdk: flutter
  flutter_facebook_login: ^3.0.0
  http: ^0.12.0+4
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  path_provider: ^1.6.5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.0+2
  build_runner: ^1.8.0

Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-US)

**Comment by harisijazwarraich** [comment]
> 
> 
> Figured it out:
> 
> @HiveType(typeId: 0)

Thanks, It worked <3

**Comment by Aaron009** [comment]
https://docs.hivedb.dev/#/custom-objects/generate_adapter

Update the documentation and be friendly to novices.

**Comment by awarmfastbear** [comment]
An exception should probably be thrown to the IDE, or intellisense should catch if an ID is not provided to the HiveType without having to go through a build attempt to catch this.

**Comment by D0xzen** [comment]
> Figured it out:
> 
> @HiveType(typeId: 0)

Can be added to the docs?

**Comment by dwitio** [comment]
> Figured it out:
> 
> @HiveType(typeId: 0)

nice, thanks
