### ISSUE TITLE
Default HiveObjects returned from [Lazy]Box.get(key, {E defaultValue}) should be initialized

### ISSUE THREAD

**Issue by shroff** [hivedb/hive#233]
**Steps to Reproduce**
The code bellow fails if the key is not found, since the default object is not yet in the box. It requires calling `Box.put`, which defeats the purpose of having `HiveObject.save()`.

A simple fix (if desired, and in line with design principles) is adding the following lines to `box_impl.dart` and `lazy_box_impl.dart`:
```
      if (defaultValue is HiveObject) {
        defaultValue.init(key, this);
      }
```
(`box_impl.dart` also needs an import of `hive_object.dart`)

**Code sample**
```
personBox.get(key, Person()).setAge(42).save()
```

**Version**
 - Platform: Android, Linux
 - Flutter version: 1.13.6 [Beta]
 - Hive version: 1.3.0

**Comment by leisim** [comment]
Thank you!
