### ISSUE TITLE
Timestamp key support

### ISSUE THREAD

**Issue by Dinver** [hivedb/hive#235]
There was a need to work with dates key in the form timestamp: 
`DateTime.now().toUtc().millisecondsSinceEpoch`
It turns out key is longer than maximum, Hive gives an error, key length exceeded. 
For this needed to use longer keys. Is there any way to implement this?

**Comment by leisim** [comment]
You can just use String keys (`DateTime.now().toUtc().millisecondsSinceEpoch.toString()`) and it will work :)

**Comment by Dinver** [comment]
Thanks, decided dividing by 1000 (conversion in seconds).
