### ISSUE TITLE
The method 'listenable' is not defined for the class 'Box'

### ISSUE THREAD

**Issue by namaye** [hivedb/hive#238]
Whenever I try to access listenable method, I get the error `The method 'listenable' is not defined for the class 'Box'`.
`Hive.box('diary').listenable()`

My Hive Versions
```
hive: 1.4.1
hive_flutter: 0.3.0+2
hive_generator: 0.7.0+2
```

**Comment by leisim** [comment]
You need to `import 'package:hive_flutter/hive_flutter.dart'`.

**Comment by namaye** [comment]
Thank you. It worked.
