### ISSUE TITLE
The method 'initFlutter' isn't defined for the class 'HiveInterface'

### ISSUE THREAD

**Issue by Rayv1** [hivedb/hive#239]
Hi,

iam trying to init Hive in Main Function with   Hive.initFlutter(); as described in your documents. Unfortunately my VS Code shows "The method 'initFlutter' isn't defined for the class 'HiveInterface'."

Maybe i missed a additional step to make it work.

 - Platform:  Android, Windows
 - Flutter version: 1.14.6
  hive: ^1.4.1
  hive_flutter: ^0.3.0+2
dev_dependencies:
  hive_generator: ^0.7.0+2
  build_runner: ^1.7.4

**Comment by owczaro** [comment]
Hi @Rayv1 ,
have you tried to import `package:hive_flutter/hive_flutter.dart`?

**Comment by Rayv1** [comment]
yep, just forget to import the second package

**Comment by sghaleb1** [comment]
i am getting the same issue, I have imported the `hive_flutter` package.

hive: ^1.4.1+1
hive_flutter: ^0.3.0+2

**Comment by lordvcs** [comment]
You need to import both `hive` and `hive_flutter`.

**Comment by JanuszHain** [comment]
Just add `import 'package:hive_flutter/hive_flutter.dart';`

Little explanation: `initFlutter()` is extension and Android Studio currently doesn't support importing extensions for Dart, that's why we have to setup import manually

**Comment by XinyueZ** [comment]
IDE issue

**Comment by berkeugur** [comment]
You must add` import 'package:hive_flutter/hive_flutter.dart'; `

**Comment by reshnu** [comment]
you should add hive_flutter in pubspec.yaml and import 'package:hive_flutter/hive_flutter.dart';
