### ISSUE TITLE
Is there an easy way of viewing the persisitant hive variables in Android Studio? 

### ISSUE THREAD

**Issue by 9thwall** [hivedb/hive#244]
Is there a way to view all the currently stored Hive box variables in Android Studio or any editor?
I have many hive boxes with all types of data being stored and if there was a way to easily view all the data somehow during development in a window, that would be great.

**Comment by leisim** [comment]
Currently not. I will eventually create a tool or plugin to view the content of boxes (maybe using Facebook's [flipper](https://github.com/facebook/flipper), but this does not have a high priority currently.

**Comment by Mravuri96** [comment]
Cant you View your contents of a Hive box in [Hive Studio](https://studio.hivedb.dev/) ?

[![Demo CountPages alpha](https://media.giphy.com/media/VFSmCmgKnJSUwtzqW9/giphy.gif)](https://media.giphy.com/media/VFSmCmgKnJSUwtzqW9/source.gif)
