### ISSUE TITLE
Cast error when reading lists

### ISSUE THREAD

**Issue by marcelgarus** [hivedb/hive#245]
**Steps to Reproduce**
Create a class with a List of a generic type, for example something like the following:
```dart
class Course {
  @HiveField(3)
  final List<Id<User>> teachers;
}
```
Hive will generate an adapter that contains the following code in the read method:
```dart
...
return Course(
  teachers: (fields[3] as List)?.cast<Id>(),
);
```
Even if the individual items of the list are correctly decoded into `Id<User>`s, this code will fail with the following error:
```
_TypeError (type 'CastList<dynamic, Id<Entity<dynamic>>>' is not a subtype of type 'List<Id<User>>')
```

**Comment by leisim** [comment]
I don't think it is possible to solve this since you cannot cast to a type with a generic parameter.

This will always fail:
```dart
someList.cast<Id<User>>
```

**Comment by marcelgarus** [comment]
I'm pretty sure this will work if all items of the list are of type `Id<User>`:

```dart
class Id<T> {}

void main() {
  var a = <dynamic>[Id<int>(), Id<int>()];
  var b = <dynamic>[Id<int>(), Id<String>()];
  print(a.runtimeType); // List
  print(b.runtimeType); // List
  print(a.cast<Id<int>>().toList().runtimeType); // List<Id<int>>
  print(b.cast<Id<int>>().toList().runtimeType); // throws error
}
```

**Comment by leisim** [comment]
Yes, you are right. I'm working on a fix. It could take a few days since I have not much time currently.
If you spot the error, a PR would also be much appreciated ;)

**Comment by marcelgarus** [comment]
I'm on it
