### ISSUE TITLE
Facing "FileSystemException: Cannot delete file" continuously, after it triggered once.

### ISSUE THREAD

**Issue by 1207roy** [hivedb/hive#248]
**Steps to Reproduce**
Not able to find exact steps. 
App was working properly, but suddenly it started showing me this error continuously (Other than this error, everything is working properly though)

**Error Stacktrace**
```
E/flutter (20468): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: FileSystemException: Cannot delete file, path = '/data/user/0/project_name/app_flutter/app_state_box.lock' (OS Error: No such file or directory, errno = 2)
E/flutter (20468): #0      _File._delete.<anonymous closure> (dart:io/file_impl.dart:293:9)
E/flutter (20468): #1      _rootRunUnary (dart:async/zone.dart:1134:38)
E/flutter (20468): #2      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter (20468): #3      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
E/flutter (20468): #4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
E/flutter (20468): #5      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
E/flutter (20468): #6      Future._completeWithValue (dart:async/future_impl.dart:526:5)
E/flutter (20468): #7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
E/flutter (20468): #8      _rootRun (dart:async/zone.dart:1126:13)
E/flutter (20468): #9      _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (20468): #10     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter (20468): #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
E/flutter (20468): #12     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
E/flutter (20468): #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
```

The error raises whenever I call this method **updateCache(someIntValue)**
(which works on updating the hive data)
**Code sample**
```
Future<void> updateCache(int a, {Object b, int c}) async {
	final Box<AppState> stateBox = await Hive.openBox<AppState>('app_state_box');

	AppState state = stateBox.get(a.toString());
	state = AppState(b ?? state.b, c ?? state.c);

	await stateBox.put(a.toString(), state);
	await stateBox.close();
}
```

**Version**
 - Platform: Android
 - Hive version: 1.4.1+1
 - Flutter version: Flutter 1.15.4-pre.241 • channel master

Am I missing something?
I'm sorry if its a silly mistake. I'm new to flutter and Hive.

**Comment by leisim** [comment]
Do you see this error in production or while debugging?

**Comment by 1207roy** [comment]
The error was showing in debugging. Not sure about production as I hadn't tried in production.

Hey, maybe it was my stupid code as I'm not facing any issue since I changed some code. 
Currently, I'm letting the Hive box open until my app is killed(I'm not closing the box). and I'm not facing any issue now.
Earlier I'm opening and closing the hive box on each user interaction. Maybe that's why the problem occurred!

**Comment by leisim** [comment]
> Earlier I'm opening and closing the hive box on each user interaction. Maybe that's why the problem occurred!

That is a very bad idea and certainly explains the error...

**Comment by 1207roy** [comment]
Yeah. My bad. I'm closing this silly issue of mine. 
Thank you for this awesome database and I appreciate your hard work.
