### ISSUE TITLE
Inheritance? "type 'Entity' is not a subtype of type 'User' in type cast"

### ISSUE THREAD

**Issue by TomasWeg** [hivedb/hive#249]
Im trying to do the following:
I have a base class called **Entity** which has a property called **Id** and another class called **User** inherits from **Entity**, but when i try to get a value from the box, this exception is thrown:

```
Unhandled exception:
type 'Entity' is not a subtype of type 'User' in type cast
#0      Keystore.getValues.<anonymous closure> (package:hive/src/box/keystore.dart:122:45)
#1      MappedIterator.moveNext (dart:_internal/iterable.dart:395:18)
#2      new List.from (dart:core-patch/array_patch.dart:47:19)
#3      Iterable.toList (dart:core/iterable.dart:400:5)
#4      HiveRepository.entities (package:live_repository/src/repository/hive_repository.dart:13:45)
#5      main (file:///E:/Bitture/Git/live-repository/src/dart/test/live_repository_test.dart:9:20)
<asynchronous suspension>
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

**Version**
 - Flutter version: Latest
 - Hive version: Latest

**Comment by leisim** [comment]
Did you register both, the `EntityAdapter` and the `UserAdapter`? If yes, you need to register the `UserAdapter` first.

**Comment by bdevay** [comment]
Is this documented how to use inheritance with Hive? I don't really understand what and how should implement in the base and subclasses.

**Comment by TheMisir** [comment]
> Is this documented how to use inheritance with Hive? I don't really understand what and how should implement in the base and subclasses.

Inheritance support is added in latest version of hive_generator and doesn't supposed to be a special **feature** and might cause some issues, so for now I think documenting this might confuse newcomers. By the way I wanna tell that if something doesn't works on hive it's probably works but doesn't supported by hive_generator which is used for generating adapter code. You can make custom adapters most of the time if something goes wrong.
