### ISSUE TITLE
Access to already existing IndexedDb instance?

### ISSUE THREAD

**Issue by pouledodue** [hivedb/hive#251]
**Question**
Hi

I am coding a Flutter Web app

I already have data in a IndexedDB instance that is created by [lovefield](https://github.com/google/lovefield) in Javascript

Is it possible to configure Hive to be able to read from that data?

**Comment by leisim** [comment]
> Is it possible to configure Hive to be able to read from that data

Unfortunately, this is not possible with the current version of Hive since the data is stored in binary form in IndexedDB.
