### ISSUE TITLE
Type adapters aren't being generated

### ISSUE THREAD

**Issue by PotatoCurry** [hivedb/hive#255]
**Steps to Reproduce**
Running `pub run build_runner build` doesn't generate a type adapter for my class (SkycordUser) I wish to use with Hive. My overall project can be found [here](https://github.com/PotatoCurry/skycord/tree/acd6a2b17b652cb84e52246ed5863b7c280ea28a).

**Code**
```dart
import 'package:hive/hive.dart';
import 'package:skyscrapeapi/sky_core.dart';

import 'main.dart';

part 'skycord_user.g.dart';

@HiveType()
class SkycordUser extends HiveObject {
  @HiveField(0)
  String discordId;

  @HiveField(1)
  String skywardUrl;

  @HiveField(2)
  String username;

  @HiveField(3)
  String password;

  @HiveField(4)
  bool isSubscribed = false;

  Future<User> getSkywardUser() async {
    if (!cachedLogins.containsKey(discordId)) {
      final skywardUser = await SkyCore.login(username, password, skywardUrl);
      cachedLogins[discordId] = skywardUser;
    }
    return cachedLogins[discordId];
  }
}
```

**Output**
Upon running `pub run build_runner build`, I get the following output.
```
[INFO] Generating build script completed, took 612ms
[INFO] Reading cached asset graph completed, took 131ms
[INFO] Checking for updates since last build completed, took 936ms
[INFO] Running build completed, took 9ms
[INFO] Caching finalized dependency graph completed, took 79ms
[INFO] Succeeded after 103ms with 0 outputs (0 actions)
```
I don't see any obvious errors; it seems as if the class just isn't recognized by `build_runner`.

**Version**
 - Platform: Windows, Linux
 - Hive version: 1.4.1+1

**Comment by krypticallusion** [comment]
Hi, any word on this issue? Facing the same.

**Comment by Mravuri96** [comment]
Provide a typeId inside the ```@HiveType``` as such ``` @HiveType(typeId: 0)```

**Comment by PotatoCurry** [comment]
@Mravuri96 Tried it, doesn't seem to make a difference.

**Comment by Mravuri96** [comment]
> @Mravuri96 Tried it, doesn't seem to make a difference.

I usually run this command and it runs fine 
```zsh
flutter pub get && flutter packages pub run build_runner build --delete-conflicting-outputs  
```

**Comment by PotatoCurry** [comment]
@Mravuri96 I'm not using Flutter though, just Dart.

**Comment by Mravuri96** [comment]
@PotatoCurry then you can just run 
```zsh
pub run build_runner build --delete-conflicting-outputs  
```

**Comment by PotatoCurry** [comment]
TypeAdapter generation now seems to work, but I don't recall making any significant changes to the code interfacing with Hive.

**Comment by MalcolmMielle** [comment]
I'm also having the same issue. Not too sure what to do about it. I tried the example and the adaptor weren't generated
