### ISSUE TITLE
where clause 

### ISSUE THREAD

**Issue by MahdiPishguy** [hivedb/hive#257]
is any where clause to search in database? i can't find any solution or documentation about this feature

**Comment by frank06** [comment]
@MahdiPishguy you can do `box.values.where((obj) => conditions(obj))`, as objects are stored in memory

**Comment by MahdiPishguy** [comment]
@frank06 thanks so much, is any document or demo for that to understand how can i get more information? like `where`,`orderby`,groupBy`,`like`

**Comment by frank06** [comment]
Sure! https://api.dart.dev/stable/2.7.1/dart-core/Iterable-class.html
