### ISSUE TITLE
Overriding typeId in Adapters is very annoying.

### ISSUE THREAD

**Issue by Renesanse** [hivedb/hive#282]
Is it possible to tool a code generator to generate typeId getter with number given in annotation?

**Comment by marcelgarus** [comment]
Can you elaborate on what exactly do you find annoying? `TypeAdapter`s are already generated with a `typeId` given in the annotation:
```dart
@HiveType(typeid: 42)
class MyClass {}

// generates:
class MyClassAdapter {
  @override
  int get typeId => 42;

  ...
}
```

**Comment by Renesanse** [comment]
Every time generator generates the adapters with typeId => null. I am did something wrong? I passed a typeId to the annotation constructor

**Comment by marcelgarus** [comment]
Hmm, that is indeed strange. Can you post a sample file and the generated output? Also, which version of <kbd>hive</kbd> and <kbd>hive_generator</kbd> are you using?

**Comment by Renesanse** [comment]
Everything is fine, just removed ^ in dependencies.
