### ISSUE TITLE
flutter: Running Gradle task 'assembleDebug'... taking forever after adding hive to pubsec

### ISSUE THREAD

**Issue by ramtinq** [hivedb/hive#292]
**Steps to Reproduce**
I just added both of these to my pubsec:

```
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
```

tried stopping and running the application again (full restart with rebuilding), and now the process stuck at: 

`Running Gradle task 'assembleDebug'...`

**Version**
 - Platform: Android
 - Flutter version: 1.12.13
 - Hive version: 1.4.1+1

flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E266,
    locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.44.2)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by dop3ch3f** [comment]
Try running "flutter clean"  then retry

**Comment by ramtinq** [comment]
@dop3ch3f thank you for your suggestion. I already have. I guess the problem was due to the fact that the process was trying to download some additional files (I even had run "flutter pub get" before trying to build).
thanks anyway.

**Comment by ramtinq** [comment]
Well, now I'm getting build errors:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':path_provider_macos'.
> Could not resolve all artifacts for configuration ':path_provider_macos:classpath'.
   > Could not find builder.jar (com.android.tools.build:builder:3.2.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.2.1/builder-3.2.1.jar
> Could not get unknown property 'android' for project ':path_provider_macos' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9m 42s
Finished with error: Gradle task assembleDebug failed with exit code 1
```

**Comment by ramtinq** [comment]
the build error above seems to happen when including any package which uses local storage. The exact same error happens with "cached_network_image" for example.

**Comment by ramtinq** [comment]
the error is made by the `hive_flutter` package, and not `hive` itself.

**Comment by ramtinq** [comment]
didn't find out what is the exact issue, but I could finally build by deleting the packages from .pub-cache directory. In the above case, deleting `path_provider_macos` before build made it to build successfully.
