### ISSUE TITLE
[Question] Noticed encryptionKey is deprecated

### ISSUE THREAD

**Issue by Nash0x7E2** [hivedb/hive#293]
**Question**
Noticed `encryptionKey` is marked as deprecated, what is the updated method to pass a de decryption/encryption key?

The example under "Advanced" still uses encryptionKey as the preferred method. See below. 
https://github.com/hivedb/docs/blob/master/advanced/encrypted_box.md

**Version**
 - Platform: iOS, Android
 - hive: 1.4.1+1
 - hive_flutter: 0.3.0+1

**Comment by biklas7** [comment]
@Nash0x7E2 I had the same problem but after checking the [change log](https://github.com/hivedb/hive/blob/master/hive/CHANGELOG.md#140) I was able to understand that now we should use an `encryptionCipher`.

It says:

Deprecated encryptionKey parameter. Use `Hive.openBox('name', encryptionCipher: HiveAesCipher(yourKey))`.

**Comment by Nash0x7E2** [comment]
Thank you!
