### ISSUE TITLE
Opening a box takes much longer time

### ISSUE THREAD

**Issue by RaviKavaiya** [hivedb/hive#294]
(Note: Please ask for more clarification again, if I can't convince at first)

**Is your feature request related to a problem? Please describe.**
Currently, I am facing a weird issue of huge delay when I open a box *after the app has started.* Let me explain:
I use `Hive.initFlutter()` with NO parameter. I have 2 boxes. One is opened before `runApp()`. That gets opened in around 200 millis, max. That's fine. Then, I `runApp`. I do some authentication check and open the **second** box based on this process. (e.g., Open specific logged in user's box).

When I open this box, it takes whopping *4-5 seconds* to open a box (Doesn't matter a new box or existing one). Note that this box was entirely *empty* when I tested. Normal / Lazy box: doesn't matter. It takes this much time no matter what condition is.

Moreover, it doesn't apply any difference whether I close the *first* box or not. Maybe this delay is caused because my app is busy in other tasks (but I also need to keep in mind that this app will be used by lower-end devices).

**Describe the solution you'd like**
Not an expert in this area. I did some digging and found that these lines consume around 60-80% of box opening time! Especially `line: 20`.

https://github.com/hivedb/hive/blob/a536cf1190bf18c0e213a31e7ba160c9c760b5f0/hive/lib/src/backend/vm/backend_manager.dart#L19-L22

Providing no parameter to `initFlutter` pointed to existing directory like `/data/data/<package>/app_flutter`, which **always exists**. So, call to `if (!await dir.exists())` seems to be not needed, removing this would save some time.

Later, I discovered that we can provide custom paths. So, this call is needed.

### My suggestion:
- The check whether the provided directory is existing or not should be **removed** from `openBox`. 
- When we call `initFlutter()` (or just `init()`), *this check should be done*. So, this check is not needed again and again.
- This will save few millis when we open boxes.

**Describe alternatives you've considered**
- Nothing

**Version**
 - Platform: Tested on Android. (Specific device: Moto G5s Plus)
 - Flutter version: 1.15.21(dev)
 - Hive version: 1.4.1+1

**Comment by leisim** [comment]
This seems to be a problem with a specific device. I'd like to hear if others have the same problem on other devices.

**Comment by AntiqPeace** [comment]
@leisim I have a suggestion. (Not directly related, but helpful). 
Please have a look at this: [https://dart-lang.github.io/linter/lints/avoid_slow_async_io.html](https://dart-lang.github.io/linter/lints/avoid_slow_async_io.html)

I guess, if we change some of the file related `async` operations to `sync` ones, this may save some time.

**Comment by leisim** [comment]
@AntiqPeace It is a huge pain that async operations are kind of slow in Dart. Unfortunately synchronous operations are not an option because they block the entire app which is not reasonable.
