### ISSUE TITLE
add "insert" method like in Dart Lists, so that we don't have to reverse a long list every time

### ISSUE THREAD

**Issue by ramtinq** [hivedb/hive#297]
**Is your feature request related to a problem? Please describe.**

Lots of the time we need to insert items to a list's beginning. In Dart's Lists, we have the insert method, like:

`myList.insert(0, "hello");`

now because of the need to repeatedly adding items to my Hive box, I have been guided through the documentations not to use `box.put("myList", myList),` and instead use the add method for every item of the List I want to be saved to the box, `like box.add(myListItem)`

The problem is that this way when I want to extract the List from the box (via `box.values.toList()` ), I have to reverse the whole list to be usable in my app, and I think this would be a heavy operation (not sure how much).

**Describe the solution you'd like**
add a method like:

`box.insert(0, someObject);`

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: [e.g. 1.5.4]
 - Hive version: [e.g. 0.5.0]

**Comment by MarnoDev** [comment]
Need this too.

**Comment by leisim** [comment]
You could keep track of the indices yourself, start with a high value (like 100000) and reduce it every time you add something. You can store the index in the same box or in a different one. 

```dart
void putObjectAtBeginning(Box box, dynamic obj) {
  var currentIndex = box.get("index") as int;
  box.put(--index, obj);
  box.put("index", index);
}
```

**Comment by leisim** [comment]
Please reopen if you need further assistance :)
