### ISSUE TITLE
The method 'initFlutter' isn't defined for the type 'HiveInterface'

### ISSUE THREAD

**Issue by vaishnavmhetre** [hivedb/hive#298]
**Steps to Reproduce**

Imported hive_flutter as mentioned in #239 but still seems to show not found

**Code sample**
![Screenshot from 2020-04-26 16-04-18](https://user-images.githubusercontent.com/14543290/80305000-a25ddc00-87d7-11ea-9f71-1eb19cb91cdb.png)

**Version**
 - Platform: Linux (dev environment)
 - Flutter version: (Channel master, v1.18.0-9.0.pre.12)
 - Hive version: "1.4.1+1"
 - Hive Flutter version: "0.2.1"

**Comment by KiritchoukC** [comment]
Hi @vaishnavmhetre,

_initFlutter_ method is available from hive_flutter version 0.3.0

**Comment by vaishnavmhetre** [comment]
Oh! Thanks for the info. Flutter dev branch messed things up.

**Comment by sghaleb1** [comment]
I am using `hive_flutter: ^0.3.0+2` but still getting same error, and I have imported hive flutter. Any fixes?

**Comment by KiritchoukC** [comment]
Does `flutter pub get` outputs any errors?

**Comment by vladaman** [comment]
Having same issue:

The method 'initFlutter' isn't defined for the type 'HiveInterface'. `flutter pub get` shows no errors.

```yaml
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  grpc: ^3.0.0
  hive: ^2.0.0
  hive_flutter: ^1.0.0
```

**flutter doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.2, on Linux, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] VS Code (version 1.54.1)
[✓] Connected device (2 available)
```

code:
```dart
import 'package:flutter/material.dart';
import 'package:hive/hive.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Hive.initFlutter();
  runApp(MyApp());
}
```
![Screenshot from 2021-03-16 06-31-26](https://user-images.githubusercontent.com/907206/111260735-a5490180-8621-11eb-8f5a-7bec7c0f6ac9.png)

**Comment by tuemaytinh1981** [comment]
add row: import 'package:hive_flutter/hive_flutter.dart';

**Comment by FlutterCyber** [comment]
best and easy answer bro thanks
