### ISSUE TITLE
Best way to debug hive

### ISSUE THREAD

**Issue by duomoteng** [hivedb/hive#300]
Hi, I am thinking that is there a better to debug hive database.

For example, we can browser the data in the hive, thought the data is saved in the mobile,

**Comment by marcelgarus** [comment]
You can open any hive file in [Hive studio](https://studio.hivedb.dev), but that's about it I believe.

**Comment by duomoteng** [comment]
Thanks, marcelgarus, but how to download the hive file from iOS to my computer in order to open it

**Comment by re-bola** [comment]
Can this support opening encrypted boxes? It says "Invalid file" when I try to open any of my boxes (which are all encrypted)

**Comment by heinzan** [comment]
how search hive file in android mobile.

**Comment by TheMisir** [comment]
> how search hive file in android mobile.

Check out [this reply](https://github.com/hivedb/hive/issues/378#issuecomment-663513990).
