### ISSUE TITLE
[Question] Modeling nested data

### ISSUE THREAD

**Issue by andreierdoss** [hivedb/hive#304]
**Question**
Is it advisable to use Hive for nested data and if so, what is the best practice on modeling it?

**Description**
In a situation where the data looks like this:
`Company -> Projects -> Employees -> Tasks`

I want to load and show the data tree in a single view from projects downward. Also I would like to easily add/update/delete employees and tasks.

There are a max of 50 tasks per employee, 10 employees per project and 10 projects per company.

**Comment by leisim** [comment]
You can do it but keep in mind that if you change any field of an object, the whole hierarchy needs to be saved. Did you take a look at the [Relationships](https://docs.hivedb.dev/#/custom-objects/relationships) docs?
