### ISSUE TITLE
Is hive discontinued?

### ISSUE THREAD

**Issue by darwin-morocho** [hivedb/hive#305]
I can't see any recent activity in this repo maybe hive is discontinued?

**Comment by srihariash999** [comment]
I contacted @leisim on reddit too. He's usually pretty prompt but did not reply for quite some days now. That'd be sad if hive is discontinued !

**Comment by Mravuri96** [comment]
I believe the creator of this package has gotten a full time job at bmw. maybe he is too busy to work on this project 🤷

**Comment by softronaut** [comment]
It would be very sad because @leisim is one of the best contributors we have in community. I love all of his works.
I have couple of projects that highly depends on hive, if this library discontinued, I'll consider other options asap :/

**Comment by themindstorm** [comment]
Could it be that he currently has too much going on at the moment? He said he'll rewrite Hive in Rust in this issue #246. Some users were [asking for updates](https://github.com/hivedb/hive/issues/246#issuecomment-616216561), but he hasn't yet replied.

> I have couple of projects that highly depends on hive, if this library discontinued, I'll consider other options asap :/

Same for me

**Comment by dop3ch3f** [comment]
Hive is not discontinued. Instead @leisim is working on major updates that would address the issues and significantly improve the performance of hive. (cough Rust cough). please sit tight and wait. something good is coming

**Comment by dop3ch3f** [comment]
Please exercise a little patience.

**Comment by adiospace** [comment]
There's a difference between being super active on github and then disappearing completely for 2 months from the internet. For me it's pretty clear something happened, I don't know what, but if he was working at a new version, he would at least make time to answer a few questions here, review pull requests and so on... basically maintain the current version as well. I hope you are ok @leisim and I hope hive will be maintained somehow, as we all depend on it for now...

**Comment by mingsai** [comment]
> There's a difference between being super active on github and then disappearing completely for 2 months from the internet. For me it's pretty clear something happened, I don't know what, but if he was working at a new version, he would at least make time to answer a few questions here, review pull requests and so on... basically maintain the current version as well. I hope you are ok @leisim and I hope hive will be maintained somehow, as we all depend on it for now...

Perhaps a request for additional maintainers ought to be put out there? When the timing is right. **Hopefully with everything going on out there, @leisim and family are all happy and healthy.**

**Comment by passsy** [comment]
I'm in contact with Simon, he's fine. Finishing his bachelor thesis while starting a new job made him shift priorities for the moment. Since he will be back soon I'd like to postpone the question for additional maintainers for now and kindly ask for a bit of patience.

**Comment by jamesdixon** [comment]
@passsy glad to hear that he's okay! 

cc: @frank06

**Comment by martinloesethjensen** [comment]
@redrocket

**Comment by TheMisir** [comment]
We (me, @leisim @marcelgarus and lots of helpful contributors) are currently maintaining hive. @leisim is also working on new db called isar.
