### ISSUE TITLE
Generate TypeAdapter for Json Serializable Model

### ISSUE THREAD

**Issue by ismailnurudeen** [hivedb/hive#307]
**Question**
How do I use generate a TypeAdapter from a JsonSerializable object?

I want to store a Movie object to Hive and i followed the instructions on how to generate a TypeAdapter but the Object I'm trying to store was generated by the [Json_model](https://pub.dev/packages/json_model) library.

So it gives me the output below.

$ flutter packages pub run build_runner build
[INFO] Generating build script...
[INFO] Generating build script completed, took 1.9s

[WARNING] Deleted previous snapshot due to missing asset graph.
[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 1m 14s

[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 5.4s

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Found 12 declared outputs which already exist on disk. This is likely because the`.dart_tool/build` folder was deleted, or you are submitting generated files to your source repository.
[SEVERE] Conflicting outputs were detected and the build is unable to prompt for permission to remove them. These outputs must be removed manually or the build can be run with `--delete-conflicting-outputs`. 
The outputs are:
lib/models/cast.g.dart
lib/models/genre.g.dart
lib/models/movie.g.dart
lib/models/movie_detail.g.dart
pub finished with exit code 78

**Code sample**
Here's the model i want to generate the TypeAdapter for.

```dart
import 'package:hive/hive.dart';
import 'package:json_annotation/json_annotation.dart';

part 'movie.g.dart';

@HiveType(typeId: 0)
@JsonSerializable()
class Movie extends HiveObject {
  Movie();
  @HiveField(0)
  String title;
 @HiveField(1)
  List genre_ids;
  @HiveField(2)
  num vote_average;
  @HiveField(3)
  String overview;


  factory Movie.fromJson(Map<String, dynamic> json) => _$MovieFromJson(json);
  Map<String, dynamic> toJson() => _$MovieToJson(this);
}

```

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: 1.12.13
 - Hive version: 0.5.2

**Comment by leisim** [comment]
Sorry, I don't know why this happens :( Please reopen if you still have this problem.

**Comment by AnhDTN** [comment]
I have same problem :( please tell me how to resolve it?

**Comment by masterix21** [comment]
I'm facing with the same issue. @ismailnurudeen, did you found a fix?
