### ISSUE TITLE
Tell me, what is the length the cursor when reading, for example in Sqlite is ~ 2MB. Thank you

### ISSUE THREAD

**Issue by VitaliyFilippov2012** [hivedb/hive#311]
**Question**
Please explain the problem you are running into.

**Code sample**
```dart
Provide a few simple lines of code to show your problem.
```

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: [e.g. 1.5.4]
 - Hive version: [e.g. 0.5.0]

**Comment by marcelgarus** [comment]
If you use a normal `Box`, _all_ of its keys and value are loaded into memory. If you use a `LazyBox`, all of its keys are loaded into memory. Note that not only the object data itself is loaded into memory, but the keys and values are instantiated as fully-featured Dart objects — so there's probably lots (and I'm talking **_lots and lots_**) of overhead.

Therefore, in the past, package owner @leisim recommended using [<kbd>sqflite</kbd>](https://pub.dev/packages/sqflite) for applications with huge data volumes. That being said, **Hive 2.0** will probably have a more efficient Rust backend, but is not even in preview — in your situation I would probably go along with <kbd>sqflite</kbd> for now and maybe switch packages later.

**Comment by VitaliyFilippov2012** [comment]
Yes, thanks)

> If you use a normal `Box`, _all_ of its keys and value are loaded into memory. If you use a `LazyBox`, all of its keys are loaded into memory. Note that not only the object data itself is loaded into memory, but the keys and values are instantiated as fully-featured Dart objects — so there's probably lots (and I'm talking **_lots and lots_**) of overhead.
> 
> Therefore, in the past, package owner @leisim recommended using [sqflite](https://pub.dev/packages/sqflite) for applications with huge data volumes. That being said, **Hive 2.0** will probably have a more efficient Rust backend, but is not even in preview — in your situation I would probably go along with sqflite for now and maybe switch packages later.
> 
> Did that answer your question?
