### ISSUE TITLE
get hive values as json string

### ISSUE THREAD

**Issue by yemenpoint** [hivedb/hive#312]
**Question**
i want to get hive values as Json 

**Code sample**
   print(box.values);

**Version**
 - Hive  ^1.4.1+1

**Comment by ThinkDigitalSoftware** [comment]
What data type are you getting?

**Comment by yemenpoint** [comment]
instance of product_hive like object i want a json

**Comment by yemenpoint** [comment]
List of Instance of 'products_hive'

**Comment by yemenpoint** [comment]
final box = Hive.box<products_hive>(kPRoductsBoxName);
  List<products_hive> producttt = box.values.toList();
    var nnn = json.encode(box.values.toList());
    
  for (var i = 0; i < producttt.length; i++) {
  print(  json.encode(producttt[i]));
}

**Comment by ThinkDigitalSoftware** [comment]
You're using an object adaptor, that's why. Don't use an adaptor and it'll return json.

```dart
final box = Hive.box(kPRoductsBoxName);
```

**Comment by yemenpoint** [comment]
my products_hive class  is complex class inside class inside classes and Hive is already save data as json i want to get data from hive directly

**Comment by ThinkDigitalSoftware** [comment]
You should start using hive without an adaptor. That way it stores and returns json.

**Comment by yemenpoint** [comment]
can i merge json serializable.g.part with hive model to get model json ?
show me an example

**Comment by leisim** [comment]
Hive does not save the values as JSON. You need to use another package like [json_serializable](https://pub.dev/packages/json_serializable) or do it manually.
