### ISSUE TITLE
Duration type saving Error

### ISSUE THREAD

**Issue by z-dmitri** [hivedb/hive#314]
It could be nice to implement Duration type processing out of the box

Currently we have error on saving object with Duration type:

[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: HiveError: Cannot write, unknown type: Duration. Did you forget to register an adapter?

**Steps to Reproduce**
Create any object with Duration type field, then try to save/restore object.

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: 1.17.0
 - Hive version: 1.4.1+1

**Comment by patmuk** [comment]
`DateTime` can be saved. Maybe that is a valid work-around in your case?

**Comment by z-dmitri** [comment]
DateTime is not Duration

**Comment by patmuk** [comment]
If cause it is not. But I suggested a workaround using it: Have two DateTimes saved and you can calculate the Duration.

**Comment by marcelgarus** [comment]
#212 is a similar issue. You can add TypeAdapters for classes that you didn't write. In this case, #212 also contains the code for a `DurationTypeAdapter`. Just register it and everything should be working

**Comment by z-dmitri** [comment]
> DateTimes saved and you can calculate the Duration.
I have object with Duration fields - I do not want to create additional proxy objects or etc specially for the Hive

**Comment by z-dmitri** [comment]
> You can add TypeAdapters for classes that you didn't write.

Nice solution, thanks a lot

**Comment by leisim** [comment]
You can also use getters or setters for your `Duration` fields which convert the `Duration` to a `long` and back.
