### ISSUE TITLE
How do I loop the box in reverse?

### ISSUE THREAD

**Issue by DeadlyMissile** [hivedb/hive#316]
I am using GidView.builder to layout my stuff. How do I loop the contents of the box in reverse so I get the newest ones first?

**Comment by marcelgarus** [comment]
Hive depends on the [<kbd>dartx</kbd>](https://pub.dev/packages/dartx) package, which is also written by @leisim. It adds a `.reversed` property on `Iterable`s, which is very handy. Not sure about the performance impact tho.

**Comment by leisim** [comment]
The underlying data structure is an indexable skip list. Unfortunately the entries do reference the previous entries so you need to rely on the index. The performance should be `O(n log n)`. I think the `dartx` `.reversed` property does not use the indices so the performance would be much worse.
