### ISSUE TITLE
HiveError: Box not found when calling Hive.openBox()

### ISSUE THREAD

**Issue by Nipodemos** [hivedb/hive#319]
**Steps to Reproduce**
To be honest i don't know exactly how to reproduce, it was working all fine, until i called the box on a model class... Now even removing this classes the error remain... the error is on main.dart

**Code sample**
```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Hive.initFlutter();
  Hive.registerAdapter(PlayerAdapter());
  await Hive.openBox<Map>("placarUno");
  await Hive.openBox<Player>("players"); //error show here
  runApp(MyApp());
}
```

**Version**
 - Platform: Android
 - Flutter version: 
```
Flutter 1.19.0-2.0.pre.83 • channel master • https://github.com/flutter/flutter.git
Framework • revision 8abf0a6d8c (2 days ago) • 2020-05-16 15:07:34 -0700
Engine • revision aaf9e79f1d
Tools • Dart 2.9.0 (build 2.9.0-9.0.dev 2676764792)
```
 - Hive version: ^1.4.1+1

Here is a screenshot:
![image](https://user-images.githubusercontent.com/11494727/82278076-bbcdf000-995f-11ea-9b1f-b0fe35437bc5.png)

**Comment by vandir** [comment]
"Generic type parameters like Box<List> are unsupported due to Dart limitations."

` await Hive.openBox<Map>("placarUno");`

Source: https://docs.hivedb.dev/#/basics/boxes

**Comment by Nipodemos** [comment]
I forgot that limitation, it might be the problem.
But it is so strange this error, I simply cannot understand how can it shows up in that specific line... Weird 

I'm gonna test today

**Comment by Nipodemos** [comment]
yeah, i removed tha Map casting all over my code, and the error stop showing.
Thank you @vandir

**Comment by Hasankanso** [comment]
> > Generic type parameters like `Box<List>` are unsupported due to Dart limitations.
> 
> I think your problem is here:
> 
> ` await Hive.openBox<Map>("placarUno");`
> 
> Source: https://docs.hivedb.dev/#/basics/boxes

is what you said also valid on `List<String>` as exmaple? `Hive.openBox<List<String>>` or `Hive.openLazyBox<List<String>>`
