### ISSUE TITLE
Hive Limitations - Storage Limit

### ISSUE THREAD

**Issue by loonix** [hivedb/hive#321]
**Question**
Hi guys, first of all well done with Hive!

I was wondering about the storage limit with Hive, is it like sqlite that has no limit?

Is the limit here for a single box or for all boxes?
https://github.com/hivedb/hive/issues/19#issuecomment-522373971

**Comment by marcelgarus** [comment]
There is no theoretical storage limit, although opening a box will get slow if you have too many entries.
And all boxes are basically different databases, so they're completely separate.

**Comment by loonix** [comment]
@marcelgarus Thanks that has cleared it for me.

**Comment by leisim** [comment]
Thanks @marcelgarus, I think we can close this issue.
