### ISSUE TITLE
migrating hive boxes when adapter changes

### ISSUE THREAD

**Issue by patmuk** [hivedb/hive#325]
pulling back the question, problem is self made!

**Comment by thize** [comment]
What did you do to solve the problem?

**Comment by patmuk** [comment]
We just solved the problems we made ourselves: We wrote a generator, which is automatically assigning the annotation to each field. In the first version we just assigned a counter as the field id. That, however, brought the problem, that a new attribute between old ones, or removing an attribute reassigned the numbers, hence the whole box was unreadable. Now we are instead taking the class' hashcode%255.
So, just a solution for our self-made problem.
