### ISSUE TITLE
[DOC] - Can't see .initFlutter()

### ISSUE THREAD

**Issue by Ahmadre** [hivedb/hive#329]
**Question**
I've seen this: `await Hive.initFlutter();` in the documentation, but I can't access that method in my flutter code.

**Version**
 - Platform: iOS, Android
 - Flutter version: 1.19.0
 - hive: ^1.4.1+1
 - hive_flutter: ^0.3.0+2

**Comment by Ahmadre** [comment]
<img width="616" alt="Bildschirmfoto 2020-06-03 um 14 48 47" src="https://user-images.githubusercontent.com/18512224/83638379-560d7500-a5a9-11ea-9dae-45e6d5eba7df.png">

**Comment by leisim** [comment]
@Ahmadre you need to `import "package:hive_flutter"` to import the extension method.

**Comment by Ahmadre** [comment]
<img width="465" alt="Bildschirmfoto 2020-06-03 um 15 07 37" src="https://user-images.githubusercontent.com/18512224/83640138-00869780-a5ac-11ea-89b8-09befe904ace.png">

**Comment by Ahmadre** [comment]
Ok, I am getting tons of this:

```
Because hive_flutter >=0.3.0-dev depends on path >=1.6.0 <1.7.0 and every version of flutter_localizations from sdk depends on path 1.7.0, hive_flutter >=0.3.0-dev is incompatible with flutter_localizations from sdk.

So, because app depends on both flutter_localizations any from sdk and hive_flutter ^0.3.0+2, version solving failed.
pub get failed (1; So, because app depends on both flutter_localizations any from sdk and hive_flutter ^0.3.0+2, version solving failed.)
exit code 1
```

So I have to fix a lot of dependecies here before it's working

**Comment by Ahmadre** [comment]
Is there any plan when the dependecy fixes will come? Or any `dependecy_override` recommendations?

**Comment by Ahmadre** [comment]
ok here's how it's working: 

```yaml
dependency_overrides:
  dartx: ">=0.2.0 <1.0.0"
  path: ">=1.6.0 <2.0.0"
```

**Comment by leisim** [comment]
> Is there any plan when the dependecy fixes will come?

I need to fix the CI first. Hopefully tomorrow...

**Comment by Ahmadre** [comment]
no stress @leisim  :)

**Comment by SardorbekR** [comment]
is there solution to this?
