### ISSUE TITLE
[BUG/DOCS] - Empty

### ISSUE THREAD

**Issue by Ahmadre** [hivedb/hive#330]
Most of the white area boxes are empty:

<img width="1680" alt="Bildschirmfoto 2020-06-03 um 22 45 50" src="https://user-images.githubusercontent.com/18512224/83687463-15831b00-a5ec-11ea-9645-34b7c8f73e85.png">

**Comment by leisim** [comment]
@Ahmadre Thanks! Looks like the live code does not work properly. I'll take a look when I have time.

**Comment by Reprevise** [comment]
Hi there, is the issue resolved? If not, do you use Brave browser? Brave browser can block live code. If you do have Brave, disable your shields, if not, then can you tell us more about your browser?

**Comment by Ahmadre** [comment]
@Reprevise No i use default Chrome, Firefox and Opera

**Comment by rwuttke** [comment]
One thing I can see (and I hope is not a read herring), there seems to be a download order that may be a problem.

Firefox gets `basics/_navbar.md` with a 404 then gets `/_navbar.md`. Note that Firefox 77.0.1 works perfectly and shows the Code example and the run button works.

Whereas Chrome 83.0.4103.97 gets the one from the **root** first and then gets the 404 on attempting to get the navbar in **basics**.

**Comment by rakhimoff** [comment]
Hi. Any progress on this issue? Why don't you use simple code blocks? There is no need to run dart pad to explain something in code. It's totally impossible to understand many concepts of Hive.

**Comment by TheMisir** [comment]
Fixed by https://github.com/hivedb/docs/commit/5469517e490703436cbd314c946b50e86af45e18 =)
