### ISSUE TITLE
The box "name" is already open and of type Box<dynamic>.

### ISSUE THREAD

**Issue by nateshmbhat** [hivedb/hive#334]
The following HiveError was thrown while handling a gesture:
```
The box "recentsearch" is already open and of type Box<dynamic>.

When the exception was thrown, this was the stack: 
#0      HiveImpl._getBoxInternal (package:hive/src/hive_impl.dart:142:9)
#1      HiveImpl.box (package:hive/src/hive_impl.dart:157:33)
```

This happens when I call Hive.box<MyType>('boxname') when it has already been opened.

But this should not at all happen when calling `box` method as it's supposed to be already open.

I am using the current github master branch code of `hive`.
commit link : https://github.com/hivedb/hive/commit/d7ee72537a3b7ce1284bcbf5ee5f86e617a4f6fc

**Comment by nateshmbhat** [comment]
This issue happens in `_getBoxInternal` method in the below line :

```      
if ((lazy == null || box.lazy == lazy) && box.valueType == E) {
```
`box.valueType != E` is getting true
 
Basically this happens when : 
+ we open the box by specifying the generic type first time when opening the box.
+ the next time when we open and don't specify the generic type , this happens.

**Comment by Reprevise** [comment]
Whenever you open a box, you should specify the type, even if it's `dynamic`.

**Comment by nateshmbhat** [comment]
Is this requirement documented?

**Comment by Reprevise** [comment]
I don't know, but it's what I've learned.

**Comment by nateshmbhat** [comment]
But the error shown is completely unrelated. This is something that needs fixing.

**Comment by Reprevise** [comment]
How is this a separate issue? You're saying that when you open the box you're specifying a generic type but when you're getting the box youre not. If you've specified a generic type when you opened it, you need to do it everywhere you use `Hive.box()`. This is stated in the documentation.

**Comment by nateshmbhat** [comment]
The error needs to show the same message isn't it?

In this scenario error says box is already open when we do Hive.box() which is not the case.

**Comment by Reprevise** [comment]
The error states that you have already opened the box with a different type than when youre getting it.

**Comment by nateshmbhat** [comment]
Well, I think it's not clear enough.

My team couldn't relate this error to the mistake of not Specifying the generic type at all.

**Comment by TheMisir** [comment]
As @Reprevise said, you must always specify box<T> generic type.

**Comment by jeco1996** [comment]
I agree with @Reprevise I think this should be better documented. same issue here.

**Comment by Tek-hp** [comment]
> As @Reprevise said, you must always specify box generic type.

how do I do that?

**Comment by Dananee** [comment]
> The following HiveError was thrown while handling a gesture:
> 
> ```
> The box "recentsearch" is already open and of type Box<dynamic>.
> 
> When the exception was thrown, this was the stack: 
> #0      HiveImpl._getBoxInternal (package:hive/src/hive_impl.dart:142:9)
> #1      HiveImpl.box (package:hive/src/hive_impl.dart:157:33)
> ```
> 
> This happens when I call Hive.box('boxname') when it has already been opened.
> 
> But this should not at all happen when calling `box` method as it's supposed to be already open.
> 
> I am using the current github master branch code of `hive`. commit link : [d7ee725](https://github.com/hivedb/hive/commit/d7ee72537a3b7ce1284bcbf5ee5f86e617a4f6fc)

I got the same problem and it was that I forgot to add a type of box in main 

Before : await Hive.openBox('blog');
After : await Hive.openBox<Blog>('blog');

it was dynamic then I specify it

**Comment by EmanuelEnan** [comment]
Using hive is probably the most exhausting thing for just a simple local database.

It has a unique capability to show an error in every possible scenario.

**Comment by vigshrav** [comment]
> Using hive is probably the most exhausting thing for just a simple local database.
> 
> It has a unique capability to show an error in every possible scenario.

I second this opinion. God damn it, it is SOO frustrating.

**Comment by EmanuelEnan** [comment]
> > Using hive is probably the most exhausting thing for just a simple local database.
> > It has a unique capability to show an error in every possible scenario.
> 
> I second this opinion. God damn it, it is SOO frustrating.

I take this back bro. I made some problem there. Now it's working great. Infact I always use hive till now whenever I needed. It's extremely great 👍

**Comment by nikhil-RGB** [comment]
> This issue happens in `_getBoxInternal` method in the below line :
> 
> ```
> if ((lazy == null || box.lazy == lazy) && box.valueType == E) {
> ```
> 
> `box.valueType != E` is getting true
> 
> Basically this happens when :
> 
> * we open the box by specifying the generic type first time when opening the box.
> * the next time when we open and don't specify the generic type , this happens.

Thanks a ton, saved me so much agony!
