### ISSUE TITLE
Support multiple hive instances

### ISSUE THREAD

**Issue by yringler** [hivedb/hive#336]
**Is your feature request related to a problem? Please describe.**
I want to use hive in a plugin, to keep track of where a user is holding in an audio file. The problem is that the main application and the plugin have to be careful not to conflict, with registering type adapters with the same type id.

**Describe the solution you'd like**
There are probably a couple ways this use case could be dealt with.
It should be possible to have multiple "contexts" of hive, which are (from the app/plugin developers perspective) not aware of each other. 

**Describe alternatives you've considered**
1. Specify the type id in main app - not possible, because type id is marked in model class
2. Have the main app create the class and set the type id - that adds an annoyance to the client, but is probably what I'll have to do for now.
3. Use a high enough type id that there hopefully won't be a conflict - that's just a bad idea.

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: 1.17.3
 - Hive version: 1.4.1+1

**Comment by yringler** [comment]
I understand that a new version of hive is being actively worked on, so IDK if this will be in current hive. But maybe something to keep in mind for the new version.

**Comment by marcelgarus** [comment]
You can already create multiple `Hive` instances and register different adapters on them:

```dart
final MyHive = HiveImpl();
MyHive.registerAdapter(…);
```

**Comment by yringler** [comment]
Is that recommended? I thought I saw in the docs that that class wasn't
part of the public interface.
Meaning, it could change or be removed even in a minor release.

**Comment by leisim** [comment]
@yringler It is not something I intended but you can create multiple `HiveImpl` without a problem.

**Comment by RaviKavaiya** [comment]
@leisim so, you mean that it won't conflict with each other, even if same type id of different classes are registered?

**Comment by leisim** [comment]
Yes exactly. The two instances will not influence each other in any way.

**Comment by yringler** [comment]
Very cool! Thank you. Would it make sense to make HiveImpl officially part of the packages public interface, and document that it is only intended to be used explicitly by plugins to avoid conflicts?

Note to other's who may read this thread: to use HiveImpl, you have to `import 'package:hive/src/hive_impl.dart';`

**Comment by felangel** [comment]
FYI this is no longer possible due to https://github.com/hivedb/hive/commit/59ad5403593283233d922f62f76832c64fa33a3b#diff-7640da40298286a6e462d5a80f1c608b0df8660fb13bd5aad0f32b6db68b42c0.

I'm not sure why the change was made and in my opinion, this is a critical use-case for packages which use Hive.
For example, if `package:a` uses hive internally and `package:b` depends on `package:a`, `package:b` cannot use hive.

**Comment by jifalops** [comment]
I've looked into the Browser implementation but I'm not sure, will there be conflicts using multiple `HiveImpl()` instances on web?
