### ISSUE TITLE
HiveError - Box Name 

### ISSUE THREAD

**Issue by JayDev43** [hivedb/hive#353]
I'm currently using Hive and I'm getting the same error I've seen before "flutter: HiveError: Box not found. Did you forget to call Hive.openBox()?". 

Would it be possible to add the name of the Hive box which has not been found to this error message? - I currently have multiple boxes, and whenever I see this error I have to debug my application and step through the application looking for the point where its failing to allow me to find out which box its has a problem with. Knowing the name of the box would make this much easier.

**Comment by Jictyvoo** [comment]
Try to create a method in your class that manage the database, to get the box, and in this method do something like
```dart
Box<dynamic> getOpenBox(String boxName) {
    if (!Hive.isBoxOpen(boxName)) {
        return Hive.openBox(boxName);
    }
    return Hive.box(boxName);
}
```
So, in this way, you always will get a opened box even if it doesn't exists

**Comment by JayDev43** [comment]
> Try to create a method in your class that manage the database, to get the box, and in this method do something like
> 
> ```dart
> Box<dynamic> getOpenBox(String boxName) async {
>     if (!Hive.isBoxOpen(boxName)) {
>         return await Hive.openBox(boxName);
>     }
>     return Hive.box(boxName);
> }
> ```
> 
> So, in this way, you always will get a opened box even if it doesn't exists

I think the update of the comment is still useful, especially for very small effort. From what I can see in the source code the boxName is already in the method where the error is thrown.

Your idea is useful though. I did make some tweaks to it to make it generic , so I thought I'd post it encase it was useful to anyone else

```dart
Future<Box<E>> getOpenBox<E>(String boxName) async {
    if(!Hive.isBoxOpen(boxName)) {
      return Hive.openBox<E>(boxName);
    }

    return Hive.box<E>(boxName);
  }
```

**Comment by TheMisir** [comment]
I'm using something like

```dart
class _State extends State<> {
  Box _box;

  @override
  void initState() {
    super.initState();
    _box = await Hive.openBox('boxName');
  }
}
```
