### ISSUE TITLE
Is there recommendation about maximum numbers of boxes?

### ISSUE THREAD

**Issue by AndreySol** [hivedb/hive#354]
**Question**
I want to develop some kind of daily planner.
There are can be dates that has a lot of entries.
Entries can be added/modified/removed, also they should be sorted by time.

I assume the following architecture:
 - each date is a separate box
 - box contains entries for current date

According to my arch, there are can be a lot of boxes e.g. several thousands (if some one will use daily planner. for a long time).
My question is can many boxes be a problem?

**Code sample**
n/a

**Version**
n/a

**Comment by TheMisir** [comment]
Each box creates 2 files on device. Actual data and lock file. So, the limitation is related to device file system. If device uses FAT32 filesystem you are limited to ~30K boxes (FAT32 can have 65,536 entries).

Check out [this](https://android.stackexchange.com/questions/12422/is-there-a-maximum-number-of-files-per-directory-or-maximum-directory-size#:~:text=This%2C%20really%2C%20isn't,the%20length%20of%20its%20name.) and [that](https://superuser.com/a/446284/773896) articles to learn more about file system limits.
