### ISSUE TITLE
Hive doesn't work with Edge Browser (flutter web)

### ISSUE THREAD

**Issue by Freundschaft** [hivedb/hive#357]
**Steps to Reproduce**
add hive to flutter web project, and run
`await Hive.openBox('box');`
works well in chrome, but in edge, breaks my app (won't load)

**Code sample**
`await Hive.openBox('box');`

**Version**
 - Platform: Windows 10, Edge Browser
 - Flutter version: [√] Flutter (Channel beta, 1.19.0-4.2.pre, on Microsoft Windows [Version 10.0.19041.329], locale de-DE)
 - Hive version: 1.4.1

**Comment by Freundschaft** [comment]
I figured out what's wrong, apparently edge doesnt implement indexeddb when browsing in private mode, this behavior is different in chrome

**Comment by Freundschaft** [comment]
apparently the error is related to getAll not being available on Microsoft Edge indexeddb implementation

**Comment by leisim** [comment]
Thanks @Freundschaft maybe we can fix it using polyfill...

**Comment by TheMisir** [comment]
@Freundschaft could you let us know Edge version you're running?

**Comment by TheMisir** [comment]
Can someone check if #400 works or not?

**Comment by Freundschaft** [comment]
Its the trident based edge version (non-chromium).

**Comment by Constans** [comment]
> Can someone check if #400 works or not?

Before this fix I got this error:
`NoSuchMethodError: Object doesn't support property or method 'getAllKeys' (Error 438)`
After the fix I get this error:
`NoSuchMethodError: Unable to get property 'KU' of undefined or null reference (Error 5007)`

The testing setup is simple. I just created a new Flutter project and added the hive packages in pubspec.yaml.
Then modified main.dart as follows:
```
import 'package:flutter/material.dart';
import 'package:hive/hive.dart';
import 'package:hive_flutter/hive_flutter.dart';

void main() async {
  await Hive.initFlutter();
  await Hive.openBox('settings');
  runApp(MyApp());
}
```
I hope it helps.

**Comment by Constans** [comment]
I've re-run my tests and it actually seems in both versions same error is thrown:

`NoSuchMethodError: Object doesn't support property or method 'getAllKeys' (Error 438)`

The difference is the line number where it happens due to the patch.

**Comment by TheMisir** [comment]
> I've re-run my tests and it actually seems in both versions same error is thrown:
> 
> `NoSuchMethodError: Object doesn't support property or method 'getAllKeys' (Error 438)`
> 
> The difference is the line number where it happens due to the patch.

Thanks, I think it caused by the line below:

```dart
if (store.getAllKeys is Function ...
```

I have to use `hasOwnProperty` method. [ref](https://stackoverflow.com/a/48765736/7616528).

**Comment by TheMisir** [comment]
It looks like I have to use [js package](https://pub.dev/packages/js). Does someone knows could adding js break hive on other platforms or not? Because it's only available for browser environment (displayed on pub.dev page).

![image](https://user-images.githubusercontent.com/29130291/90774957-4b8d8c80-e309-11ea-8aa6-2c9dfb5c0a32.png)

**Comment by TheMisir** [comment]
@Constans can you please test latest commit https://github.com/hivedb/hive/pull/400/commits/5d1742f1e9ce969745b5e879c921a5d56cc1ce21 [/fix/issues/357](https://github.com/hivedb/hive/tree/fix/issues/357)?

**Comment by Constans** [comment]
> @Constans can you please test latest commit [5d1742f](https://github.com/hivedb/hive/commit/5d1742f1e9ce969745b5e879c921a5d56cc1ce21) [/fix/issues/357](https://github.com/hivedb/hive/tree/fix/issues/357)?

Works like a charm after overriding the current with the patch:

```
dependency_overrides:
  hive:
    git:
      url: git://github.com/hivedb/hive.git
      ref: fix/issues/357
      path: hive
  hive_flutter:
    git:
      url: git://github.com/hivedb/hive.git
      ref: fix/issues/357
      path: hive_flutter
  hive_generator:
    git:
      url: git://github.com/hivedb/hive.git
      ref: fix/issues/357
      path: hive_generator
```

This was bugging me for almost 1 year. :)) 
I have a lot of dependencies in a project and I just assumed it will not work on Microsoft Edge. :)
Thanks for the fix!
