### ISSUE TITLE
Only classes or enums are allowed to be annotated with @HiveType

### ISSUE THREAD

**Issue by obrunsmann** [hivedb/hive#361]
**Steps to Reproduce**
I have several enums, for example:

```
@HiveType(typeId: 7)
enum TimerMode {
  @HiveField(0)
  AMRAP,
  @HiveField(1)
  FT,
  @HiveField(2)
  FQ,
}
```

The generation worked without problems. Only after an update of completely different dependencies, the build runner does not work anymore.

I get the following error message:

> [SEVERE] hive_generator:hive_generator on lib/constants/timer_mode.dart:
> Error running TypeAdapterGenerator
> Only classes or enums are allowed to be annotated with @HiveType.

I tried to comment out the check in https://github.com/hivedb/hive/blob/master/hive_generator/lib/src/type_adapter_generator.dart#L60 afterwards the generation worked fine again.

**Version**
  Flutter Version 1.19.0-4.2.pre
  build_runner: ^1.10.0
  json_serializable: ^3.3.0
  hive_generator: ^0.7.0+2
  hive: ^1.4.1+1

**Comment by Aeon-Avinash** [comment]
I also did encounter the exact same problem after updating other dependencies.
The build runner for hive generator doesn't work anymore for ENUM types.

> [SEVERE] hive_generator:hive_generator on lib/src/models/medicine/medicine_type.dart (cached):
> Error running TypeAdapterGenerator
> Only classes or enums are allowed to be annotated with @HiveType.

I even tried rolling back the dependencies but still got the same error. 
Only way to circumvent that was to comment out the type check in hive_generator code as [obrunsmann has mentioned above](https://github.com/hivedb/hive/blob/master/hive_generator/lib/src/type_adapter_generator.dart#L60).

Flutter 1.17.5 • channel stable
shared_preferences: ^0.5.7+3
hive: ^1.4.1+1
hive_flutter: ^0.3.0+2
path_provider: ^1.6.11
cloud_firestore: ^0.13.7
provider: ^4.1.3
rxdart: ^0.24.1
connectivity: ^0.4.9
intl: ^0.16.1

**Comment by TheMisir** [comment]
Fixed by https://github.com/hivedb/hive/pull/365
