### ISSUE TITLE
Hive with flutter_localizations

### ISSUE THREAD

**Issue by EpiSayLaCata** [hivedb/hive#367]
Hello guys,

I'm using Hive for my app to stock multiple datas from my back-end. And since tomorrow, I wanted to do some multi language (english / french actually) with flutter_localizations.

But there is one major problem with it and I cannot find any fixes anywhere and nothing on stackoverflow.

![output](https://user-images.githubusercontent.com/5529304/86755402-e8d67f00-c041-11ea-9519-1b20d899ea9b.PNG)
![pubspec](https://user-images.githubusercontent.com/5529304/86755404-e96f1580-c041-11ea-9343-862e4b8d29a9.PNG)

I joined the pubspec with my dependencies, and the output in the console where the pub get is supposed to work.

Is there any way to work on that ? 

Thank you !

**Comment by EpiSayLaCata** [comment]
Alright, this is working with what you're saying. Thanks a lot !

By the way, why Hive won't be updated ? I'm using it a lot in my project actually ^^'

**Comment by Jictyvoo** [comment]
What I do know is that the Hive repository is updated, but a new version of the package is needed to use all new changes to a project.

**Comment by EpiSayLaCata** [comment]
Alright, thank you for your response :)
