### ISSUE TITLE
Where clause example

### ISSUE THREAD

**Issue by guit4eva** [hivedb/hive#371]
**Question**
Is there an example of a where clause somewhere? I am trying to get my head around the following:

`box.values.where((obj) => conditions(obj))`

**Code sample**
```dart
import 'package:hive/hive.dart';

part 'book.g.dart';

@HiveType(typeId: 0)
class Book {
  @HiveField(0)
  String id;
  @HiveField(1)
  String title;
  String category;

  Book({
    this.id,
    this.title,
    this.category
  });

  factory Book.fromMap(Map<String, dynamic> map) => Book(
        id: map['id'],
        title: map['title'],
        category: map['category'],
      );

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'title': title,
      'category': category,
    };
  }
}
```
**This is where I need to get all books where category is equal to "drama":**
```dart
box.values.where((element) => element).toList(); 
```

**Comment by marcelgarus** [comment]
Did you try `box.values.where((book) => book.category == 'drama').toList()`?

**Comment by guit4eva** [comment]
> Did you try `box.values.where((book) => book.category == 'drama').toList()`?

I could have sworn I tried that! It's working now though :) Thanks very much - really appreciated 👍🏼
