### ISSUE TITLE
How to scale hive across applications

### ISSUE THREAD

**Issue by kalluriramkumar** [hivedb/hive#380]
Currently we have an application which uses hive as its database. We are coming up with few more applications(mobile apps) to uses the same hive database. As the load increases from multiple applications, how to scale hive database? Further, can we run hive as a separate service such that all the applications communicate with hive running as a service. 

**Version**
 - Platform: Linux - Ubuntu
 - Dart version: 2.8.4 (stable)
 - Hive version: 1.3.0

**Comment by TheMisir** [comment]
I'm not sure hive is capable of handling requests from different clients. There might be conflicts between clients and even race condition issues may occur if 2 clients tries to write to same box at same time.
