### ISSUE TITLE
lazyBox and valuelistenablebuilder

### ISSUE THREAD

**Issue by prerakkumar** [hivedb/hive#381]
i am able to use normal box with valueListenableBuilder. How can i achieve the same thing with lazybox

**Comment by TheMisir** [comment]
`LazyBox`es already supports [listenable](https://github.com/hivedb/hive/blob/master/hive_flutter/lib/src/box_extensions.dart#L21). Did you tried?

```dart
ValueListenableBuilder(
  valueListenable: Hive.lazyBox('myLazyBox').listenable(),
  ...
),
```

**Comment by prerakkumar** [comment]
![Untitled](https://user-images.githubusercontent.com/61604061/88337476-6c87af80-cd54-11ea-99c6-a126422fc8f2.png)
thank you so much for the response.i have attached the error i am getting .basically when i am using it with a builder to list items in a list. its producing the error.

**Comment by prerakkumar** [comment]
> `LazyBox`es already supports [listenable](https://github.com/hivedb/hive/blob/master/hive_flutter/lib/src/box_extensions.dart#L21).
> 
> ```dart
> ValueListenableBuilder(
>   valueListenable: Hive.lazyBox('myLazyBox').listenable(),
>   ...
> ),

Thank you so much for the response. 
problem is actually i am not able to solve the combining values of a lazybox in a list as i can do with a normal box.
![Untitled](https://user-images.githubusercontent.com/61604061/88337946-339c0a80-cd55-11ea-9587-12a6a27ac5d0.png)

**Comment by TheMisir** [comment]
@prerakkumar the issue is LazyBox doesn't caches items in memory. So there is not `LazyBox.values` property. You can use `box.keys.length` instead to get item count.

**Comment by prerakkumar** [comment]
> @prerakkumar the issue is LazyBox doesn't caches items on memory. So there is not `LazyBox.values` property. You can use `box.keys.length` instead to get item count.
> 
> Also the previous issue was due to you have used `Box<T>` instead of `LazyBox<T>` which is different types.

yeah i figured it out at the last minute <T> issue. and gotcha, i will definitely try to achieve the results which i want through lazybox. and thank you for such a quick response and for such a great Database.

**Comment by TheMisir** [comment]
Not at all. fyi: The db was made by @leisim, not me )
