### ISSUE TITLE
How to do test with hive?

### ISSUE THREAD

**Issue by LeonardoRosaa** [hivedb/hive#382]
**Question**
Hi, thanks for package. But i'm with difficulty for a create test in my app. Your has a tutorial to this?

**Code sample**
```dart
test('Should create a block and return id', () async {
      final blockId = await blockService.save(new BlockModel(name: 'Test block'));

      print(blockId);
    });
```

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: [e.g. 1.20.0-7.1.pre - channel dev]
 - Hive version: [e.g. 1.4.1+1]

**Comment by TheMisir** [comment]
You can check [hive_imply_test.dart](https://github.com/hivedb/hive/blob/master/hive/test/tests/hive_impl_test.dart) which has some tests that you can use it for yourself.

For example you can write something like that:

```dart
Future<HiveImpl> initHive() async {
  var tempDir = await getTempDir();
  var hive = HiveImpl();
  hive.init(tempDir.path);
  return hive;
}

test('returns false if no box was created', () async {
  var hive = await initHive();
  var box = await hive.openBox('testBox');
  await box.put('key', 'value');
  expect(box.get('key'), 'value');
  await hive.close();
});
```
