### ISSUE TITLE
Hierarchy structure with hive?

### ISSUE THREAD

**Issue by MBaumgartenBR** [hivedb/hive#388]
Hey guys!

I'm new to hive... Before deep diving in the library I would like to know if the autoincrement feature is safe to use for referencing ids, like:

ID : 0, parent: null  //root
ID : 1, parent : 0    //child of root
... And so on.

Because I need to work with a tree style of data.

What I understood is that if I delete index 1, index 2 would take its place as index 1. So doing that, the children of index 2 would lose reference and later when I add a new object it would get index 2 and take the children of the deleted index 2.
Is that how the autoincrement was implemented?

I could fix that by creating another hive box to store an integer to use as key and increment it manually whenever I would add another object. Is there a better way of doing it?

Am I missing something?
Thanks in advance for your time!

**Comment by rafaelgazani** [comment]
you can define your own index. I use uuid.

**Comment by TheMisir** [comment]
I think autoincrement should work for your needs. You can also use custom indices like @rafaelgazani said.

**Comment by MBaumgartenBR** [comment]
Thanks guys!
