### ISSUE TITLE
Can .watch({String key}) take option to emit initial value?

### ISSUE THREAD

**Issue by JoshJuncker** [hivedb/hive#389]
Hi.  I am really enjoying Hive so far.  Thanks for all the work!

The main snag I am running into is when I use a StreamBuilder with the Box watch function. It doesn't emit the original value as far as I can tell. It only emits changes. I realize I can supply 'initialData' to StreamBuilder and supply a new BoxEvent(key, value, deleted). I'm just hoping for the extra syntactical sugar as usually when I use a StreamBuilder, I want it to emit the initial value.
Right now I have a hacky workaround as seen below. I'm sure I could figure something else out to add the initial data to the stream rather than re-writing the object, but I don't know enough of creating my own streams yet...

```dart
import 'package:hive/hive.dart';

extension BoxExtensions on Box {
  Stream<BoxEvent> watchWithInitial({String key}) {
    Future.delayed(Duration(milliseconds: 10), () {
      var obj = get(key);
      put(key, obj);
    });
    return watch(key: key);
  }
}
```

**Comment by leisim** [comment]
I don't think your extension method is Jacky. If we would implement the feature, this is exactly how it would be done.

**Comment by TheMisir** [comment]
I think this is because, Box.watch emits events instead of data. So you have to get data manually (eg: using `Hive.box<E>(boxName).getAt(i)`) before building the widget. The StreamBuilder will rebuild when value is changed.

**Comment by rohankandwal** [comment]
I can see few issues mentioning same thing. I am using Hive with BLoC wherein I listen to the stream but all have to get initial data the first time. There should be a easy way out wherein we get the initial data and then new events thereafter.
