### ISSUE TITLE
Make generic TypeAdapters possible

### ISSUE THREAD

**Issue by marcelgarus** [hivedb/hive#41]
**Is your feature request related to a problem? Please describe.**
Currently, if I have a generic type, I can't register a generic TypeAdapter for that type.

For example, I have the following class (coming from the [repository](https://pub.dev/packages/repository) package):
```dart
class Id<T> {
  String id;
  ... (custom implementations of ==, hashCode etc.)
  String toString() => '<$T with id $id>';
}
```
It's then used by my entity classes like this:
```dart
@HiveType()
class Article {
  @HiveField(0)
  Id<Article> id;

  @HiveField(1)
  ...
}
```
Now, I want to save an `Article` to hive.
I registered the automatically generated `ArticleAdapter()` and a custom-built `Adapter<Id>`.

However, hive complains that it doesn't know how to serialize `Id<Article>`. That's because internally, there's a map of types to their adapters and `Id != Id<Article>`.

Can this easily be implemented?

**Comment by leisim** [comment]
Are you using the latest version of Hive? This should actually work...

**Comment by leisim** [comment]
I'm going to close this since I belive it is already resolved. Please reopen if it doesn't work for you...
