### ISSUE TITLE
Extended ASCII characters

### ISSUE THREAD

**Issue by InfiniteTabs** [hivedb/hive#412]
**Question**
I'm running into an issue where characters like 'ö' throwing an error, then I noticed this part in the code:

```dart
bool get isAscii {
    for (var cu in codeUnits) {
      if (cu > 127) return false;
    }
    return true;
  }
```

Is there a reason to not include all 255 ASCII characters?

Best regards

**Comment by apoleo88** [comment]
> I recommend using the `dartx` `String.chars` extension.

.chars or .characters converts from string to a list of unicode char. I don't understand how to get to ascii from there.

I am trying to use as a key a list of bytes, converting it somehow to unicode, but I keep bumping in conversion errors or invalid characters. 
Can you please provide an example and add it to the documentation?

**Comment by proformance** [comment]
Another solution that allows you to use any character is to use base64-encoding (it's only restricted for keys)

```
final String encodedKey = base64.encode(utf8.encode(key));
box.put(encodedKey, json);
```
