### ISSUE TITLE
What happens when a box is open and the application is killed?

### ISSUE THREAD

**Issue by NeilKerman** [hivedb/hive#414]
**Question**
Hello, I want to know, what happens when a box is open and the Flutter application is killed by the user?

Let's say, I have declared a box called 'database'. Now I have opened this box in void main() under main.dart in Flutter. It was on the XYZ page (when the box is still open) and the user killed the application. Will the box be closed automatically when this happens?

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: [e.g. 1.5.4]
 - Hive version: [e.g. 0.5.0]

**Comment by JagandeepBrar** [comment]
https://docs.hivedb.dev/#/more/faq?id=what-happens-if-my-app-is-killed

> The worst thing that can happen is that you lose the last entry if it isn't written completely yet. Hive has built-in integrity checking and crash recovery and takes care of everything.

**Comment by TheMisir** [comment]
Nothing will happen if the app is not killed during write process (eg: `Hive.box('box').put(key, value)`). If it killed during writing to the disk you'll might lose last entry as @JagandeepBrar said.
