### ISSUE TITLE
box.put method with same key is always growing the hive file

### ISSUE THREAD

**Issue by forfuns** [hivedb/hive#417]
**Question**
I build app with hive storage state, no matter same key with same value ,the hive db file always growing,then read data is slow and not smooth.
box.put method should Overwrite the data with key ?
I saw hive file with so many repeated record

**Code sample**
```dart
var sameKey = "SAME_KEY";
SameObject value = SameObject();
var box = await Hive.openBox(HIVE_BOX_NAME);
box.put(sameKey,value);

// the HIVE_BOX_NAME.hive file will alway growing
```

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: 1.20.2
 - Hive version: 1.4.4

**Comment by TheMisir** [comment]
Please check [compaction](https://docs.hivedb.dev/#/advanced/compaction) section from hive docs.

> Hive is an append-only data store. When you change or delete a value, the change is written to the end of the box file. Sooner or later, the box file uses more disk space than it should. Hive may automatically "compact" your box at any time to close the "holes" in the file.

**Comment by leisim** [comment]
This is expected behavior because of the append only architecture of Hive.
