### ISSUE TITLE
What happens with hive db if I update a box without encryption key with new encryption key ?

### ISSUE THREAD

**Issue by alejandrogiubel** [hivedb/hive#427]
**Question**
I have a box without encryption key, and naw I which to improve the security of the database using encryption key. I lost the database information if I upgrade a box without encryption key to a box with encryption key?

**Version**
 - Platform: iOS, Android
 - Flutter version: [1.17.0]
 - Hive version: [1.4.4]

**Comment by leisim** [comment]
> I have a box without encryption key, and naw I which to improve the security of the database using encryption key. I lost the database information if I upgrade a box without encryption key to a box with encryption key?

If you try that without clearing or deleting the unencrypted box first, it will crash during the opening.
