### ISSUE TITLE
[Feature Request] ReadOnly Box

### ISSUE THREAD

**Issue by Afsar-Pasha** [hivedb/hive#43]
Request for ReadOnly Box which can read data without write permission(Ex.from flutter assets)

**Comment by leisim** [comment]
I will look into this...

**Comment by re-bola** [comment]
I would also find this super helpful. Let me know if you need a hand.

**Comment by re-bola** [comment]
Any update on this? Also, if this is implemented, can you read directly from assets (for flutter) instead of having to copy over the box?

**Comment by leisim** [comment]
@re-bola I'm still working on this and yes you will be able to open a box directly from the assets. It will look somehow like this:
```
var bytes = rootBundle.load('assets/myBox.hive');
var box = Hive.openBoxFromBytes('myBox', bytes);
```

Would that be okay?

**Comment by re-bola** [comment]
Looks good. Will it still support LazyBoxes?

**Comment by leisim** [comment]
Not in combination with read only boxes from bytes. It makes no sense since you cannot write to boxes from bytes anyways...

But the regular lazy boxes will still be there...

**Comment by X-Wei** [comment]
Seems `openBoxFromBytes()` method is not present in hive v2.0 -- how can we open a box in read-only mode now?

**Comment by fredrikbaberg** [comment]
@X-Wei I think the `bytes` argument should be used now. Not sure where I saw it described, but it's what I'm using in my current project. You could try the following code snippet; I've only tested it target Windows in debug mode but hope it helps.

```dart
var _bytes = await rootBundle
            .load(path)
            .then((value) => value.buffer.asUint8List());
        _box = await Hive.openBox(
          name,
          bytes: _bytes,
        );
```

**Comment by X-Wei** [comment]
Thanks @fredrikbaberg !

But explicitly adding read-only boxes would be helpful, e.g. we could allow concurrent access to read-only boxes possible. @leisim WDYT?
