### ISSUE TITLE
Check opened box is lazy

### ISSUE THREAD

**Issue by jimpeeters97** [hivedb/hive#441]
**Question**
I use 2 types of boxes (regular and lazy) in my code. The 2 methods I define below are both used for CRUD-operations but sometimes I get an error because a regular box is open when I try to open a lazy one. Is there a way I can check whether the box that is opened is lazy or not?

**Code sample**
```dart
static Future<Box<StorageDAO>> _openStorageBox() async {
    if (Hive.isBoxOpen('box')) {
      return Hive.box('box');
    }
    return Hive.openBox('box');
  }

  static Future<LazyBox<StorageDAO>> _openStorageBoxLazy() async {
    if (Hive.isBoxOpen('box')) {
      return Hive.lazyBox('box');
    }
    return Hive.openLazyBox('box');
  }
```

Thanks.

**Comment by TheMisir** [comment]
It's not part of the public API but I think you can use:

```dart
var box = Hive.getBoxWithoutCheckInternal('name_here');
print(box.lazy);
```

---

Btw may I know why are you opening same box as regular and lazy box on same app?

**Comment by jimpeeters97** [comment]
Right, i will try that one. Can I make it public for the use of my implementation?

I was searching for ways to save as much RAM as possible, so i try closing the box after it isn't used for like 90 seconds or so.

For the reading of data, I use a regular box, because i need the values. For other actions (save, delete, ...) I try to use lazy boxes when the regular box isn't open.

I don't know if it benefits the use of RAM and/or performance, but I'm trying to optimize it as much as possible. Is this the most efficient way to use boxes or should I just use the regular boxes and keep them open?

**Comment by TheMisir** [comment]
> Right, i will try that one. Can I make it public for the use of my implementation?

Yeah you can use the function for your implementation. I can not guarantee the method will not removed in future or not. But for now you can keep using it.

> I don't know if it benefits the use of RAM and/or performance, but I'm trying to optimize it as much as possible. Is this the most efficient way to use boxes or should I just use the regular boxes and keep them open?

I think it depends on how much data does the box stores. Also you can also use `LazyBox.get(key)` and `LazyBox.getAt(index)` methods to get data from the LazyBox (the methods are asynchronous).

**Comment by jimpeeters97** [comment]
Perfect, that's a good tip. Thanks!

I use a split strategy for my domain objects: for the objects where <= 1000-2000 records have to be stored, I use Hive because of the high performance and for objects with > 2000 records I use Moor because of the use of indexes, ...
