### ISSUE TITLE
Updating app may put it in dead state due to hive

### ISSUE THREAD

**Issue by Grrravity** [hivedb/hive#445]
Firstly i'm sorry I cannot show any error logs nor steps to reproduce it as it happens when we update the app from the store.

We're running a flutter app using Hive for the entire data we are using.
Some of our users are facing issues when an update is been released that cause the app to load infinitly or to provide null datas.

After my own searchs and experiments I figured out that hive is the probleme as the data we're trying to receive from our API has changed since the last release. The models we've updated are not stored and makes our app to load for years (we've been updating that to stop loading and show errors but still the probleme is there).

We've tryied to fix that by .clear() our boxes but I wonder if that's enought.

My question is : 
Is .clear() box enought to clear out datas we've stored in box and being able to reuse the same box with brand new model/datas inside
Or do I have to .close() them to be sure I can put a new model version inside ?

I mean for exemple I've got a token model with 2 fields : String token and String expireAt
I want to update it and changed it to : String token, Date expireAt, String tokenType

do that kind of changes requires .clear() or .close() or none of them ?

Thanks a lot for your help :)

**Comment by TheMisir** [comment]
Please check [updating a class](https://docs.hivedb.dev/#/custom-objects/generate_adapter?id=updating-a-class) section.

**Comment by leisim** [comment]
> Is .clear() box enought to clear out datas we've stored in box and being able to reuse the same box with brand new model/datas inside

`.clear()` is enough. It will delete the whole box file and you should be fine again...

If you however resprect the limitations on the page liked by @TheMisir you should not need any manual migration logic.

**Comment by Grrravity** [comment]
I'll check it out, thanks :)

**Comment by Grrravity** [comment]
Seems like we're already aware of that @TheMisir . I'll doublecheck with my team tho.
I guess if this issue still occur it may not come from Hive as @leisim said .clear() was enougth.

I'm closing this.
Thanks
