### ISSUE TITLE
[hive_generator] remove analyzer version constraint

### ISSUE THREAD

**Issue by Akora-IngDKB** [hivedb/hive#446]
**Steps to Reproduce**
1. Set up a new dart project.
2. Add `build_runner: ^1.10.3` and  `hive_generator: ^0.7.2+1` to the `pubspec.yaml`.
3. Run `pub get`.

**Version**
 - Platform: Native
 - Flutter version: `1.22.0-10.0.pre.363`
 - Hive version: `^1.4.4`

**Output**
```
Because no versions of hive_generator match >0.7.2+1 <0.8.0 and hive_generator 0.7.2+1 depends on analyzer >=0.36.0 <0.40.0, hive_generator ^0.7.2+1 requires analyzer >=0.36.0
  <0.40.0.
And because build_runner >=1.10.3 depends on build_resolvers ^1.4.0 which depends on analyzer ^0.40.1, hive_generator ^0.7.2+1 is incompatible with build_runner >=1.10.3.
So, because local_firebase_auth depends on both build_runner ^1.10.3 and hive_generator ^0.7.2+1, version solving failed.
```

**Comment by leisim** [comment]
I believe we can just remove this constraint and it should be solved.

**Comment by Akora-IngDKB** [comment]
Yes it should.

**Comment by WizSan** [comment]
Try "flutter upgrade"

**Comment by Akora-IngDKB** [comment]
> Try "flutter upgrade"

I did that but because of the version constraint, it didn't work.
I had to downgrade `build_runner` in order to get it to work.

As @leisim said, removing, the constraint will fix the issue.

**Comment by WizSan** [comment]
Are you trying to generate type builder ? Because I have some problems related to this and it is being solved using the version of hive generator: ^0.7.2+1, without removing the carat notation.

**Comment by Akora-IngDKB** [comment]
I'm am using build_runner and hive_generator in the same project.
Both depend on analyzer but the correct `build_runner: ^0.10.3` depends on `build_resolvers: ^1.4.0` which requires `analyzer: ^0.40.1` and `hive_generator: ^0.7.2+1` uses `analyzer: >=0.36.0 <0.40.0`, version solving failed.

I had to downgrade build_runner to a version whose analyzer is within the `>=0.36.0 <0.40.0` constraint

**Comment by WizSan** [comment]
Ok I see I haven't been with that problem yet. It might difficult for me to figure out how to find the solution yet.

**Comment by lifeofsems** [comment]
I got the same problem. Downgrading build_runner from 1.10.3 to 1.10.0 solves it.

**Comment by mistyn8** [comment]
^1.10.2 does it for me...
```dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.0
  flutter_native_splash: ^0.1.9
  json_serializable: ^3.3.0
  hive_generator: ^0.7.2+1
  build_runner: ^1.10.2
  injectable_generator: any

**Comment by TheMisir** [comment]
I think upgrading hive_generator should fix the issue:

```yaml
dev_dependencies:
  hive_generator: ^0.7.3
```
