### ISSUE TITLE
Be able to specify base path, not only subfolder

### ISSUE THREAD

**Issue by NightOwlCoder** [hivedb/hive#452]
This tool is great, but I would like to be able to specify where the boxes go, not just a subfolder under documents.

if able to send the whole path, we could use

`getApplicationSupportDirectory();`

what is perfect for my app on windows, as it points to the `Roaming` data folder.

**Comment by TheMisir** [comment]
You can initialize Hive with [`Hive.init(customPath)`](https://pub.dev/documentation/hive/latest/hive/HiveInterface/init.html) instead of `initFlutter`.
