### ISSUE TITLE
How to get specific box like 'where' in firebase?

### ISSUE THREAD

**Issue by shinewanna** [hivedb/hive#453]
**Question**
How can i get age>10 box list.

**Code sample**
```dart
 Hive.box(MESSAGE_BOX).listenable() // with ValueListenableBuilder for listen
```

**Version**
 - Platform:  Android
 - Flutter version: 1.20.3
 - Hive version: 1.2.0

**Comment by TheMisir** [comment]
You can use [`values`](https://pub.dev/documentation/hive/latest/hive/Box/values.html) property to filter result.

```dart
Hive.box(MESSAGE_BOX).values.where((item) => item.age > 10)
```
