### ISSUE TITLE
How can i update with property type?

### ISSUE THREAD

**Issue by shinewanna** [hivedb/hive#457]
**Question**
How to update a specific items 'if(item.price == 200) //i want to update the items to 100'

**Code sample**
I only know update with index like that
```dart
 Hive.box<MessageOb>(MESSAGE_BOX).putAt(index, messageOb);
```

**Version**
 - Platform:  Android
 - Flutter version: 1.20.3
 - Hive version: 1.2.0

**Comment by TheMisir** [comment]
SQL like queries are not supported by key-value databases. You can loop over items and update if needed.

```dart
var items = Hive.box<MessageOb>(MESSAGE_BOX).items;

for (int i = 0; i < items.length; i++) {
  if (items[i].price == 200) {
    Hive.box<MessageOb>(MESSAGE_BOX).putAt(i, newValue);
  }
}
```
