### ISSUE TITLE
Feature to got through every entry in a Box?

### ISSUE THREAD

**Issue by Tanzil7274** [hivedb/hive#458]
**Is your feature request related to a problem? Please describe.**
I need to get every entry from a small ( 7 items ) Box, and while a workaround for this can be implemented in my code relatively easily, a much more scalable, and more importantly _baked in solution_ , would be awesome.
 
**Describe the solution you'd like**
Considering Hive as many nice to have methods for searching through the data, it would be very beneficial ( and I'm surprised such methods haven't already been added ) that could iterate through every item in a Hive Box and perform a function on them.
I'm new, and the wording could probably have been better, but basically I was asking for something akin to List.forEach that is already available for Lists in Dart.

**Describe alternatives you've considered**
Since my very specific use case was concerned with a fixed 7 item long box that was indexed with incrementing keys, my solution was a simple workaround involving for loops that run 7 times, assign the value from the box at that particular key to a variable and return it.My main gripe and feature request is a method baked in that does that, particularly for when the length is not known

**Version**
Platform: iOS, Android
Flutter version: [1.20.3]
Hive version: [1.4.4]
Describe the solution you'd like

**Comment by TheMisir** [comment]
You can use `Hive.box(boxName).values` property to get item iterator. (This only works for regular boxes, not lazy boxes. Because lazy box items doesn't stored on memory).

**Comment by Tanzil7274** [comment]
Thank you! Both for the explanation and code sample, and for the sub 15 minute reply.This covers my use case fully.Thanks again!
