### ISSUE TITLE
Put it into own repository and organisation

### ISSUE THREAD

**Issue by prsolucoes** [hivedb/hive#46]
Hi,

Put it into own repository and organisation.

I made it with my project too, ezored (https://ezored.com).

Thanks.

**Comment by leisim** [comment]
What are the reasons you did that?

**Comment by prsolucoes** [comment]
It is more professional than a personal organisation.

You only need create an organisation and move it to there.

Is the same movement than other projects, like this:
https://github.com/emscripten-core/emscripten/issues/4880

It still yours, but will me more organised and can have own repositories for hive organisation.

It's my suggestion.

**Comment by leisim** [comment]
Thanks, I'll do that when I have time...

**Comment by Nipodemos** [comment]
thinking that straight, i think it would more organized one repositry for hive, other for hive_flutter and other for hive_generator.
Well, in the end it won't change anything, just keep things more organized, so i'ts up to you.

**Comment by leisim** [comment]
Yes I'm going to split them once I move Hive. The problem is that I rely heavily on GitHub Actions and they are still not available for everyone. I have to wait until the new organization also has access to GitHub Actions.

**Comment by leisim** [comment]
I contacted GitHub and the enabled GitHub actions. The repo is now moved and `hive_generator` and `hive_flutter` have been split into own repos.
