### ISSUE TITLE
KeyComparator usage

### ISSUE THREAD

**Issue by xavierbernasconi** [hivedb/hive#462]
**Question**
I would like to open the box using a different key to sort alphabetically the result.
I would like to use this.nome as key to sort the box
any hint or example on how to use keycomparator would be great!
thanks

**Code sample**

```dart
@HiveType(typeId: 0)
class Cliente extends HiveObject{
  @HiveField(0)
  String id;
  @HiveField(1)
  String nome;
.....

Cliente({this.id,this.nome,....});

}
///////////////////////
///This is how i open the box, I suppose this is where i should use KeyComparator
Hive.registerAdapter(ClienteAdapter());
await Hive.openBox<Cliente>(HiveBoxes.cliente);   <---- IN HERE ??? 
 
////OR SHOULD I USE IT WHEN I BUILD THE LISTITEM WIDGET???

body: ValueListenableBuilder(
        valueListenable: Hive.box<Cliente>(HiveBoxes.cliente).listenable(),   <---- IN HERE???
        builder: (context, Box<Cliente> box, _) {
          if (box.values.isEmpty)
```   

**Version**
 - Platform:  Android
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2

**Comment by leisim** [comment]
You have to provide your key comparator to the [`openBox()`](https://pub.dev/documentation/hive/latest/hive/HiveInterface/openBox.html) method.

**Comment by xavierbernasconi** [comment]
thanks for the reply?do you have a simple example at hand that i could use as reference?

**Comment by TheMisir** [comment]
> thanks for the reply?do you have a simple example at hand that i could use as reference?

Here's default comparator that hive uses:

```dart
/// Efficient default implementation to compare keys
int defaultKeyComparator(dynamic k1, dynamic k2) {
  if (k1 is int) {
    if (k2 is int) {
      if (k1 > k2) {
        return 1;
      } else if (k1 < k2) {
        return -1;
      } else {
        return 0;
      }
    } else {
      return -1;
    }
  } else if (k2 is String) {
    return (k1 as String).compareTo(k2);
  } else {
    return 1;
  }
}
```

**Comment by xavierbernasconi** [comment]
ah, great thanks

**Comment by schuster-rainer** [comment]
How can I access the values while opening the box in the comparator? I want to sort the box base on a predicate on the values
