### ISSUE TITLE
Only insert values the first time opening a box

### ISSUE THREAD

**Issue by xanderread** [hivedb/hive#463]
Hi there,
Is it possible to open a box the first time the app is launched with a list of defined values and never insert these values afterwards. 
I need to store a list of high scores on some 'topics' for my app. Because of this could I create a box using hive to store these scores and set them all equal to 0 the first time the app is ever opened. I DONT want to have the scores set back to 0 every time the user opens the app 

Thanks,
Alex

**Comment by leisim** [comment]
Just open two boxes, one with the scores and another one in which you write a `hasBeenOpened`: `true` entry to check in the future whether the app has been opened before.

**Comment by xanderread** [comment]
> Just open two boxes, one with the scores and another one in which you write a `hasBeenOpened`: `true` entry to check in the future whether the app has been opened before.

Good idea, cheers mate
