### ISSUE TITLE
Unhandled Exception: type 'List<dynamic>' is not a subtype of type 'DateTime' in type cast

### ISSUE THREAD

**Issue by amanv8060** [hivedb/hive#464]
**Steps to Reproduce**
Have been using this class since long , giving this error for the first time . 

Dont know what to do 

**Code sample**
```
import 'package:hive/hive.dart';

part 'userModel.g.dart';
@HiveType(typeId: 1)
class MyUser {
  @HiveField(0)
  String name;

  @HiveField(1)
  String email;

  @HiveField(2)
  String photoUrl;

  @HiveField(3)
  String uid;

  @HiveField(4)
  String accountType;

  @HiveField(5)
  int points;

  @HiveField(6)
  DateTime createdAt;

  @HiveField(7)
  String phone;

  @HiveField(8)
  int earned;

  MyUser(
      {this.accountType,
      this.createdAt,
      this.email,
      this.photoUrl,
      this.name,
      this.phone,
      this.points,
      this.earned,
      this.uid});
}
```

**Version**
 - Platform: iOS, Android
 - Flutter version:1.22.0
 - Hive version:1.5.0-pre

**Comment by amanv8060** [comment]
@TheMisir

**Comment by TheMisir** [comment]
Could you write stack trace?

**Comment by amanv8060** [comment]
Yup
but i would also like to mention , same works perfectly with 

  hive: ^1.4.4
  hive_flutter: ^0.3.1
  hive_generator: ^0.7.1

https://pastebin.com/EpnppYEx

**Comment by amanv8060** [comment]
@TheMisir , i have been into this for approximately 5-6 hrs now . trying to understand what is going wrong , but idk  .Do lemme Know if there is a workaround

**Comment by KrystofM** [comment]
@TheMisir @amanv8060 Has there been any update to this? Trying to save Map<Object, Object> and getting this exception. The stackTrace returns null.

**Comment by TheMisir** [comment]
The data is probably corrupted.

**Comment by ousvat** [comment]
> The data is probably corrupted.

Yep. After I deleted the app and reinstall it the error was gone.

**Comment by ABDO-AR** [comment]
When updating a class and still want to read the old class adapter you should provide the `defaultValue` parameter for the non-nullable properties in `@HiveField` for example like that:

    @HiveField(1, defaultValue: "")
    String localeCode;

**Comment by ABDO-AR** [comment]
> > The data is probably corrupted.
> 
> Yep. After I deleted the app and reinstall it the error was gone.

Yeah this is natural but like that, you delete all the old saved data in the application so it'll use the new adapter without issues, but when your application goes into production mode you'll have to use `defaultValue`  for the new properties to keep the old data as well as use the new data, do you understand me or explain more?

**Comment by TMolinas** [comment]
> 

Yes, can you explain more about field which type is List<List<String>> please, can we set the defauldValue: "" ?

**Comment by TMolinas** [comment]
Yes can you explain more please if the field has type List<List< String >> , can we set the defaultValue: "" ?
