### ISSUE TITLE
Hive clear() function does not work as expected. It clears new values added after the .clear() command.

### ISSUE THREAD

**Issue by rpriyanshu9** [hivedb/hive#466]
**Question**
After adding all the values inside _noteBox, when I try to print them, it shows me that box is empty.

**Code sample**
```
 List<Note> noteList = _noteBox.values.cast<Note>().toList();  //storing list of all values in box named _noteBox
_noteBox..clear();                        // clearing the box
noteList.insert(0, newNote);       // insert new element at starting of noteList
_noteBox.addAll(noteList);         // putting old+ 1 new value in the box
```

**Version**
 - Platform: Android
 - Flutter version: [1.20.4]
 - Hive version: [^1.4.1+1]

**Comment by TheMisir** [comment]
You have to `await box.clear()`. Otherwise clear will be called after all next lines were executed.
