### ISSUE TITLE
Data reappears after reinstall app

### ISSUE THREAD

**Issue by thize** [hivedb/hive#467]
If i reinstall app some data continue, but, if i clear all data (in android settings) , it works, but if i uninstall and install again, the data reappears. '-'

**Steps to Reproduce**
1° Save some box with User (with Registred Adapter) and delete the app.
2° Reinstall the app

**Version**
 - Platform: Release Version Android
 - Flutter version: 1.22.0
 - Hive version: hive 1.4.4+1

**Comment by TheMisir** [comment]
Might be caused by [android data backup](https://developer.android.com/guide/topics/data/backup). Which I think enabled by default on new flutter projects.

**Comment by thize** [comment]
Work! Thank you !

**Comment by tandacedric** [comment]
I have the same problem

**Comment by TheMisir** [comment]
@tandacedric , check this: https://github.com/hivedb/hive/issues/467#issuecomment-706969817

**Comment by cinder92** [comment]
i tried this 

android:allowBackup="false"

lets see if this works

**Comment by Sameera-Perera** [comment]
It worked for me. Also we can try remove cash and data dir using path provider.
