### ISSUE TITLE
Is there solution for pagination?

### ISSUE THREAD

**Issue by pro100svitlo** [hivedb/hive#468]
**Question**
I need to implement pagination: getting by 10 values from db.

So I wondered, maybe there is already some sample or example for such case? 🙏

**Comment by TheMisir** [comment]
You can use `Iterable<T> box.values` to paginate items.

```dart
var box = await Hive.openBox<Post>('posts');
var items = box.values.take(10 /* limit */).skip(20 /* offset */);
```

**Comment by pro100svitlo** [comment]
thank you!

**Comment by luis901101** [comment]
What about pagination from a LazyBox? If I have a long list of elements stored in a box and I want to lazy-load that elements with pagination?

**Comment by yakubmoris** [comment]
How can we paginate using **while** condition along with **take** and **skip** together on box.values.

**Comment by themisir** [comment]
> How can we paginate using **while** condition along with **take** and **skip** together on box.values.

You mean **where** condition?

If so like this:

```dart
box.values.where((e) => e.userId == currentUserId).skip(20).take(10);
```
