### ISSUE TITLE
Why does the documentation say it is not ready for production?

### ISSUE THREAD

**Issue by jonataslaw** [hivedb/hive#47]
Why isn't Hive ready for production?
I've been testing Hive for months, and I'm tempted to get Hive up and running on an app with 2 million users.
I needed a Lightweight dart library (my bridge with native code is already too overloaded, so it had to be 100% dart) that would allow simple storage of user settings (night mode, notification settings, and so on). your username and avatar downloaded from the API), and Hive has outperformed me on numerous issues over Seembast that they claim is in production. The main thing that makes Hive a killer of anything that stores data is being able to use it synchronously. Man, you made me delete 600 lines of code in futurebuilders, I almost didn't believe it when I found Hive.

Thanks for keeping up the good work in this library!
And I hope to know the risks I am taking, as I am about to use it even for storing self-destructive messages from a chat application (the key would be the username of the conversation, the value a map, which is self destructive , would be passed to a message list, displayed on screen, and deleted from Hive) this other app has 700,000 users.

**Comment by leisim** [comment]
It is ready as of today. Maybe I forgot to remove a notice from the documentation. Where does it say it isn't ready?

I'm really happy to hear that you like the library. If you have any suggestions, I'm always grateful.

It would be cool if you could send me a link when your app is ready. I'd love to see it ;)

**Comment by leisim** [comment]
Please reopen if you need more information.
