### ISSUE TITLE
Is there any way to access hive from native code?

### ISSUE THREAD

**Issue by onurcanari** [hivedb/hive#473]
**Question**
I am trying to create native widgets and i need to access my favorite list. can i access to hive from swift or kotlin? i know there is method channels but i don't think it will work on widget because while widgets are on the screen app may not be opened. But i didnt actually try that so i will comeback after trying..

**Version**
 - Platform: iOS, Android
 - Flutter version: [1.22,2]
 - Hive version: [1.4.4+1]

**Comment by onurcanari** [comment]
I wrote a method channel and called from there. Worked fine. Sorry for opening issue without trying.

**Comment by redanium** [comment]
> I wrote a method channel and called from there. Worked fine. Sorry for opening issue without trying.

Hi, can you show a piece of code ?
