### ISSUE TITLE
Purpose of save method in HiveObject

### ISSUE THREAD

**Issue by hashirshoaeb** [hivedb/hive#476]
**Question**
What is the purpose of save method in HiveObject?
on calling save() it saves the instance of object. If I’m directly mutating the object then why do I need to call save()?

**Code sample**
Hive Object code says,
```dart
  /// Get the key associated with this object. Returns `null` if object has
  /// not been added to a box yet.
  dynamic get key => _key;

  void _requireInitialized() {
    if (_box == null) {
      throw HiveError('This object is currently not in a box.');
    }
  }

  /// Persists this object.
  Future<void> save() {
    _requireInitialized();
    return _box.put(_key, this);
  }
```
For example
```dart
@HiveType()
class Person extends HiveObject {
  @HiveField(0)
  String name;
}

// main 

 var person = Person()
    ..name = 'Lisa';

  box.add(person);

// let’s say initial key is 0;
// if I do
person.name = “Luna”
// and don’t call save()
// and get from box
var p = box.get(0)
print(p.name) // it prints Luna

```
**Question**
If there is an object instance which is not added in the box and I try to call save()
since the the instance is not in the box so its key will be null
so how the box will put any key as null in map?

**Version**
 - Platform: iOS
 - Flutter version: 1.22.2
 - Hive version: ^1.4.4+1

**Repo**
[StarBook](https://github.com/hashirshoaeb/star_book/)

**Comment by TheMisir** [comment]
It prints Luna because that's how memory works (`box.get(x)` returns same instance of `Person` that you've added). When you call `save()` changes will be saved to persistent storage.

**Comment by hashirshoaeb** [comment]
Thanks
