### ISSUE TITLE
Using multiple paths in parallel

### ISSUE THREAD

**Issue by GauteHaugen** [hivedb/hive#488]
**Question**
Hi,
I'm developing an app using hive, where we use it to allow part of the app to support offline. I think I have come across and potential issue for us. When we store the boxes we want to store the boxes in different folders. This for us is possible with using ```Hive.init(String path);```. But when looking into the Hive.init function, I noticed it clears all current boxes and set a new path. My concern for our use case:

1. Does this close currently open boxes as they are no longer available through Hive variable?
2. If we run multiple functions in parallel, where the path could be different. Could this cause issues where we in function 1 init path 1 to open box 1, but before it can open box 1 function 2 has init path 2, making function 1 trying to open box 1 in path 2? An example would be two run multiple instances of the function below with different paths in parallel.

**Code sample**
```dart
  Future<void> syncItemsOnlineToOffline(String path, String boxName) async {
    List<Object> fetchedItems = await fetchItemsForOffline();

    Hive.init(path);
    var box = await Hive.openBox(boxName);

    await box.putAll(
        // fetchedItems converted to valid input
    );

    await box.close();
  }
```

I noticed that I would be able to import the HiveImpl class so that I in theory could create instances to use instead of the Hive variable. This way all the functions could run on different HiveImpl instance, but I was unsure if HiveImpl depended on other variables or methods that would not have its separate instance

**Version**
 - Platform: iOS, Android
 - Flutter version: [e.g. 1.22.3]
 - Hive version: [e.g. 1.4.4+1]

**Comment by TheMisir** [comment]
You can create custom Hive instance using `HiveImpl()` class constructor. Please use IntelliSense to import required dart files from the package.

**Comment by GauteHaugen** [comment]
Ok. If I have 2+ instances of ```HiveImpl``` that try to read or write from the same box at the same time in parallel. How will that work? I don't think I will end up in that situation as I'm at the start of my implementation using Hive, so I will not know before in a couple of weeks/months.

**Comment by TheMisir** [comment]
This might cause race conditional issues. If you open same box on 2 different hive instances the data will not be synchronized between boxes (because after you've opened the box the data will be stored on memory to speed up read/writes).
