### ISSUE TITLE
Unhandled Exception: HiveError: Cannot write, unknown type: _Type. Did you forget to register an adapter?

### ISSUE THREAD

**Issue by PurushottamHari** [hivedb/hive#491]
**Steps to Reproduce**
Please tell me exactly how to reproduce the problem you are running into.

This is popping up for the use case where I have implemented a map like this..

@HiveType(typeId: 15)
class UserBodyDetails{
  @HiveField(0)
   Map<dynamic,UserBodyGroupDetails> bodyGroupInfo;     <<-----------------
}

I have already generated an adapter for UserBodyGroupDetails as well....but still im encountering this issue

Also, why is it showing an error as "_Type"?....cause its difficult to narrow down the place where the issue is popping up

**Code sample**
```
Provide a few simple lines of code to show your problem.
```

**Version**
 - Platform: Windows
 - Flutter version: latest
 - Hive version: latest

**Comment by TheMisir** [comment]
Could you share exact error message here?

**Comment by PurushottamHari** [comment]
Thanks for such a quick response...I figured out the issue in this case and it was that I was assigning a class type as a value and not its object.
