### ISSUE TITLE
Can i use an Abstract class as a parent for Hive Objects?

### ISSUE THREAD

**Issue by PurushottamHari** [hivedb/hive#492]
**Question**
Please share a sample code in the docs so that I can get an idea of the implementation....I ran into multiple errors while executing it

**Comment by TheMisir** [comment]
Could you share your code alongside with caused errors?

**Comment by PurushottamHari** [comment]
/////////////////////////////////////////////////
"This is what I was trying to implement"

@HiveType(typeId: 3)
abstract class BodyGroup{
  @HiveField(0)    //Will be part of every other class below
  final Map<String,bool> parts;

  BodyGroup(this.parts);

  //Abstract function
  Map<String,double> tabMap();
  
  void incrementTabMap(Map<String,double> tabMap){
    tabMap.forEach((String part, double hits) {
      if(parts[part])
        tabMap[part] = tabMap[part] + 1;
    });
  }
}


@JsonSerializable()
@HiveType(typeId: 4)
class Shoulders extends BodyGroup{
  @HiveField(1)
  bool front;
  @HiveField(2)
  bool rear;

  Shoulders({bool front,bool rear}) : super({"front":front,"rear":rear}){
    this.front = front;
    this.rear = rear;
  }


  factory Shoulders.fromJson(Map<String,dynamic> data) => _$ShouldersFromJson(data);

  Map<String,dynamic> toJson() => _$ShouldersToJson(this);

  @override
  Map<String,double> tabMap() {
    return {
      "front":0,
      "rear":0
    };
  }

}
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

But the error was caused by Hive write implementation....when i ran the build_runner function stating that an instance of an abstract class cannot be made

So I was wondering how to approach this situation where I am using an abstract class

**Comment by TheMisir** [comment]
This is expected behavior since you are trying to construct abstract class instance. Change class signature (remove abstract keyword) or add `@HiveType` annotation to only implementations of this abstract class.

**Comment by PurushottamHari** [comment]
ok thanks I just ended up not using an abstract class in this case
