### ISSUE TITLE
The changes within Hive Objects of a box are not persisting when I kill the appllication

### ISSUE THREAD

**Issue by PurushottamHari** [hivedb/hive#495]
**Steps to Reproduce**
Please tell me exactly how to reproduce the problem you are running into.
I am updating the attributes within a hive object stored in a box.
The box does reflect the changes throughout the ongoing session but as soon as I kill the app, the Hive Object re-initialises every time for some reason

**Code sample**

```
////My appState////
      WidgetsFlutterBinding.ensureInitialized();
      final location = await Path.getApplicationDocumentsDirectory();
      Hive.init(location.path);
      registerCustomAdapters();  //Register all adapters here
      userProfileBox = await Hive.openBox("userProfileBox");
      if(!userProfileBox.containsKey("Main-User")) {
        debugPrint("[AppState]Making the user profile");
        userProfileBox.put("Main-User",new User());
      }
///////////////////////



///The User Class/////////

@HiveType(typeId: 16)
class User{
  @HiveField(0)
  Map<Move,UserMovesData> movesData;
  @HiveField(1)
  UserBodyDetails userBodyDetails;

  User(){
    if(movesData==null) {
      debugPrint("[User Profile] Initializing movesData");
      movesData = {};
    }
    if(userBodyDetails==null) {
      debugPrint("[User Profile] Initializing userBodyDetails");
      userBodyDetails = new UserBodyDetails();
    }
  }

  void updateDetails(var workout){
    workout.forEach((move,details){
      debugPrint("[Profile Update]Called for "+move.name);
      if(!movesData.containsKey(move)) {
        debugPrint("[Profile Update] Adding "+move.name);
        movesData.addAll({move: UserMovesData(move: move)});
      }
      movesData[move].updateDetails(details);
      userBodyDetails.updateDetails(move,details);
    });
  }
}
////////////////////////////////////////
```

So basically when I update the Hive Object.....it doesn't seem to persist.

Please help me out here

Thank you in advance

**Version**
 - Platform:Android,Windows
 - Flutter version: latest
 - Hive version: latest

**Comment by PurushottamHari** [comment]
I found a workaround and that was to make the initializations in another method and not in the constructor...
But still, since I have added checks in the constructor for "User" above as well.......I am not sure why the Hive-Object was initializing them again and again

**Comment by TheMisir** [comment]
Please check [this section on the FAQ page](https://docs.hivedb.dev/#/more/faq?id=what-happens-if-my-app-is-killed).

**Comment by PurushottamHari** [comment]
l
