### ISSUE TITLE
Null-safety

### ISSUE THREAD

**Issue by TheMisir** [hivedb/hive#496]
This issue used to track null-safety implementation.

- [x] Migrating code to null-safety
- [x] Dependencies does supports null-safety
- [x] Create pre-release

**Comment by KalilDev** [comment]
im migrating the package. soon ill open an wip PR

**Comment by TheMisir** [comment]
> im migrating the package. soon ill open an wip PR

Thank you so much. I've been so busy for last a few months.

**Comment by KalilDev** [comment]
pr is at https://github.com/hivedb/hive/pull/521

**Comment by TheMisir** [comment]
[1.6.0-nullsafety.1](https://pub.dev/packages/hive/versions/1.6.0-nullsafety.1) published.
