### ISSUE TITLE
Separating generated adapters into a separate folder.

### ISSUE THREAD

**Issue by ZenMittal** [hivedb/hive#503]
**Is your feature request related to a problem? Please describe.**
I have lots of custom models in my app (7 for just now in the starting), each requiring a generated TypeAdaptor file.
The thing is that it looks really messy when all generated files which I never actually touch to be kept there in the Models folder, along with the actual models that I do work with.

**Describe the solution you'd like**
It's more of a requested feature for hive_generator I guess.

I want hive_generator to send all the generated models into a separate folder: for example inside 'lib/models/generated'
to keep the models folder clean.

**Describe alternatives you've considered**
I tried using the new folder location in the part line of the models 
`part '/generated/user_profile.g.dart';`

But build command throws this error:
```
[WARNING] hive_generator:hive_generator on lib/models/user_profile.dart:
Missing "part 'user_profile.g.dart';".
```

If there is a less manual way of separating all generated adapters please let me know, otherwise I would love to see this feature implemented.

**Version**
 - Platform: Windows
 - Flutter version: 1.22
 - hive: ^1.4.4+1
 - hive_flutter: ^0.3.1
 - hive_generator: ^0.8.2

**Comment by mbaumgartenbr** [comment]
Hey! A quick tip: most IDEs can hide files for you, just specify the extension of the file, for example: `*.g.dart`

 I'm not sure if it works, but have you tried changing the content of "part" in your model's files? Something like `part 'generated/my_model.g.dart';` so that all files end up in generated/ (havent tried this)

**Comment by mbaumgartenbr** [comment]
Hey! Did you know that most IDEs can hide files? Just add `*.g.dart` to the list of hidden files 🙂

The code generation is the same for all packages that use it (as far as I know of)

**Comment by ZenMittal** [comment]
> Hey! Did you know that most IDEs can hide files? Just add `*.g.dart` to the list of hidden files 🙂
> 
> The code generation is the same for all packages that use it (as far as I know of)

Thanks buddy. I didn't know that. Using this feature in VScode now, and it's great. 
Still if the requested feature can be implemented then it still will be awesome for cleaner organization of code.

**Comment by TheMisir** [comment]
> > Hey! Did you know that most IDEs can hide files? Just add `*.g.dart` to the list of hidden files 🙂
> > The code generation is the same for all packages that use it (as far as I know of)
> 
> Thanks buddy. I didn't know that. Using this feature in VScode now, and it's great.
> Still if the requested feature can be implemented then it still will be awesome for cleaner organization of code.

Hive uses [source_gen](https://github.com/dart-lang/source_gen) for code generation. So I would suggest opening the issue on source_gen or build_runner repository.
