### ISSUE TITLE
Observed multiple entries in file, while storing item against a single key.

### ISSUE THREAD

**Issue by jasxir** [hivedb/hive#511]
**Question**
I'm storing user-preference in a `Box` using a fixed key, each time there's a change I use `.put` method. It's working fine on the surface, but when I opened the file as text, I was able to see multiple entries present. Is this the desired behavior?
I was thinking of it like a map i.e. each put will replace the previous value.

**Code sample**
```dart
_preferenceBox.put(_KEY_PREFERENCE, userPreference);
```

**Note**
I open the said Box on app start and use the same instance, if that matters in any way.
Also are there any performance implications for this?
`.close` is not being called anywhere.

**Version**
 - Platform: Android, iOS,
 - Flutter version: 1.22.4
 - Hive version: 1.4.4+1

Thanks in advance.

**Comment by dspells** [comment]
Have you tried calling .compact periodically?

**Comment by jasxir** [comment]
> Have you tried calling .compact periodically?

Thanks alot. Didn't know that box works this way. Getting to know about compaction helped in understanding what's going on.
