### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by amanv8060** [hivedb/hive#514]
**Question**

I Create 3 class as HiveType class A , class B , User

i generate type adapter for all the three

one of data members of User is `List <CLass A>` and other is instance of class B 

when i only have `List<CLass A >` as member everything works fine , but while also adding class B everything breaks apart

@TheMisir

**Comment by TheMisir** [comment]
Could you post:

- Your models
- What exactly happening when you add class B?

**Comment by amanv8060** [comment]
Posting the model , **clearing the appdata** then flutter clean then rebuilding worked 
<details><summary>class A</summary>
```@HiveType(typeId: 2)
class A {
  @HiveField(0)
  String a;

  @HiveField(1)
  String b;

  @HiveField(2)
  String c;

  @HiveField(3)
  String d;

  A({this.a, this.b, this.c, this.d});
}
```
</details>

class B is almost simalar with an extra bool

**Comment by TheMisir** [comment]
May I know what went wrong exactly? Adapter generation or runtime issue?

**Comment by amanv8060** [comment]
runtime issue

**Comment by amanv8060** [comment]
can not reproduce
