### ISSUE TITLE
How can i backup and restore the data i have in my hive boxes?

### ISSUE THREAD

**Issue by rpriyanshu9** [hivedb/hive#515]
**Question**
I have some data stored in the hive database or `Hive Box`. And I want to take a backup of some form, and later restore that data into `Hive` database.

**Comment by TheMisir** [comment]
You have two (or more) options:

1. Export all of your models into json (or something else) format. You can get all elements inside box using `value` property.
2. Export hive file. (Hive creates boxes inside app data directory)

--

I would recommend first option cause you'll not have to deal with binary stuff in future.

**Comment by rpriyanshu9** [comment]
thanks for the reply! How to later restore this `json` or some other file format? I mean how to convert these backed up files into `Hive Box(es)` ?

**Comment by TheMisir** [comment]
> thanks for the reply! How to later restore this `json` or some other file format? I mean how to convert these backed up files into `Hive Box(es)` ? @TheMisir

For json or some other file formats you just have to deserialize json to objects then add them into hive.

```dart
var jsonString = '...';
var jsonObjects = json.decode(jsonString) as List<dynamic>;
var objects = jsonObjects.map(MyModel.fromJson).toList();

Hive.box('boxName').addAll(objects);
```

But importing hive database files is a bit tricky. If you don't care about exists data you can copy file directly into app data directory with same name as box name. But keep in mind that all of exists data will be overwritten. Or you can open imported hive file as a new box then read all values and copy into exists box. I would suggest going with json serialization method cause it's a bit easy to understand and execute.

**Comment by rpriyanshu9** [comment]
thanks @TheMisir

**Comment by shinewanna** [comment]
Hello, i hope ur pass over this issue.
Humm, not a issue but kind of.
Which trick u use to export and import.
and which one is more easy and efficient.
If u have example code to export and import for hive, it'll be helpful for me.
