### ISSUE TITLE
How do I get the key for an entry in hive's box?

### ISSUE THREAD

**Issue by rehman-00001** [hivedb/hive#517]
**Question**
I use auto-increment keys always. I've stored the list of some records in the box: "records" _(for instance)_
Here, the intention is to display the list of records in one screen and when user taps on any of the record, navigate to another screen from where that record can be edited. To save that "record" in the editor screen, I am doing `recordsBox.put(index, <updatedRecord>)`;

`index` is the value I forward from the record list screen to editor screen. Things are working fine for now.
I came across hive's [documentation](https://docs.hivedb.dev/#/basics/auto_increment) where this line is mentioned:

```
Even if you only use auto increment keys, you should not rely on keys and indices being the same.
```

Right now, I'm only relying on index of the entry in hive box for update & delete _(which might change after `box.compact()`)_.
 But I feel the correct way is to use the auto-incrementing keys assigned by hive while adding each record. 

If that's the case, after adding a record,
```dart
  recordsBox.add(newRecord);
``` 
 How do I get to know what is the value of key assigned for my `newRecord`?

**Version**
 - Flutter version: [e.g. 1.5.4]
 - Hive version: [e.g. 0.5.0]

**Comment by mbaumgartenbr** [comment]
`box.add(value)` returns an auto incremented integer.

If your model extends HiveObject:

```dart
Future<void> upsert(MyModel myModel) async {
  if (!box.containsKey(myModel.id)) {
    final id = await box.add(myModel);
    myModel.id = id;
  }
  myModel.save();
}
```

**Comment by mprostock** [comment]
The .add() method returns the int key, so if you store it, you can use it.

```dart
var key = recordsBox.add(newRecord);
```

But I can't find how to get the keys of things already stored in the database?! 
Help on that would be appreciated! 

Right now I am mixing keys (for newly added items) and list-like indices (for pre-existing entries) everywhere, which seems very un-clean code and error-prone.

**Comment by rehman-00001** [comment]
Ok, the solution here is to have all our models extend `HiveObject`. 
That way, each record will have a unique identifier key that can be accessed as:  `record.key `.

**Comment by eaedev** [comment]
Hi!

¿Could you please provide an example of this? ¿Is it already implemented?

**Comment by 6heads** [comment]
> Hi!
> 
> ¿Could you please provide an example of this? ¿Is it already implemented?

```
class YourModel : HiveObject {
}
```

Your model then has the following property: `yourModel.key`.
You can use it like this: `yourBox.put(yourModel.key, yourModel);`

**Comment by vishwatejaaverager** [comment]
what if we open a box with out model !

**Comment by tony123S** [comment]
How to get specific item based on key?
https://github.com/hivedb/hive/issues/1185
