### ISSUE TITLE
About HiveType and its typeId

### ISSUE THREAD

**Issue by pratamatama** [hivedb/hive#518]
I felt ambiguous with the explanation provided on the docs, should the `typeId` of `@HiveType` be unique per model? Or I could do it like this, for instance:

```dart
@HiveType(typeId: 0)
class ClassA extends HiveObject {}

@HiveType(typeId: 0)
class ClassB extends HiveObject {}

@HiveType(typeId: 0)
class ClassC extends HiveObject {}
```

Or it should be like this?

```dart
@HiveType(typeId: 0)
class ClassA extends HiveObject {}

@HiveType(typeId: 1)
class ClassB extends HiveObject {}

@HiveType(typeId: 2)
class ClassC extends HiveObject {}
```

**Version**
 - Platform: iOS, Android
 - Flutter version: 1.22.5
 - Hive version: ^1.4.4+1

**Comment by mbaumgartenbr** [comment]
It **must** be unique! 😁

**Comment by pratamatama** [comment]
Hi @mbaumgartenbr ! Thanks for answering, so the properway is like the 2nd snippet I defined above?

**Comment by mbaumgartenbr** [comment]
Yep 🙂

**Comment by pratamatama** [comment]
I see.. Thanks for fast response, have a nice day! I'm closing it. 🐱‍🏍

**Comment by Minsamin** [comment]
Link -> [https://docs.hivedb.dev/#/custom-objects/type_adapters?id=register-adapter](url)
"Every type has a unique typeId which is used to find the correct adapter when a value is brought back from disk. All typeIds between 0 and 223 are allowed."

1. This means I can have a maximum of 223 dart model classes ? 
2. I have to remember what's the last Type ID I used in my app, and increment accordingly ?
3. If my app need more than 223 Model Classes then what should I do ?

**Comment by denghejun** [comment]
That's a shit design ...to be honest, why did you use a number, why not string? class name?

**Comment by adrianvintu** [comment]
> That's a shit design ...to be honest, why did you use a number, why not string? class name?

I assume it's because it generates code like this:

```
  @override
  void write(BinaryWriter writer, NewsModel obj) {
    writer
      ..writeByte(5)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.title)
      ..writeByte(2)
      ..write(obj.content)
      ..writeByte(3)
      ..write(obj.categories)
      ..writeByte(4)
      ..write(obj.date);
  }
```

This allows the plugin to regenerate the same order of writes, no matter the order in the source code.
