### ISSUE TITLE
HiveList problem/ how does it work?

### ISSUE THREAD

**Issue by Jolana-vsb** [hivedb/hive#519]
I have a question about how HiveList works and also I would like to ask if hive is a good solution for my problem. Now to the problem - I need to have a database with aircrafts for remote control. So I have box "Model" which keeps info about model and I will need to store to each model its "Sensors" (2nd box) and "Flight history" (3rd box, one model can have multiple logs and sensors). Also each Sensor box keeps info about SensorValue (4th box).  I decided to use a HiveLists for this. I provide an example for box "Model":

```
@HiveType(typeId: 3)
class Model extends HiveObject {
  @HiveField(0)
  final int id;

  @HiveField(1)
  String name;

  @HiveField(2)
  ModelType type;

  @HiveField(3)
  HiveList<Sensor> sensors;

 @HiveField(4)
  HiveList<FlightHistory> logs;
}
```

Is Hive database and HiveLists a good solution or should I rather move to another db? I wanna also ask what happens if I will have the same ID like values in other sensor? Will it store some unique ID itself? When I try to store Sensors in my HiveList sensors in box Model, it will throw an error:
```
E/flutter (12719): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: HiveError: HiveObjects needs to be in the box "sensors".
```
And code when I try to fill my HiveList sensors:
```
    var model = Model(id: 10, name: "modelWithList", type: ModelType.XCopter);
    model.sensors = HiveList<Sensor>(_sensorsBox); 
    var sensor1 = Sensor(manufacturerID: 1, deviceID: 1, name: "sensor1");
    var sensor2 = Sensor(manufacturerID: 2, deviceID: 2, name: "sensor2");
    model.sensors.addAll([sensor1, sensor2]);   //it fails here
    print(model.sensors);
```

**Comment by reyesGeorge** [comment]
Hello,
I was having the same problem I was able to solve it by using HiveLists.

This is what my model looks like:
```
class VeggieItems extends HiveObject {
  VeggieItems(this.name, this.image, this.retailPrice, this.sItems, {this.isFavorite = false});
  @HiveField(0)
  String name;

  @HiveField(1)
  Uint8List image;
  
  @HiveField(2)
  double retailPrice;
  
  @HiveField(3)
  List<SavingsItems> sItems; // make the real savings list

  @HiveField(4)
  bool isFavorite;
}

@HiveType(typeId: 5)
class SavingsItems extends HiveObject{
  SavingsItems(this.savingsInput, this.date);
  @HiveField(0)
  double savingsInput;
  
  @HiveField(1)
  DateTime date;
}
```

And this is how I add to it:
```
final veggiesBox = Hive.box('veggies');
DateTime today = DateTime.now();
var items = SavingsItems(harvestYield, today);

var vals = veggiesBox.getAt(widget.vIndex);
vals.sItems.add(items);
vals.save();

```

I tried using HiveLists but was not able to get the above working using the documentation /:
HiveLists sounds like it would have been efficient but being on a time crunch this is better than nothing, hope it helps!

**Comment by Jolana-vsb** [comment]
> Hello,
> 
> I was having the same problem I was able to solve it by using regular Lists instead of HiveLists
> 
> Make sure to register the TypeAdapters:
> 
> ```
> Hive.registerAdapter(myMODELAdapter());
> ```
> 
> This is what my model looks like:
> 
> ```
> class VeggieItems extends HiveObject {
>   VeggieItems(this.name, this.image, this.retailPrice, this.sItems, {this.isFavorite = false});
>   @HiveField(0)
>   String name;
> 
>   @HiveField(1)
>   Uint8List image;
>   
>   @HiveField(2)
>   double retailPrice;
>   
>   @HiveField(3)
>   List<SavingsItems> sItems; // make the real savings list
> 
>   @HiveField(4)
>   bool isFavorite;
> }
> 
> @HiveType(typeId: 5)
> class SavingsItems extends HiveObject{
>   SavingsItems(this.savingsInput, this.date);
>   @HiveField(0)
>   double savingsInput;
>   
>   @HiveField(1)
>   DateTime date;
> }
> ```
> 
> And this is how I add to it:
> 
> ```
> final veggiesBox = Hive.box('veggies');
> DateTime today = DateTime.now();
> var items = SavingsItems(harvestYield, today);
> 
> var vals = veggiesBox.getAt(widget.vIndex);    // fetch your data record, I am accessing from a Listview.builder so I am using index but you can use a key value by using get(myKEY, values)
> vals.sItems.add(items);
> vals.save();
> ```
> 
> I tried using HiveLists but was not able to get the above working using the documentation /:
> HiveLists sounds like it would have been efficient but being on a time crunch this is better than nothing, hope it helps!

Hi,
thanks for reply, I solved it like you did in your example and it works :)
