### ISSUE TITLE
Write binary format spec

### ISSUE THREAD

**Issue by joeblew99** [hivedb/hive#53]
Is there more info on the binary format ?

I am working in golang and protobufs. So i am thinking about writing a code generator to work with hive to help code gen from the Server IDL

**Comment by leisim** [comment]
I haven't started to document the binary format.


It looks like this:

Each key-value Kombination is called frame. Each frames has four components:


### 1. Frame header:


```

uint32 frame lenght

uint8 key type

```


### 2. key


for string key:

```

unit8 key lenght

uint8 char1

...

uint8 charN

```


for int key:

```

uint32 key

```

 

### 3. value


Ints and doubles are always stored as 8-byte double


Lists, Maps and Strings have a uint32 which contains the length.


```

uint8 listLength

float64 value1

...

float64 valueN

```


```

uint8 stringLength (in bytes)

uint8 codeUnit1

...

uint8 codeUnitN

```


Non primitive lists and primitive lists which contain at least one `null` value store the type of each element:


```

uint32 listLength

uint8 type1

any value1

...

uint8 typeN

uint8 valueN

```


### 4. Checksum


Each frame ends with a 4-byte checksum (CRC32) of all other bytes (including the 4 length bytes)



Sorry, I know this is not much information but it's all I got atm.


You can find most of the implementation in the [Frame](https://github.com/hivedb/hive/blob/master/hive/lib/src/binary/frame.dart) class, the [BinaryReaderImpl](https://github.com/hivedb/hive/blob/master/hive/lib/src/binary/binary_reader_impl.dart) and the [BinaryWriterImpl](https://github.com/hivedb/hive/blob/master/hive/lib/src/binary/binary_writer_impl.dart).

Don't hesitate to ask if you have problems.
