### ISSUE TITLE
HiveList error on app execution

### ISSUE THREAD

**Issue by Censored1375** [hivedb/hive#540]
**Steps to Reproduce**
I'm using `HiveList` as below and getting a type error, this error is shown on execution of the app
```
E/flutter (19210): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: type 'int' is not a subtype of type 'HiveList<HiveObject>' in type cast
```
The `HiveList<Object>` just changes to `List<dynamic>` in the error message if i try to use `List<Task>` instead of `HiveList<Task>` in the code below

**Code sample**
```
@HiveType(typeId: 1)
class Project extends HiveObject{
  @HiveField(0)
  String projectName;
  @HiveField(1)
  String note;
  @HiveField(2)
  String creationDate;
  @HiveField(3)
  String deadline;
  @HiveField(4)
  String progress;
  @HiveField(5)
  HiveList<Task> tasks;

  Project(
      this.projectName,
      this.note,
      this.creationDate,
      this.deadline,
      this.progress,
  );
}
```

**Version**
 - Platform: Android - Windows
 - Flutter version: 1.24.0-10.2.pre • channel beta
 - Hive version: 1.4.4+1

**Comment by rnvitter** [comment]
@Censored1375 did you find a fix for this?

**Comment by TheMisir** [comment]
You've probably changed data model. Removing exists data would fix the issue in case of that. Please note that changing type of @HiveField(index) will damage the deserialization process. Because it's written as integer previous time but now the app wants the data as an HiveList but it was int last time it was written.

**Comment by rnvitter** [comment]
@TheMisir that was the issue, thanks!

**Comment by Censored1375** [comment]
I haven't tested this out yet but thanks anyway, i hope it works :))
