### ISSUE TITLE
The method 'toList' isn't defined for the type 'Box'

### ISSUE THREAD

**Issue by zachisit** [hivedb/hive#549]
**Question**
When trying to retrieve a Box's values to a `List`, using the `.toList()` method, I receive the following error in my IDE: 

> The method 'toList' isn't defined for the type 'Box'.

What am I missing here?

**Code sample**
```dart
import 'package:hive/hive.dart';
import 'package:hive_flutter/hive_flutter.dart';

batteryBox = await Hive.openBox<BatteryInformation>(batteryBoxName);
batteryBox.toList(); // The method 'toList' isn't defined for the type 'Box'.
```

**Comment by mbaumgartenbr** [comment]
Try `box.values.toList()`
