### ISSUE TITLE
Encrypted box - Why store the encryption key?

### ISSUE THREAD

**Issue by BenPoell** [hivedb/hive#556]
Hi!
In your example in the doc you store the encryption key in a FlutterSecureStorage but actually you don't need that key anymore later on.
https://docs.hivedb.dev/#/advanced/encrypted_box?id=encrypted-box

As I understood hive manages the encryption and decryption by it's own, meaning I don't need the key anymore to put encrypted values and get decrypted values.
Is there some specific reason why you store it in e.g. FlutterSecureStorage or somewhere else?

The only use case I can imagine is, when the app crashes that you don't loose the encrypted values and you can open the hive-box with the local stored key.

**Code sample from the documentation**
```dart
import 'dart:convert';
import 'package:hive/hive.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';

void main() async {
  final FlutterSecureStorage secureStorage = const FlutterSecureStorage();
  var containsEncryptionKey = await secureStorage.containsKey(key: 'key');
  if (!containsEncryptionKey) {
    var key = Hive.generateSecureKey();
    await secureStorage.write(key: 'key', value: base64UrlEncode(key));
  }
  
  var encryptionKey = base64Url.decode(await secureStorage.read(key: 'key'));
  print('Encryption key: $encryptionKey');

  var encryptedBox = await Hive.openBox('vaultBox', encryptionCipher: HiveAesCipher(encryptionKey));
  encryptedBox.put('secret', 'Hive is cool');
  print(encryptedBox.get('secret'));
}
```

**Comment by leisim** [comment]
Hive can help you generating a secure and random key when you create a new box but when you open an existing box, you need to provide the key you used to create it. Hive cannot help you with that. Otherwise a key would somehow need to be built in and that would be pointless.

**Comment by Techno-Disaster** [comment]
@leisim @TheMisir If we don't create a encrypted box, just a simple .openBox(), is there anyway I can edit the box.hive file in my documents directory by opening it in a text editor later?

**Comment by leisim** [comment]
@Techno-Disaster No, Hive uses a custom binary format so you can't edit Hive files manually.

**Comment by Techno-Disaster** [comment]
> Hive can help you generating a secure and random key when you create a new box but when you open an existing box, you need to provide the key you used to create it. Hive cannot help you with that. Otherwise a key would somehow need to be built in and that would be pointless.

Does that mean, if I don't provide a key I can't retrieve the value? The docs say `Sometimes it is necessary to store data securely on the disk. Hive supports AES-256 encryption out of the box (literally).` so I assume encryption, decryption happen automatically.
