### ISSUE TITLE
Shoud a box be closed, or doesn't it matter?

### ISSUE THREAD

**Issue by wujek-srujek** [hivedb/hive#563]
**Question**
I have just starting to read the docs, and came across this piece:
```
Before your application exits, you should call Hive.close() to close all open boxes. Don't worry if the app is killed before you close Hive, it doesn't matter.
```
It's pretty confusing: so should the boxes be closed, or doesn't it matter? Should I strive to always cleanly close the box, or can I just forget about it?

**Comment by TheMisir** [comment]
I have an app running on production that doesn't closes open boxes on exit because it's very tricky to know when the app is closed or killed (well, because it's killed it couldn't execute your code anyways).

**Comment by wujek-srujek** [comment]
Right, this would mean each right is 'complete', as in: it writes data to disk completely, and closing doesn't add any kind of footer or whatever, that is required for the box to be correct?

My question was also about the documentation, that it is pretty confusingly worded, because it starts the sentence with 'you should close' but then it says you don't have to care about closing.

**Comment by leisim** [comment]
@wujek-srujek No need to close boxes. This passage was changed multiple times and resulted in something stupid haha
