### ISSUE TITLE
Using an enum in a Model

### ISSUE THREAD

**Issue by zachisit** [hivedb/hive#564]
I am trying to save a Model that has an enum property assigned to a parameter/property of the Model. If I remove this enum logic the saving works fine, but when I try to add the enum logic it fails. I tried adding additional helpers to the Model as listed in #526 but that doesn't seem to resolve my issue.

The Model with its enum logic is here:

```dart
part 'ticket.g.dart';

enum Status {
  open,
  closed,
}

@HiveType(typeId: 10)
class Ticket extends HiveObject {
  @HiveField(0)
  final Geofence geofence;
  @HiveField(1)
  final BeaconsInRange beacons;
  @HiveField(2)
  final bool canEdit;
  @HiveField(3)
  final Status status;
  @HiveField(4)
  final String timeStarted;
  @HiveField(5)
  final String ticketId;
  @HiveField(6)
  final String deviceId;
  @HiveField(7)
  final String timeEnded;

  Ticket({
    @required this.geofence,
    @required this.beacons,
    @required this.status,
    @required this.ticketId,
    @required this.timeStarted,
    @required this.deviceId,
    this.canEdit,
    this.timeEnded,
  })  : assert(geofence != null),
        assert(beacons != null),
        assert(status != null),
        assert(ticketId != null),
        assert(deviceId != null),
        assert(timeStarted != null);

  @override
  String toString() => '${geofence.name}';

  String enumToString(Status value) {
    return value.toString().split('.').last;
  }

  Status stringToEnum(String value) {
    return <String, Status>{
      'open': Status.open,
      'closed': Status.closed,
    }[value];
  }
}
```

The error when saving is:

**Unhandled Exception: HiveError: Cannot write, unknown type: Status. Did you forget to register an adapter?**

What am I missing here, in order to save my enum?

**Version**
 - Platform: Android
 - Flutter version: 1.22.6
 - Hive version: ^1.4.4+1

**Comment by MaldonadoAndres** [comment]
If I remember correctly you need to also generated an adapter just as with another object

**Comment by mbaumgartenbr** [comment]
Hey @zachisit! To store it that way, you would have to create a HiveType for the  `Status` enum. Following the line of thought we had in the other issue, I'd say changing the type of the status to `String` and using the helper methods to convert to and from the `Status` enum would require less effort.

```dart
// Instead of
@HiveField(3)
final Status status;

// it would look like this
@HiveField(3)
final String status;

// Make `enumToString` an extension getter of Status:

extension StatusX on Status {
  String get valueAsString => toString().split('.').last;

  // Or as a function
  String asString() => toString().split('.').last;
}  

// The instantiation of the class would look like this:
final ticket = Ticket(status: Status.open.valueAsString);
/*
  Or
  final ticket = Ticket(status: Status.closed.asString());
*/
```

Then to use the enum:

```dart
final ticket = Ticket(status: Status.closed.asString());
print(ticket.stringToEnum(ticket.status);
```

To remove a bit of the boilerplate, you could make `status` private and have a `status` getter that already does the `toEnum`  conversion:

```dart
class Ticket {
  Ticket({Status status}) : _status = status;

  String _status;

  // If you want to set it from outside of the constructor
  set status(Status value) => _status = value.valueAsString;

  // You can extract the logic to another method if the enum has more fields
  Status get status => _status == 'open' ? Status.open : Status.closed;
}
```
If build runner complains about the getter and setter, do the generation without them and add them later.

I haven't tested it with Hive but I'm pretty sure it works.

_Sorry for the late reply_
