### ISSUE TITLE
box.delete(dynamic key) doesn't work

### ISSUE THREAD

**Issue by arnacologie** [hivedb/hive#57]
**Steps to Reproduce**
Put a key value pair in a box, delete the key, => the key is really deleted
Restart the app => the key is back 

**Code sample**
```
//this doesn't work
await box.delete(collectionName);
//I had to use deleteAll as a workaround
await box.deleteAll([collectionName]);
```

**Version**
 - Platform: Android
 - Flutter version:  1.9.1
 - Hive version: 1.0.0

**Comment by leisim** [comment]
Thanks for reoorting this. It is very suprising that this kind of problem is undetected by the unit tests.
I'll take a look.

**Comment by arnacologie** [comment]
You're welcome ! Hopefully you'll find the issue without too much hassle :)

**Comment by leisim** [comment]
I could not reproduce this unfortunately. But there is a new version (`1.1.0-beta`). please reopen this bug if the new version still has this problem.
