### ISSUE TITLE
Binary Writer

### ISSUE THREAD

**Issue by chandrabezzo** [hivedb/hive#575]
**Steps to Reproduce**
I have two HiveObject with different HiveType. Adapter can successfully generated. But when I insert to local storage, I got error about BinaryWriter. I call method addAll() from Hive. I think that error from writer.

E/flutter (18743): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: type 'DataMovieModel' is not a subtype of type 'FavoriteModel' of 'obj'

**Code sample**
@HiveType(typeId: 0, adapterName: "FavoriteAdapter")
class FavoriteModel extends HiveObject {
  @HiveField(0)
  final int id;

  @HiveField(1)
  final String image;

  @HiveField(2)
  final String title;

  @HiveField(3)
  final String releaseDate;

  @HiveField(4)
  final double userScore;

  @HiveField(5)
  final double popularity;

  @HiveField(6)
  final String desc;

  FavoriteModel({
    this.id,
    this.image,
    this.title,
    this.releaseDate,
    this.userScore,
    this.popularity,
    this.desc
  });
}

@HiveType(typeId: 1, adapterName: "MovieAdapter")
class DataMovieModel extends HiveObject {

  @HiveField(0)
  bool adult;

  @HiveField(1)
  String backdropPath;

  @HiveField(3)
  List<int> genreIds;

  @HiveField(4)
  int id;

  @HiveField(5)
  String originalLanguage;

  @HiveField(6)
  String originalTitle;

  @HiveField(7)
  String overview;

  @HiveField(8)
  double popularity;

  @HiveField(9)
  String posterPath;

  @HiveField(10)
  DateTime releaseDate;

  @HiveField(11)
  String title;
  
  @HiveField(12)
  bool video;

  @HiveField(13)
  double voteAverage;

  @HiveField(14)
  int voteCount;

  DataMovieModel({
    this.adult,
    this.backdropPath,
    this.genreIds,
    this.id,
    this.originalLanguage,
    this.originalTitle,
    this.overview,
    this.popularity,
    this.posterPath,
    this.releaseDate,
    this.title,
    this.video,
    this.voteAverage,
    this.voteCount
  });
}

**Version**
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.6 19G2021 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.53.2)
[✓] Connected device (1 available)
 
hive: ^1.4.4+1
hive_flutter: ^0.3.1

build_runner: ^1.11.1
hive_generator: ^0.8.2

**Comment by chandrabezzo** [comment]
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'favorite_model.dart';

// **************************************************************************
// TypeAdapterGenerator
// **************************************************************************

class FavoriteAdapter extends TypeAdapter<FavoriteModel> {
  @override
  final int typeId = 0;

  @override
  FavoriteModel read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return FavoriteModel(
      id: fields[0] as int,
      image: fields[1] as String,
      title: fields[2] as String,
      releaseDate: fields[3] as String,
      userScore: fields[4] as double,
      popularity: fields[5] as double,
      desc: fields[6] as String,
    );
  }

  @override
  void write(BinaryWriter writer, FavoriteModel obj) {
    writer
      ..writeByte(7)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.image)
      ..writeByte(2)
      ..write(obj.title)
      ..writeByte(3)
      ..write(obj.releaseDate)
      ..writeByte(4)
      ..write(obj.userScore)
      ..writeByte(5)
      ..write(obj.popularity)
      ..writeByte(6)
      ..write(obj.desc);
  }

  @override
  int get hashCode => typeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FavoriteAdapter &&
          runtimeType == other.runtimeType &&
          typeId == other.typeId;
}

**Comment by chandrabezzo** [comment]
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'data_movie_model.dart';

// **************************************************************************
// TypeAdapterGenerator
// **************************************************************************

class MovieAdapter extends TypeAdapter<DataMovieModel> {
  @override
  final int typeId = 1;

  @override
  DataMovieModel read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return DataMovieModel(
      adult: fields[0] as bool,
      backdropPath: fields[1] as String,
      genreIds: (fields[3] as List)?.cast<int>(),
      id: fields[4] as int,
      originalLanguage: fields[5] as String,
      originalTitle: fields[6] as String,
      overview: fields[7] as String,
      popularity: fields[8] as double,
      posterPath: fields[9] as String,
      releaseDate: fields[10] as DateTime,
      title: fields[11] as String,
      video: fields[12] as bool,
      voteAverage: fields[13] as double,
      voteCount: fields[14] as int,
    );
  }

  @override
  void write(BinaryWriter writer, DataMovieModel obj) {
    writer
      ..writeByte(14)
      ..writeByte(0)
      ..write(obj.adult)
      ..writeByte(1)
      ..write(obj.backdropPath)
      ..writeByte(3)
      ..write(obj.genreIds)
      ..writeByte(4)
      ..write(obj.id)
      ..writeByte(5)
      ..write(obj.originalLanguage)
      ..writeByte(6)
      ..write(obj.originalTitle)
      ..writeByte(7)
      ..write(obj.overview)
      ..writeByte(8)
      ..write(obj.popularity)
      ..writeByte(9)
      ..write(obj.posterPath)
      ..writeByte(10)
      ..write(obj.releaseDate)
      ..writeByte(11)
      ..write(obj.title)
      ..writeByte(12)
      ..write(obj.video)
      ..writeByte(13)
      ..write(obj.voteAverage)
      ..writeByte(14)
      ..write(obj.voteCount);
  }

  @override
  int get hashCode => typeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MovieAdapter &&
          runtimeType == other.runtimeType &&
          typeId == other.typeId;
}

**Comment by TheMisir** [comment]
Your data is probably damaged. I would suggest removing & recreating database file. (You can either use removeFromDisk method or clear storage on mobile device).

**Comment by chandrabezzo** [comment]
Hello @TheMisir thank you for your solution, I still got that error. I was clear cache, storage, clearFromDisk, uninstall but still error. I think, your solution about clear storage very worrying if it happens when the apps have published.

**Comment by kirill-plotnikov** [comment]
> Hello @TheMisir thank you for your solution, I still got that error. I was clear cache, storage, clearFromDisk, uninstall but still error. I think, your solution about clear storage very worrying if it happens when the apps have published.

Same problem

**Comment by chandrabezzo** [comment]
E/flutter ( 6483): #0      FavoriteAdapter.write (package:flutter_arch/features/favorite/data/models/favorite_model.g.dart)
package:flutter_arch/…/models/favorite_model.g.dart:1
E/flutter ( 6483): #1      BinaryWriterImpl.write
package:hive/…/binary/binary_writer_impl.dart:316
E/flutter ( 6483): #2      BinaryWriterImpl.writeFrame
package:hive/…/binary/binary_writer_impl.dart:254
E/flutter ( 6483): #3      StorageBackendVm.writeFrames.<anonymous closure>
package:hive/…/vm/storage_backend_vm.dart:123
E/flutter ( 6483): #4      ReadWriteSync.syncWrite.<anonymous closure>
package:hive/…/vm/read_write_sync.dart:26
E/flutter ( 6483): #5      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter ( 6483): #6      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 6483): #7      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter ( 6483): #8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter ( 6483): #9      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter ( 6483): #10     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:393:9)
E/flutter ( 6483): #11     _rootRun (dart:async/zone.dart:1190:13)
E/flutter ( 6483): #12     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 6483): #13     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter ( 6483): #14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter ( 6483): #15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 6483): #16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

**Comment by kirill-plotnikov** [comment]
> > Hello @TheMisir thank you for your solution, I still got that error. I was clear cache, storage, clearFromDisk, uninstall but still error. I think, your solution about clear storage very worrying if it happens when the apps have published.
> 
> Same problem

Please show, how you register adapters

**Comment by chandrabezzo** [comment]
> ```
> Notes
> I'm not understand why detected as FavoriteModel.
> ```
> 
> Please show, how you register adapters
> 
> Try register it with generic argument, like this:
> 
> `Hive.registerAdapter<Coordinate>(CoordinateAdapter());`

Yeah, that's resolve my problem thank you very much. You must define model that extends from HiveObject. Please refers to /// Register a [TypeAdapter] to announce it to Hive.
void registerAdapter<T>(TypeAdapter<T> adapter);
You need to define "T" when register the adapter. Sorry for my mistakes, I register the adapter without define "T" just like

`Hive.registerAdapter(FavoriteAdapter)`
