### ISSUE TITLE
Box Name Requirements

### ISSUE THREAD

**Issue by mneber** [hivedb/hive#576]
**Question**
This should hopefully be a quick and easy one. What are the limitations on the name of a box i.e. the string passed to Hive.openBox(); specifically the length.

I understand it is case insensitive. What is the limit of how many chars?

Thanks!

**Comment by TheMisir** [comment]
Box names is used for naming database files (in mobile OS-es). So any limits available on operation systems for file naming also applies to box naming in hive.

**Comment by marcelgarus** [comment]
Just to add to that: Boxes are stored as files and operating systems certainly have limits for file names:

**Windows**: 255 bytes
**MacOS**: 1024 bytes
**Linux**: 255 bytes
**iOS**: 255 bytes
**Android**: is a Linux-variant, so the hard limit is 255 bytes. [Apparently](https://stackoverflow.com/questions/13204807/max-file-name-length-in-android#:~:text=stick%20to%20a%20limit%20of%20127.&text=In%20the%20specific%20case%20of,in%20Android%20Studio%201.2%20beta.), 127 bytes is a guideline.

Those bytes include the `.hive` extension and `.hivec` extension while compacting.
So, I'd treat 121 bytes as a maximum.

Just to be safe, I wouldn't make the names dynamic (like ids), but short compile-time constants.

**Comment by mneber** [comment]
This is perfect, thank you all for the info!
