### ISSUE TITLE
Can Hive be used for state management?

### ISSUE THREAD

**Issue by deadsoul44** [hivedb/hive#58]
Thank you for the great work. Can Hive be used for state management? What will be the disadvantages? Is it an anti-pattern? Is there anyone who tried?

**Comment by leisim** [comment]
Yes, Hive is a perfect fit for state management.
I don't see any disadvantages since this kind of unrelated data can be stored in a kv-store very easily.

**Comment by deadsoul44** [comment]
Thanks a lot.
