### ISSUE TITLE
Is it possible to store an Object that has a generic Type?

### ISSUE THREAD

**Issue by Hasankanso** [hivedb/hive#581]
**Question**
I wonder if I can store an instance that has a generic Type attribute
**Code sample**
```
Class Person<T>{

@Hivefield(0)
int age;
@Hivefield(1)
T contact
}
```

And contact can be a phone number string or an address class etc.

**Comment by meg4cyberc4t** [comment]
So you closed the issue without a single answer, I have exactly the same task... ._.

**Comment by Hasankanso** [comment]
Hello man.

As I remember the answer is no, you can't store a generic type in hive. I believe it's written somewhere in their documentation.

but to be sure, read the documentation please.
