### ISSUE TITLE
Hive Generator - false negative null safety check

### ISSUE THREAD

**Issue by NatsuOnFire** [hivedb/hive#584]
**Steps to Reproduce**
With `hive_generator: ^0.9.0-nullsafety.1` in pubspec.yaml
Run `flutter pub outdated --mode=null-safety`

**False Negative with Null Safety support**
```
Package Name    Current               Upgradable           Resolvable            Latest
hive_generator  ✗0.9.0-nullsafety.1  ✗0.9.0-nullsafety.1  ✗0.9.0-nullsafety.1  ✗0.9.0-nullsafety.1
```

I think it's because the minimum version of dart sdk in hive_generator is >=2.10.0
Update to >=2.12.0 will probably fixe the problem

**Version**
 - Flutter version: 2.0.0
 - Dart version 2.12.0
 - Hive version: 1.6.0-nullsafety.2
 - Hive Generator version: 0.9.0-nullsafety.1

**Comment by arsamme** [comment]
This could fixed by updating dart version to >2.12.0 for hive_generator and hive_flutter

**Comment by TheMisir** [comment]
Hive_generator depends on [source_gen](https://pub.dev/packages/source_gen) which does not supports null safety yet.

**Comment by NatsuOnFire** [comment]
> Hive_generator depends on [source_gen](https://pub.dev/packages/source_gen) which does not supports null safety yet.

Ok, thanks for the information. Wait & See ^_^

**Comment by petoknm** [comment]
`source_gen` now supports null-safety, yay! :D
