### ISSUE TITLE
Calling Hive.init() multiple times

### ISSUE THREAD

**Issue by tomvanoost** [hivedb/hive#595]
In Hive version 1.* I could call Hive.init(path) multiple times after each other.
This was a great feature because you could effectively have multiple databases on disk (different paths) and switch between them.

In Hive 2.0.0 this doesn't work anymore. Error: **HiveError: Instance has already been initialized.**

Is it possible to bring this feature back?

**Comment by MahmoudAbunaji** [comment]
Same issue any solution?

**Comment by MahmoudAbunaji** [comment]
@tomvanoost 

Can you try to use this library for getting the path instead using "Directory.current.path" -> https://pub.dev/packages/path_provider
I think the issue is trying to create on a read only path \ .

It solved my  issue.

**Comment by MahmoudAbunaji** [comment]
@tomvanoost 

Try to use  **path_provider** library to get accessible path to save the boxes instead of get path with **read only** permission on the machine, 

Then you can **initiate** the path and register the adapters if  the path **not initialized**, Open the boxes and  save the data as you want. 

It works for me.

**Comment by TheMisir** [comment]
@leisim what do you think about that? I think lots of people are already initializing hive multiple times to change root path. 

https://github.com/hivedb/hive/commit/59ad5403593283233d922f62f76832c64fa33a3b 

So the change above break their code.

**Comment by tomvanoost** [comment]
> @tomvanoost
> 
> Try to use **path_provider** library to get accessible path to save the boxes instead of get path with **read only** permission on the machine,
> 
> Then you can **initiate** the path and register the adapters if the path **not initialized**, Open the boxes and save the data as you want.
> 
> It works for me.



> @tomvanoost
> 
> Try to use **path_provider** library to get accessible path to save the boxes instead of get path with **read only** permission on the machine,
> 
> Then you can **initiate** the path and register the adapters if the path **not initialized**, Open the boxes and save the data as you want.
> 
> It works for me.

@MahmoudAbunaji no that doesn't help. As the issue describes the problem lies in initializing multiple times. The first time it works fine of course.

**Comment by tomvanoost** [comment]
Solved, see #594
