### ISSUE TITLE
saving data from workmanager to Hive error

### ISSUE THREAD

**Issue by jaydangar** [hivedb/hive#596]
I am getting following error, while saving data from workmanager plugin to hive db.

`HiveError: Box not found. Did you forget to call Hive.openBox()?`

I have opened the box, still getting this error. What can be done to use hive from workmanager, particularly to save the data?

**Comment by leisim** [comment]
The workmanager probably accesses Hive from a background isolate so you definitely need to reopen your box. Please make sure that you don't access Hive from multiple isolates simultaneously

**Comment by jaydangar** [comment]
@leisim I need to use Hive from workmanager to write data and listen for changes from the UI. If I use two different Isolated, will it listen to the changes and change the UI? I am not able to do it. can you describe solution for that?

**Comment by leisim** [comment]
@jaydangar unfortunately not. It's a limitation of Dart. The only thing you can do is use SendPort and ReceivePort to communicate.

It's one of the reasons why I created [Isar](github.com/Isar/Isar) You can use it in multiple isolates and get notified when something changes.

**Comment by jaydangar** [comment]
@leisim thank you let me give it a try then. Thanks again.

**Comment by jaydangar** [comment]
@leisim can I use Isar for just an API call and saving the data to listen from UI? The documentation says it's not ready for serious usage. I just need one API call from the workmanager to be saved and listen to from the UI? is it a good idea?

**Comment by leisim** [comment]
@jaydangar I would use shared preferences and SendPort and ReceivePort for your use case

**Comment by jaydangar** [comment]
@leisim okay, thank you for the prompt response.

**Comment by jaydangar** [comment]
@leisim, I am opening the Hive DB from the workmanager using Hive.init() and passing the path using path_provider package, which causes error, do we have any alternative way to open and read from hive from the backend?

**Comment by jaydangar** [comment]
I got my answer from one of the issues, thanks again.
