### ISSUE TITLE
Flutter run --release not working 

### ISSUE THREAD

**Issue by amanv8060** [hivedb/hive#599]
**Steps to Reproduce**
Please tell me exactly how to reproduce the problem you are running into.

My Main Function 

```
void main() async {

  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  SystemChrome.setPreferredOrientations(
      [DeviceOrientation.portraitDown, DeviceOrientation.portraitUp]);
  await Hive.initFlutter();
  Hive.registerAdapter(MyUserAdapter());
  await Hive.openBox<MyUser>(userBox);
  runApp(MyApp());
}
```

StackTrace

```
E/flutter ( 4615): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
E/flutter ( 4615): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156)
E/flutter ( 4615): <asynchronous suspension>
E/flutter ( 4615): #1      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:139)
E/flutter ( 4615): <asynchronous suspension>
E/flutter ( 4615): #2      HiveX.initFlutter (package:hive_flutter/src/hive_extensions.dart:11)
E/flutter ( 4615): <asynchronous suspension>
E/flutter ( 4615): #3      main (package:dealerapp/main.dart:19)
E/flutter ( 4615): <asynchronous suspension>
E/flutter ( 4615): 


```

**Version**
 - Platform: iOS, Android
 - Flutter version: 2.0.1
 - Hive version:  
 hive: ^2.0.0
  hive_flutter: ^1.0.0

**Comment by amanv8060** [comment]
@TheMisir

**Comment by bounty1342** [comment]
@amanv8060 Maybe ? => https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects#full-flutter-app-migration

**Comment by wesleytoshio** [comment]
same here, not working in --release

**Comment by tintran-dev** [comment]
To me, on iOS still works normally but Android has the same error.
I think the problem is with Flutter 2 `WidgetsFlutterBinding.ensureInitialized();` did not work at release with R8 on Android

I corrected it this way and it worked for me:

in `android/app/build.gradle`

```
buildTypes {
        release {
            shrinkResources false  //add this line
            minifyEnabled false //add this line
            signingConfig signingConfigs.release
        }
}
```

Hope that can be of help to you

**Comment by dibadibadiudiu** [comment]
> 
> 
> To me, on iOS still works normally but Android has the same error.
> I think the problem is with Flutter 2 `WidgetsFlutterBinding.ensureInitialized();` did not work at release with R8 on Android
> 
> I corrected it this way and it worked for me:
> 
> in `android/app/build.gradle`
> 
> ```
> buildTypes {
>         release {
>             shrinkResources false  //add this line
>             minifyEnabled false //add this line
>             signingConfig signingConfigs.release
>         }
> }
> ```
> 
> Hope that can be of help to you

Perfect , thank you !
