### ISSUE TITLE
Unsuccessful flutter web builds

### ISSUE THREAD

**Issue by Mravuri96** [hivedb/hive#60]
**Question**
Is anyone able to build their app with hive support to build for web? I'm not even able to build the sample todo app .

**Version**
 - Platform: Web
 - Flutter version: 1.10.7-pre.69
 - Hive version: 1.0.0
 - Hive_flutter version: 0.2.1

**Comment by leisim** [comment]
What error message are you getting?

**Comment by Mravuri96** [comment]
Launching lib/main.dart on Chrome in debug mode...

Skipping compiling todo|lib/main_web_entrypoint.dart with ddc because some of its
transitive libraries have sdk dependencies that not supported on this platform:

path_provider|lib/path_provider.dart
platform|lib/src/interface/local_platform.dart

https://github.com/dart-lang/build/blob/master/docs/faq.md#how-can-i-resolve-skipped-compiling-warnings
Building application for the web...                                10.7s
Attempting to connect to browser instance..
(This is taking an unexpectedly long time.)

**Comment by leisim** [comment]
I just found out that Flutter does not allow to import the dart:io library anymore for web projects. Before it was fine as long as it has not been actually used.

This has nothing to do with Hive itself. 
You are not allowed to import the `path_provider` package anymore when you build for web.

The Hive samples do that. You can either comment out all the imports of `path_provider` or you use conditional imports.

Here is the corresponding Flutter issue: https://github.com/flutter/flutter/issues/39998

**Comment by Mravuri96** [comment]
> I just found out that Flutter does not allow to import the `dart:io` library anymore for web projects. Before it was fine as long as it has not been actually used.
> 
> This has nothing to do with Hive itself.
> You are not allowed to import the `path_provider` package anymore when you build for web.
> 
> The Hive samples do that. You can either comment out all the imports of `path_provider` or you use conditional imports.
> 
> Here is the corresponding Flutter issue: [flutter/flutter#39998](https://github.com/flutter/flutter/issues/39998)

oh alright thank you very much.
