### ISSUE TITLE
Fixed length list

### ISSUE THREAD

**Issue by devmemory** [hivedb/hive#602]
**Steps to Reproduce**
When I used Flutter version 1.22.6, I used Hive version 1.4.4+1, everything was totally fine.

But I'm facing a problem when I use List since I migrated to Flutter 2.0.0 and Hive 2.0.0.

In detail, I put my List<String> to the box with a key. And I bring back when I open app again.

And storing is working fine. When I get a List, it's fine.

But when I modify a list such as adding and removing, errors are thrown.

When I add **cannot add to a fixed-length list**.
And when I remove **cannot remove from a fixed-length list**

So I can guess with error stack like "When I get a list from box, it's gotten as **Fixed Length List**".

You can test with my sample code. Just copy and paste it. And you have to add data and close app.

After that, open the app again and try adding or removing. Then the errors will be thrown.

Finally, I appreciate that you made a good package.

**Code sample**
```
void main() async {
  await Hive.initFlutter();
  runApp(MaterialApp(home: TestSplash()));
}

class TestSplash extends StatefulWidget {
  @override
  _TestSplashState createState() => _TestSplashState();
}

class _TestSplashState extends State<TestSplash> {
  @override
  void initState() {
    super.initState();
    init();
  }

  void init() async {
    await Hive.openBox('test');

    ListData data = ListData();
    await data.init();

    Navigator.push(
        context,
        MaterialPageRoute(
            builder: (_) => ListTest(title: 'List test example', data: data)));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold();
  }
}

class ListTest extends StatefulWidget {
  final String title;
  final ListData data;

  ListTest({required this.data, required this.title});

  @override
  _ListTestState createState() => _ListTestState();
}

class _ListTestState extends State<ListTest> {
  late ListData _data;

  @override
  void initState() {
    super.initState();
    _data = widget.data;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      body: ListView.builder(
          itemCount: _data.list.length,
          itemBuilder: (_, index) {
            String title = _data.list[index];
            return Card(
              child: ListTile(
                leading: CircleAvatar(child: Text(index.toString())),
                title: Text(title),
                onTap: () {
                  setState(() {
                    _data.removeData(index);
                  });
                },
              ),
            );
          }),
      floatingActionButton: FloatingActionButton(
          child: Icon(Icons.edit),
          onPressed: () {
            showDialog(
                context: context,
                builder: (_) => AlertDialog(
                        title: Text('Add'),
                        content: TextField(onChanged: (value) {
                          _data.title = value;
                        }),
                        actions: [
                          TextButton(
                              onPressed: () {
                                _data.title = '';
                                Navigator.pop(context);
                              },
                              child: Text('Cancel')),
                          TextButton(
                              onPressed: () {
                                setState(() {
                                  _data.addData();
                                });
                                Navigator.pop(context);
                              },
                              child: Text('Confirm')),
                        ]));
          }),
    );
  }
}

class ListData {
  List<String> list = [];
  String title = '';
  late Box box;

  Future<void> init() async {
    box = Hive.box('test');
    list = box.get('list') ?? [];
  }

  void addData() {
    list.add(title);
    box.put('list', list);
  }

  void removeData(int index) {
    list.removeAt(index);
    box.put('list', list);
  }
}
```

**Error**
```
The following UnsupportedError was thrown while handling a gesture:
Unsupported operation: Cannot remove from a fixed-length list

When the exception was thrown, this was the stack: 
#0      FixedLengthListMixin.removeAt (dart:_internal/list.dart:61:5)
#1      ListData.removeData (package:version_2/list/list_test.dart:90:10)
#2      _ListTestState.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:version_2/list/list_test.dart:37:27)
#3      State.setState (package:flutter/src/widgets/framework.dart:1267:30)
#4      _ListTestState.build.<anonymous closure>.<anonymous closure> (package:version_2/list/list_test.dart:36:19)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#c4ebb
  debugOwner: GestureDetector
  state: ready
  won arena
  finalPosition: Offset(149.4, 292.7)
  finalLocalPosition: Offset(145.4, 42.5)
  button: 1
  sent tap down

------------------------------------------------------------------------------------

The following UnsupportedError was thrown while handling a gesture:
Unsupported operation: Cannot add to a fixed-length list

When the exception was thrown, this was the stack: 
#0      FixedLengthListMixin.add (dart:_internal/list.dart:21:5)
#1      ListData.addData (package:version_2/list/list_test.dart:85:10)
#2      _ListTestState.build.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:version_2/list/list_test.dart:63:41)
#3      State.setState (package:flutter/src/widgets/framework.dart:1267:30)
#4      _ListTestState.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:version_2/list/list_test.dart:62:33)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#de3bc
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(309.4, 375.6)
  finalLocalPosition: Offset(48.1, 27.0)
  button: 1
  sent tap down
```

**Version**
 - Platform: Android
 - Flutter version: 2.0.2
 - Hive version: 2.0.0

**Comment by Tromp6** [comment]
We face the exact same issue

**Comment by ThorgeL** [comment]
Same. I found a workaround:

Old code that triggers the fixed.length exception when new item is added:
`
model.voiceNoteList = hiveModel.voiceNoteList
`

Temporary workaround:
`
var tempVoiceNoteList = <VoiceNote>[...hiveModel.voiceNoteList];
 model.voiceNoteList = tempVoiceNoteList;
`

**Comment by TheMisir** [comment]
Not sure but I think this line below assings FixedLengthList to list variable. I'm not sure if it's related to hive or not. If you could create simple reproducible example I would like to work on this issue.

List<String> list = [];

**Comment by devmemory** [comment]
@TheMisir 

As I said in the first line, it worked without any problem in previous version with same code.

According to official dart list API, I have to write like below if I want to create it Fixed length list.
(Link : 2.10.5 version https://api.dart.dev/stable/2.10.5/dart-core/List-class.html
2.12.1 version https://api.dart.dev/stable/2.12.1/dart-core/List-class.html)

2.10.5
List<int> fixedLengthList = new List(5);
List<int> growableList = [1, 2];

2.12.1
var fixedLengthList = List<int>.filled(5, 0);
var growableList = [1, 2];

When I initialize a list, I always created as a growable list such as [] or ['a', 'b'].

So according to official API, it can never be a fixed length list.

If it was other problem, I want to ask why it works perfectly without hive and previous version.

Also, I think I gave you enough sample code which can reproduce the problem..?

**Comment by bemarinho** [comment]
I have the exact same issue as @devmemory.

```
part 'my_class.g.dart';

@HiveType(typeId: 1)
class MyClass extends HiveObject {
    MyClass({this.prop});

    @HiveField(0)
    List<MyProp>? prop;
}
```
```
part of 'my_class.dart';

class MyClassAdapter extends TypeAdapter<MyClass> {
    @override
    final int typeId = 1;
    ....
    return MyClass(
        prop: (fields[0] as List?)?.cast<MyProp>()
    );
    .....
}
```
```
MyClass createClass() {
    return MyClass(
        prop: [];    <---- growable
    );
}
```
```
void addProp(MyProp prop) {
    myClass.add(prop);   <----- throws
}
```
```
void removeProp(MyProp prop) {
    myClass.remove(prop);    <------- throws
}
```

The first time I run the app it works fine, but once I close it, open again and try to add/remove anything from the list it throws saying it's fixed length.
Is it possible that somehow Hive is storing it with the wrong type when closing and reopening boxes?

The workaround suggested by @ThorgeL did not work for me, sadly.

**Comment by ahmedkassem** [comment]
I was facing the same problem, so as a walk around I downgraded hive and hive flutter packages and did dependency override for path_provider, now it works fine

dependencies:
  hive: 1.5.0-pre
  hive_flutter: 0.3.1

dependency_overrides:
  path_provider: ^2.0.1

**Comment by devmemory** [comment]
I think it's better to write a code like this for people who are having same issue

So rest of them are same with my code which I uploaded in the first.

And init function should be like this

`Future<void> init() async {
    box = Hive.box('test');
    //list = box.get('list') ?? []; // this will cause a fixed length list error
    list.addAll(box.get('list') ?? []);
  }`

Instead of saving reference, saving values will be reasonable even if it takes more time and memory.

**Comment by gouthamravella** [comment]
This issue is hampering the release of one of my project. Does anyone have a working solution to this yet?

**Comment by kamacostik** [comment]
> I have the exact same issue as @devmemory.
> 
> ```
> part 'my_class.g.dart';
> 
> @HiveType(typeId: 1)
> class MyClass extends HiveObject {
>     MyClass({this.prop});
> 
>     @HiveField(0)
>     List<MyProp>? prop;
> }
> ```
> 
> ```
> part of 'my_class.dart';
> 
> class MyClassAdapter extends TypeAdapter<MyClass> {
>     @override
>     final int typeId = 1;
>     ....
>     return MyClass(
>         prop: (fields[0] as List?)?.cast<MyProp>()
>     );
>     .....
> }
> ```
> 
> ```
> MyClass createClass() {
>     return MyClass(
>         prop: [];    <---- growable
>     );
> }
> ```
> 
> ```
> void addProp(MyProp prop) {
>     myClass.add(prop);   <----- throws
> }
> ```
> 
> ```
> void removeProp(MyProp prop) {
>     myClass.remove(prop);    <------- throws
> }
> ```
> 
> The first time I run the app it works fine, but once I close it, open again and try to add/remove anything from the list it throws saying it's fixed length.
> Is it possible that somehow Hive is storing it with the wrong type when closing and reopening boxes?
> 
> The workaround suggested by @ThorgeL did not work for me, sadly.

I was facing the same problem

**Comment by joscha0** [comment]
A workaround that worked for me:
```dart
list = list.toList();
list.add(value);
```

**Comment by TheMisir** [comment]
Will be fixed with https://github.com/hivedb/hive/pull/631

**Comment by siprogramas** [comment]
> A workaround that worked for me:
> 
> ```dart
> list = list.toList();
> list.add(value);
> ```

funcionou perfeitamente.
