### ISSUE TITLE
update field inside hive

### ISSUE THREAD

**Issue by miladrashidizade** [hivedb/hive#604]
**Question**
I want to update the value inside the reminders

**Code sample**
```dart

@HiveType(typeId: 0)
class Contact {
  @HiveField(0)
  String id;

  @HiveField(1)
  String name;

  @HiveField(2)
  String family;

  @HiveField(3)
  String phone;

  @HiveField(4)
  List<Reminders> reminders;
```

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: [e.g. 1.22.6]
 - Hive version: [e.g. 0.3.1]
[](url)

**Comment by TheMisir** [comment]
Sure

**Comment by TheMisir** [comment]
Please open another issue with more details to help us understand and help you.

**Comment by mkhtradm01** [comment]
Make sure you register Reminder Adapter too.

**Comment by Hasankanso** [comment]
You have to update the whole contact instance in the box, you can't update one field without updating others. as far as I know.
