### ISSUE TITLE
Storing functions

### ISSUE THREAD

**Issue by xakeppok** [hivedb/hive#606]
**Question**
Hi. I'm creating local db for application and i want store API calls in hive db, and then when internet connection comes up i will send this requests.

**Code sample**
db service
Box<Function> calls = await Hive.openBox<Function>(AppConstants.calls);
storing 
 await localDbService.calls
              .add(() async => await api.updateSettings(settings.toJson()));
error: Cannot write, unknown type: () => Future<Response<dynamic>>. Did you forget to register an adapter?

Any ways to resolve this issue ?

**Version**
 - Platform: iOS, Android
 - Flutter version: [1.22.5]
 - Hive version: [1.4.4+1]

**Comment by Mayb3Nots** [comment]
Why don't just keep the functions on the app? Why do you need to store it on the user's device?

**Comment by TheMisir** [comment]
It's not possible.

You can not store functions in any database (declaring functions in databases like postgresql is not same as saving function as an entry).

**Comment by xakeppok** [comment]
> Why don't just keep the functions on the app? Why do you need to store it on the user's device?

My application has offline mode. So that why i tried to store functions.

**Comment by xakeppok** [comment]
> It's not possible.
> 
> You can not store functions in any database (declaring functions in databases like postgresql is not same as saving function as an entry).

got it. any way to make API call after turning on internet ?

**Comment by Mayb3Nots** [comment]
> > Why don't just keep the functions on the app? Why do you need to store it on the user's device?
> 
> My application has offline mode. So that why i tried to store functions.

yea why not just write the function in your code then call it when u need it. I don't see why you need to store it separately.

>got it. any way to make API call after turning on internet?

there is a package called [internet_connection_checker](https://pub.dev/packages/internet_connection_checker) that uses a simple API to determine whether the device is connected to the internet by pinging google's server.

**Comment by Mayb3Nots** [comment]
Sounds like firebase firestore is good for ur use case

**Comment by xakeppok** [comment]
Bad news. Customer doesn't want to use firebase in this application. But thank you for answering.

**Comment by TomasWeg** [comment]
@xakeppok This is as simple as storing objects. I explain.

Suppose you make a request to update user information and looks like this: PATCH /account {firstName: "Jose", lastName: "Ryan"}.
If the device does not have internet connection, just create a model called HttpCall and store critical information about it. For example, HttpMethod (PATCH in this case), Body (if any), Path (to the resource), QueryParams (if any), and so on. And then, when you detect internet activity, parse it and send as a normal request.

**Comment by xakeppok** [comment]
@TomasWeg yeah,thats a good idea, thank you very much!
