### ISSUE TITLE
List reversed or OrderBy in hive?

### ISSUE THREAD

**Issue by wesleytoshio** [hivedb/hive#608]
**Question**
How to do something similar? I need the values saved in Hive and to revert from the list, or to sort by the date

**Code sample**
```dart
List<dynamic> list = [1,2,3,4];
List<dynamic> reversed= list .reversed.toList();
print(reversed); // result: [4,3,2,1];
```

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: 2.0.3
 - Hive version: 2.0.0

**Comment by GarvMaggu** [comment]
Hi @wesleytoshio, you can sort values using this, I am using a Hive Box entries as children in my ListView
`ValueListenableBuilder(
                      valueListenable:
                          Hive.box(boxName).listenable(),
                      builder: (BuildContext context, Box snapshot, _) {
                        var snapshot2 = snapshot.values.toList();
                        snapshot2.sort((a, b) =>
                            Timestamp.fromDate(DateTime.parse(b['dateTime']))
                                .compareTo(Timestamp.fromDate(
                                    (DateTime.parse(a['dateTime'])))));
                        return ListView(
                            shrinkWrap: true,
                            padding: EdgeInsets.only(top: 10, bottom: 30),
                            physics: ClampingScrollPhysics(),
                            children: snapshot2.map((data) {
                              return Container(
                                padding: EdgeInsets.only(
                                    left: 14, right: 14, top: 10, bottom: 10),
                                child: Align(
                                  child: Container(
                                    padding: EdgeInsets.all(16),
                                    child: Text(
                                      data["content"],
                                      style: TextStyle(fontSize: 15),
                                    ),
                                  ),
                                ),
                              );
                            }).toList());
                      }),`

**Comment by wesleytoshio** [comment]
> Hi @wesleytoshio, you can sort values using this, I am using a Hive Box entries as children in my ListView
> 
> This is an example of my Hivebox entry
> {'a': {dateTime:'yyyy-MM-ddTHH:mm:ss.mmmuuu', 'content': 'Hello'}}
> 
> ```
> ValueListenableBuilder(
>                       valueListenable:
>                           Hive.box(boxName).listenable(),
>                       builder: (BuildContext context, Box snapshot, _) {
>                        //If you want to reverse
>                         var snapshot2 = snapshot.values.toList().reversed.toList();
>                        // If you want to sort it by dateTime
>                         snapshot2.sort((a, b) =>
>                             Timestamp.fromDate(DateTime.parse(b['dateTime']))
>                                 .compareTo(Timestamp.fromDate(
>                                     (DateTime.parse(a['dateTime'])))));
>                         return ListView(
>                             shrinkWrap: true,
>                             padding: EdgeInsets.only(top: 10, bottom: 30),
>                             physics: ClampingScrollPhysics(),
>                             children: snapshot2.map((data) {
>                               return Container(
>                                 padding: EdgeInsets.only(
>                                     left: 14, right: 14, top: 10, bottom: 10),
>                                 child: Align(
>                                   child: Container(
>                                     padding: EdgeInsets.all(16),
>                                     child: Text(
>                                       data["content"],
>                                       style: TextStyle(fontSize: 15),
>                                     ),
>                                   ),
>                                 ),
>                               );
>                             }).toList());
>                       }),
> ```

hello thanks for the time ... but it doesn't work if it is a list with CRUD, Hive updates the wrong index, because the ordering is not done by the same.

**Comment by GarvMaggu** [comment]
> > Hi @wesleytoshio, you can sort values using this, I am using a Hive Box entries as children in my ListView
> > This is an example of my Hivebox entry
> > {'a': {dateTime:'yyyy-MM-ddTHH:mm:ss.mmmuuu', 'content': 'Hello'}}
> > ```
> > ValueListenableBuilder(
> >                       valueListenable:
> >                           Hive.box(boxName).listenable(),
> >                       builder: (BuildContext context, Box snapshot, _) {
> >                        //If you want to reverse
> >                         var snapshot2 = snapshot.values.toList().reversed.toList();
> >                        // If you want to sort it by dateTime
> >                         snapshot2.sort((a, b) =>
> >                             Timestamp.fromDate(DateTime.parse(b['dateTime']))
> >                                 .compareTo(Timestamp.fromDate(
> >                                     (DateTime.parse(a['dateTime'])))));
> >                         return ListView(
> >                             shrinkWrap: true,
> >                             padding: EdgeInsets.only(top: 10, bottom: 30),
> >                             physics: ClampingScrollPhysics(),
> >                             children: snapshot2.map((data) {
> >                               return Container(
> >                                 padding: EdgeInsets.only(
> >                                     left: 14, right: 14, top: 10, bottom: 10),
> >                                 child: Align(
> >                                   child: Container(
> >                                     padding: EdgeInsets.all(16),
> >                                     child: Text(
> >                                       data["content"],
> >                                       style: TextStyle(fontSize: 15),
> >                                     ),
> >                                   ),
> >                                 ),
> >                               );
> >                             }).toList());
> >                       }),
> > ```
> 
> hello thanks for the time ... but it doesn't work if it is a list with CRUD, Hive updates the wrong index, because the ordering is not done by the same.

Ohh okay, didn't realize that

**Comment by TheMisir** [comment]
Box.values.reversed.toList() should work. Don't forget to put keys to list items on UI to help flutter to keep track of the changes. Otherwise the changes will not be displayed as expected on UI.

**Comment by wesleytoshio** [comment]
> Box.values.reversed.toList () deve funcionar. Não se esqueça de colocar teclas para listar itens na IU para ajudar a agitar e manter o controle das mudanças. Caso contrário, as alterações não serão exibidas conforme o esperado na IU.

**Box.values** does not contain reversed method :(, I need to turn it into a list and then do the reverse, I believe that this is also not an efficient practice, I think Hive should provide this by default.

**Comment by TheMisir** [comment]
Hive is more likely a key-value type database. If you want to write advanced queries like `SELECT * FROM table ORDER BY something` then using SQLite3 would be better than hive for you. If you don't want to deal with SQL, well "There ain't no such thing as a free lunch".
