### ISSUE TITLE
Get box's file size

### ISSUE THREAD

**Issue by Mayb3Nots** [hivedb/hive#609]
How do you get a box's file size on the device. I guess if you have a root-ed phone you can view the file directory but is there a way to get the box's file size in dart?

**Comment by PavelPZ** [comment]
```box.path``` (null for web) and dart:io does not help?

**Comment by Mayb3Nots** [comment]
> `box.path` (null for web) and dart:io does not help?

Oh yea! Didn' though about that. We can get the file path and get the file size. Thanks!

**Comment by TheMisir** [comment]
As @PavelPZ said you can use `File(box.path).lengthSync()` to get box size.
