### ISSUE TITLE
Hive add x put x clear

### ISSUE THREAD

**Issue by PavelPZ** [hivedb/hive#610]
I'm trying to learn a Hive database.

I ran the following test several times (Dart without Flutter, VS Code). I can't derive the behavior of the Hive database from the code at all. Only **Run 1** works as it should. I run everything without physically deleting the database directory (e:\temp\hive.bin\).

Any explanation welcome (I read the documentation at https://docs.hivedb.dev/).

```
void main() {
  test('hive', () async {
    Hive.init('e:\\temp\\hive.bin');
    final friends = await Hive.openBox('friends');
    friends.clear();

    friends.add('Lisa');
    friends.put(123, 'Marco');
    friends.put(124, 'Paul');
    friends.put('xx', 'yy');

    print(friends.values);
    print(friends.keys);
    print(friends.toMap());

    print(friends.getAt(0));
    print(friends.get(0));

    print(friends.getAt(1));
    print(friends.get(123));

    print(friends.getAt(2));
    print(friends.get(124));

    print(friends.getAt(3));
    print(friends.get('xx'));

    await Future.delayed(Duration(milliseconds: 300));
  });
}
```

# Console dumps
## Run 1
```
(Lisa, Marco, Paul, yy)
(0, 123, 124, xx)
{0: Lisa, 123: Marco, 124: Paul, xx: yy}
Lisa
Lisa
Marco
Marco
Paul
Paul
yy
yy
```
## Run 2
```
(Lisa, Marco, Paul, Lisa, yy)
(0, 123, 124, 125, xx)
{0: Lisa, 123: Marco, 124: Paul, 125: Lisa, xx: yy}
Lisa
Lisa
Marco
Marco
Paul
Paul
Lisa
yy

```
## Run3
```

(Marco, Paul, Lisa, Lisa, yy)
(123, 124, 125, 126, xx)
{123: Marco, 124: Paul, 125: Lisa, 126: Lisa, xx: yy}
Marco
null
Paul
Marco
Lisa
Paul
Lisa
yy
```

**Comment by PavelPZ** [comment]
Solved, **await friends.clear();** helps.

I used the example at https://docs.hivedb.dev/#/basics/auto_increment, where is ```friends.clear``` without await.

**Comment by Mayb3Nots** [comment]
Wow interesting, i didn't know getAt() works without the keys being integer. I always though it only works when you auto-increment with intergers

**Comment by PavelPZ** [comment]
I think getAt(0) works with index only, not with key (nor string nor integer). 
It is interesting, that integer key may affect autoincrement value. Than index and autoincremet could be different.
