### ISSUE TITLE
Using HiveObject as a Mixin

### ISSUE THREAD

**Issue by rlch** [hivedb/hive#613]
**Question**
Hey there, I'm wondering if it's possible to use `HiveObject` through a mixin rather than inheritance? 

**Code sample**
```dart
@HiveType(typeId: 8)
class HiveIdentityKeyStore extends InMemoryIdentityKeyStore with HiveObject {
  HiveIdentityKeyStore({
    required this.identityKeyPair,
    required this.localRegistrationId,
  }) : super(identityKeyPair, localRegistrationId);

  @override
  @HiveField(0)
  final IdentityKeyPair identityKeyPair;
  @override
  @HiveField(1)
  final int localRegistrationId;
}
```

**Comment by TheMisir** [comment]
Nice idea. I'll try to create `HiveObjectMixin` if it doesn't breaks anything. (The naming will contain Mixin to support exists `HiveObject`).

**Comment by rlch** [comment]
Awesome, thanks so much! In the mean time, should I expect weird behavior if I use `HiveObject` as a mixin?

**Comment by TheMisir** [comment]
Now you can use `HiveObjectMixin`. (`HiveObject` **is not** deprecated, you can use it as well).
