### ISSUE TITLE
Cross Domain Storage

### ISSUE THREAD

**Issue by Ferdzzzzzzzz** [hivedb/hive#614]
**Question**

I've used Hive in a couple of production native apps and absolutely love it. Looking to use it in a web project but I have a requirement to store access tokens for multiple domains in one place, eg. `dev.com` and `auth.dev.com` and `app.dev.com` etc all need access to the same storage. Is this possible with Hive?

I know in Javascript this is complicated as cross-domain access to localstorage isn't allowed. One solution is to use an iFrame, which is what [cross-storage](https://www.npmjs.com/package/cross-storage) does. But I'm not sure what the limitations of Hive are and how one would achieve this?

**Comment by TomasWeg** [comment]
What about using cookies?

**Comment by Ferdzzzzzzzz** [comment]
@TomasWeg I guess that's an option, but not really a correct use case for cookies. Storing access tokens for a web app is a job for localstorage or something similar. So I guess a better general question would be: is it possible for two different Flutter apps to access the same Hivedb?

**Comment by TheMisir** [comment]
No Hive doesn't supports using same database on multiple domains.  Because, hive uses IndexedDB for storing data on web. And IndexedDB limits access scope to only current origin.
