### ISSUE TITLE
How to store in one box a model Profile, which has a list field ?

### ISSUE THREAD

**Issue by tagirahmad** [hivedb/hive#616]
**Question**
My question is: how to store in one box a model Profile, which has a list field ?

For example, I have a such kind of class, i've generated adapter and I want to have one box with that one class schema in order to put/update data for only one profile. What should I do next?

Suppose, 
```dart
Hive.registerAdapter(ProfileHiveAdapter());
var profile = await Hive.openBox<ProfileHive>('profile');
```

Then, in order to write/update  fields, what should I do?

**Code sample**
```dart
@HiveType(typeId : 1)
class ProfileHive {
  @HiveField(0)
  late String name;

  @HiveField(1)
  late int age;

  @HiveField(2)
  late String city;

  @HiveField(3)
  late String profileImagePath;

  @HiveField(4)
  late List<YearAim> yearAims;

  @HiveField(5)
  late List<LifeAim> lifeAims;
}
```

**Version**
 - Platform: iOS, Android
 - Flutter version: 2.0.1
 - Hive version: 2.0.0

**Comment by TheMisir** [comment]
You also have to annotate `YearAim`, `LifeAim` with `@HiveType`.
