### ISSUE TITLE
HiveObjectMixin not assigning box to object

### ISSUE THREAD

**Issue by rlch** [hivedb/hive#618]
**Steps to Reproduce**
Replace `extends HiveObject` with `with HiveObjectMixin`

**Code sample**
```dart
@HiveType(typeId: 20)
class HiveProtocolStore extends HiveObject implements SignalProtocolStore {
  HiveProtocolStore(
    this._iks, {
    required this.pks,
    required this.ss,
    required this.spks,
  });

  @HiveField(0)
  final HiveIdentityKeyStore _iks;
  @HiveField(1)
  HivePreKeyStore pks;
  @HiveField(2)
  HiveSignedPreKeyStore spks;
  @HiveField(3)
  HiveSessionStore ss;

  static Future<void> init({required String userId}) async {
    final keyBox = await Hive.openBox<HiveProtocolStore>('keys');

    final iks = await HiveIdentityKeyStore.init(userId);
    final spks = await HiveSignedPreKeyStore.init(userId, iks.identityKeyPair);
    final ss = await HiveSessionStore.init(userId);
    final pks = await HivePreKeyStore.init(userId);

    final store = HiveProtocolStore(iks, pks: pks, ss: ss, spks: spks);
    await keyBox.put(userId, store);
  }
```

When pulled from a `Box`, we get the following:

![image](https://user-images.githubusercontent.com/35163478/112935385-63ff3880-916f-11eb-98aa-f0dcb60bfa28.png)

The same code but with `extends HiveObject` replaced with `with HiveObjectMixin` causes the variable to be initialized as such when pulled from a `Box`:

![image](https://user-images.githubusercontent.com/35163478/112935225-15ea3500-916f-11eb-86c4-80b810fa3c19.png)

Having `HiveObjectMixin` work properly would really clean up more complex codebases that rely on Hive imo, I really appreciate any support with this issue.

**Version**
 - Platform: Android
 - Flutter version: 2.0.3
 - Hive version: latest

**Comment by TheMisir** [comment]
Thanks for reporting. Working on it!
