### ISSUE TITLE
[BUG] `HiveObject` will failed to parse after fields are added and opened at the first time

### ISSUE THREAD

**Issue by AlexV525** [hivedb/hive#625]
TL;DR, newly added fields are `null` when the first time open the app after they were generated.

**Code sample**
Demo repo: https://github.com/AlexV525/hive_object_null_issue

**Version**
 - Platform: All
 - Flutter version: 2.0.4
 - Hive version: 2.0.2

**Comment by AlexV525** [comment]
I saw a PR (#557) for fixing the default value for enum, but not for other types. It's a pity that the `defaultValue` isn't indicate the **default value** for the field, but for whether it's a default value.

**Comment by AlexV525** [comment]
cc @TheMisir

**Comment by zmtzawqlp** [comment]
In my option, if something is null, we should not set it, so that we can use the default value of it.

for example, we have value property at the first time then we add test property.  we can't read test property in TypeAdapter read method. It should be nice to not set it to null.
``` dart
@HiveType(typeId: 0)
AppSetting extends HiveObject
{
   @HiveField(0)
    int value=0;

   @HiveField(1)
   bool test=false;
}


..test = fields[1] as bool;

```

**Comment by AlexV525** [comment]
My opinion is quite different from @zmtzawqlp . I'm more preferred to the solution in the `json_serializable` with `JsonKey`.
https://github.com/google/json_serializable.dart/blob/818c48f82893764c7d6bee7f884a63d301310713/json_annotation/lib/src/json_key.dart#L12

```dart
class HiveField {
  final int index;

  final Object? defaultValue;

  const HiveField(this.index, {this.defaultValue});
}
```

Then the default value will be inserted to the adapter if it's exist.

**Comment by TheMisir** [comment]
I don't know if it's possible to read runtime values from annotations during code generation phase. If it's possible I would use `defaultValue` property of `HiveField` as default value.

**Comment by AlexV525** [comment]
If you mean read from the code, sure, it can. That what `json_annotation` did.
