### ISSUE TITLE
Where are the files stored?

### ISSUE THREAD

**Issue by daybson** [hivedb/hive#628]
Where is the database files are stored into Android disk (similar to SQLite)? 
I mean, after the user install the apk, where Hive save the data?
I'm using Hive with Flutter.

**Comment by TheMisir** [comment]
Hive stores the files inside the directory provided when calling `Hive.init(..)` method. If you've initialized Hive using initFlutter in that case hive will use path_provider to `getApplicationDocumentsDirectory()` method to determine application data directory.
