### ISSUE TITLE
Hive database backup locally and restore

### ISSUE THREAD

**Issue by sanchaykasturey** [hivedb/hive#629]
**Question**

I want to know if there is a way by which I can export all the database of the hive into a backup and then restore it so if a user wants to uninstall the app the user can backup the data locally into a location like sdcard or phone storage and after reinstalling they can restore from backup all the database and can use it again. So what can be the ways by which it can be done?

**Version**
 - Platform: Android
 - Flutter version: 2.0.3 stable
 - Hive version: hive: ^1.4.4+1
                         hive_flutter: ^0.3.1

**Comment by TheMisir** [comment]
Yes you can. You can get path of the database files using .path property of the Box.

```dart
File(Hive.box('example').path).copy('/path/to/backup/file.hive');
```

And you can restore the box using:

```dart
var box = Hive.box('example');
var boxPath = box.path;
await box.close(); // close current box, so we can replace it with a new data
File('/path/to/backup/file.hive').copy(boxPath); // copy backup file
box = await Hive.openBox('example'); // re-open the box to read new data
```

**Comment by sanchaykasturey** [comment]
I am new to flutter, what I want is to let the user backup their data onto a location which they want by providing a button of backup and then it should ask for the path and then the data can be backed up and I want similar function with restore button as well can u please briefly tell me how can I do it?

**Comment by TheMisir** [comment]
Hey @sanchaykasturey ,

Let's assume you want to backup a box named "data". First you have to somehow ask user to choose which directory does he wants to backup files into. You can use file dialog packages or use TextField to get user input.

```dart
import 'dart:io';

import 'package:hive/hive.dart';

Future<void> backupHiveBox<T>(String boxName, String backupPath) async {
  final box = await Hive.openBox<T>(boxName);
  final boxPath = box.path;
  await box.close();

  try {
    File(boxPath).copy(backupPath);
  } finally {
    await Hive.openBox<T>(boxName);
  }
}

Future<void> restoreHiveBox<T>(String boxName, String backupPath) async {
  final box = await Hive.openBox<T>(boxName);
  final boxPath = box.path;
  await box.close();

  try {
    File(backupPath).copy(boxPath);
  } finally {
    await Hive.openBox<T>(boxName);
  }
}
```

**Comment by sanchaykasturey** [comment]
Okay, thank you so much for your help.

**Comment by TheSeriousProgrammer** [comment]
Can this be added in README ? It will be convenient for new comers

**Comment by godara-anil** [comment]
I have two boxes in my app. Do I have to copy them separately or is there any way I can copy them as one file?

**Comment by MarwanCS** [comment]
> I have two boxes in my app. Do I have to copy them separately or is there any way I can copy them as one file?
did you get a way to copy them as one file?

**Comment by harryandroiddev** [comment]
on android we can get the exterenal path with path provider package but for ios it does not support any exterenal storage path , so we can we backup the data on ios .

**Comment by armandojimenez** [comment]
> on android we can get the exterenal path with path provider package but for ios it does not support any exterenal storage path , so where do we backup the hive data on ios .

Any answer for this? Is there any way to upload it iCloud for example?

**Comment by triggerfx** [comment]
> Hey @sanchaykasturey ,
> 
> Let's assume you want to backup a box named "data". First you have to somehow ask user to choose which directory does he wants to backup files into. You can use file dialog packages or use TextField to get user input.
> 
> ```dart
> import 'dart:io';
> 
> import 'package:hive/hive.dart';
> 
> Future<void> backupHiveBox<T>(String boxName, String backupPath) async {
>   final box = await Hive.openBox<T>(boxName);
>   final boxPath = box.path;
>   await box.close();
> 
>   try {
>     File(boxPath).copy(backupPath);
>   } finally {
>     await Hive.openBox<T>(boxName);
>   }
> }
> 
> Future<void> restoreHiveBox<T>(String boxName, String backupPath) async {
>   final box = await Hive.openBox<T>(boxName);
>   final boxPath = box.path;
>   await box.close();
> 
>   try {
>     File(backupPath).copy(boxPath);
>   } finally {
>     await Hive.openBox<T>(boxName);
>   }
> }
> ```

I get this error after I want to access the box again:
HiveError (HiveError: Box has already been closed.)

**Comment by ghost** [comment]
> Hey @sanchaykasturey ,
> 
> Let's assume you want to backup a box named "data". First you have to somehow ask user to choose which directory does he wants to backup files into. You can use file dialog packages or use TextField to get user input.
> 
> ```dart
> import 'dart:io';
> 
> import 'package:hive/hive.dart';
> 
> Future<void> backupHiveBox<T>(String boxName, String backupPath) async {
>   final box = await Hive.openBox<T>(boxName);
>   final boxPath = box.path;
>   await box.close();
> 
>   try {
>     File(boxPath).copy(backupPath);
>   } finally {
>     await Hive.openBox<T>(boxName);
>   }
> }
> 
> Future<void> restoreHiveBox<T>(String boxName, String backupPath) async {
>   final box = await Hive.openBox<T>(boxName);
>   final boxPath = box.path;
>   await box.close();
> 
>   try {
>     File(backupPath).copy(boxPath);
>   } finally {
>     await Hive.openBox<T>(boxName);
>   }
> }
> ```

I'm having  an error with this:

Unhandled Exception: FileSystemException: Cannot copy file to '/storage/emulated/0/Download/Backup', path = '/data/user/0/com.example.app/app_flutter/orders.hive' (OS Error: Is a directory, errno = 21)

When copying a box, I got this message immediately.

**Comment by ghost** [comment]
Okey, I fixed it.

The problem was that i was copying the hive file without set a name.

The solution with corrections:

```dart
Future<void> backupHiveBox<T>(String boxName, String backupPath) async {
  final box = await Hive.openBox<T>(boxName);
  final boxPath = box.path;
  await box.close();

  try {
    await File(boxPath!).copy('$backupPath/$boxName.hive');
  } finally {
    await Hive.openBox<T>(boxName);
  }
}
```
