### ISSUE TITLE
How to fetch data monthwise and returning its sum?

### ISSUE THREAD

**Issue by sanchaykasturey** [hivedb/hive#636]
**Question**
I am making an app using hive with flutter, it provides the option to users to add a financial transaction by them and adding details related to it like the date (transaction was added), mode of payment, etc. I want to add a screen which will have all the months for a year (in ListTile) title can be the name of the months and then it should contain the sum of all the expenses done on that month. How can I make a query for the same which will return the sum of all the transactions for a month? I am new to flutter please also tell me how to implement the same in flutter?

![Screenshot_1618367952](https://user-images.githubusercontent.com/58870251/114646384-c708d780-9cf8-11eb-8a48-ead8c9b66694.png)
![Screenshot_1618367959](https://user-images.githubusercontent.com/58870251/114646356-bd7f6f80-9cf8-11eb-9aa8-cdf347a1db0d.png)

Thank you for your replies

**Version**
 - Platform:  Android
 - Flutter version: 2.0.3
 - Hive version: 1.4.4

**Comment by TheMisir** [comment]
If you need working with advanced queries I would suggest using SQLite3 or a new database created by @leisim (author of hive): https://isar.dev

**Comment by sanchaykasturey** [comment]
Can't i process this kind of query with hive?

**Comment by TheMisir** [comment]
You can access stored data in box using values property: `Hive.box('...').values` which then you can manipulate using various dart methods like `.where((it) => it.date.isAfter(startOfMonth) && it.date.isBefore(endOfMonth))`.

**Comment by sanchaykasturey** [comment]
Okay i will try that, thanks for your help

**Comment by Petrus-Nauyoma** [comment]
> Okay i will try that, thanks for your help

Hi, did you figure out how to do this? I have a similar problem.
