### ISSUE TITLE
How to migrate hive box on production

### ISSUE THREAD

**Issue by ermand-hoxha** [hivedb/hive#640]
I have publish my app on PlayStore and AppStore. Now i have made a change on one box i have created before.
How can i migrate box to the new one, because i want to put new field with userId on it.

 - Platform: iOS, Android
 - Hive version: [2.0.3]

**Comment by TheMisir** [comment]
You can add a new field to exists HiveType-s. Only thing to keep in mind that you can not modify previous HiveFields. If you need to remove a field, you can remove it but skip its field ID.

For example:

```dart
class Customer {
  @HiveField(1)
  final int id;

  @HiveField(2)
  final String name;
}
```

To modify `String name` with `int age` you can write like:

```dart
class Customer {
  @HiveField(1)
  final int id;

  @HiveField(3) // We should not use previous field ID with different data type, so we skip it to avoid read errors & data damages.
  final int age;
}
```

You can read more about migrations on Hive docs:

[Generate Adapter > Updating a class](https://docs.hivedb.dev/#/custom-objects/generate_adapter?id=updating-a-class)

**Comment by ermand-hoxha** [comment]
What i want is to add new field, but with value. Example:
Old box:
      class Customer { @HiveField(1) final int id; 
          @HiveField(2) final String name; }

New box:
        class Customer { @HiveField(1) final int id; @HiveField(2) final String name;  @HiveField(3)  final String  userId}

**Comment by TheMisir** [comment]
@ermand-hoxha your class migration is okay.

An additional question: are you using null safety? If you do I would suggest using nullable String type cause previous entries doesn't contains that field: `@HiveField(3) finalString? userId`.

**Comment by ermand-hoxha** [comment]
No i'm not yet, i will. Thank you.
But how can i fill previus data with userId value?

**Comment by TheMisir** [comment]
> No i'm not yet, i will. Thank you.
> But how can i fill previus data with userId value?

I just published hive_generator v1.1.0 and hive v2.0.4, which adds default value support. So, after upgrading both packages you can define default value as like below:

```dart
@HiveField(3, defaultValue: 0)
final String  userId;
```

**Comment by ermand-hoxha** [comment]
I have problem with some packages version after this. 
     [SEVERE] json_serializable:json_serializable on lib/packages/models/user/jwt_token_entity.dart:
     Generator cannot target libraries that have not been migrated to null-safety.

It seems that json_serializable not support null-safety

**Comment by TheMisir** [comment]
You can try adding dependency_override until flutter_cached_pdfview becomes compatible with path_provider 2.0.0.

```yaml
dependency_overrides:
  path_provider: ^2.0.0
```

**Comment by Diaglyonok** [comment]
@TheMisir , is there way to move data from one class to another? I mean, there is class Example with some fields, and I want to create class Example2 with similar values and move data (Example -> Example2).

**Comment by TheMisir** [comment]
> @TheMisir , is there way to move data from one class to another? I mean, there is class Example with some fields, and I want to create class Example2 with similar values and move data (Example -> Example2).

```dart
for (final key in exampleBox.keys) {
  final example = exampleBox.get(key);
  example2Box.put(key, Example2(
    field1: example.field1,
    field2: example.field2,
    ...
  ));
}
```

**Comment by svonidze** [comment]
from https://docs.hivedb.dev/#/custom-objects/generate_adapter?id=updating-a-class
> If you add new fields, any objects written by the "old" adapter can still be read by the new adapter.

that is not 100% true, since hive is migrated to null-safety you have to specify `defaultValue` to any new filed otherwise you will get 
> type 'Null' is not a subtype of type 'bool' in type cast

due to previously generated code `fields[1] as bool`.

so with `@HiveField(1, defaultValue: true)` the hive_generator will rewrite the code `fields[1] == null ? true : fields[1] as bool,`

I think this info has to be added to the docs, @TheMisir do you agree?

**Comment by jack24254029** [comment]
Can `typeId` reused?

1. create class A
```dart
@HiveType(typeId: 1)
class A {}
```
2. Delete class A ,create class B and use the same `typeId`
```dart
@HiveType(typeId: 1)
class B {}
```

**Comment by themisir** [comment]
> Can `typeId` reused?
> I can't find information on document.
> 
> For example:
> 
> 1. Create class A
> 
> ```dart
> @HiveType(typeId: 1)
> class A {}
> ```
> 
> 1. Delete class A, create class B and use the same `typeId`
> 
> ```dart
> @HiveType(typeId: 1)
> class B {}
> ```

If you try to read from a box that previously written data with class A, the `openBox` operation will fail because it'll try to read data written using serializer (adapter) for class A but now tries to read with adapter created for class B. If both classes doesn't contains same fields in same order it'll fail.

**Comment by jack24254029** [comment]
> > Can `typeId` reused?
> > I can't find information on document.
> > For example:
> > 
> > 1. Create class A
> > 
> > ```dart
> > @HiveType(typeId: 1)
> > class A {}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 1. Delete class A, create class B and use the same `typeId`
> > 
> > ```dart
> > @HiveType(typeId: 1)
> > class B {}
> > ```
> 
> If you try to read from a box that previously written data with class A, the `openBox` operation will fail because it'll try to read data written using serializer (adapter) for class A but now tries to read with adapter created for class B. If both classes doesn't contains same fields in same order it'll fail.

So `HiveType#typeId`'s rules are same with `HiveField#id`.
Did I get that right?

**Comment by themisir** [comment]
> If the answers is YES, from my understand, HiveType#typeId's rules are same with HiveField#id.
Did I get that right?

For strict reasons we usually say the same rules applies for both. But if you don't open the box that contains data written by class A adapter, it should work fine. (Also consider that case for your exists user base).

**Comment by jack24254029** [comment]
> > If the answers is YES, from my understand, HiveType#typeId's rules are same with HiveField#id.
> > Did I get that right?
> 
> For strict reasons we usually say the same rules applies for both. But if you don't open the box that contains data written by class A adapter, it should work fine. (Also consider that case for your exists user base).

Thank you !

**Comment by UsamaKarim** [comment]
How do you get rid of the error of uninitialized variable?

#### Example
```dart
@HiveField(3, defaultValue: false)
 final bool isRead;
```
#### Error
```
The final variable 'isRead' must be initialized.
Try initializing the variable.
```

**Comment by themisir** [comment]
> How do you get rid of the error of uninitialized variable?

It looks like the error is from dart analyzer. You have to initialize final members of classes. In your case you probably have to initialize it from class constructor.

```dart
class Example {
  final bool isRead;

  Example({ required this.isRead }); // required because `isRead` is not nullable.
}
```
