### ISSUE TITLE
Using Hive.init() multiple times

### ISSUE THREAD

**Issue by GauteHaugen** [hivedb/hive#643]
**Question**
As mentioned in issues #594 and #595, there was an issue with calling `Hive.init(somePath);` multiple times. This was resolved by allowing it. But now the init method is printing warnings each time you try to init with the same path. Since I have multiple paths for my hive boxes depending on where they are used in my app, I need to use the init to make sure the path is correct before I try to open the box. Since there at the moment is no way for me to check the initialized homepath, I will in some cases call the init method on the same home path.

If the path forward for Hive is not to call init method multiple times on the same path, shouldn't there be a way for the developer to check the current path before trying to change it?

**Code sample**
```dart
// Current implementation in HiveImpl
class HiveImpl extends TypeRegistryImpl implements HiveInterface {
  // ...
  @visibleForTesting
  String? homePath;
  // ...
  @override
  void init(String path) {
    if (homePath == path) {
      print(
        'Hive instance has already been initialized. Please call Hive.init '
        'only once if possible.',
      );
    }
    homePath = path;
  }
  // ...
}


// Suggested implementation
class HiveImpl extends TypeRegistryImpl implements HiveInterface {
  // ...
  String? _homePath;
  String? get homePath => _homePath;
  @visibleForTesting
  set homePath (String newValue) => _homePath = newValue;
  // ...
  @override
  void init(String path) {
    if (homePath == path) {
      print(
        'Hive instance has already been initialized. Please call Hive.init '
        'only once if possible.',
      );
    }
    _homePath = path;
  }
  // ...
}
```

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: 2.0.5
 - Hive version: 2.0.4

**Comment by TheMisir** [comment]
So in short, do you want to check currently set `homePath` value?

**Comment by GauteHaugen** [comment]
yes, so I can do this:

````dart
if (Hive.homepath != 'some/path') {
  Hive.init('some/path');
}
```

**Comment by GauteHaugen** [comment]
Any updates on if this will be implemented?

**Comment by TheMisir** [comment]
@GauteHaugen already implemented.

You can call Hive.init multiple times after `hive: ^2.0.1`. I've replaced error throwing with just printing warning on console.

**Comment by GauteHaugen** [comment]
The reason I was asking, was not because it was throwing error. The reason is that my console is now full of spam because I try to change the homepath before opening a box to make sure I'm in the correct path, and it is usually the same homepath. If you are printing a warning to tell me to not init with the same homepath multiple times, shouldn't there be a way to check the current homepath to avoid the warning?

**Comment by TheMisir** [comment]
@GauteHaugen 

The reason we print out warning is because sometimes for some weird reasons that I don't know why, when you init hive multiple times it crashes data. I don't know why but it does. (Or maybe it doesn't but something really weird is happening).

You can check out mentioned comment here to understand what I'm talking about: https://github.com/hivedb/hive/issues/263#issuecomment-744689680

**Comment by GauteHaugen** [comment]
@TheMisir, wouldn't that make the request to have a way to check homepath before init more valid? If you are telling me that it crashes date if you init multiple times, would it make sense for me to check the homepath before calling init? Or just have init just return if the new path is equal to homepath?
