### ISSUE TITLE
BUG: Hive generator generates nullable HiveLists

### ISSUE THREAD

**Issue by vandir** [hivedb/hive#644]
Minimal working example:

```dart
import 'package:hive/hive.dart';

part 'person.g.dart';

@HiveType(typeId: 1)
class Person extends HiveObject {
  @HiveField(0)
  HiveList<Person> friends;

  Person(this.friends);
}
```

The (redacted) generated code is as follow:

```dart
.
.
.
class PersonAdapter extends TypeAdapter<Person> {
  @override
  final int typeId = 1;

  @override
  Person read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return Person(
      (fields[0] as HiveList)?.castHiveList(),
    );
  }
.
.
.
```
The (type) error is:
```
The argument type 'HiveList<Person>?' can't be assigned to the parameter type 'HiveList<Person>'
```

The line `(fields[0] as HiveList)?.castHiveList()` is wrong because is nullable but `friends` is not. Here the problem is the use of the `?.` operator over a non nullable expression (`(fields[0] as HiveList)`)

**Comment by vandir** [comment]
up

**Comment by vandir** [comment]
@TheMisir

**Comment by emme1444** [comment]
Would be nice to get this solved. Any updates?

As a work-around I modify the generated code from this:
```dart
(fields[0] as HiveList)?.castHiveList(),
```
to this:
```dart
(fields[0] as HiveList).castHiveList(),
```

Just ensuring this is an accepted way to work around the problem? Although, ideally I wouldn't want to modify the generated code. Obviously.

**Comment by Myl0g** [comment]
Seconded. Still experiencing this issue. I don't see why replacing `?.` with `.` wouldn't be a suitable workaround in the meantime.

**Comment by Myl0g** [comment]
After working with Hive for a few days I've had no trouble with replacing `?.` with `.` @emme1444 . Definitely a suitable workaround.

**Comment by TheMisir** [comment]
I'm a bit busy those days, so fixing this issue might take some time. If anybody wants to work on this issue PRs are appreciated (let me know if you need assistance) 😊

**Comment by Myl0g** [comment]
Got it, found the issue. I'll open a PR soon.
