### ISSUE TITLE
Error updating hive class

### ISSUE THREAD

**Issue by adrianrl99** [hivedb/hive#647]
When I try update a hive class, following [this](https://docs.hivedb.dev/#/custom-objects/generate_adapter?id=updating-a-class) rules, I get this error: Unhandled Exception: type 'Null' is not a subtype of type 'List' in type cast

![update class hivedb](https://user-images.githubusercontent.com/61700204/116554105-cc554d00-a8c8-11eb-97c5-28f3557ef81a.png)

**Version**
 - Platform:  Android
 - Flutter version: 2.0.1
 - Hive version: 2.0.2
 - hive_flutter: ^1.0.0
 - hive_generator: ^1.0.1
 -  build_runner: ^1.12.2

**Comment by TheMisir** [comment]
Try setting default value for added not-nullable properties.

```dart
@HiveField(6, defaultValue: const [])
List<String> notes;
```

**Comment by TheMisir** [comment]
> > Try setting default value for added not-nullable properties.
> > ```dart
> > @HiveField(6, defaultValue: const [])
> > List<String> notes;
> > ```
> 
> defaultValue can only be boolean
> The argument type 'List' can't be assigned to the parameter type 'bool'

You have to upgrade hive and hive_generator to latest version. It's a new feature.

**Comment by adrianrl99** [comment]
> > > Try setting default value for added not-nullable properties.
> > > ```dart
> > > @HiveField(6, defaultValue: const [])
> > > List<String> notes;
> > > ```
> > 
> > 
> > defaultValue can only be boolean
> > The argument type 'List' can't be assigned to the parameter type 'bool'
> 
> You have to upgrade hive and hive_generator to latest version. It's a new feature.

Its work, thanks.
