### ISSUE TITLE
Sample link not working

### ISSUE THREAD

**Issue by marcelgarus** [hivedb/hive#65]
**Steps to Reproduce**
When clicking on the sample link in [`hive/example`](https://github.com/hivedb/hive/tree/master/hive/example) (or the corresponding ["example" tab on the pub site](https://pub.dev/packages/hive#-example-tab-)), it's displaying a 404 error.

**Why is this happening?**
The reason it's not working is that the samples directory moved into a top-level repo in the hivedb organisation from https://github.com/hivedb/hive/tree/master/examples (not working) to https://github.com/hivedb/samples.

**Solution**
The link should be updated.

**Comment by leisim** [comment]
Thanks, I forgot that... Will be updated with the next release (in one or two days)

**Comment by leisim** [comment]
Fixed with `1.1.0-beta`.
