### ISSUE TITLE
Use json deserialization and serialization

### ISSUE THREAD

**Issue by dalton5** [hivedb/hive#659]
Hi,

I need to store some objects with hive. They are complex objects.

I wonder if I could reuse the json methods I use for my API calls and use Hive to store the json string.

And to retrieve my object I could retrieve the json string and apply the deserialization from the json string like I do when I receive the json from the api.

Is there some drawbacks and issues I could have?

Will it harm the performance?

**Comment by TheMisir** [comment]
I'm already using JSON serialization with hive and it doesn't makes any significant performance drawback. If you're not storing hundreds of items or huge models it should be fine.
