### ISSUE TITLE
Is Hive surpport transaction?

### ISSUE THREAD

**Issue by leedstyh** [hivedb/hive#66]

**Comment by leisim** [comment]
Not currently. What would you use transactions for?

If you want to write multiple entries with a single disk access,  you can use `putAll()`.

**Comment by leedstyh** [comment]
If `putAll()` fails, are all the kv pairs not written?

**Comment by leisim** [comment]
Yes exactly

**Comment by leedstyh** [comment]
Thanks @leisim

**Comment by leisim** [comment]
@benoitverstraete 

I do but it is not high on the priority list. The next update will improve performance and introduce `HiveObject`s, `ListView` and `MapView`. The update after that will contain queries. Then I plan to look at transactions...

**Comment by kaboc** [comment]
What if you need to do both `put()` and `delete()` in a single transaction?

e.g. ToDo app

* categoryA
    * task1
    * task2
* categoryB
    * task3

If you want to delete categoryB at the same time as task3 is moved to categoryA which makes categoryB empty, a series of update and removal operations is probably necessary. The feature of transaction seems useful in such a case.

**Comment by leisim** [comment]
> The feature of transaction seems useful in such a case.

I agree. It's still on my radar...
