### ISSUE TITLE
allowBackup="true" for hive database

### ISSUE THREAD

**Issue by sanjay23singh** [hivedb/hive#661]
Is it safe to use **allowBackup="true"** for automatically backup hive database.
Also, Hive docs says it uses AES-256 encryption, does it is applied to all hive data automatically or we have to do it manually?

**Comment by TheMisir** [comment]
> Also, Hive docs says it uses AES-256 encryption, does it is applied to all hive data automatically or we have to do it manually?

It only does encryption if you've requested it by providing `encryptionCipher` argument on `openBox` method.

**Comment by sanjay23singh** [comment]
> > Also, Hive docs says it uses AES-256 encryption, does it is applied to all hive data automatically or we have to do it manually?
> 
> It only does encryption if you've requested it by providing `encryptionCipher` argument on `openBox` method.
where should we store this key when we uninstall the app, for data recovery on next installation. 
and what about safety of **allowBackup="true"** ?

**Comment by TheMisir** [comment]
> where should we store this key when we uninstall the app, for data recovery on next installation.

I would suggest storing key in [flutter_secure_storage](https://pub.dev/packages/flutter_secure_storage).

> what about safety of allowBackup="true" ?

I'm not sure about that. I think our own apps allows backups and had not an issue about that.
