### ISSUE TITLE
flutter packages pub run build_runner build don't detect my hive type

### ISSUE THREAD

**Issue by thedarkknight197** [hivedb/hive#663]
Hello, I have create my model like:

```dart
import 'package:hive/hive.dart';
part 'user.g.dart';

@HiveType(typeId: 0)
class User extends HiveObject {
  @HiveField(1)
  String id;

  @HiveField(2)
  String name;
....
```

When I run: flutter packages pub run build_runner build 
in console i have this output and still not generate user.g.dart:

```
[INFO] Generating build script...
[INFO] Generating build script completed, took 469ms

[SEVERE] Nothing can be built, yet a build was requested.
[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 59ms

[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 360ms

[INFO] Running build...
[INFO] Running build completed, took 3ms

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 36ms

[INFO] Succeeded after 55ms with 0 outputs (0 actions)
```

I don't understand why not generate my user.g.dart file.

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: sdk: ">=2.12.0 <3.0.0"
 - Hive version: ^2.0.4
 - MacBook Pro M1

**Comment by TheMisir** [comment]
What's name of the file containing this model?

**Comment by thedarkknight197** [comment]
1) user.dart inside models folder
2) No, now I have added and it worked, why it is not write on documentation grr.

Now I have this problem on my generated class. In my user.dart I have this constructor:
`User({
    required String id,
    required this.name,
    required this.surname,
    required this.email,
    required this.password,
  }) {
    this._id = id;
  }`

I use this because my backend Node, with mongodb database create the id with name _id. So from my backend I receive this map:

`factory User.fromJson(Map<String, dynamic> json) {
    return User(
      id: json['_id'],
      name: json['name'],
      surname: json['surname'],
      email: json['email'],
      password: json['password'],
    );
  }`

The problem in the class generated is: 
`@override
  User read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return User(
      name: fields[1] as String,
      surname: fields[2] as String,
      email: fields[3] as String,
      password: fields[4] as String,
    ).._id = fields[0] as String;
  }`
The named parameter 'id' is required, but there's no corresponding argument.
How could I fix it?

**Comment by thedarkknight197** [comment]
> * What's name of the file containing this model?
> * Have you added `hive_generator` to list of dev_dependencies?

I have tried to fix like this:
' @override
  User read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return User(
      id: fields[0] as String,
      name: fields[1] as String,
      surname: fields[2] as String,
      email: fields[3] as String,
      password: fields[4] as String,
    ) /*.._id = fields[0] as String*/;
  }'

but I receive this error: 

Reloaded 0 libraries in 547ms.
[VERBOSE-2:shell.cc(242)] Dart Unhandled Exception: HiveError: Cannot write, unknown type: User. Did you forget to register an adapter?, stack trace: #0      BinaryWriterImpl.write (package:hive/src/binary/binary_writer_impl.dart:337:9)
#1      BinaryWriterImpl.writeFrame (package:hive/src/binary/binary_writer_impl.dart:281:9)
#2      StorageBackendVm.writeFrames.<anonymous closure> (package:hive/src/backend/vm/storage_backend_vm.dart:127:31)
#3      StorageBackendVm.writeFrames.<anonymous closure> (package:hive/src/backend/vm/storage_backend_vm.dart:123:28)
#4      ReadWriteSync.syncWrite.<anonymous closure> (package:hive/src/backend/vm/read_write_sync.dart:26:41)
#5      _RootZone.runUnary (dart:async/zone.dart:1612:54)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:152:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:704:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:733:32)
#9      Future._addListener.<anonymous clo<…>

When I try to register user on local db like: 

void AddUser(User user) async {
    var box = await Hive.openBox('userLogged');
    //TODO - add user to db
    box.add(user);
    return;
  }

**Comment by thedarkknight197** [comment]
> Hive.registerAdapter<User>(UserAdapter())

I don't understand about @JsonKey(name: '_id') I am new in Flutter.

Good for register Adapter on my main, I try it

**Comment by thedarkknight197** [comment]
With the new storage method I am not allowed to return an Future<User> in my FutureBuilder, it told me that it won't 
`======== Exception caught by widgets library =======================================================
The following _TypeError was thrown building FutureBuilder<User>(state: _FutureBuilderState<User>#ab8aa):
type 'User' is not a subtype of type 'Map<String, dynamic>'

The relevant error-causing widget was: 
  FutureBuilder<User> file:///Users/michele/Documents/MVB_DEV/Flutter/greentrip/lib/views/LoadingScreen.dart:21:13
When the exception was thrown, this was the stack: 
#0      new ProfileScreen (package:greentrip/views/ProfileScreen.dart:8:40)
#1      new LayoutController (package:greentrip/controllers/LayoutController.dart:24:15)
#2      new _LayoutViewState (package:greentrip/views/LayoutView.dart:10:43)
#3      LayoutView.createState (package:greentrip/views/LayoutView.dart:6:37)
#4      new StatefulElement (package:flutter/src/widgets/framework.dart:4584:24)
...
====================================================================================================`

On line 21:
`body: FutureBuilder(
        future: loadScreen(),
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.done) {
            print(snapshot.data);
            if (snapshot.data != null) {
              return LayoutView();
            }
          }`

but in console he print that in snapshot.data I have my User instance  
`flutter: Instance of 'User'`

**Comment by thedarkknight197** [comment]
I find the problem in my code.

Could you explain to me what is @JsonKey(name: '_id') annotation from json_serializable package to define custom name. please?

**Comment by TheMisir** [comment]
> Could you explain to me what is @jsonkey(name: '_id') annotation from json_serializable package to define custom name. please?

It simply uses '_id' instead of property name for (de)serializing json. Here's another example:

```dart
class Customer {
  @JsonKey(name: 'FullName')
  final String name;
}
```

The code generated by json_serializable will look for "FullName" key instead of "name" (also will use "FullName" for serializing data into Json). That's all I can say.

Reference: https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonKey/name.html

**Comment by thedarkknight197** [comment]
> > Could you explain to me what is @jsonkey(name: '_id') annotation from json_serializable package to define custom name. please?
> 
> It simply uses '_id' instead of property name for (de)serializing json. Here's another example:
> 
> ```dart
> class Customer {
>   @JsonKey(name: 'FullName')
>   final String name;
> }
> ```
> 
> The code generated by json_serializable will look for "FullName" key instead of "name" (also will use "FullName" for serializing data into Json). That's all I can say.
> 
> Reference: https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonKey/name.html

Thancks for your answer, I think I have understand what do you mean <3

**Comment by jbryanh** [comment]
> It's already there, on the homepage https://docs.hivedb.dev.

Just to follow-up: the documentation is spotty for anyone not experienced with this.  
1. You have to include all 4 dependencies listed above.
2. You need to include part 'user.g.dart'; in each model file. (using the above example).
3. Run flutter packages pub run build_runner build 
4. Step 2.5 of https://docs.hivedb.dev/#/custom-objects/generate_adapter would include the part, and step 1 should reinforce the multiple dependencies.  I'll post a documentation request.
