### ISSUE TITLE
Add a @Deprecated Box.listenable() field for people who forgot to import hive_flutter

### ISSUE THREAD

**Issue by thegoldgoat** [hivedb/hive#669]
**Is your feature request related to a problem? Please describe.**
It looks like a lot of people (see #598) forget to import 'hive_flutter' and they can't find `Box.listenable()`

**Describe the solution you'd like**
As suggested [here](https://github.com/hivedb/hive/issues/598#issuecomment-845127432), we could add a `@Deprecated` annotation with a `throw` body in the base hive package to notify developer they need to import 'hive_flutter' in order to use it

**Comment by mbaumgartenbr** [comment]
In addition i think it would be great if `hive_flutter` could export 'hive' by default so we don't have to import both packages.

And to avoid getting concurrent extensions on box the export on hive_flutter show `hide` the hive package `@Deprecated` extension.

**Comment by TheMisir** [comment]
As discussed in #598 this might cause some backwards compatibility and conflict issues. Instead we exported hive library from hive_flutter so users could import hive_flutter to use box extensions and hive itself.
