### ISSUE TITLE
HiveError: Box not found. 

### ISSUE THREAD

**Issue by mingyouzhu** [hivedb/hive#675]
**Steps to Reproduce**

HiveError: Box not found. did you forget to cell Hive.openBox()? 

**Code sample**
```
var box = Hive.box('test');

  String value = box.get('value');
  if(value == null){
    box.put('value','test data');
  }
```

**Version**
 - Platform: iOS, Android
 - Flutter version: [e.g. 2.0.3]
 - Hive version: [e.g. 2.0.4]

**Comment by havudk** [comment]
Same with me. How to use Hive without await?

**Comment by mingyouzhu** [comment]
Is my operation incorrect or the document is not updated？？？

<img width="837" alt="Screen Shot 2021-05-24 at 2 40 32 PM" src="https://user-images.githubusercontent.com/37821420/119307360-2e258e80-bc9e-11eb-94a0-4f54ff0c9366.png">

https://pub.dev/packages/hive

**Comment by mbaumgartenbr** [comment]
You should call `Hive.openBox('test')` at least once and then you are able to call `Hive.box('test')`.

**Comment by gaelthas** [comment]
> You may call box('testBox') to get the singleton instance of an already opened box.
That means we should call openBox before box.
