### ISSUE TITLE
Testing with Hive

### ISSUE THREAD

**Issue by Offtree** [hivedb/hive#68]
**Question**
As far as I can tell there's no documented way of unit integration testing with Hive.
Could we consider adding a test suite to one of the examples?

**Code sample**
N/A

**Version**
 - Hive version: 1.0.0

**Comment by leisim** [comment]
I agree, there should be an interface and documentation for integration testing...

**Comment by GMC254** [comment]
> **Question**
> As far as I can tell there's no documented way of unit integration testing with Hive.
> Could we consider adding a test suite to one of the examples?
> 
> **Code sample**
> N/A
> 
> **Version**
> 
> * Hive version: 1.0.0

Thank you for bringing this up. Could not run unit tests too. I assumed that it's because Hive uses path provider in initiation which would require platform specific code.

**Comment by leisim** [comment]
> I assumed that it's because Hive uses path provider in initiation which would require platform specific code.

Hive does not use `path_provider` and has no platform code. What error are you seeing?

**Comment by GMC254** [comment]
> > I assumed that it's because Hive uses path provider in initiation which would require platform specific code.
> 
> Hive does not use `path_provider` and has no platform code. What error are you seeing?

What I meant was that hive requires one to run Hive.init(path), the path part (not Hive, of course) requires that i use path provider provide the path which uses some platform specific code in its tests. All tests i'm currently running fail and I thought that was the cause. I look forward to the testing documentation. Thanks for this great package.

**Comment by leisim** [comment]
All the unit tests for Hive itself run successfully. Maybe you want to take a look at them.

What error message are you getting?

@Offtree Hive has abstract classes for all its public APIs. You can use them to create mocks for your unit tests. I will create an example which shows how to do it...

**Comment by Offtree** [comment]
> @Offtree Hive has abstract classes for all its public APIs. You can use them to create mocks for your unit tests. I will create an example which shows how to do it...

I'll give that a shot and see how it works out what I get some time

**Comment by leisim** [comment]
If you need something that is currently missing (like an exposed field), just let me know...

**Comment by GMC254** [comment]
Sorry, testing works great. It was just an oversight on my end as all values returned were null. Again thanks for the package.
