### ISSUE TITLE
Type Adapter for external Enums

### ISSUE THREAD

**Issue by obitodarky** [hivedb/hive#681]
**Question**
I'm writing a TypeAdapter manually for an object from an External Library. This library is using an enum as one of the fields in that object. I'm getting a similar error as stated in #564 but the solution over there seems to be useful only for generated type adapters. How do I work around with an Object and an Enum from an external library?

**Code sample**
```dart
//enum from external library
enum Status{
 connected,
 disconnected,
}

//my TypeAdapter
class FooAdapter extends TypeAdapter<ObjectFromLibrary>{
  @override
  final typeId = 1;

  @override
  ObjectFromLibrary read(BinaryReader reader) {
    return ObjectFromLibrary(
      reader.read() as String,
      reader.read() as Status
    );
  }

  @override
  void write(BinaryWriter writer, ObjectFromLibrary obj) {
    writer.write(obj.value);
    writer.write(obj.status);
  }
}
```

This obviously is giving me the following error: `unknown type: Status. Did you forget to register an adapter?`
Is there something I can do to make this work?

**Version**
 - Platform: Android
 - Flutter version: 2.0.2
 - Hive version: 2.0.4

**Comment by TheMisir** [comment]
You can store enums as int.

```dart
  @override
  ObjectFromLibrary read(BinaryReader reader) {
    return ObjectFromLibrary(
      reader.read() as String,
      Status.values[reader.read() as int]
    );
  }

  @override
  void write(BinaryWriter writer, ObjectFromLibrary obj) {
    writer.write(obj.value);
    writer.write(obj.status.index);
  }
```

**Comment by obitodarky** [comment]
That worked, thanks a lot!
