### ISSUE TITLE
Is it correct practice to store password/token with hive?

### ISSUE THREAD

**Issue by BSiddharth** [hivedb/hive#686]

**Comment by TheMisir** [comment]
It depends..

But generally would suggest using [flutter_secure_storage](https://pub.dev/packages/flutter_secure_storage).

**Comment by BSiddharth** [comment]
I see I was thinking of using the same, any particular reason ? hive storage is also encrypted right. @TheMisir

**Comment by TheMisir** [comment]
Hive does supports encryption but you'll need to store encryption key to somewhere else. Secure storage uses operation system APIs to store data which usually uses dedicated hardware chips that I think secure than using software based solution.

**Comment by BSiddharth** [comment]
Understood Thank you
