### ISSUE TITLE
[hive_flutter] Null-safety support

### ISSUE THREAD

**Issue by fabricio-godoi** [hivedb/hive#688]
**Question**
Greetings,

Will [hive_flutter package](https://pub.dev/packages/hive_flutter) be updated with Null-safety in pub.dev? I check that the code is ready to support it, but the pub.dev still outdated.

Thank you!

**Comment by hhstore** [comment]
+1

**Comment by mbaumgartenbr** [comment]
Check out #698.

The null safety score is failing because of an issue with `dart:indexed_db`.

**Comment by hhstore** [comment]
> Check out #698.
> 
> The null safety score is failing because of an issue with `dart:indexed_db`.



- Now that this `pr` has been merged, when can it be published to `pub.dev`? 
- Does anyone handle this?

**Comment by hhstore** [comment]
- https://pub.dev/packages/hive_flutter/versions
- `hive_flutter: ^1.1.0`
- From the pub.dev `version  list`, it looks like it is already `null safety`, but it is `not marked as Null safety`. 
- This is very strange. But it seems to be working fine. Thank you. @TheMisir 


![image](https://user-images.githubusercontent.com/3252130/122700990-e6832a00-d27e-11eb-9563-55c937a34b98.png)

**Comment by mbaumgartenbr** [comment]
Hi!

When I was working on #698 I ran pana analyzer locally, this issue is due to flutter's incompatibility with dart:indexed_db used by hive on web.

Take a look at: flutter/flutter/issues/44937

As soon as you take out the dependency on flutter from pubspec.yaml the error goes away.

**Comment by m8811163008** [comment]
don't support null safety:

 - package:hive
 - package:crypto
 - package:convert
