### ISSUE TITLE
[hive_flutter] Flutter adapters aren't exported

### ISSUE THREAD

**Issue by Reprevise** [hivedb/hive#691]
hive_flutter doesn't export the type adapters `Color` and `TimeOfDay` so nobody can access them.

**Comment by TheMisir** [comment]
There's actually a `Color` and `TimeOfDay` adapters are available on **hive_flutter** package here https://github.com/hivedb/hive/tree/master/hive_flutter/lib/src/adapters. But they're not registered.

**Comment by Reprevise** [comment]
> There's actually a `Color` and `TimeOfDay` adapters are available on **hive_flutter** package here https://github.com/hivedb/hive/tree/master/hive_flutter/lib/src/adapters. But they're not registered.

Yes I understand that however they cannot be accessed externally by my app because they're not exported therefore I cannot register them.
