### ISSUE TITLE
BoxEvent should distinguish event types, such as inserts, updates, deletes?

### ISSUE THREAD

**Issue by Silentdoer** [hivedb/hive#692]
BoxEvent should distinguish event types, such as inserts, updates, deletes?
if event is update event, callable should support old and new value args?

**Comment by TheMisir** [comment]
It's currently not possible without breaking existing API. But you can listen to stream from `Hive.box('  ').watch()` which broadcasts box events (which contains changed entry key, value and whether or not the the entry is deleted).
