### ISSUE TITLE
Create a GitHub Release / Tag for v2.0.4

### ISSUE THREAD

**Issue by b3arco** [hivedb/hive#695]
So far, every version has gotten its own [release](https://github.com/hivedb/hive/releases) and [tag](https://github.com/hivedb/hive/tags).

Please do the same for version 2.0.4.

The version was bumped to 2.0.4 on April 19 in commit [49f9561100c1cec80c6301fc51e03da2795f72ca](https://github.com/hivedb/hive/commit/49f9561100c1cec80c6301fc51e03da2795f72ca)

**Comment by TheMisir** [comment]
https://github.com/hivedb/hive/releases/tag/v2.0.4

Done!
