### ISSUE TITLE
Add a method to close a single box

### ISSUE THREAD

**Issue by Wouter12** [hivedb/hive#696]
**Is your feature request related to a problem? Please describe.**
If a user logs out of the application, i want to close all the boxes he opened, however there are some boxes that need to remain open (ex box with registered users).

**Describe the solution you'd like**
Have the possibility to call 

```
Hive.close(name);
```

**Describe alternatives you've considered**

Store all the opened boxes in some type of registry in memory, and call close on each of them.

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: [e.g. 2.2.0]
 - Hive version: [e.g. 2.0.4]

**Comment by mbaumgartenbr** [comment]
Hi!

You can do it yourself, each box has it's own `.close()` method.
