### ISSUE TITLE
How to create a Streaks App 🐎 

### ISSUE THREAD

**Issue by madd-project** [hivedb/hive#699]
# What I have Made Till Now
Hey, ❤️ I want to Create a Hive-based Application, real-ated to Streaks .
I have made 80% of the App successfully. Thanks to the Hive and all the Opensource Packages.
I want to seek help in this,

I have Created a Partial Streak app, and Initially, it the UI will be shown like this to the user, 
![1623490116251015](https://user-images.githubusercontent.com/64954854/122638298-fe3ca000-d110-11eb-827c-c0fdbf898f22.png)

then if we press the leading button, 💡 it will light up and just be removed from my `streakBox` and will be added to the `completedStreakBox` and to and fro just happens to when we click the leading button of this too...
![1624095678714](https://user-images.githubusercontent.com/64954854/122638490-f6313000-d111-11eb-9bd6-4002d0b264dc.png)
This is how Far I have Made it.

# What needs to be Done
The Question Growing in the Head is,🌱
I want to check if a certain streak is not performed by the user, I will streakBox.deleted() that and then it will push the completed ones to the incompleted ones with the +1 increments in the Count. 

# For Resetting. What Code I am Using?
In the Init-state,
```

resetStreakOnOpening(context) {
  if (today's Date of todayDate box is null then) {
    DateTime now = DateTime.now();
    add in the today's date in the box
    (Here Goes the Suggestion of the HIVE Team 💡 )

  } else if (today's date in the box is not null then){
    
    if (today's date is equal to today's date inside the HiveBox then) {
      print("nothing to do");
    } else {
     (Here Goes the Suggestion of the HIVE Team 💡 )
  }
}
```
# Model, I am Using
And the Same Model goes with the `completedStreakBox`, this is the Working Model of the `streakBox`.
```
//import 'package:flutter/material.dart';
import 'package:hive/hive.dart'; //Local Database, Easy....

part 'streak_model.g.dart';

@HiveType(typeId: 1)
class StreakModel extends HiveObject {
  @HiveField(0)
  String streakName;
  @HiveField(1)
  int streakCount;
  @HiveField(2)
  String streakEmoji;
  @HiveField(3)
  String streakRemainder;
  @HiveField(4)
  int streakDays;
  @HiveField(5)
  bool isCompleted;

  StreakModel(
      {this.streakName,
      this.streakCount,
      this.streakEmoji,
      this.streakRemainder,
      this.streakDays,
      this.isCompleted});

}

``` 

# Question
The question is simple. 🍰 
How to Take up the incompleted ones streaks and clear them and completed ones will be incompleted the next day, with the +1 increments.

The Question was simpler as the seed. the Above Lines were just to better explain and support the question.
Thanks for all the help that Hive provides to the young developers,
Thanks for always being there for my question.
Thanks for my productivity and,
Thanks for everything that I cannot count.
 
**Version**
- [x] Android
- [x] Flutter version: 2.2.1
- [x]  Hive version: 2.0.4

**Comment by TheMisir** [comment]
> How to Take up the incompleted ones streaks and clear them and completed ones will be incompleted the next day, with the +1 increments.

Can you please simplify this question a bit, I couldn't get exactly what you need? Maybe you can provide a small example and the code which doesn't works.

**Comment by madd-project** [comment]
Heype, @TheMisir How are you.
I am great.
Sorry, for the un-understandable question I asked 🙏🏼 ..
Before Simplifying I just want you to read the above Chapters above the Question Tag.
like,

- [ ] What I have Made Till Now
- [ ] Models
- [ ] What needs to be Done
- [ ] For Resetting. What Code I am Using?

I was trying to ask, with the respect to all the data above, 
I want to create up the streak App, 
Here I Got the Two Boxes, StreakBox and CompletedStreakBox, 
with the Model Above mention (model is the same as the completedStreakBox and StreakBox the difference is just the names).
as you are seeing in this one Image.
![image](https://user-images.githubusercontent.com/64954854/122641840-5bdae780-d125-11eb-913b-ef1bd4d81445.png)


Now with the Buttons Present in the (leading Check Button)
![Uploading 1623490116251015.png…]()

I am deleting the object from here and adding the object to completedStreakBox...
with .add() and .delete(index) property.

You can really understand the whole from the _What I Have Made Till Now chapter_.

As there is no direct-looking code I could provide, and even the minimal will look so maximal, thus, I am trying to make it more simple with our own languages.

Now Next day, I want to reset the, CompletedStreakBox and Re-establish the Items to the StreakBox with incrementing +1 to the count of the Object(You can refer _For Resetting. What Code I am Using?_ and also the _Model_ )

And At last I want to Remove the Left up things which user not touched, i.e if user has not continued a streak let's say for more than One, the StreakBox will delete the Item. 

I hope it is understandable now, 
I usually shivers when I gets the opportuinity to make things understandable.
It's my error, I just need a debug, You just smile @TheMisir  😄

**Comment by TheMisir** [comment]
I think this code will comply with your requirements:

```dart
final completedStreaksBox = Hive.box('completed_streaks');
final streaksBox = Hive.box('streaks');

for (final key in completedStreaksBox.keys.toList()) { // Loop over completed streaks
  final streak = completedStreaksBox.get(key);
  if (streak.isCompleted) {
    streak.streakCount++;
    streak.isCompleted = false;
    completedStreaksBox.remove(key);
    streaksBox(streak);
  }
}
```

**Comment by madd-project** [comment]
Hey @TheMisir It was not Working a bit, That was a bit weird for me, can you see these little 50 lines below in it.


- In the completedStreakBox related File, Look Up the Code of Line [113-120](https://github.com/madd-project/toodolee/blob/d88c23a9841dd74aa072f8c18bfc7b63c6d94e39/lib/uis/Streak/streakCompletedUi.dart#L113 ) and line [153-177](https://github.com/madd-project/toodolee/blob/d88c23a9841dd74aa072f8c18bfc7b63c6d94e39/lib/uis/Streak/streakCompletedUi.dart#L153) of the **streakCompletedUi.dart**
- In the StreakBox related File, can you check the line, [114-121](https://github.com/madd-project/toodolee/blob/d88c23a9841dd74aa072f8c18bfc7b63c6d94e39/lib/uis/Streak/streakListUi.dart#L114) and [490-515](https://github.com/madd-project/toodolee/blob/d88c23a9841dd74aa072f8c18bfc7b63c6d94e39/lib/uis/Streak/streakListUi.dart#L490) of the **streakListUi.dart**
- And this is the Code of the Processes.dart,

```
import 'package:date_format/date_format.dart';
import 'package:hive/hive.dart';
import 'package:jiffy/jiffy.dart';
import 'package:toodo/main.dart';
import 'package:toodo/uis/Streak/streakCompletedUi.dart';
import 'package:toodo/uis/addTodoBottomSheet.dart';


resetStreakMidNight(context) {
  if (settingsBox.get("todayDate") == null ||
      settingsBox.get("monthFirstDay") == null ||
      settingsBox.get("nextDay") == null) {
    DateTime now = DateTime.now();

    var year = now.year;
    var month = now.month;
    var day = now.day;

    var nextDayDate = Jiffy()
        .add(duration: Duration(days: 1))
        .yMMMMd
        .replaceAll(",", "")
        .split(" ");
    print(nextDayDate);

    var endOfMonthDaysRemaining =
        Jiffy().endOf(Units.MONTH).fromNow().split(" ");
    var checkWhentheMonthwillEnd = Jiffy().add(
        duration: Duration(
            days: endOfMonthDaysRemaining[1] == "a"
                ? 30
                : int.parse(endOfMonthDaysRemaining[1])));
    print(endOfMonthDaysRemaining[1]);
    print(checkWhentheMonthwillEnd.yMMMMd);
    var nextMonthYear = Jiffy(checkWhentheMonthwillEnd, "MMM dd yy").year;
    var nextMonthMonth = Jiffy(checkWhentheMonthwillEnd, "MMM dd yy").month;
    var nextMonthDay = Jiffy(checkWhentheMonthwillEnd, "MMM dd yy").date;

    print(nextMonthMonth);
    print(nextMonthDay);
    print(nextMonthYear);
    settingsBox.put("todayDate", [year, month, day]);
    settingsBox.put("nextDayDate", nextDayDate[1]);
    settingsBox
        .put("monthFirstDay", [nextMonthYear, nextMonthMonth, nextMonthDay]);

    print("everything is reset-ed");
  } else {
    DateTime now = DateTime.now();

    var year = now.year;
    var month = now.month;
    var day = now.day;
    var endOfMonthDaysRemaining =
        Jiffy().endOf(Units.MONTH).fromNow().split(" ");
    var checkWhentheMonthwillEnd = Jiffy().add(
        duration: Duration(
            days: endOfMonthDaysRemaining[1] == "a"
                ? 30
                : int.parse(endOfMonthDaysRemaining[1])));
    print(endOfMonthDaysRemaining[1]);
    print(checkWhentheMonthwillEnd.yMMMMd);
    var nextMonthYear = Jiffy(checkWhentheMonthwillEnd, "MMM dd yy").year;
    var nextMonthMonth = Jiffy(checkWhentheMonthwillEnd, "MMM dd yy").month;
    var nextMonthDay = Jiffy(checkWhentheMonthwillEnd, "MMM dd yy").date;
    if ((year == settingsBox.get("todayDate")[0] &&
            month == settingsBox.get("todayDate")[1] &&
            day == settingsBox.get("todayDate")[2]) ||
        (nextMonthYear == settingsBox.get("monthFirstDay")[0] &&
            nextMonthMonth == settingsBox.get("monthFirstDay")[0] &&
            nextMonthDay == settingsBox.get("monthFirstDay")[2])) {
      print("nothing to do");
    } else if (day == settingsBox.get("nextDay")) {

     (Here TheMisir Gives Suggestion)
      print("everything is reset-ed");
      settingsBox.put("todayDate", [year, month, day]);
      settingsBox
          .put("monthFirstDay", [nextMonthYear, nextMonthMonth, nextMonthDay]);
    } else if (((year != settingsBox.get("todayDate")[0] &&
                month != settingsBox.get("todayDate")[1] &&
                day != settingsBox.get("todayDate")[2]) ||
            (nextMonthYear != settingsBox.get("monthFirstDay")[0] &&
                nextMonthMonth != settingsBox.get("monthFirstDay")[0] &&
                nextMonthDay != settingsBox.get("monthFirstDay")[2])) ||
               settingsBox.get("nextDayDate") != day) {
  (Here TheMisir Gives Suggestion,)
  (Delete the Streaks that User has not Completed, and Completed Streaks will be Made it's path to the StreakBox with the count++)
    }
  }
}
```

I am so sorry, If I am just troubling you, I have no place where I could ask HIVE based Questions , nor StackOverFlow, nor Gooogle Groups,  
The Hive Issues is the only Place, where I could ask Hive Based questions. 
Thanks a lot, 
If this Software works, That's my commitment, I will be funding Hive, Most Beautifully. Amen

**Comment by madd-project** [comment]
Okay, Wait for a bit, @TheMisir, 
it is working great, 

```
 for (final key in streakBox.keys.toList()) {
// Loop over completed streaks
                      final streak = streakBox.get(key);
                      if (streak.isCompleted) {
                        streak.streakCount++;
                        streak.isCompleted = false;
                        streak.save();
                        // completedStreakBox.delete(key);
                        // streakBox.add(streak);
                      }
                    }

```

let me implement it, I will give you stats, thanks brother, I love your contribution, You are better in terms of love for passion than any one living now.

**Comment by TheMisir** [comment]
Thanks for your lovely words, and sorry for my late responses. Unfortunately I'm a bit busy for last few months and unable to spend too much time on open source.

> How to Remove those who were incompleted, like one who is streak.isCompleted = false;

```dart
 for (final key in streakBox.keys.toList()) {
  // Loop over completed streaks
  final streak = streakBox.get(key);
  if (streak.isCompleted) {
    streak.streakCount++;
    streak.isCompleted = false;
    streak.save();
    // completedStreakBox.delete(key);
    // streakBox.add(streak);
  } else {
    streakBox.remove(key);
  }
}
```

You can remove item by calling `streakBox.remove(key);`.

**Comment by madd-project** [comment]
@TheMisir I won the Race, I am Now the Late Guy to Respond, (no Latestestest  😄 )
Thank you for guiding me till the end, All the Parts are working beautifully I will surely show you the app, As it will build. Amen.

and how it can shape up the humanity as to how @fonibo is shaping in specific ways. Beautifully from you and yours, @rafaelsetragni, @mbaumgartenbr, God, and every package that was ever made so simply. just helped me create the App, in the most beautiful way. 

You are the Warrior.

**Comment by madd-project** [comment]
I also Wanted to Showcase a code, that Matheus Baumgarten has shown,
and which is also working perfectionally. 

```
for (final key in streakBox.keys.toList()) {
        var streak = streakBox.get(key);

        if (streak.isCompleted) {
          streak.isCompleted = false;
          streakBox.put(key, streak);
        } else {
          streakBox.delete(key);
        }
      }
```
