### ISSUE TITLE
how to watch for nested objects inside hive 

### ISSUE THREAD

**Issue by davidAg9** [hivedb/hive#702]
**Question**
can I watch for deeply nested objects in a hive data base
**Code sample**
```
class Post {
String id ;
List<Category> categories;
}

class Catergory{
User user;
String title;
String msg;

}
// can I do something like this with hive ....or there is another to person a stream listener and filter out the part of the object I was to listen to 


final subscribedate = hivebox.get(post.id).watch().where(filterstring:categories.title =="Sports");
```

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: 2.2.2
 - Hive version: 2.0.4

**Comment by TheMisir** [comment]
The feature is not supported in hive. You have to provide your own state management solution for that.
