### ISSUE TITLE
The same instance of an HiveObject cannot be stored in two different boxes.

### ISSUE THREAD

**Issue by aifrosals** [hivedb/hive#703]
**Steps to Reproduce**
I want to update the user data in the hive box, so whenever I run the below function, at first call it runs fine but on next calls it gives me this error The same instance of an HiveObject cannot be stored in two different boxes.

**Code sample**
```
var box = await Hive.openBox<User>(HiveConstants.USER_BOX_NAME);
  await box.put(HiveConstants.USER_Model,Provider.of<AuthProvider>(Values.navigatorKey.currentContext!,listen: false).user!);
  box.close();
```

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: 2.2.1
 - Hive version: 2.0.4

**Comment by TheMisir** [comment]
Because HiveObject is linked to boxes to track changes and makes it possible to call .save(). So Hive only supports linking HiveObject to only a single box. If you need to save same object on multiple boxes, you have to remove `extends HiveObject` part.

**Comment by aifrosals** [comment]
I want to update the object in the same hive box, the USER_BOX_NAME is a constant should not it open the same box created before?

**Comment by aifrosals** [comment]
Why it is creating a different box?

**Comment by TheMisir** [comment]
Hey @aifrosals 

If you don't need features described [here](https://docs.hivedb.dev/#/custom-objects/hive_object) you can remove `HiveObject` from your model and it should work as expected.
