### ISSUE TITLE
Suggestion for performance?

### ISSUE THREAD

**Issue by MilesAdamson** [hivedb/hive#713]
**Question**
Problem: when logging in to the app for the first time, thousands of objects are loaded from the server and each are cached with hive. Writing them all at once makes the UI freeze up (for as long as 10 seconds), even as `async` code in a service outside the UI. 

The code to write the data is simple but ends up calling `box.put` over 25,000 times in some circumstances. The database has over 10,000 locations and each are cached individually (but they are fetched as a group). Each also has a timestamp for when it was last fetched. 

**Code sample**
```dart
  void cacheResponse(T response) {
    box.put(_queryKey(response.cacheKey), response.toJson());
    _setQueryLastUpdated(response);
    _addCachedId(response.cacheKey);
  }

  void _setQueryLastUpdated(T response) {
    box.put(_queryDateKey(response.cacheKey),
        DateTime.now().toUtc().toIso8601String());
  }

  void _addCachedId(String id) {
    Set<String> allIds = _cachedIds();
    allIds.add(id);
    box.put(_idListKey, allIds.join(","));
  }
```

If I simply comment out the contents of `cacheResponse`, the app runs super fast again. So I've got some questions about how I could design this better and use Hive in a more performant way.

- Would it be better to cache entire responses as 1 key? I have been caching each object within the response so far.
- Would it be better to run `cacheResponse` in a different isolate?

**Version**
 - Platform: iOS + Android
 - Flutter 2.2.0
 - hive: ^2.0.4

**Comment by MilesAdamson** [comment]
It runs about 50 times faster with this, but I'd still be curious to see what you guys suggest in general

```
  void cacheResponse(List<T> response) {
    final cachedAt = DateTime.now().toUtc().toIso8601String();
    Set<String> allIds = _cachedIds();
    allIds.addAll(response.map((e) => e.cacheKey));

    box.putAll(
      Map.fromEntries([
        ...response.map((t) => MapEntry(_queryDateKey(t.cacheKey), cachedAt)),
        ...response.map((t) => MapEntry(_queryKey(t.cacheKey), t.toJson())),
        MapEntry(_idListKey, allIds.join(",")),
      ]),
    );
  }
```

**Comment by modeckrus** [comment]
hello u can use hive in isolate(it's require intitiate and use hive only in this new isolate), but it's solve ur problem
