### ISSUE TITLE
Unhandled Exception: HiveError: String keys need to be ASCII Strings with a max length of 255

### ISSUE THREAD

**Issue by spacekestrel** [hivedb/hive#717]
I am trying to put key-value pair with key being cyrillic letters and hive give me - 
```
Unhandled Exception: HiveError: String keys need to be ASCII Strings with a max length of 255
```
error.

**Comment by UnicornsOnLSD** [comment]
ASCII only supports English characters, so cyrillic characters can't be encoded in ASCII.

**Comment by spacekestrel** [comment]
Yea, already figured it out. Thanks.

**Comment by kholyphoenix0** [comment]
So the only language on the planet is English?

**Comment by UnicornsOnLSD** [comment]
I agree that it's disappointing that ASCII text is used. In theory, Hive could switch to UTF-8 without breaking current databases, although I don't know if they're doing anything that assumes that 1 character = 1 byte.

**Comment by kholyphoenix0** [comment]
> I agree that it's disappointing that ASCII text is used. In theory, Hive could switch to UTF-8 without breaking current databases, although I don't know if they're doing anything that assumes that 1 character = 1 byte (edit: maybe the 255 length limit means that Hive expects the key to be 8*255 bits at most?).
> 
> Also, this is only the key, you can still store unicode characters in the actual content.

Is there any way to use special characters then?

**Comment by UnicornsOnLSD** [comment]
Not in the key, no. You can store strings that use Unicode characters in the value though. IMO, you probably shouldn't be using non-ASCII in the key anyway
