### ISSUE TITLE
Hive Box Not Found on same line where a Box is opened

### ISSUE THREAD

**Issue by kulny** [hivedb/hive#719]
I am trying to implement Hive to store some objects. I am consistently running into an error where Hive calls a box not found error on the very line I am calling to open the box. I have looked into the issue, and while nothing seems to specifically align, I wonder if it is possibly caused by trying to use Lists in my classes, and how I am interacting with them using Hive. 

This is a basic function I am using to ensure the box I am using is open before interacting with it later on.
```
  Future<Box<dynamic>> ensureOpenBox() async {
    var b = Hive.isBoxOpen(testingDB)
        ? Hive.box(testingDB)
        : await Hive.openBox(testingDB); // here is where the error is flagged
    return b;
  }
```

Here is the class I am trying to hold in the Hive box.
```
...
  @HiveField(0)
  final EntryType entryType;
  @HiveField(1)
  final Id id;
  @HiveField(2)
  String name;
  @HiveField(3)
  String desc;
  @HiveField(4)
  List<String> images;
  @HiveField(5)
  late HiveList aliases;
  @HiveField(6)
  List<GroupField> groups;
  @HiveField(7)
  List<CustomFieldData> fields = [];
  @HiveField(8)
  late HiveList events;
...
```

![image](https://user-images.githubusercontent.com/27989807/125315869-89224c00-e305-11eb-8ae9-49dcbb8d4324.png)

I had a similar problem with another class I am using Hive with that seemed to be experiencing the exact same issue. I rewrote that class without using Lists and it seems to have fixed the error, at least so far as my testing has gone. 

Can anyone explain exactly why this is happening, and if there are any ways around it?

 - Platform: Windows
 - Flutter version: 2.3.0-24.0.pre
 - Hive version: 2.0.4

**Comment by Jictyvoo** [comment]
Make sure you have called
```dart
  await Hive.initFlutter('db_folder');
```

or Hive.init if you are not using Flutter

**Comment by kulny** [comment]
That was not the issue. I called `await Hive.initFlutter();` at the beginning of main before any other Hive operations. I cannot test whether I am correct or not because of another issue I am having with Hive, but I believe my issue may have been with how I was calling a variable from Hive which gave me an unexpected String value. 

For now, I am closing this, though I will see about re-opening it if it turns out the issue has not been solved.

**Comment by kulny** [comment]
Upon further inspection, the issue really was as simple as attempting to open a box that had not yet been opened. As part of my class, I had set a couple of HiveLists to be initialized by Hive (not knowing where to best initialize them otherwise) at the instantiation of the class. This initialization did not have a Hive.openBox call, but rather a .box call, which led to the error.
