### ISSUE TITLE
Need update analyzer in hive_generator

### ISSUE THREAD

**Issue by nikitadol** [hivedb/hive#725]
```yaml
  json_serializable: ^5.0.0
  hive_generator: ^1.1.0
```

```log
Because no versions of hive_generator match >1.1.0 <2.0.0 and hive_generator 1.1.0 depends on analyzer ^1.0.0, hive_generator ^1.1.0 requires analyzer ^1.0.0.
And because json_serializable >=5.0.0 depends on analyzer ^2.0.0, hive_generator ^1.1.0 is incompatible with json_serializable >=5.0.0.
So, because rm_backend depends on both json_serializable ^5.0.0 and hive_generator ^1.1.0, version solving failed.
pub get failed (1; So, because rm_backend depends on both json_serializable ^5.0.0 and hive_generator ^1.1.0, version solving failed.)
```

**Comment by definev** [comment]
I faced with the same problem.

**Comment by flukejones** [comment]
Temporary fix is :
```
dev_dependencies:
  analyzer: ^1.7.2
```

but yeah, update required soon.

**Comment by dened** [comment]
What's about this issue? Many packages have moved to analyzer 2.0.0.

**Comment by RicardoRB** [comment]
@hivedb Would be great to update it

**Comment by RicardoRB** [comment]
PR created https://github.com/hivedb/hive/pull/765

**Comment by roubachof** [comment]
@zs-dima  is right, generator doesn't work starting with json_serializable see #795

**Comment by Silfalion** [comment]
Would like a solution for this too please

**Comment by zs-dima** [comment]
> Would like a solution for this too please

The best solution I found for now - to use SQLite/Drift instead of discontinued Hive.
It is reliable and has the same performance in case of load data in memory, plus it support complex queries.

**Comment by Silfalion** [comment]
> > Would like a solution for this too please
> 
> The best solution I found for now - to use SQLite/Drift instead of discontinued Hive. It is reliable and has the same performance in case of load data in memory, plus it support complex queries.

I see. Thanks for the tip. Considered ObjectBox as well but it faces the same problem with freezed.

**Comment by zs-dima** [comment]
> > > Would like a solution for this too please
> > 
> > The best solution I found for now - to use SQLite/Drift instead of discontinued Hive. It is reliable and has the same performance in case of load data in memory, plus it support complex queries.
> 
> I see. Thanks for the tip. Considered ObjectBox as well but it faces the same problem with freezed.

OpenBox has no FlutterWeb support and is not so reliable as SQLite, so I can see no advantages to use it.

**Comment by Silfalion** [comment]
> > > > Would like a solution for this too please
> > > 
> > > 
> > > The best solution I found for now - to use SQLite/Drift instead of discontinued Hive. It is reliable and has the same performance in case of load data in memory, plus it support complex queries.
> > 
> > 
> > I see. Thanks for the tip. Considered ObjectBox as well but it faces the same problem with freezed.
> 
> OpenBox has no FlutterWeb support and is not so reliable as SQLite, so I can see no advantages to use it.

I see. Thank you.
