### ISSUE TITLE
How I can remove multiple value on Box ?? or Can My Box update automatically its value whenever I make changes to my local List ?? 

### ISSUE THREAD

**Issue by tonyhart7** [hivedb/hive#738]
How I can delete value of List in flutter Hive ??

~~~
example list = [
record(
    name: 'john',
    class: 'Coffee',
  ),
record(
    name: 'sarah',
    class: 'Coffee',
  ),
record(
    name: 'rala',
    class: 'Water',
  ),
];
~~~

as you can see I have multiple value and want to delete all record that contains value of coffee but Hive dnt have such as function that can do that

edit: Iam using Box.add function to add value using auto increment key Iam thingking about delete all the box in hivedb and putAll updated list in var to Hive but iam open to other more effective way or advice

Platform: iOS, Android, Mac, Windows, Linux, Web
Flutter version: 2.2.3
Hive version: **2.0.4**

thanks for those who read this

**Comment by tonyhart7** [comment]
@TheMisir

**Comment by TheMisir** [comment]
Hive stores data in memory, so you can manipulate data using for loops. It doesn't have sql like syntax because it doesn't need that, doing multiple things isn't as costly as like in other databases.

**Comment by tonyhart7** [comment]
I see, thanks for clarification I will do that
