### ISSUE TITLE
Issue while opening a box

### ISSUE THREAD

**Issue by cimplesid** [hivedb/hive#744]
**Steps to Reproduce**
It was working normally. As I was caching more data suddenly when I hot restart the app it failed to open the box. It has something to do with encryption I think here is the log
**Code sample**
```
E/flutter ( 5490): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: HiveError: This should not happen. Please open an issue on GitHub.
E/flutter ( 5490): #0      BinaryReaderImpl.readFrame
package:hive/…/binary/binary_reader_impl.dart:250
E/flutter ( 5490): #1      _KeyReader.readKeys
package:hive/…/io/frame_io_helper.dart:73
E/flutter ( 5490): <asynchronous suspension>
E/flutter ( 5490): #2      FrameIoHelper.keysFromFile
package:hive/…/io/frame_io_helper.dart:32
E/flutter ( 5490): <asynchronous suspension>
E/flutter ( 5490): #3      StorageBackendVm.initialize
package:hive/…/vm/storage_backend_vm.dart:88
E/flutter ( 5490): <asynchronous suspension>
E/flutter ( 5490): #4      HiveImpl._openBox
package:hive/src/hive_impl.dart:116
E/flutter ( 5490): <asynchronous suspension>
E/flutter ( 5490): #5      HiveImpl.openLazyBox
package:hive/src/hive_impl.dart:162
E/flutter ( 5490): <asynchronous suspension>
```

**Version**
 - Platform: Android-emulator Pixel 2, Mac-M1,
 - Flutter version: [2.0.6]
 - Hive version: [2.0.4]
 - Hive Flutter version [1.1.0]

**Comment by malaschitz** [comment]
Maybe it is another problem, but I was not able open box created in version 1.x.x with Hive 2.x.x

**Comment by nayefradwi** [comment]
I have the same issue and I am not using encryption, but when I hot restart the app this happens. If I uninstall the app and reinstall then the issue stops until I hot restart some point again

**Comment by cimplesid** [comment]
This issue only seems to happen in Emulators and debug mode and can easily be fixed by clearing data or reinstalling
