### ISSUE TITLE
docs.hivedb.dev is timing out

### ISSUE THREAD

**Issue by refi64** [hivedb/hive#76]
Pretty much want the title says...

**Comment by leisim** [comment]
What country are you trying to access the docs from? It works fine for me...

**Comment by leisim** [comment]
I just tried it using VPN and you are right: The page is REALLY slow sometimes. I'll try to improve it...

**Comment by leisim** [comment]
This should be fixed now...

**Comment by refi64** [comment]
Indeed, it's working now!
