### ISSUE TITLE
store Image to List 

### ISSUE THREAD

**Issue by tonyhart7** [hivedb/hive#763]
I want to save my image to list using File data type but it seems Hive dnt support File data type

How I can store my Image to List ?? what datatypes I must convert ??

thanks b4
~~~~
HiveError (HiveError: Cannot write, unknown type: _File.
~~~~

**Version**
 - Platform: iOS, Android,
 - Flutter version: latest version
 - Hive version: latest version

**Comment by tonyhart7** [comment]
@themisir

**Comment by themisir** [comment]
You can store file path instead of File object.

**Comment by tonyhart7** [comment]
but I want to store it to the List

**Comment by themisir** [comment]
> but I want to store it to the List

File is a runtime reference object - means it can not be stored on persistent storage in a meaningful way. The easiest way is to store file path and create a `File` instance using that path when needed.

You can use Iterable.map method to convert file list into path list.

```dart
model.files = files.map((file) => file.path).toList();
```

**Comment by tonyhart7** [comment]
> > but I want to store it to the List
> 
> File is a runtime reference object - means it can not be stored on persistent storage in a meaningful way. The easiest way is to store file path and create a `File` instance using that path when needed.
> 
> You can use Iterable.map method to convert file list into path list.
> 
> ```dart
> model.files = files.map((file) => file.path).toList();
> ```

but what if I want to backup that to server ??

**Comment by tonyhart7** [comment]
its OK i will store it to ByteData
