### ISSUE TITLE
ValueListenableBuilder Renders incorrectly on `box.put` instead of `box.add`

### ISSUE THREAD

**Issue by Dj-Polyester** [hivedb/hive#775]
**Steps to Reproduce**

The code sample below is working fine until I modify the portion in `passwd_screen.dart` as  `KeyStore.passkeys.put(passkey.desc, passkey)`. After that, the listview builder shows the list sorted with the last element repeated once. For example before `put` I have the listview as `["a", "b", "d" ]`, after I `put` a passkey with `passkey.desc = "c"` the HiveObject `passkeys` is correct as `["a", "b", "c","d" ]`, but the UI renders the listview as  `["a", "b", "d","d" ]`. I need to refresh the listview (i.e. switch navigation bar or hot reload/restart the app) in order to make the UI render correctly.

**Code sample**
db.dart:
```
class KeyStore {
  static Box<PassKey> get passkeys => Hive.box<PassKey>("passkeys");
}
```
passwd_screen.dart:
```
...
KeyStore.passkeys.add(passkey);
...
```
vault.dart:
```
import "db.dart";
import "passwd_screen.dart";
...
ValueListenableBuilder<Box<PassKey>>(
        valueListenable: KeyStore.passkeys.listenable(),
        builder: (context, box, _) {
          List<PassKey> passkeys = box.values.toList();
         ...
return ListView.builder(
            padding: const EdgeInsets.all(Globals.itemsPaddingMax),
            itemCount: passkeys.length,
            itemBuilder: (BuildContext context, int i) {
              PassKey passkey = passkeys[i];

              return CustomListItem(
                passkey: passkey,
                customListItemView: (BuildContext context) => PassKeyItemView(
                    passkey: context.select(
                        (CustomListItemModel customListItemModel) =>
                            customListItemModel.passkey)),
              );
            },
          );
        },
      );
...
```

**Version**
 - Platform: Android (didn't test on other platforms)
 - Flutter version: [2.6.0]
 - Hive version: [2.0.4]

**Comment by pishguy** [comment]
@Dj-Polyester  where you used `put`?

**Comment by Dj-Polyester** [comment]
@pishguy In place of `add` in `passwd_screen.dart`, as stated earlier. Coming from [this post](https://stackoverflow.com/a/64417638/10713877), I think the problem is with the `ListView.builder`. When I want to insert (`put`) instead of append (`add`) to the builder, it wasn't rendering correctly as stated earlier. When I pass a `UniqueKey` object to the builder, it now renders as intended. The issue seems to have been resolved now. I will close it for now, considering to reopen when the issue persists in the future. If do you have any suggestions or knowledge about where this behavior originates from, I will appreciate that.
