### ISSUE TITLE
Documentation can be improved for newcomers

### ISSUE THREAD

**Issue by bernaferrari** [hivedb/hive#78]
I have begun to play with Hive and it is awesome, but sometimes frustrating because documentation is lacking some information. This might be specially difficult for newcomers (including me).

For example:

1. How do I even init Hive? I would modify [this page](https://docs.hivedb.dev/#initialize) to inform that you need to import path_provider on Android and iOS, but not web. I would also add a link to the corresponding sample. It is hard to guess without looking at the sample.

2. So now I know how to open a box. Where should I open it? Should I use FutureBuilder on the Scaffold or may I use FutureBuilder in an individual component? Does it matter?

3. Should I call `registerAdapter` inside openBox (like on [this sample](https://github.com/hivedb/samples/blob/33dd761663b178784854ab2d357e614664c5e472/sketchpad/lib/main.dart#L18)) or outside, before runApp is even called, like on [this sample](https://github.com/hivedb/samples/blob/33dd761663b178784854ab2d357e614664c5e472/todo/lib/main.dart#L11)? You are calling it before `Hive.init(dir.path)`, I didn't know it was possible and there is nothing in the documentation.

4. Then we learn how to [read to a box](https://docs.hivedb.dev/boxes/read). Awesome. But how do I listen for the changes? I want to observe them, is this possible? Is it compatible with stream? Can I put together with RxDart and debounce them? Will it work only with FutureBuilder or anything else? I later saw the [watch changes](https://docs.hivedb.dev/boxes/watch_changes) page, but you could link them.

5. Regarding [delete](https://docs.hivedb.dev/boxes/delete), I would probably add a comma in the `you can either override it using for example put() or delete it`. It felt weird/confusing reading the first time. You could also add another line, like `box.delete('key'); // value was already deleted, returns nothing immediately`. Those snippets could be more complete, exactly like you did [here](https://docs.hivedb.dev/boxes/auto_increment).

I think that's it.

**Comment by leisim** [comment]
Thank you very much for taking the time to give me feedback.

I agree with every point and start improving the docs. I think it is really lacking "best practices"...

**Comment by bernaferrari** [comment]
Another thing that made me go into "???" is the samples. I automatically went [here](https://github.com/hivedb/hive/tree/master/hive/example) which directed me [here](https://docs.hivedb.dev/more/examples) which directed me [here](https://github.com/hivedb/samples/tree/master/counter). Couldn't you keep the samples in the same repository? Or at least provide a nice README that avoids two clicks?

**Comment by bernaferrari** [comment]
Another question, when does `snapshot.error != null` happen? Sometimes? Never (as long as I configured Hive correctly)? I couldn't find anything. Worth adding to the documentation.

**Comment by leisim** [comment]
snapshot.error != null happens for example if you try to write to a directory where you don't have write permission. It is just good practice to handle a possible error in the FutureBuilder .

 hive_flutter does not have a documentation yet.

you should add a description for typeId in the sample.


What do you mean by that?

**Comment by bernaferrari** [comment]
> you should add a description for typeId in the sample.

You use value 35 randomly. On documentation, I found it could be any value between 0 and 255. You could add a comment saying "this value is random and could be any value between 0 and 255" so we don't have to look in the documentation.

**Comment by leisim** [comment]
Ah, yes :+1:

**Comment by bernaferrari** [comment]
If I correctly setup Hive, snapshot.error != null will never happen, right? I am wrapping my full app with hive, so I want to be sure it will never fail catastrophically randomly.

**Comment by leisim** [comment]
> If I correctly setup Hive, snapshot.error != null will never happen, right? I am wrapping my full app with hive, so I want to be sure it will never fail catastrophically randomly.

It won't happen because of Hive. But if you init Hive with a folder where you don't have write access it will fail.

**Comment by leisim** [comment]
@bernaferrari I'm currently working on a new version on the docs and I'd love to get your input or even a pull request. See #165.
