### ISSUE TITLE
Iterating through keys/values

### ISSUE THREAD

**Issue by radzish** [hivedb/hive#792]
Does Hive allow to lazily iterate through all keys OR values? Or calling keys/values getters will load everything into memory ?

**Comment by mbaumgartenbr** [comment]
Hey @radzish!

Normal boxes are loaded into memory as soon as you call `Hive.openBox()`.

You can take a look at [LazyBox](https://docs.hivedb.dev/#/advanced/lazy_box) that only loads the keys into memory.

**Comment by radzish** [comment]
Hmmm... I have a lots of records. Will probably need to look for something else. Thanks!
