### ISSUE TITLE
How to autogenerate Adaptors with dart?

### ISSUE THREAD

**Issue by shady-ti** [hivedb/hive#796]
**Question**
The hive docs outline [how to autogenerate adaptors for flutter projects](https://docs.hivedb.dev/#/custom-objects/generate_adapter), the same instruction cannot be used for pure dart projects, I've done some searching but I hit a dead end any help would be appriciated.

**Code sample**
- Any annotated class in a pure dart project

**Version**
 - Platform: Windows
 - Flutter version: 2.5.1 stable
 - Hive version: latest (started my proj day b4)

**Comment by bit-garden** [comment]
The instructions there do only list Flutter commands, but what happens if you do the dart variants? `dart run build_runner build`.

**Comment by themisir** [comment]
Hive generator doesn't depend on flutter. You can run `build_runner` either using dart or flutter tool cli.

```sh
flutter pub run
dart pub run
dart run
```
I haven't tested personally but AFAIK all of those should have same effect.

**Comment by shady-ti** [comment]
I assume we need to use [build_runner from pub](https://pub.dev/packages/build_runner)?
