### ISSUE TITLE
Custom object with lists does not save childs in box.

### ISSUE THREAD

**Issue by nicolasvac** [hivedb/hive#797]
**Steps to Reproduce**
1. Create a custom type.
2. Add a list of another custom type inside.
3. Populate the list of children object and save the main object which contains the list.

You expect all the childrens to have a key after the save, but they do not. 

**Code sample**
```
@HiveType(typeId: 0)
class Big extends HiveObject {
    @HiveField(0)
    final List<Child> childs;

    Big(this.childs);
}

@HiveType(typeId: 1)
class Child extends HiveObject {
    @HiveField(0)
    final String name;

    Child(this.name);
}

void main() async {
List<Child> childs = [Child('Test'), Child('Test 2')];

Big big = new Big(childs);

await big.save();

# This will print all nulls instead of the keys.
print(big.childs.map((child) => child.key)).toList().toString();
}
```

Note: i excluded on purpose all the init stuff and register adapter.

**Version**
 - Platform : Every
 - Flutter version: 2.5.0
 
```
hive: ^2.0.4
hive_flutter: ^1.1.0
hive_generator: ^1.1.1
```

**Comment by bit-garden** [comment]
There are several issues with your example code.

It doesn't init or open a box, it doesn't add or put big anywhere, and lastly(the main thing causing key to be null), the child objects are not being put in the box directly, only added to the list.

```
import 'package:hive/hive.dart';
import 'package:hive_generator/hive_generator.dart';

part 'test.g.dart';

@HiveType(typeId: 0)
class Big extends HiveObject {
  @HiveField(0)
  final List<Child> childs;

  Big(this.childs);
}

@HiveType(typeId: 1)
class Child extends HiveObject {
  @HiveField(0)
  final String name;

  Child(this.name);
}

void main() async {
  // gotta init the hive
  Hive
    ..init('./hives')
    // you need these adapters
    ..registerAdapter(BigAdapter())
    ..registerAdapter(ChildAdapter());

  // need a box to save things to
  var box = await Hive.openBox('childrenTest');

  List<Child> childs = [Child('Test'), Child('Test 2')];
  
  // add children to box
  for (var i in childs) box.add(i);

  Big big = new Big(childs);

  // add big to box. This should cause a save automatically.
  await box.put('big', big);

  // Technically not needed in this example since put would save already.
  await big.save();

  // This will print the key(ints in this case) of the childs list.
  for (var e in big.childs) {
    print(e.key);
  }
}
```

**Comment by nicolasvac** [comment]
Hello @bit-garden , i tought my note on the post was clear:
`Note: i excluded on purpose all the init stuff and register adapter.`

Apart from that, arent lists supported by hive and part of the object itself ? The generator has a writeByte method and read method for the list.

**Comment by bit-garden** [comment]
`HiveList`s specifically need to have `HiveObject`s that are already in the box because they use that key to reference the existing object instead of keeping a copy.

In your case, it looks like you are using normal lists, so the `Child` class actually doesn't need to inherit `HiveObject` to be used in Hive.

`HiveObject` descendants _need_ to be added to a box in order to get given a key. They don't automatically get the key of the parent object.

---

Are you needing the `Child` instances to have a key for a specific reason or were you thinking that any object put in a Hive needed to inherit `HiveObject`?

**Comment by nicolasvac** [comment]
Hello @bit-garden , thank you for the reply.

Basically what i need is that that child have also their information saved inside this big object.

Problem is, if i reload the big object from hive, i do loose the child infos because they are not saved automatically like i tought.

**Comment by bit-garden** [comment]
Here is a minimal example of that.

![image](https://user-images.githubusercontent.com/10319571/135346345-beb21fc1-9fc4-47a8-bc67-12da2e871656.png)

```
import 'package:hive/hive.dart';
import 'package:hive_generator/hive_generator.dart';

part 'test.g.dart';

@HiveType(typeId: 0)
class Big {
  @HiveField(0)
  final List<Child> childs;

  Big(this.childs);
  toString() => 'Big($childs)';
}

@HiveType(typeId: 1)
class Child {
  @HiveField(0)
  final String name;

  Child(this.name);
  toString() => 'Child($name)';
}

void main() async {
  Hive
    ..init('./hives')
    ..registerAdapter(BigAdapter())
    ..registerAdapter(ChildAdapter());

  Box<Big> box = await Hive.openBox('childrenTest');

  var old_data = box.get('big');

  if (old_data != null) {
    print(old_data);
  } else {
    print('creating data');
    Big big = new Big([Child('Test'), Child('Test 2')]);
    await box.put('big', big);
  }
}
```

**Comment by nicolasvac** [comment]
@bit-garden but they do not have a key. Is this still safe ?

**Comment by bit-garden** [comment]
Yeah. Keys aren't required to be stored in the object unless you use something like `HiveList`. Then it's used internally by Hive to keep track of the references.

You probably can use the key for other reasons, but it's not 'needed' to simply exist in the box.

**Comment by nicolasvac** [comment]
Hello @bit-garden , thank you.

What if i need to edit a child property after it was saved ?
Do i need to save big again to keep the new changes or are the changes automatically persisted ?

**Comment by bit-garden** [comment]
We are reaching more of a tutorial string of questions now and not so much
an issue. Please follow the docs regarding this topic.
https://docs.hivedb.dev/#/basics/read_write
