### ISSUE TITLE
Hive Build Type Adapter Error - The type 'TypeAdapter' is declared with 0 type parameters, but 1 type arguments were given.

### ISSUE THREAD

**Issue by MrudulAddipalli** [hivedb/hive#811]
Hi,

    I am getting an error in generated file for Hive Models with typeId 2 to 10, below image is the error, these models from typeId 2 to 10 were added later into the project, so I have to delete previous generated file and rerun the build command [ flutter packages pub run build_runner build ] , now the Hive Generated TypeAdapters for Type 0 and Type 1 are correct, but for Type 2 to 10 it's giving error.

![image](https://user-images.githubusercontent.com/40620858/137336517-60dee1f0-db1b-4c59-8a7d-dbea80194706.png)

Below are my models with respective @HiveType and @HiveField,

File 1 Models

      @HiveType(typeId: 0)
      class UserData {
        @HiveField(0)
        String token;
        int userID;
        @HiveField(1)
        String firstName;

        UserData({
          this.userID,
          this.firstName,
        });
      }

      @HiveType(typeId: 1)
      class Module {
        @HiveField(0)
        int moduleID;
        @HiveField(1)
        String moduleName;

        Module({
          this.moduleID,
          this.moduleName,
        });
      }

File 2 Models

    @HiveType(typeId: 2)
    class ExamData {
      @HiveField(0)
      int moduleID;
      @HiveField(1)
      int broadcastID;

      ExamData(
          {this.moduleID,
          this.broadcastID,});
    }

    @HiveType(typeId: 3)
    class Section {
      @HiveField(0)
      int sectionID;
      @HiveField(1)
      String title;

      Section(
          {this.sectionID,
          this.title
      });
    }

    @HiveType(typeId: 4)
    class Question {
      @HiveField(0)
      int questionID;
      @HiveField(1)
      String title;

      Question(
          {this.questionID,
          this.title});
    }

    @HiveType(typeId: 5)
    class Type {
      @HiveField(0)
      int typeId;
      @HiveField(1)
      String name;

      Type({this.typeId, this.name});
    }

    @HiveType(typeId: 6)
    class Answer {
      @HiveField(0)
      int answerID;
      @HiveField(1)
      String title;

      Answer({this.answerID, this.title});
    }

    @HiveType(typeId: 7)
    class FileInfo {
      @HiveField(0)
      int fileID;
      @HiveField(1)
      String type;

      FileInfo(
          {this.fileID,
          this.type});
    }

    @HiveType(typeId: 8)
    class Meta {
      @HiveField(0)
      String tempFieldForHiveTest;
      @HiveField(1)
      List<Tag> tags;

      Meta({this.tags, this.tempFieldForHiveTest: ""});
    }

    @HiveType(typeId: 9)
    class Tag {
      @HiveField(0)
      int tagID;
      @HiveField(1)
      int moduleID;

      Tag(
          {this.tagID,
          this.moduleID,});
    }

    @HiveType(typeId: 10)
    class SectionStatus {
      @HiveField(0)
      Section section;
      @HiveField(1)
      bool isAttempted;
      SectionStatus({this.section, this.isAttempted});
    }

 - Platform: Android, Mac, Windows, Linux, Web
 - Flutter version: [stable, 2.2.3]
 - Hive version: [2.0.4]

below are my dev dependencies

  dev_dependencies:
      hive_generator: ^1.1.1
      build_runner: ^2.0.6
      flutter_launcher_icons: ^0.9.2

**Comment by mbaumgartenbr** [comment]
Hi @MrudulAddipalli!

It seems like you are getting the wrong TypeAdapter imported, see the vscode hint of your mouse hover.

The `TypeAdapter` being used comes from `"package:vallued/Models/response_models/exam_response_models.dart"` try removing the import in the not generated file (the one that has `part '.g.dart';`) or adding a suffix `hide TypeAdapter` to it like so:

```dart
import "package:vallued/Models/response_models/exam_response_models.dart" hide TypeAdapter";
```
