### ISSUE TITLE
 non-ASCII characters, is there a reason?

### ISSUE THREAD

**Issue by JobiJoba** [hivedb/hive#84]
**Question**
I would like to create keys which contains Thai letters (ex: "ป็นไรครับ"). 
Unfortunately, I'm facing the error of non-ascii characters. 
Right now, my keys are stored in Firebase and I wanted to sync with Hive. 
Is there a technical reason why we couldn't do something like that? 
Thanks

**Code sample**

openBox.put("ป็นไรครับ", 10);

**Version**
 - Platform: Mac; ios ; android
 - Flutter version: 1.9.4+hotfix.4
 - Hive version: 1.0

**Comment by leisim** [comment]
Yes there is. Keys have to be read very quickly. It is super fast to read ASCII strings compared to Unicode strings...

**Comment by JobiJoba** [comment]
Ok. 
I'll write that content as a value then :) 

Thanks
