### ISSUE TITLE
HiveError: This should not happen...

### ISSUE THREAD

**Issue by sgehrman** [hivedb/hive#841]
Any ideas?  I'm storing lots of data in hive.

Nov 22 14:40:46 5950x google-chrome.desktop[3776]: HiveError: This should not happen. Please open an issue on GitHub.
Nov 22 14:40:46 5950x google-chrome.desktop[3776]: package:hive/src/binary/binary_reader_impl.dart 250  BinaryReaderImpl.readFrame
Nov 22 14:40:46 5950x google-chrome.desktop[3776]: package:hive/src/binary/frame_helper.dart 21         FrameHelper.framesFromBytes
Nov 22 14:40:46 5950x google-chrome.desktop[3776]: package:hive/src/io/frame_io_helper.dart 42          FrameIoHelper.framesFromFile
Nov 22 14:40:46 5950x google-chrome.desktop[3776]: [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: HiveError: This should not happen. Please open an issue on GitHub.
Nov 22 14:40:46 5950x google-chrome.desktop[3776]: #0      BinaryReaderImpl.readFrame (package:hive/src/binary/binary_reader_impl.dart:250)
Nov 22 14:40:46 5950x google-chrome.desktop[3776]: #1      FrameHelper.framesFromBytes (package:hive/src/binary/frame_helper.dart:21)
Nov 22 14:40:46 5950x google-chrome.desktop[3776]: #2      FrameIoHelper.framesFromFile (package:hive/src/io/frame_io_helper.dart:42)
Nov 22 14:40:46 5950x google-chrome.desktop[3776]: <asynchronous suspension>
Nov 22 14:40:46 5950x google-chrome.desktop[3776]: #3      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:86)
Nov 22 14:40:46 5950x google-chrome.desktop[3776]: <asynchronous suspension>
Nov 22 14:40:46 5950x google-chrome.desktop[3776]: #4      HiveImpl._openBox (package:hive/src/hive_impl.dart:116)
Nov 22 14:40:46 5950x google-chrome.desktop[3776]: <asynchronous suspension>
Nov 22 14:40:46 5950x google-chrome.desktop[3776]: #5      HiveImpl.openBox (package:hive/src/hive_impl.dart:145)
Nov 22 14:40:46 5950x google-chrome.desktop[3776]: <asynchronous suspension>
Nov 22 14:40:46 5950x google-chrome.desktop[3776]: #6      HiveBox.open (package:dfc_flutter/src/hive_db/hive_box.dart:33)
Nov 22 14:40:46 5950x google-chrome.desktop[3776]: <asynchronous suspension>
Nov 22 14:40:46 5950x google-chrome.desktop[3776]: #7      BoxManager._dataBox (package:pathfinder/web_server/storage/box_manager.dart:102)
Nov 22 14:40:46 5950x google-chrome.desktop[3776]: <asynchronous suspension>
Nov 22 14:40:46 5950x google-chrome.desktop[3776]: #8      BookmarkDatabase._add (package:pathfinder/web_server/storage/bookmark_database.dart:71)
Nov 22 14:40:46 5950x google-chrome.desktop[3776]: <asynchronous suspension>
Nov 22 14:40:46 5950x google-chrome.desktop[3776]: #9      BookmarkDatabase.add (package:pathfinder/web_server/storage/bookmark_database.dart:45)
Nov 22 14:40:46 5950x google-chrome.desktop[3776]: <asynchronous suspension>
Nov 22 14:40:46 5950x google-chrome.desktop[3776]: #10     BookmarkManager.add (package:pathfinder/web_server/storage/bookmark_manager.dart:38)
Nov 22 14:40:46 5950x google-chrome.desktop[3776]: <asynchronous suspension>
Nov 22 14:40:46 5950x google-chrome.desktop[3776]: #11     LocalServerBookmarks.handleAddRecentReq (package:pathfinder/web_server/local_server_bookmarks.dart:103)
Nov 22 14:40:46 5950x google-chrome.desktop[3776]: <asynchronous suspension>
Nov 22 14:40:46 5950x google-chrome.desktop[3776]: #12     handleRequest (package:shelf/shelf_io.dart:114)
Nov 22 14:40:46 5950x google-chrome.desktop[3776]: <asynchronous suspension>

**Comment by sgehrman** [comment]
I have a file that I think is corrupted.  it's 8mb.

![gnome-shell-screenshot-ODKUC1](https://user-images.githubusercontent.com/287137/143235509-d74556dd-f98d-4720-ad45-8f9360b5b9b6.png)

**Comment by lodisy** [comment]
Check out the pinned issue.

**Comment by sgehrman** [comment]
I looked at the pinned.  Is there a solution?  Is the corruption a mystery?

**Comment by yasargil** [comment]
@sgehrman do you mind sharing the corrupted file i want to have a look at it to check where and what the corruption is.

**Comment by themisir** [comment]
Closed with #914.

Please upgrade to hive [v2.0.6](https://pub.dev/packages/hive/versions/2.0.6).
