### ISSUE TITLE
I don't understand why there is not an addAt() function in order to update a particular part of the Hive box

### ISSUE THREAD

**Issue by HygertMetallari1** [hivedb/hive#845]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: [e.g. 1.5.4]
 - Hive version: [e.g. 0.5.0]

**Comment by nicoeg** [comment]
Do you mean `put`?
https://docs.hivedb.dev/#/basics/read_write?id=write
