### ISSUE TITLE
Weird bug with TypeAdapter

### ISSUE THREAD

**Issue by bernaferrari** [hivedb/hive#85]
I don't know what is going on. I made a minimal reproducible sample modifying the counter sample: [counter.zip](https://github.com/hivedb/hive/files/3720251/counter.zip)

```
I/flutter (24325): HiveError: There is already a TypeAdapter for typeId 35.
```

It loads fine, then refreshes (probably because put has occurred) and things get weird. Why is that happening?

**Comment by leisim** [comment]
Your sample works fine for me. What device are you testing on? Maybe try to execute `flutter clean`.

**Comment by bernaferrari** [comment]
Well, that's certainly weird. I tried `flutter clean` without success.
Currently Android Emulator API 29.

**Comment by bernaferrari** [comment]
Hey, could you reproduce it? I'm locked because of it.

**Comment by leisim** [comment]
I think I know the problem. When you do a hot reload, your `_openBox()` is called a second time and fails because the `TypeAdapter` has already been registered.

This should work:
```dart
var initialized = false;
Future _openBox() async {
  if (!initialized) {
    initialized = true;
    if (!isBrowser) {
      var dir = await getApplicationDocumentsDirectory();
      Hive.init(dir.path);
    }
    Hive.registerAdapter(ColorAdapter(), 35);
  }

  return await Hive.openBox('myBox');
}

**Comment by bernaferrari** [comment]
Nope, not working:
 
![image](https://user-images.githubusercontent.com/351125/66859868-788f4700-ef62-11e9-9071-148e6f3479a8.png)

**Comment by bernaferrari** [comment]
Nope. When I press run it gives this. 
![image](https://user-images.githubusercontent.com/351125/66859995-b2f8e400-ef62-11e9-9f8f-56e57ef4d2f1.png)

When I hot-restart it works. Really weird.

**Comment by leisim** [comment]
[counter.zip](https://github.com/hivedb/hive/files/3731366/counter.zip)

This works fine for me...

**Comment by bernaferrari** [comment]
I think I know the issue!

I think the Hive database got somehow corrupted. I needed to reinstall my app, now it is working fine. Thanks!
