### ISSUE TITLE
Update data without call put method

### ISSUE THREAD

**Issue by valetanddama** [hivedb/hive#86]
**Question**
I get some data from a box by a key, then update value in the data and the data updates in box without call a PUT method.

**Code sample**
```
Future<dynamic> getUser() async {
    Box box = Hive.box('some_storage');
    dynamic user = await box.get('user');

    return user;
}

dynamic user = await getUser();
print(user['age']); // 26

user['age'] = 27

dynamic user = await getUser();
print(user['age']); // 27
```

**Version**
 - Platform:  Android
 - Flutter version: [1.9.1+hotfix.2]
 - Hive version: [1.0.0]

**Comment by Offtree** [comment]
Per the docs there's currently the option to extend `HiveObject` from your `HiveTypes` which give you the option to call `.save()` and `.delete()` which are pretty close to what you're looking for.

```
@HiveType
class HiveUser extends HiveObject {
    @HiveField(0)
     int age;
}

Future<HiveUser> getUser() async {
    Box box = Hive.box('some_storage');
    HiveUser user = await box.get('user') as HiveUser;

    return user;
}

HiveUser user = await getUser();
print(user.age); // 26

user.age = 27
user.save()

HiveUser user = await getUser();
print(user.age); // 27
```

Which I feel is close enough to what you're looking for.

**Comment by valetanddama** [comment]
@Offtree Actually I wrote about other problem. I didn't call put method, but the data in the box was updated.

**Comment by leisim** [comment]
Every object only exists once. You don't change the persisted object but the cached one. That is the intended behavior. It should be documented more clearly.

**Comment by leisim** [comment]
This has been added to the docs.
