### ISSUE TITLE
Error: The non-abstract class '_$_UserEntity' is missing implementations for these members: HiveObjectMixin.box/delete/isInBox/key/save

### ISSUE THREAD

**Issue by maximcore** [hivedb/hive#869]
I have a class generated with freezed, this error occurs in runtime. Any ideas?

 lib/domain/entities/user_entity/user_entity.freezed.dart:164:7: Error: The non-abstract class '_$_UserEntity' is missing implementations for these members:
[   +1 ms]  - HiveObjectMixin.box
[        ]  - HiveObjectMixin.delete
[        ]  - HiveObjectMixin.isInBox
[        ]  - HiveObjectMixin.key
[        ]  - HiveObjectMixin.save
[        ] Try to either
[        ]  - provide an implementation,
[        ]  - inherit an implementation from a superclass or mixin,
[        ]  - mark the class as abstract, or
[        ]  - provide a 'noSuchMethod' implementation.

**Code sample**
```
import 'package:flutter/foundation.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:hive/hive.dart';

part 'user_entity.freezed.dart';

part 'user_entity.g.dart';

@freezed
class UserEntity extends HiveObject
    with _$UserEntity {

  @HiveType(typeId: 1)
  const factory UserEntity({
    @HiveField(0) @Default('') String username,
    @HiveField(1) @Default('') String email,
    @HiveField(2) @Default('') String id,
    @HiveField(3) @Default('') String profilePictureUrl,
  }) = _UserEntity;

  factory UserEntity.fromJson(Map<String, dynamic> json) => _$UserEntityFromJson(json);
}
```

 - Platform: iOS, Android
 - Flutter version: 2.8.1
 - Hive version: 2.0.5
 - Hive_flutter version: 1.1.0
 - Hive_generator version: 1.1.1
 - Freezed version: 1.1.0
 - Build_runner version: 2.1.7

**Comment by maximcore** [comment]
It should be `class UserEntity with _$UserEntity `, not `class UserEntity extends HiveObject
    with _$UserEntity`

**Comment by mirkancal** [comment]
In my case, adding a named constructor is fixed.

```
@freezed
class HostRewardsDTO extends HiveObject with _$HostRewardsDTO {
  @HiveType(typeId: 7, adapterName: 'HostRewardsAdapter')
  factory HostRewardsDTO({
    @HiveField(1) required num currentRewardAmount,
    @HiveField(2) required int currentUserJoins,
    @HiveField(3) required num firstTimePayingUserJoins,
  }) = _HostRewardsDTO;

  HostRewardsDTO._();

  factory HostRewardsDTO.fromJson(Map<String, dynamic> json) =>
      _$HostRewardsDTOFromJson(json);
}
```

**Comment by cofirazak** [comment]
If you want to be able to define methods/properties in your freezed classes (like in this case), the you need an extra step: 
Define a private empty constructor:

```
@freezed
class Person with _$Person {
  // Added private empty constructor. Must not have any parameter
  const Person._();

  const factory Person(String name, {int? age}) = _Person;

  void method() {
    print('hello world');
  }
}
```

https://pub.dev/packages/freezed#adding-getters-and-methods-to-our-models
