### ISSUE TITLE
Future of Hive, should we all switch to isar?

### ISSUE THREAD

**Issue by bw-flagship** [hivedb/hive#871]
**Question**
Dear Hive maintainters,
I love Hive and use it in many flutter projects.
However, I see that the initial creator @leisim puts his effort in IsarDB, which seems promising as well.
Will Hive still be maintained in the future, or is the plan that everyone switches to IsarDB once its ready?
In case both Hive and IsarDB are meant to survive in the future, it would be great to publish some kind of feature-comparison or recommendation when to use which.

Thanks!

**Comment by leisim** [comment]
Hive and Isar are very different and one does not replace the other. It might even make sense to use both in a single app.

Hive is a key-value database without schema and support for dynamic data.

Isar is a NoSQL database with fixed schema and query support.

**Comment by bw-flagship** [comment]
Thanks for clarification!
