### ISSUE TITLE
Can you migrate database versions?

### ISSUE THREAD

**Issue by nnior** [hivedb/hive#88]
Hi, I'm starting to read a lot about Hive, and it's very cool. I currently use Sqlite with Moor for storage, and I want to migrate to Hive. I have not seen in the documentation information about the migration of versions with Hive.
For example, with SQLite and Moor I do it this way:

```dart
@override
MigrationStrategy get migration => MigrationStrategy(
   onUpgrade: (m, from, to) async {
     // Update version
     if (from <= 3) {
       await m.createTable(userTable);
      // update columns
      // update tables
      // delete rows
      // insert rows
      // insert columns
      // and more
     }
   },
);
```

Is there any way to do the same with Hive in current versions?

Greetings and thanks: D

**Comment by leisim** [comment]
There is no need for conventional migration. As long as you [follow the rules](https://docs.hivedb.dev/typeadapters/generate_adapter#updating-a-class), Hive will migrate your boxes automatically.

If you need to migrate the data in a box, you could, for example, put the version in each box (`box.put('version', 2)`) and check it when you open a box. This is not part of Hive on purpose. It gives you the freedom to implement a solution that fits your app.

**Comment by nnior** [comment]
Thanks for the reply.
So, when I start my application, would I have to do something like this?

```dart
void main() async {
  Hive.init(Directory.current.path);
  var box = await Hive.openBox('myBox');
  int version = box.get('version');
  if(version <= 3){
     // execute changes and update version...
  }
  runApp(MyApp());
}
```

Or would you recommend a better solution?

**Comment by leisim** [comment]
This is exactly what I would do. 

Be careful where you execute this tho. I would run it in a `FutureBuilder` and show a spash screen or a spinner. Otherwise your UI will feel like it freezes.

**Comment by nnior** [comment]
Great, thank you very much, I will explore more details of the library. 😄
