### ISSUE TITLE
Adapter problem with Implementation of DataTime class

### ISSUE THREAD

**Issue by kherel** [hivedb/hive#880]
**Question**
I have my own implementation of DataTime class, called TimeWithTimeZone, I need it to save dates with different time zone offsets.
I have many adapters in my project and TimeWithTimeZoneAdapter is only one of them..

The problem is that when I’m saving TimeWithTimeZone object, it’s not calling write method, but saving it as DateTime

**Code sample**
```dart
class TimeWithTimeZone implements DateTime {
	..
	final DateTime _utc
	final Duration offset;
}

class TimeWithTimeZoneAdapter extends TypeAdapter<TimeWithTimeZone> {
  @override
  final int typeId = HiveAdapters.timeWithTimeZone;

  @override
  TimeWithTimeZone read(BinaryReader reader) {
    final string = reader.readString();
    return TimeWithTimeZone.parse(string);
  }

  @override
  void write(BinaryWriter writer, TimeWithTimeZone obj) {
    writer.writeString(obj.toIso8601String());
  }

  @override
  int get hashCode => typeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TimeWithTimeZoneAdapter &&
          runtimeType == other.runtimeType &&
          typeId == other.typeId;
}

```

**Version**
 - Platform: iOS, Android
 - Flutter version: 2.8.1 • channel stable
 - Hive version: 2.0.5

**Comment by kherel** [comment]
I think my question very similar to this issue..
https://github.com/hivedb/hive/issues/821

**Comment by saibotma** [comment]
Is there any solution to this problem already?
