### ISSUE TITLE
hive_flutter ^2.0.5 which doesn't match any versions

### ISSUE THREAD

**Issue by GavinDon** [hivedb/hive#884]
**Question**
flutter pub get .

**Code sample**
```dart
Pub get  happen error ' hive_flutter ^2.0.5 which doesn't match any versions'
```

**Version**
 - Platform: iOS, Android,
 - Flutter version: [2.5.1]
 - Hive version: [2.0.5]

**Comment by Rohithgilla12** [comment]
@GavinDon `hive_flutter` latest version is 1.1.0
You can check that here
https://pub.dev/packages/hive_flutter/changelog

**Comment by GavinDon** [comment]
> @GavinDon `hive_flutter` latest version is 1.1.0 You can check that here https://pub.dev/packages/hive_flutter/changelog

Thank you. I was careless. I thought all versions were consistent
