### ISSUE TITLE
Hive Database Disappearing When Restarting Flutter Web Browser or close the Tab.

### ISSUE THREAD

**Issue by pramodkr123** [hivedb/hive#885]
**Question**
Hive Database Disappearing When Restarting Flutter Web Browser or close the Tab.
Insert data successfully.
but it lost after restart or close tab.

**Code sample**
void main() async {
  // Register Adapter
  Hive.registerAdapter(UserAdapter()); 

  var box = await Hive.openBox<User>('userBox');

  box.put('Ravi', User('Ravi'));
  box.put('jay', User('jay'));

  print(box.values);
}

**Version**
 - Platform: Web
 - Flutter version: 2.10.0
 - Hive version: 2.0.5

**Comment by pramodkr123** [comment]
fixed.
Working in production.

**Comment by grimatoma** [comment]
I am running into the same issue with the development web instance creating a new instance on each restart of the web clearing the entire database. Did you figure out a way to persist data or reuse the existing web?

**Comment by pramodkr123** [comment]
yes it is the issue in development mode, creating new web instance every time on restart.
But it's not creating new instance every time on restart when it is in production mode.
