### ISSUE TITLE
Need for stream

### ISSUE THREAD

**Issue by themumy10** [hivedb/hive#890]
I m trying to listen for changes in box by using bloc pattern. I need stream subscription for my database changes.

We need a watch method for box. Because of lazy initialization of the box I think this is not possible. So instead of lazy box we may divide boxes into two categories. 

 We need an un-lazy box to subscribe changes in database changes 

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: [2.8.1]
Hive version [2.0.5]

**Comment by raveesh-me** [comment]
Use a StreamController / StreamSink and make the watcher add events on that sink. Simple.

**Comment by themumy10** [comment]
Watcher event does not update on add to box. While using a bloc pattern design watch method doesn't update on add event

**Comment by gosemathraj** [comment]
@themumy10 this seems to work for listening DB changes.

Hive.box("user").listenable().addListener(() {
      voidCallback.call();
});
