### ISSUE TITLE
Sort from A-z

### ISSUE THREAD

**Issue by kholyphoenix0** [hivedb/hive#898]
Hi,
Could someone explain to me how I do to sort from A-z the Items inside the Hive?
I'm using ListView.Builder with count: cartList.length and I need the products to be ordered from A-z.

Thanks!

**Comment by NathanDraco22** [comment]
Mmm... I suppose you have a Product Class Model with product name property, so before the build method return the ListView.builder, use the <sort()> method of your list of products. Set the custom sort, and then storage in a box of hiveDB.
The sort() method receive a Comparator function as argument.
For more info, check the docs.

**Comment by kholyphoenix0** [comment]
Thanks a lot!

  ```
void organizeCart() {
    int i = 0;
    final myKeys = cartBox.keys.toList();
    final myProducts = cartBox.values.toList();

    myProducts.sort((a, b) => a.toString().compareTo(b.toString()));

    if (cartBox.length > 0) {
      myProducts.forEach((element) async {
        cartBox.put(myKeys[i], [myProducts[i][0], myProducts[i][1], myProducts[i][2], myProducts[i][3]]);
        i++;
      });
    }
    debugPrint('Productor Order (A-z)');
  }
```
