### ISSUE TITLE
HiveError: Not all bytes have been used.

### ISSUE THREAD

**Issue by foosionsapps** [hivedb/hive#90]
**Question**
I'm having this error: HiveError: Not all bytes have been used.

I also I tried using lazy loading but my app never starts and shows me that error.
I tried on IOS and Android emulators.

There is something wrong on my code?

**Code sample**
```dart
void main() async {
  final appDocumentDir = await path_provider.getApplicationDocumentsDirectory();
  Hive.init(appDocumentDir.path);
  Hive.registerAdapter(UserAdapter(), 0);
  await Hive.openBox('user');
  runApp(MyApp());
}
```

**Version**
 - Platform: iOS, Android
 - Flutter version: v1.9.1+hotfix.4
 - Hive version: 1.0.0

**Comment by leisim** [comment]
This error indicates that something has gone very wrong.

Did you write the `UserApdater` yourself or generate it?

What happens when you clear all the files of your app?

**Comment by foosionsapps** [comment]
Oh, that's strange. 

I generate the UserAdapter with this command:
flutter packages pub run build_runner build

This is my User class:
import 'package:hive/hive.dart';

part 'user.g.dart';

@HiveType()
class User {
  @HiveField(0)
  String uid;
  @HiveField(1)
  String email;
  @HiveField(2)
  String name;
  @HiveField(3)
  String phone;
  @HiveField(4)
  String avatar;
  @HiveField(5)
  String photoUrl;
  @HiveField(6)
  bool profileCompleted;
  @HiveField(7)
  String handle;
  @HiveField(8)
  String hashTag;
  @HiveField(9)
  String nameSearch;
  @HiveField(10)
  String facebook;
  @HiveField(11)
  String instagram;
  @HiveField(12)
  String pinterest;
  @HiveField(13)
  String twitter;
  @HiveField(14)
  String yelp;
  @HiveField(15)
  String invitationId;
  @HiveField(16)
  String profileStatus;
  @HiveField(17)
  dynamic submittedDate;
  @HiveField(18)
  String title;
  @HiveField(19)
  dynamic updatedTime;
  @HiveField(20)
  String defaultAddressName;
  @HiveField(21)
  String defaultPaymentMethod;

//  List<Address> addresses;
//  List<CreditCard> paymentMethods;

  User(
      {this.uid,
      this.email,
      this.name,
      this.phone,
      this.avatar,
      this.photoUrl,
      this.profileCompleted,
      this.handle,
      this.hashTag,
      this.nameSearch,
      this.facebook,
      this.instagram,
      this.pinterest,
      this.twitter,
      this.yelp,
      this.invitationId,
      this.profileStatus,
      this.submittedDate,
      this.title,
      this.updatedTime,
      this.defaultAddressName,
      this.defaultPaymentMethod});

  factory User.fromJson(userData) {
    return User(
      uid: userData['uid'],
      email: userData['email'],
      name: userData['name'],
      phone: userData['phone'],
      avatar: userData['avatar'] ?? '',
      photoUrl: userData['photoUrl'] ?? '',
      profileCompleted: userData['profile_completed'] ?? false,
      handle: userData['handle'],
      hashTag: userData['hashTag'] ?? '',
      nameSearch: userData['nameSearch'],
      facebook: userData['facebook'],
      instagram: userData['instagram'],
      pinterest: userData['pinterest'],
      twitter: userData['twitter'],
      yelp: userData['yelp'],
      invitationId: userData['invitationId'],
      profileStatus: userData['profileStatus'],
      submittedDate: userData['submittedDate'],
      title: userData['title'],
      updatedTime: userData['updatedTime'],
      defaultAddressName: userData['defaultAddressName'],
      defaultPaymentMethod: userData['defaultPaymentMethod'],
    );
  }
}

**Comment by leisim** [comment]
I'll test your class. Please use code highlighting when you paste code on GitHub. :+1:

**Comment by foosionsapps** [comment]
Ok now is working:

This that's I have done:
1) I added some additional fields to class that I need.
2) Deleted the generated user.g.dart class
3) I ran this command: flutter packages pub run build_runner build
4) Delete the app
5) Finally I ran the app and now I can see my saved user :)

Thanks for your library!

**Comment by leisim** [comment]
Perfect :)
