### ISSUE TITLE
Update benchmark with latest version

### ISSUE THREAD

**Issue by leisim** [hivedb/hive#91]

**Comment by spiralni** [comment]
Hi! I am very thankful for this lib, sql is really horrible when used in flutter.
I have a question: How can I run my own benchmark? Where is the code do you use for running your benchmark? Thanks

**Comment by leisim** [comment]
Sorry for the late response. The code is here: https://github.com/hivedb/hive_benchmark

**Comment by canewsin** [comment]
update needed for hive_benchmark repo.

**Comment by TheMisir** [comment]
Done ✅
