### ISSUE TITLE
Back up Hive database on Google drive

### ISSUE THREAD

**Issue by iamaddaiboateng** [hivedb/hive#929]
**Question**
I am looking for a way to back up my hive database in google dive.
I successfully zip the folder containing the hive file and upload the zipped file to google drive.
I also successfully download the zipped file, unzip it and save the backed up files in the same directory containing the hive files.
The issue is after replacing the database with the download files, the application is unable to read the files. 

**Initialising Hive**

`// get application directory
  Directory? dir = await getExternalStorageDirectory();

  // get path to document directory
  String path = dir!.path;

  // join path with application directory
  String databasePath = join(path, 'MyApp/Database');

  // initialise hive with database path
  await Hive.initFlutter(databasePath);`

**Backing up data to google drive**

`Future<File> createZippedFile() async {
    // get application directory
    Directory? dir = await getExternalStorageDirectory();

    // get path to document directory
    String path = dir!.path;

    // join path with application directory
    String databasePath = join(path, 'MyApp/Database');

    // create file path to hold zip file
    String zipPath = join(path, 'MyApp/Database.zip');

    ZipFileEncoder encoder = ZipFileEncoder();

   // create the zip file
    encoder.create(zipPath);

    // get all files in database directory
    List files = Directory(databasePath).listSync();

    // loop through all files and add them to the zip file
    for (var file in files) {
      encoder.addFile(file);
    }

    // close the zip file
    encoder.close();

    // get the zip file be uploaded to google drive
    return File(zipPath);
  }

// create a function to back up date
  
  backUpData(drive.DriveApi driveApi) async {
    File zippedFile = await createZippedFile();

    // upload the zip file to google drive
    driveApi.files
        .create(
      drive.File()..name = 'MyAppDatabase.zip',
      uploadMedia: drive.Media(zippedFile.openRead(), zippedFile.lengthSync()),
    )
        .whenComplete(() {
      Get.defaultDialog(
        radius: 5,
        title: 'Backup was Successful',
        content: Text(
          'You Successfully backed up your database',
        ),
      );
    });
  }

getDownloadedFile(drive.DriveApi driveApi, String fileId) async {
    // get application directory
    Directory? dir = await getExternalStorageDirectory();

    // get path to document directory
    String path = dir!.path;

    // create file path to hold zip file
    String zipPath = join(path, 'MyApp/Database1.zip');

    // get path to hive database
    String databasePath = join(path, 'MyApp/Database');

    // create a file to hold the zip file
    final savedFile = File(zipPath);

    // download zipped file from google drive
    drive.Media response = await driveApi.files.get(fileId,
        downloadOptions: drive.DownloadOptions.fullMedia) as drive.Media;

    List<int> dataStore = [];

    response.stream.listen((data) {
      print("**********");
      dataStore.insertAll(dataStore.length, data);
    }).onDone(() {
      print('done');

      // save zipped file
      savedFile.writeAsBytes(dataStore).then((value) {
        final inputStream = InputFileStream(value.path);

        final archive = ZipDecoder().decodeBuffer(inputStream);

        // extract database from zipped file and
        //save them in the hive db directory
        for (var file1 in archive.files) {
          print('files ${file1.name}');
          final filePath = join(databasePath, file1.name);

          final file = File(filePath);
          file.writeAsString(filePath);
        }
      }).whenComplete(() {
        //
        List files = Directory(databasePath).listSync();

        print(files.length);
      });

      print('*******');
    });

    print("response: ${response}");
  }
`

**Version**
 - Flutter version: 2.10.1
 - hive: ^2.0.4
 - hive_flutter: ^1.1.0

**Comment by MERCURY-76** [comment]
Hi can I know if you have found a solution ? because I would desperately need it
