### ISSUE TITLE
Firefox private showing blank screen when using Hive package

### ISSUE THREAD

**Issue by PranayDosii** [hivedb/hive#936]
In firefox private mode shows a blank screen when using the hive package. In chrome, works fine any solutions for this.
`Uncaught (in promise) Error: [object Event]` caught error when loading flutter web app on firefox private mode.

**Comment by TheOneWithTheBraid** [comment]
That's easy to answer: indexed DB is not available in Firefox Private windows. Hive has no impact on this.

**Comment by dpajak99** [comment]
do you know any alternative caching plugins that work in firefox in private mode?

**Comment by TheOneWithTheBraid** [comment]
Well, the issue of the private mode is that it's idea is *not* o keep any data. There won't be a proper solution except of showing users a warning.

**Comment by dpajak99** [comment]
Oh, right. I completely ignored it. Thanks
