### ISSUE TITLE
Lock failed, path = '...' (OS Error: Resource temporarily unavailable, errno = 11)

### ISSUE THREAD

**Issue by architsangal** [hivedb/hive#942]
**Question**
I am getting this error message - 

00:23 +159 -1: loading /talawa/test/widget_tests/after_auth_screens/app_settings/app_setting_page_test.dart [E]
  Failed to load "/talawa/test/widget_tests/after_auth_screens/app_settings/app_setting_page_test.dart": lock failed, path = 'temporaryPath/currentuser.lock' (OS Error: Resource temporarily unavailable, errno = 11)
  package:hive/src/backend/vm/storage_backend_vm.dart 81:5                           StorageBackendVm.initialize
  ===== asynchronous gap ===========================
  package:hive/src/hive_impl.dart 116:9                                              HiveImpl._openBox
  ===== asynchronous gap ===========================
  package:hive/src/hive_impl.dart 145:12                                             HiveImpl.openBox
  ===== asynchronous gap ===========================
  test/widget_tests/after_auth_screens/app_settings/app_setting_page_test.dart 98:3  main
  ===== asynchronous gap ===========================
  /tmp/flutter_tools.LUVMPV/flutter_test_listener.QPCJSL/listener.dart 19:3          _testMain

I got this error - when I run `flutter test`. 

**Code sample**

It is a big codebase.  Here is the link - https://github.com/architsangal/talawa
(Commit - https://github.com/architsangal/talawa/commit/1f087095002ba5898e09176eda342125f18a4c79)

**Version**
 - Platform: Not applicable
 - Flutter version: 2.10.3 
 - Hive version: ^2.0.4

**Comment by architsangal** [comment]
Can someone please help? Project has more than 250 test so [this](https://github.com/hivedb/hive/issues/333) kind of solution will not work, I think.

**Comment by fabis94** [comment]
@architsangal did you end up figuring it out? i'm running into the exact same issue

**Comment by architsangal** [comment]
It was happening in my local system. When I pushed my code to GitHub, GitHub Action didn't give any errors. Flutter test run in parallel. So, it is possible that a resource is getting locked by one of the tests. Some other test wants to use that resource at that same movement. This looked like a typical OS lock error. You can try to find a way to run a flutter test in a single thread. I didn't get that part, yet. Please let me know if you get it.

**Comment by hikionori** [comment]
Hello, I found the solution for running tests on a local machine, and don't take this error
```cmd
flutter test --concurrency=1 --test-randomize-ordering-seed=random
```
This command runs tests in one thread and shuffles them in random order.
