### ISSUE TITLE
 Isn't there a way to listen to each value change?

### ISSUE THREAD

**Issue by Faamica** [hivedb/hive#947]
Hi, I've been developing for less than a year and I'm developing an app alone.

I am using hive <typeadapter>, but i have a prolem.

Assume that the 'User' class consists of the following. (ofcourse i generated typeadapter by running build_runner)

```
class User {
String? name;
String? address;
int? age;
```

Then I can access the <User> box and get data like this

```
Box<User>? userBox;
userBox = Hive.box<User>('userBox');
usersBoxData = userBox.get('uid');
```

**What I wanna do is :
1. I will change each variable individually, not all at once. (only name change, or only address change etc)
2. And I'll show the changed value in realtime**

So what i am coding now is:
```
anotherFile.dart

ElevatedButton(
onPress: () {
usersBoxData.name = 'john';
usersBoxData.address = 'earth';)}
```

```
screenFile.dart

child: ValueListenableBuilder(
            valueListenable: Hive.box<User>('usersBox').listenable(),
            builder: (context, Box<User> usersDBBox, widget) {
              var usersBoxData =
                  usersDBBox.get('uid');
            name = usersBoxData.name;
            address = usersBoxData.address;
               return ListView(
               children: [
                Text('$name'),
                Text('$address'),
                Text('$age')]);})
```

However, the screen does not rebuild although I change the name or address by pressing button.
How can I rebuild or is there a different way to change each variable individually?

If I use box.put(uid, User(address: 'earth')) -> then all other variables' values are go to null except which I changed. But the screen rebuilds yeah...

And I used 'save' method, but it also needs the 'put' method before 'save' as I searched.

Please help this newbie... Thx

**Comment by mbaumgartenbr** [comment]
Hi @Faamica!

The easiest way is to make `User` extend `HiveObject` and call `user.save()` as follows:

```dart
class User extends HiveObject {
  // Your properties and methods
}

// Then in the button press
Future<void> onPressed() async {
  user.property = value
  // user.otherProps = otherValues

  await user.save(); // <- important
}
```

Hope it helps 😊

**Comment by Faamica** [comment]
It didn't work when I did it, but why do you tell me and then I succeed? Wow!!
Thank you very much
The hive is so good..... why didn't anyone tell me the hive earlier T T

However, the strange thing is that, although I registered only one 'User class' box in the 'value listenerble', the other box in the builder is also updated.
It's what I wanted though




> Hi @Faamica!
> 
> The easiest way is to make `User` extend `HiveObject` and call `user.save()` as follows:
> 
> ```dart
> class User extends HiveObject {
>   // Your properties and methods
> }
> 
> // Then in the button press
> Future<void> onPressed() async {
>   user.property = value;
>   // user.otherProps = otherValues;
> 
>   await user.save(); // <- important
> }
> ```
> 
> Hope it helps 😊

**Comment by Faamica** [comment]
Thank you. It is solved
