### ISSUE TITLE
hive_flutter web support

### ISSUE THREAD

**Issue by ridyio** [hivedb/hive#955]
The issue was from somewhere else. hive_flutter supports web.

**Comment by Meripro** [comment]
packages/flutter/src/widgets/framework.dart 3551:18
updateChild
packages/flutter/src/widgets/framework.dart 6215:14
mount
packages/flutter/src/widgets/framework.dart 3817:15
inflateWidget
packages/flutter/src/widgets/framework.dart 3551:18
updateChild
packages/flutter/src/widgets/framework.dart 4832:16
performRebuild
packages/flutter/src/widgets/framework.dart 4529:5
rebuild
packages/flutter/src/widgets/framework.dart 4787:5
[_firstBuild]
packages/flutter/src/widgets/framework.dart 4781:5

**Comment by Meripro** [comment]
error are popping up in my command line , what could be the problem
