### ISSUE TITLE
Use Hive.init without path

### ISSUE THREAD

**Issue by andreyeurope** [hivedb/hive#96]
**Question**
Would it be possible to have a default directory for hive files?
It would make sense for me, because I need Hive initialized in a synchronous manner inside a constructor.

**Comment by leisim** [comment]
Sorry I don't quite understand what you want to do. The directory you provide with `Hive.init()` is the default directory.

**Comment by andreyeurope** [comment]
What I mean is to have an `init` method that you can use as `Hive.init()`, with no arguments.
If I remember correctly, you need to use init as `Hive.init('my/directory')`.

**Comment by andreyeurope** [comment]
That's what I am suggesting. Have a directory (wherever you decide) that plays the "default directory" role. It can be `appPath/hive`.

**Comment by leisim** [comment]
But each operating system has different directories. There is no way for me to know where you have write permission.

**Comment by andreyeurope** [comment]
Well, you have write permission inside your app directory, don't you?

**Comment by andreyeurope** [comment]
You are right. I need to await `Hive.openBox()`.
I was trying to initialize Hive inside a constructor for a service, but it seems it is not possible.
I'll close this, as it seems there is nothing you can do.
