### ISSUE TITLE
How to add new HiveField?

### ISSUE THREAD

**Issue by Faamica** [hivedb/hive#962]
**Question**
Hi, I'm using HiveObject and newbie at Hive

What I am curious about is whether it is necessary to add hivefield only to the class and then save it.
The automatically created class.g.dart file does not show the hivefield added after creation. Is it ok?

**Code sample**
```
@HiveType(typeId: 2)
class UsersDB extends HiveObject {
  @HiveField(0)
  String? name;

  @HiveField(1)
  String? address;

  @HiveField(2)
  String? age;
```

After the usersDB.g.dart file is automatically created,
If I add a hivefield to the usersDB.dart file(like HiveField(2), age above), is there anything else I need to do?

Thank you

**Comment by silverhairs** [comment]
Not sure if I got this right but if you mean to ask how to add a new field to `UsersDB` while the `usersDB.g.dart` is already generated, you can add the field in the `UsersDB` hive object then run the command:
```dart pub run build_runner run --delete-conflicting-outputs```
the command will delete the existing `usersDB.g.dart` and generate a new one.

**Comment by Faamica** [comment]
> Not sure if I got this right but if you mean to ask how to add a new field to `UsersDB` while the `usersDB.g.dart` is already generated, you can add the field in the `UsersDB` hive object then run the command: `dart pub run build_runner run --delete-conflicting-outputs` the command will delete the existing `usersDB.g.dart` and generate a new one.

Thank you soooo much. What I want to know is, if I add new field to "usersDB.dart" (model file), then should I run the command to regenerate usersDB.g.dart. ```dart pub run build_runner run --delete-conflicting-outputs``` is safe command T T? Because Hive document said "Don't modify the typeId ~~$#", I'm afraid of run the code again

**Comment by silverhairs** [comment]
@Faamica I think if you change the `typeId` of a `HiveType`, you might need to clear the cache of the app and restart; but changing the id of a `HiveField` is ok as long as you run the command with `--delete-conflicting-outputs`.

**Comment by Faamica** [comment]
> @Faamica I think if you change the `typeId` of a `HiveType`, you might need to clear the cache of the app and restart; but changing the id of a `HiveField` is ok as long as you run the command with `--delete-conflicting-outputs`.

Thanks a lot! I will try it. Have a nice day : )

**Comment by Faamica** [comment]
Solved. Thx
