### ISSUE TITLE
Breaking change in 2.1.0..2.2.0

### ISSUE THREAD

**Issue by jaripekkala** [hivedb/hive#970]
**Steps to Reproduce**
- Use hive v. 2.1.0 with mockito to generate a mock class for HiveInterface
- Upgrade to hive v. 2.2.0
- Tests fails

```
test/my_test.mocks.dart:173:8: Error: The method 'MockHiveInterface.init' has fewer named arguments than those of overridden method 'HiveInterface.init'.
```

The issue raised in our CICD pipeline, as `pub get` resolved the latest version from `^2.0.4` constraint.

**Code sample**
```
@GenerateMocks([HiveInterface])
void main() {
  // tests
}
```

**Version**
 - Platform: N/A
 - Flutter version: 2.8.1
 - Hive version: 2.2.0

**Comment by jaripekkala** [comment]
To be clear, it's not issue just with mockito, but rather with any subclass

```
```

**Comment by sgehrman** [comment]
2.2.0 crashes on flutter web.

**Comment by andrea689** [comment]
I have this error on flutter web:

`Uncaught HiveError: Cannot read, unknown typeId: 18. Did you forget to register an adapter?`

I downgrade to my previous version (2.0.6) to fix it

**Comment by mrcsh** [comment]
I also had to down grade to 2.1.0 to avoid the unknown typeid: 18 and the apparently lack of support for DateTime.

```
EX:HiveError: Cannot write, unknown type: DateTime. Did you forget to register an adapter?>>¶
HiveError: Cannot write, unknown type: DateTime. Did you forget to register an adapter?¶
```

**Comment by Macacoazul01** [comment]
@mrcsh using the same version here

**Comment by Macacoazul01** [comment]
@themisir this should be closed as the error is already fixed
