### ISSUE TITLE
Accessing "get" in a strongly typed way ?

### ISSUE THREAD

**Issue by iangregsondev** [hivedb/hive#973]
**Question**

I am pretty new to Hive and been reading the website to try and get some insight and I can see how you can Save using a model in a Type safe way (strongly typed), so no need to do a put as far as I see, create a new instance of a class and then use "save" (an inherited method) - This is great!

Most of the examples I have seen are using "get" to get values and passing in a string for the key, is it possible to load the data into the class to access all values?

Thank you

**Comment by TheOneWithTheBraid** [comment]
> is it possible to load the data into the class to access all values?

Could you clarify what you mean here? I didn't properly understand it.

In general, you can get safely typed data by creating a typed `Box` using `Hive.openBox<MyType>(...)`.

**Comment by iangregsondev** [comment]
Thats it, sorry, I overlooked that, should have read a little bit further. Going to close this now. Thanks for the response.
