### ISSUE TITLE
can we use data which is in my hive local storage when my app is in killed state ?

### ISSUE THREAD

**Issue by MishraVaibhav1999** [hivedb/hive#980]
I have a problem in my chat messaging app that i have to store token in hive storage and when message notification arrives I am able to reply the message using api without open the app so regarding this can I store token data in this and without open the app I am able to use it?

**Comment by TheOneWithTheBraid** [comment]
Theoretically, you can simply open the Hive database file with any other programming language too. Unfortunately, there are no generic implementations of Hive's storage format in other languages.

I just know of someone who wrote a read-only implementation in Swift for exactly this use case on iOS.

Moreover, the Hive web implementation is an exception here: Hive simply stores its data in Indexed DB databases which can be easily accessed by any other JavaScript code too.

I am closing this issue, as it is far beyond the scope of this package to provide implementations in other programming languages too. It's simply a question of development capacity we don't have.
